### ISSUE TITLE
Please get Python 3 support finished!

### ISSUE THREAD

**Issue by robdoesstuff** [Supervisor/supervisor#1000]
Due to upcoming Python 2 EoL, we're migrating all of our projects to Python 3 and we depend on this. We can run it with 2 for the time being but it's a much more complex deployment when we have to do that.

**Comment by mnaberez** [comment]
As mentioned in several other tickets, the issues tagged [python 3](https://github.com/Supervisor/supervisor/labels/python%203) need to be fixed before a release can be made.  Please don't create even more work for us by creating duplicate issues like this one.

**Comment by robdoesstuff** [comment]
Not trying to create more work, just trying to show that there are many of us with projects switching to Python 3 atm and we don't want to leave supervisor for something else. Also I was looking through the issue list as well as the PRs, and while I'd love to help, I see you have PRs that address the Python 3 issues just sitting in a queue, so I wouldn't want to spend any time working on things that are already done. If you clear out your PR queue, you will probably receive more help - I'll jump on an issue if it'll help get this done.

**Comment by tuxayo** [comment]
> Not trying to create more work, just trying to show that there are many of us with projects switching to Python 3

You can upvote the relevant issues.

> If you clear out your PR queue, you will probably receive more help

I guess it's already possible to help to test, fix, rebase, QA, etc the existing PRs.
