### ISSUE TITLE
supervisorctl doesn't load included config files, misleading and undocumented

### ISSUE THREAD

**Issue by farialima** [Supervisor/supervisor#1007]
I have supervisor 3.2.0 on ubuntu 16.10, installed from the ubuntu package.

I was unable to use supervisorctl, even when providing the `-c` option:

```
$ supervisorctl
unix:///var/run/supervisor.sock no such file
supervisor> exit
$ supervisorctl -c /etc/supervisor/supervisord.conf 
unix:///var/run/supervisor.sock no such file
supervisor> 
```

The reason is that I had customized the socket (so that it's not in a root-owned folder) used by supervisor _in an included config file_. I.e. I have the unmodified  default Debian/Ubuntu config `/etc/supervisor/supervisord.conf`:
```
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
(...)
[include]
files = /etc/supervisor/conf.d/*.conf
```
and I have added a `/etc/supervisor/conf.d/my.conf` that contains (among other things):
```
[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock
```

However, that setting is not taken in account by supervisorctl... it took me to look in the code (in `ClientOptions`) to see that supervisorctl doesn't load the config files listed in the [include] section... This is quite misleading, and not documented in http://supervisord.org/running.html#running-supervisorctl ...

**Comment by farialima** [comment]
related to #498 (i.e. supervisord config != supervisorcrtl config) At least it would be worth documenting it ?

**Comment by farialima** [comment]
see also #480

**Comment by mnaberez** [comment]
There is an open pull request for this in #277. I will close this issue in favor of that one.
