### ISSUE TITLE
When Golang progress crashed, supervisord did not attempt to start the progress 

### ISSUE THREAD

**Issue by zhangketing** [Supervisor/supervisor#1010]
Excuse me, I used supervisord to watch the golang progress .
when the progress crashed,supervisord did not attempt to start the progress.
Why is this ?

**Comment by FAKERINHEART** [comment]
Not set autorestart?

**Comment by zhangketing** [comment]
this is supervisord.conf ：

[program:gmcServer]
redirect_stderr = true
stderr_logfile = /usr/local/logs/gmcServer_stderr.log
command = /usr/local/gmcServer/gmcServer
autostart = false
directory = /usr/local/gmcServer
autorstart = true
stdout_logfile = /usr/local/logs/gmcServer_std.log

I already set  autorestart.

**Comment by zhangketing** [comment]
If I killed the progress, supervisord can watch the golang progress ,and restart the progress. But when the progress crashed,supervisord did not attempt to start the progress.

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by zhangketing** [comment]
Excuse me, I used supervisord to watch the golang progress .
when the progress crashed,supervisord did not attempt to start the progress.
Why is this ?

this is supervisord.conf ：

[program:gmcServer]
redirect_stderr = true
stderr_logfile = /usr/local/logs/gmcServer_stderr.log
command = /usr/local/gmcServer/gmcServer
autostart = false
directory = /usr/local/gmcServer
autorstart = true
stdout_logfile = /usr/local/logs/gmcServer_std.log

I already set autorestart.

**Comment by FAKERINHEART** [comment]
change config from `autorstart` to `autorestart`

**Comment by zhangketing** [comment]
Hello，I want to ask a question, Golang progress exited abnormal.
supervisord logs ：(exit status 2; expected). supervisord did not attempt to start the progress.

**Comment by julien6387** [comment]
Hello,
By default, exit code 2 is expected.
You have to update the related ini file with:
exitcodes=0
Default value is 0,2 as explained in
http://supervisord.org/configuration.html#program-x-section-values


2017-11-08 10:26 GMT+01:00 zhangketing <notifications@github.com>:

**Comment by zhangketing** [comment]
That is OK,Thank You very much.I will try again
