### ISSUE TITLE
unexpected keyword argument 'wait'

### ISSUE THREAD

**Issue by aleperno** [Supervisor/supervisor#1012]
I'm preforming some tests to interact with supervisor through Python

```python
from supervisor import childutils

env = {
 'SUPERVISOR_SERVER_URL':"unix:///var/run/supervisor.sock",
 'SUPERVISOR_USERNAME':"",
 'SUPERVISOR_PASSWORD':""
}
x = childutils.getRPCInterface(env)
x.supervisor.startProcess('myprocess', wait=True)  
```
This raises

```
TypeError: __call__() got an unexpected keyword argument 'wait'
```

Is there anything I'm doing wrong? According to the docs, the versions do support the 'wait' argument.

Versions
Python 2.7.6
Supervisor (lib) 3.3.3
Supervisor 3.0b2-1

**Comment by mnaberez** [comment]
> ```
> x = childutils.getRPCInterface(env)
> x.supervisor.startProcess('myprocess', wait=True)  
> ```
>
> This raises
>
> TypeError: __call__() got an unexpected keyword argument 'wait'


`getRPCInterface` returns a [`ServerProxy`](https://docs.python.org/2/library/xmlrpclib.html#xmlrpclib.ServerProxy) for communicating with `supervisord` via XML-RPC.  The XML-RPC protocol does not support keyword arguments.  Call it using positional arguments:

```
x.supervisor.startProcess('myprocess')               # True is the default

x.supervisor.startProcess('myprocess', True)  
```

**Comment by aleperno** [comment]
Gee, thanks @mnaberez for the prompt response
