### ISSUE TITLE
cannot get [include.files] to work

### ISSUE THREAD

**Issue by ORESoftware** [Supervisor/supervisor#1017]
This is kinda nasty. I just want to include the $HOME env variable in my conf

https://stackoverflow.com/a/47301185/7898461

The problem is that if I use this:

```
[include]
files = %(ENV_HOME)/.suman/global/node_modules/suman-daemon/sup.conf
```

I get this error:

`Error: Format string '%(ENV_HOME)/.suman/global/node_modules/suman-daemon/sup.conf' for 'include.files' is badly formatted: unsupported format character '/' (0x2f) at index 11 For help, use /usr/local/bin/supervisord -h`

then I do this:

```
[include]
files = %(ENV_HOME).suman/global/node_modules/suman-daemon/sup.conf
```

I get _no error_ with the latter, but it doesn't work either, supervisor doesn't actually pick up the sup.conf file.

Things do work, if I just hardcode the path:

```
[include]
files = /Users/alexamil/.suman/global/node_modules/suman-daemon/sup.conf
```

TBH this is not very user-friendly, I see some room for improvement. :(

**Comment by mnaberez** [comment]
The syntax is`%(ENV_HOME)s` not `%(ENV_HOME)` as you have above.  See the [documentation](http://supervisord.org/configuration.html#environment-variables) for examples.

We use this issue tracker mainly for bugs in Supervisor itself.  Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.

**Comment by ORESoftware** [comment]
Wow, that's pretty gnarly syntax. It's probably too late, but one thing you could have done is launch a child process with bash and then echo back the string, in Node.js that would be:

```js
const cp = require('child_process');
const k = cp.spawn('bash');
k.stdout.on('data', handleStdout);   // read-in the bash stdout
k.write('echo "$HOME"');
k.end('\n');
```

that way you can let bash interpret the string for you. Of course, there's a 50ms penalty for starting up a child process, but it's worth it. Next time, lol.
