### ISSUE TITLE
Support question - how to add .conf files to an already-running supervisord process

### ISSUE THREAD

**Issue by ORESoftware** [Supervisor/supervisor#1018]
Say that supervisord is already launched. How can I add a new .conf file? I want supervisord to launch and monitor a new/nominal process.

if I do:

`supervisorctl add my.conf`

or 

`supervisord add my.conf`

it gives me errors,
`ERROR: no such process/group: my.conf`

Hopefully the question is clear - since I am such a supervisord newb, it's hard for me to better explain it.

**Comment by ORESoftware** [comment]
I asked a similar question on StackOverflow if someone wants an upvote - https://stackoverflow.com/questions/47300888/add-new-service-to-existing-supervisord-process

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by ORESoftware** [comment]
no prob thanks
