### ISSUE TITLE
supervisord.org website down

### ISSUE THREAD

**Issue by ygbr** [Supervisor/supervisor#1021]
Hi guys,

I have just noticed the website (supervisord.org) is down (pending domain renewal).

Just pinging here so the responsible for the domain can be notified.

**Comment by mnaberez** [comment]
@mcdonc owns the supervisord.org domain and only he has access to it.  @mcdonc?

**Comment by function10** [comment]
Looks like a work around for now in case anyone needs the docs: http://supervisord.readthedocs.io/en/stable/introduction.html

**Comment by mnaberez** [comment]
https://twitter.com/chrismcdonough/status/933157441344286720
