### ISSUE TITLE
Pass arguments to program when starting a job?

### ISSUE THREAD

**Issue by mpdude** [Supervisor/supervisor#1023]
Is is possible to pass (additional) arguments to a program when starting a job?

Like `supervisorctl start myprogram extra-arg-1 extra-arg-2`?

I'd like `supervisord` to monitor a couple of jobs, but the arguments are not known until the program has to be started.

In case this should be possible (and I missed the docs section?), can several instances of a single program with different arguments run concurrently?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by mpdude** [comment]
Oops, sorry!

**Comment by gusostow** [comment]
(Replying here because it looks like the mailing list has been down for quite some time.)

Is there any plan to add this feature? Would it be a welcome contribution?

**Comment by iahim** [comment]
Why not create a YAML file where you add these parameters and your program/app will read that file each time it is started?

**Comment by claudiombsilva** [comment]
@mnaberez The mailing list is down.
If we can't request features here, then where can we request them?
