### ISSUE TITLE
supervisor controlled program can't connect more than 1000 sockets

### ISSUE THREAD

**Issue by LinAndy** [Supervisor/supervisor#1025]
Issue:
I have a program which is controlled by supervisor , my program will use more than 1000  tcp sockets (in child process).
Now the problems is:  when sockets connection increase to 1000+,  CPU occupation of my program is very high （200%+） (not supervisord itself), and the TCP sockets connections abnormal (many connections is in closing state and some new sockets created)

More:
1. The CPU is very low if the socket connection is less than 1000.
2. If my program run with no supervisor ctrl, then everything is OK, my programme can connect 3000+ tcp sockets with no low CPU.
3. I checked supervisor log but found no abnormal.
4, I suspect it's related related change below fix, but my tested version included thsi change.
"3.3.0 (2016-05-14)
supervisord will now use kqueue, poll, or select to monitor its file descriptors, in that order, depending on what is available on the system. Previous versions used select only and would crash with the error ValueError: filedescriptor out of range in select() when running a large number of subprocesses (whatever number resulted in enough file descriptors to exceed the fixed-size file descriptor table used by select, which is typically 1024). Patch by Igor Sobreira."

Env:
CentOS Linux release 7.2.1511
supervisor-3.3.1-2.el7.noarch  (I also tried supervisor-3.1.3-3.el7.noarch, the same result)
python-libs-2.7.5-58.el7.x86_64
python2-meld3-1.0.2-4.el7.noarch
python-setuptools-0.9.8-7.el7.noarch

ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63471
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63471
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

My supervisor conf is simple:
[program:ar1]
command=xxxx
directory=xxxx
autorestart=true
user=root
stdout_logfile=NONE
stderr_logfile=xxxxx
environment=LD_LIBRARY_PATH="/usr/local/lib"
priority=510

Please help to check and tell me if more information required.

**Comment by mnaberez** [comment]
> 4, I suspect it's related related change below fix, but my tested version included thsi change.
"3.3.0 (2016-05-14)
supervisord will now use kqueue, poll, or select to monitor its file descriptors, in that order, depending on what is available on the system. Previous versions used select only and would crash with the error ValueError: filedescriptor out of range in select() when running a large number of subprocesses (whatever number resulted in enough file descriptors to exceed the fixed-size file descriptor table used by select, which is typically 1024). Patch by Igor Sobreira."

Why do you suspect it is related to that change?  Were you using a version of Supervisor before 3.3.0 and did not have an issue, but then you upgraded to 3.3.0 and you have an issue?

**Comment by LinAndy** [comment]
@mnaberez Thank you for your reply and sorry for this confusion. In fact, i found this issue on 3.1.3 firstly，i thought it was related with that change because of 1024 fd limitation. But i'am wrong. After version upgraded to 3.3.1,issue is still there.

**Comment by LinAndy** [comment]
Anyone others had this issue?  Are there some workaround way with Supervisor ? Thanks a lot

**Comment by wgw335363240** [comment]
find supervisord pid
   ps -ef|grep supervisord
cat /proc/$pid/limits
check open files and max user processes

**Comment by LinAndy** [comment]
@ wgw335363240, you are correct, my Centos version have this problem. The system wide service did not use the configuration in  /etc/security/limits.conf. :-(
Thank you very much.
