### ISSUE TITLE
variables in /etc/default/supervisor are not loaded in debian 9

### ISSUE THREAD

**Issue by carlware** [Supervisor/supervisor#1033]
In Debian 7 i set my env variables in the file '/etc/default/supervisor'
like:
`export MY_ENV="hello"`
and everything was working as I expected in any subprocess

Now, I am trying to do the same in Debian 8 but is not working anymore, the only workaround is put the env variables in '/etc/supervisor/supervisord.conf' with `environment=`

package details with apt-cache:
Debian 7:
```
supervisor:
  Installed: 3.0a8-1.1+deb7u1
  Candidate: 3.0a8-1.1+deb7u2
```

Debian 9:
```
supervisor:
  Installed: 3.3.1-1+deb9u1
  Candidate: 3.3.1-1+deb9u1
```

**Comment by mnaberez** [comment]
Please report this issue to the maintainers of the Debian package you are installing.  

The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.python.org/pypi/supervisor).  We do not build any of the OS-specific packages such as those for Debian.  Our Python packages do not have any OS integration, so we can't affect how `/etc/default/supervisor` works.  The issue can only be addressed by the maintainers of the specific package you are installing.
