### ISSUE TITLE
connection refused error 

### ISSUE THREAD

**Issue by maxfu9** [Supervisor/supervisor#1037]
getting following error

supervisorctl
http://127.0.0.1:9001 refused connection

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

The error message above probably indicates that either `supervisord` was not running at the time `supervisorctl` tried to connect, or that `supervisord` was configured to use a different port than `supervisorctl` was configured to use.
