### ISSUE TITLE
supervisor cannot see my system variables

### ISSUE THREAD

**Issue by mkingbe** [Supervisor/supervisor#1038]
Hello, 

I'm trying to deploy a dockerized supervisor with some jobs that trigger php code.
However the system variables are not passed to the php script. 

I did searches and searches and I din't find any solution. 
I tried this (in supervisord.conf, also in my job files): 
environment=APP_ENV=%(ENV_APP_ENV)s,APP_DEBUG=%(ENV_APP_DEBUG)s

And I received:

`Starting supervisor: Error: Format string 'APP_ENV=%(ENV_APP_ENV)s,APP_DEBUG=%(ENV_APP_DEBUG)s' for 'environment' contains names ('ENV_APP_ENV') which cannot be expanded. Available names: ENV_LANG, ENV_LANGUAGE, ENV_LC_ADDRESS, ENV_LC_ALL, ENV_LC_COLLATE, ENV_L
C_CTYPE, ENV_LC_IDENTIFICATION, ENV_LC_MEASUREMENT, ENV_LC_MESSAGES, ENV_LC_MONETARY, ENV_LC_NAME, ENV_LC_NUMERIC, ENV_LC_PAPER, ENV_LC_TELEPHONE, ENV_LC_TIME, ENV_PATH, ENV_PWD, ENV_TERM, group_name, here, host_node_name, process_num, program_name in section`

Could you please help me in order to pass the env in sub-processes?! 
  
`supervisord -v
3.3.1
`

**Comment by mkingbe** [comment]
problem solved, seems that if you run supervisor as a service it will not load env variables... you need to run it standalone supervisord - c /etc/supervisor/supervisord.conf

**Comment by Var-iazioni** [comment]
Is this a bug? I need run supervisor as a service.

**Comment by chrisbjr** [comment]
Thanks for this. Been searching all over the web. Good thing i chanced upon this issue.

I was running supervisor in my entrypoint as `service supervisor start` and it wouldn't see the system environment variables.

Running `supervisord -c /etc/supervisor/supervisord.conf` fixed it.
