### ISSUE TITLE
State transition can take far too long if system clock is set to an earlier time

### ISSUE THREAD

**Issue by jleveque** [Supervisor/supervisor#1043]
If the system clock is set to an earlier time after a process is started but before it has entered the `RUNNING` state, `supervisorctl start <process_name>` can hang for a very long time waiting for the current system time to become greater than `self.laststart + self.config.startsecs`, depending on how far backward the system time has moved.

I have resolved the issue with the following modification to the `transition()` function in process.py:

```
def transition(self):
    now = time.time()
    state = self.state

    logger = self.config.options.logger

    # If system clock has moved backward, reset self.laststart to current system time
    if now < self.laststart:
        self.laststart = now;

   ...
```

This solution still ensures that the process has remained running for at least `self.config.startsecs` while only increasing the maximum wait time to `2 * self.config.startsecs` if the system clock is detected to have moved backward.

As I'm not too familiar with this code, I'm not sure if this is the best solution, nor am I sure if any other functions may require a check of this nature as well, so I figured I would leave this suggestion here and let a Supervisor dev who is more familiar with the code base decide on the most appropriate solution.

Please let me know if I can be of further assistance.

**Comment by mnaberez** [comment]
What version of Supervisor are you using (`supervisord --version`)?

**Comment by jleveque** [comment]
Version 3.3.2

**Comment by jleveque** [comment]
To add more context, this is definitely a separate issue from https://github.com/Supervisor/supervisor/issues/802. It appears the HTTP response issue has since been fixed; this is a separate issue which can present similar symptoms.

**Comment by jleveque** [comment]
I pushed some changes to my PR (https://github.com/Supervisor/supervisor/pull/1047) a few weeks ago in an attempt to address your comments. Please review the latest changes when you have a moment.
