### ISSUE TITLE
When changing a process of a group, reloadConfig returns the group, not the process 

### ISSUE THREAD

**Issue by palmkevin** [Supervisor/supervisor#105]
When changing a process of a group in the supervisor configuration file, than `reloadConfig` indicates that the `group` has changed, not the `process`. (The group's name is returned)
I wonder if this behavior is intentional or if it is a failure? IMHO the current behavior is incorrect ...

**Comment by mikeyg123** [comment]
-1
I like the current behavior. The group is the primary unit of configuration.  (If you don't specify a group for a program then one is created implicitly with the same name.)
How else could it work?  What if you changed a group's members but not any of the programs?

**Comment by mnaberez** [comment]
Based on the current implementation of supervisord, I don't see how this could be changed.
