### ISSUE TITLE
View logs conveniently with supervisorctl

### ISSUE THREAD

**Issue by kootenpv** [Supervisor/supervisor#1050]
Is there a form of:

    supervisorctl logs myservice

Which would just be like a "tail -f" to the stdout or stderr file read from config.

**Comment by mnaberez** [comment]
`supervisorctl tail -5000 procname stderr` will read the last 5000 bytes from the stderr log for procname.  See `help tail` for other examples.

**Comment by kootenpv** [comment]
Thanks, I hadn't seen tail (I've only scanned the args), but I see it now under actions. Perhaps `logs` could be added as an alias? Just a suggestion. Very happy that I can use it.

**Comment by timotheecour** [comment]
IIUC it's `tail -f` not `tail`, otherwise doesn't seem to work
