### ISSUE TITLE
Why supervisor faild to start the program ?

### ISSUE THREAD

**Issue by BibhuGlobussoft** [Supervisor/supervisor#1051]
I am working with laravel queue jobs and using supervisor to manage workers. I have more than one numprocs which working perfectly for some days and then all the programs or workers goes to **FATAL STATE** after that they are not processing any job and the supervisor **goes down** even if the supervisor in **active state**.
Then we need to restart the Supervisor to start processing again. But this is not a proper solution for this as we are not be there to check its working or not.
My config file like this

`[program:name]        
process_name=%(program_name)s_%(process_num)02d 
command=php /path/artisan queue:work --queue=queue1,queue2,queue3,queue4,default --tries=1 --daemon 
autostart=true 
autorestart=true 
startretries=15 
numprocs=150 
user=root 
redirect_stderr=true 
stdout_logfile=/path/worker.log 

stderr_logfile=/path/workerError.log`

My question is why supervisor fail to start and what is the solution for that ?

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by BibhuGlobussoft** [comment]
Okay but supervisor is not able to start the program and the process remain in-active until we restart the supervisor again manually so this is an issue of supervisor only.
So have you any idea to solve this one?
why it is breaking ?
