### ISSUE TITLE
Log configuration reload and process groups added/removed

### ISSUE THREAD

**Issue by felipou** [Supervisor/supervisor#1055]
Shouldn't supervisor log something when its configuration is reloaded, and when process groups are added or removed? This seems like critical information to me, it would really help us understand what's going on.

I can create a pull request adding such logs, would this feature be accepted?

**Comment by mnaberez** [comment]
That sounds reasonable.  We'd review a pull request for that.  Thanks!

**Comment by felipou** [comment]
Done: https://github.com/Supervisor/supervisor/pull/1056
It was surprisingly easy, but I'm not sure everything is according to supervisor standards.
