### ISSUE TITLE
Unable to start Docker container when it is stopped or crashed

### ISSUE THREAD

**Issue by samudrala11** [Supervisor/supervisor#1059]
I am trying to maintain Docker Containers using `supervisord`. I have three containers running. Configured three containers to `Supervisord`. When I hit `docker stop static-site`, `supervisorctl` is not starting container . Below are my config files:

>cat /etc/supervisor/conf.d/supervisord.conf:
```
[unix_http_server]
file=/var/run/supervisor.sock
chmod=700

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
logfile_maxbytes=10MB
logfile_backups=2
loglevel=info
minfds=2048
minprocs=100

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
```
>cat /etc/supervisor/conf.d/static-site.conf:
```
#Site-1 container
[program:static-site]
command=docker start static-site
autostart=true
autorestart=true
startsecs=20
startretries=5
exitcodes=0,2,127,200

#Log file location
stdout_logfile=/var/log/docker/static-site.log
stderr_logfile=/var/log/docker/static-site-error.log

#Log files rotation
logfile_maxbytes=20MB
logfile_backups=2
```
Not sure where I am going wrong. Do we have any way for `Supervisord` to maintain Docker Containers specifically?

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
