### ISSUE TITLE
Supervisord automatically shut down and exit when a particular managed program exits?

### ISSUE THREAD

**Issue by Omnifarious** [Supervisor/supervisor#1062]
This is a question. :smile:

I, like many, want to use supervisord in a Docker container. This Docker container has a primary application and a couple of support daemons. When the primary application stops (normally or abnormally), I want every support daemon to be killed and for supervisord to exit.

Does supervisord support this directly? If not, is there a recommended way to make this happen?

Thank you.

**Comment by mnaberez** [comment]
Duplicate of #712
