### ISSUE TITLE
Why hard links ?

### ISSUE THREAD

**Issue by SaavdhaanCyber** [Supervisor/supervisor#1067]
os.link is necessary ? Can os.symlink can be used (I think easily ) but I want to know from you

**Comment by mnaberez** [comment]
Some context would be useful, such as the file/line you're asking about.

**Comment by lkdevil** [comment]
https://github.com/Supervisor/supervisor/blob/70720a0311d868fbf58a31cd26a7147921dcff29/supervisor/http.py
Line no. 578

**Comment by FAKERINHEART** [comment]
@lkdevil @mnaberez The system hard link of socket codes in supervisord, which is referenced by @lkdevil, is the reason that partially causes the overylay fs system can not use supervisord. [https://github.com/moby/moby/issues/12080](url)

**Comment by rqcy** [comment]
Yes, please merge the PR #1069 !

1. os.rename is cleaner, shorter and easier to understand in code than os.link/os.unlink, unless there's some good reason to use the later one. For reference: https://stackoverflow.com/questions/18653112/which-is-costlier-rename-or-link-and-unlink-in-c

2. I've recently installed supervisor in Termux on Android and Python there does not support os.link, but does support rename. After this change, I could use supervisor in Termux via pip.

Thanks for your work!

**Comment by mnaberez** [comment]
`os.link()`
```
$ touch foo
$ touch bar
$ python -c "import os; os.link('foo', 'bar')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 17] File exists
$
```

`os.rename()`
```
$ touch foo
$ touch bar
$ python -c "import os; os.rename('foo', 'bar')"
$ ls
bar
```

`os.link()` guarantees the destination filename does not exist.  `os.rename()` overwrites it.  Changing from `os.link()` to `os.rename()` would no longer have the guarantee that the socket file does not exist.  A check like `os.path.exists()` would need to be added before it, and then the code would no longer be atomic.  A race condition would then be possible, which likely has security implications.

I'd rather not change anything here.  Supporting systems without hard links is not a goal of this project, sorry.  `supervisorctl` can communicate with `supervisord` over both a UNIX domain socket (what this code is for) or over a TCP socket.  Perhaps a TCP socket bound to localhost could be used instead.
