### ISSUE TITLE
Supervisor 4 release date? 

### ISSUE THREAD

**Issue by 61t** [Supervisor/supervisor#1070]
Master, any plan or release date for supervisor 4 with full support of python 3?

**Comment by mnaberez** [comment]
Duplicate of #1060

**Comment by 61t** [comment]
@mnaberez I checked above duplicate. Just want to now ETA as next important feature of my project that is based on python 3, is depending on supervisor 4 support. I am absolutely new to supervisor, but really want to know if it is practical to test supervisor 3 from now on, or wait a couple of weeks until Supervisor 4 released.
