### ISSUE TITLE
Killing process in STOPPING state

### ISSUE THREAD

**Issue by mihirk11** [Supervisor/supervisor#1073]
I don't want supervisor to automatically kill my process after stopwaitsecs. So I pass TERM signal with stopwaitsecs=600 (sufficient large value). But, this makes me wait for 600 secs or kill process from outside supevisor in cases when I legitimately want to kill process after issuing stop command. 

This happens because supervisor does not kill process in STOPPING state. 

Feature to send kill signal to process in STOPPING state would be nice.

**Comment by mnaberez** [comment]
Duplicate of #734
