### ISSUE TITLE
cronolog with supervisor

### ISSUE THREAD

**Issue by sgoogal** [Supervisor/supervisor#1074]
Our supervisor config is as below, how can we rotate our log files mentioned here using cronolog, we definitely want to use cronolog but not sure how to change the supervisor conf to use cronolog, kidnly help us

stderr_logfile=/var/log/supervisor/82stderr.log
stdout_logfile=/var/log/supervisor/82stdout.log

[program:abc-82]
command=java -server -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=50M -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:+UseG1GC -XX:MaxGCPauseMillis=256 -XX:InitiatingHeapOccupancyPercent=75 -XX:+UseTLAB -XX:+ResizeTLAB -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+UseBiasedLocking -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseFastAccessorMethods -XX:+HeapDumpOnOutOfMemoryError -Dsun.net.inetaddr.ttl=60 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Xms1024m -Xmx1024m -Xloggc:/abc-82/gc.log -XX:ErrorFile=/abc-82/java-%%p.log -XX:HeapDumpPath=/abc-82/java-%%p.hprof -DLOG_FILE=/abc-82/java.log -jar /opt/xyz/abc-82/current/abc.jar  --spring.config.location=/abc/xyz/1.1.3-dir/config/app.yaml --logging.config=/opt/xyz/abc/1.2.3.dir/config/logback.groovy
process_name=%(program_name)s
numprocs=1
numprocs_start=0
priority=999
autostart=true
autorestart=true
startsecs=1
startretries=3
exitcodes=0,2
stopsignal=TERM
stopwaitsecs=10
user=abc
redirect_stderr=false
stdout_logfile=/var/log/supervisor/82stdout.log
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stdout_capture_maxbytes=0
stdout_events_enabled=false
stderr_logfile=/var/log/supervisor/82stderr.log
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
stderr_capture_maxbytes=0
stderr_events_enabled=false
directory=/opt/xyz/abc-82/1.2.3.4-dir
serverurl=AUTO

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
