### ISSUE TITLE
[Feature] Configurable http templates dir (html, css and js)

### ISSUE THREAD

**Issue by cunhaax** [Supervisor/supervisor#1077]
I have a real usecase for this (and a working implementation)
At my company we have a distributed software solution with several components that need to be running and monitored.
All the software is installed on client's machines (including supervisor).
It is a nice to have, to be able to customize the style of the http status page, and we really want to hide the 'restart all' and 'stop all' buttons.

The modification is just to allow setting a directory  where all the UI files live.
Would you accept a PR for this?
Thanks

**Comment by mnaberez** [comment]
I don't think so, sorry.  This isn't something that would be used by many users, and I don't think we want to commit to supporting such a feature long term.  We might change the templating system or remove it entirely.  Please continue to use your own fork of Supervisor if you need this, or write another program to provide the front end you need.

**Comment by cunhaax** [comment]
Ok, no problem, thanks anyway for the quick reply!
