### ISSUE TITLE
Invalid seek when using logfile = /dev/stdout

### ISSUE THREAD

**Issue by enumag** [Supervisor/supervisor#1078]
When running supervisor in docker it would be useful to simply write all log entries into `/dev/stdout` instead of a file. This doesn't work at the moment.

```
[supervisord]
logfile = /dev/stdout
```

Causes this error (using supervisor 3.3.4):

```
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/bin/supervisord", line 11, in <module>
api_1       |     load_entry_point('supervisor==3.3.4', 'console_scripts', 'supervisord')()
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 357, in main
api_1       |     go(options)
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 367, in go
api_1       |     d.main()
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 71, in main
api_1       |     self.options.make_logger()
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1430, in make_logger
api_1       |     self.logger.info(msg)
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 275, in info
api_1       |     self.log(LevelsByName.INFO, msg, **kw)
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 293, in log
api_1       |     handler.emit(record)
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 186, in emit
api_1       |     self.doRollover()
api_1       |   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 211, in doRollover
api_1       |     if not (self.stream.tell() >= self.maxBytes):
api_1       | IOError: [Errno 29] Invalid seek
```

**Comment by mnaberez** [comment]
From http://supervisord.org/configuration.html:
> `logfile_maxbytes`
> 
> The maximum number of bytes that may be consumed by the activity 
> log file before it is rotated (suffix multipliers like “KB”, “MB”, 
> and “GB” can be used in the value). Set this value to 0 to indicate 
> an unlimited log size.
> 
> Default: 50MB

You haven't specified `logfile_maxbytes` in your configuration, so it is using the default of 50MB.  You have log rotation enabled but that doesn't make sense for `/dev/stdout`.  Setting `logfile_maxbytes = 0` will stop `supervisord` from trying to seek the file.

**Comment by enumag** [comment]
Indeed this helps. Thank you!

**Comment by browseman** [comment]
IMHO - this dependency should be written in the documentation. Just had the same issue and heading to report the same issue, but manage to find it before hand. Probably it will be very useful for many others docker adopters.

Thanks in advance and sorry if this is not the correct place to write my statement.

**Comment by pe224** [comment]
@mnaberez 
This error is resurfacing in `4.0.0.dev0` on Python 3.7.1

Setting `logfile_maxbytes=0` is not helping, as `loggers.handle_file` [is always called](https://github.com/Supervisor/supervisor/blob/e0d548c649b6c21077ac966616005dc017f03ddf/supervisor/options.py#L1448-L1455) with `rotating=True`

It then uses `RotatingFileHandler(filename, 'a', maxbytes, backups)` [here](https://github.com/Supervisor/supervisor/blob/77ded5a597f29ad71b74228e49558c3f64726dcb/supervisor/loggers.py#L417) with `mode='a'`.

The [fix for handling the special case](https://github.com/Supervisor/supervisor/blob/77ded5a597f29ad71b74228e49558c3f64726dcb/supervisor/loggers.py#L158-L169) of `dev/stdout` is, however, only called for `mode='ab'` not for `mode='a'`.
