### ISSUE TITLE
%(host_node_name)s missing in [supervisord] config section

### ISSUE THREAD

**Issue by devenoges** [Supervisor/supervisor#108]
possible?

**Comment by kodefear** [comment]
```
[supervisord]
logfile = /vagrant/logs/%(host_node_name)s/supervisord.log
loglevel = info``
```
Version : 3.2.0
Getting the following error , still not allowing to expand 

> %(host_node_name)s

> Error: Format string '/vagrant/logs/%(host_node_name)s/supervisord.log' for 'supervisord.logfile' contains names ('host_node_name') which cannot be expanded. Available names: ENV_DEV_SITE_CONFIG_PATH, ENV_DOCKER_COMPOSE_CENTOS_6_BUILDER_CACHE, ENV_DOCKER_COMPOSE_CENTOS_7_BUILDER_CACHE, ENV_DOCKER_COMPOSE_UBUNTU_14_BUILDER_CACHE, ENV_DOCKER_COMPOSE_UBUNTU_16_BUILDER_CACHE, ENV_GRADLE_HOME, ENV_HOME, ENV_JAVA_HOME, ENV_LANG, ENV_LESSCLOSE, ENV_LESSOPEN, ENV_LOGNAME, ENV_LS_COLORS, ENV_MAIL, ENV_OLDPWD, ENV_PATH, ENV_PWD, ENV_SHELL, ENV_SHLVL, ENV_SSH_AUTH_SOCK, ENV_SSH_CLIENT, ENV_SSH_CONNECTION, ENV_SSH_TTY, ENV_TERM, ENV_TRIFACTA_CONF, ENV_USER, ENV_USER_GID, ENV_USER_UID, ENV_XDG_RUNTIME_DIR, ENV_XDG_SESSION_ID, ENV__, here

Even the documentation does not say for supervisord section name , is it possible ?
