### ISSUE TITLE
Stability of Supervisord 4 with Python3?

### ISSUE THREAD

**Issue by Encrypt** [Supervisor/supervisor#1083]
Hello,

First of all, I recently discovered supervisor and I have had to opportunity to test it.
I have to say you did a great job guys! :+1: 

I am interested in using it on production servers since it offers a lot of advantages compared to the tools we are currently using. We have Python 3 on all servers but we only have Python 2.7 on **a few** servers (and we can't easily "fix" that).

Moreover, I have understood, version 4 (unealeased) of supervisord is the only version to support Python3.

Therefore, I have two questions:
- How stable is Supervisor v4, used with Python3? Would you use it on production servers?
- When do you plan to release version 4 of Supervisor?

Thanks in advance four your answers!

**Comment by mnaberez** [comment]
Duplicate of #1060

**Comment by Encrypt** [comment]
Whoops, sorry!

Thanks for your help :smile:
