### ISSUE TITLE
pip install supervisor fail on centos

### ISSUE THREAD

**Issue by abc19899** [Supervisor/supervisor#1087]
output contains error but report success, is there any bug?

DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting supervisor
/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Downloading supervisor-3.3.4.tar.gz (419kB)
    100% |████████████████████████████████| 419kB 55kB/s 
Requirement already satisfied: meld3>=0.6.5 in /usr/lib64/python2.6/site-packages (from supervisor)
Building wheels for collected packages: supervisor
  Running setup.py bdist_wheel for supervisor ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HHLe9z/supervisor/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8Mi2Gupip-wheel- --python-tag cp26:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-HHLe9z/supervisor/setup.py", line 86, in <module>
      'pidproxy = supervisor.pidproxy:main',
    File "/usr/lib/python2.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python2.6/distutils/core.py", line 138, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 439, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib64/python2.6/distutils/dist.py", line 460, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 754, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib64/python2.6/distutils/dist.py", line 518, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 574, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2422, in load
      return self.resolve()
    File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2428, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
      ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                     ^
  SyntaxError: invalid syntax
  
  ----------------------------------------
  Failed building wheel for supervisor
  Running setup.py clean for supervisor
Failed to build supervisor
Installing collected packages: supervisor
  Running setup.py install for supervisor ... done
Successfully installed supervisor-3.3.4

system:
cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m

python --version
Python 2.6.6

pip --version
pip 9.0.3 from /usr/lib/python2.6/site-packages (python 2.6)

**Comment by mnaberez** [comment]
> File "/usr/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
> ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
> ^
> SyntaxError: invalid syntax

This error is not from the Supervisor package, it's from the tools trying to install it.  The error [looks like](https://github.com/pypa/wheel/blob/0.30.0/wheel/bdist_wheel.py?utf8=%E2%9C%93#L407) code from [pypa/wheel](https://github.com/pypa/wheel).  From their [`setup.py`](https://github.com/pypa/wheel/blob/0.30.0/setup.py#L25-L26), it looks like they do not support Python 2.6 anymore.

You may still be able to install Supervisor 3.x on a system with Python 2.6 by [downloading](https://pypi.python.org/pypi/supervisor/3.3.4) the package tarball and running `python setup.py install`.
