### ISSUE TITLE
Supervisord uses unidentificated disk space

### ISSUE THREAD

**Issue by Anon0511** [Supervisor/supervisor#1089]
Hello,

this is a business related question. 
Our production system was about to run full of disk space today and we weren't able to identify where more than 1GB of space was going since du -sh only reported about 3GB. 
We decided to clean the child-process log in the /tmp-dir which was about 200MB by restarting supervisord but it somehow actually freed 1,5GB of space.
Can someone hit me up where these files are and what they do since they clearly came from supervisord? We already configured a daily restart of supervisord now to prevent this situation in the future.

We are running supervisord 2.1 (yeah, it is old..)

Greets

**Comment by mnaberez** [comment]
`supervisord` reads a [configuration file](http://supervisord.org/configuration.html).  The options you have configured there determine where logs are written and whether `supervisord` will rotate them or not.

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
