### ISSUE TITLE
Unable to launch waves script 

### ISSUE THREAD

**Issue by netrosec** [Supervisor/supervisor#1096]
I use supervisor to run about 6 startup scripts. The services start fine. But I then noticed that the scripts that had to do with calling a wav sound file did not work. 

checking the status of supervisor I see that all my scripts are running yet the wav scripts fail to launch. 
how can I fix this problem?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
