### ISSUE TITLE
How to make Supervisor reopen logs for of one the managed processes?

### ISSUE THREAD

**Issue by mindojo-victor** [Supervisor/supervisor#1098]
I deleted a log file of one the managed processes (stdout). Supervisor is still writing the logs into it.

I want to recreate the log file right now, but I can't afford to restart the process (for example because I don't want downtime).

Is it possible to make Supervisor reopen logs for a process?

Another wish is to be able to tell Supervisor to reopen the log file(s) while the closed logs to be renamed.

This would be useful for backing up the logs. I would tell Supervisor to reopen the log and then would compress, back up and delete the old one. I need this because `logrotate` fails sometimes: `gzip: stdin: file size changed while zipping`. `delaycompress` option for `logrotate` doesn't suit me, because I need to clean disk space right now by reopening the logs and backing up the old ones, then deleting them.

So it's like `stdout_logfile_maxbytes` but on demand.

**Comment by mnaberez** [comment]
> Is it possible to make Supervisor reopen logs for a process?

[`SIGUSR2`](http://supervisord.org/running.html#signal-handlers)

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by Gourds** [comment]
Good Job

**Comment by pushp1997** [comment]
Hi, I too am facing the same issue, I deleted the log file and now supervisor is not creating the log file again and writing logs into it, I tried to create the log file manually, but supervisor doesn't writes the log to it. Is there a way around for this? I do not want to restart the process because of the downtime.

**Comment by lonix1** [comment]
For anyone else who stumbles on this, for completeness in case it's not obvious, the command is:

````sh
kill -s SIGUSR2 $(cat /var/run/supervisord.pid)     # pid file defined in /etc/supervisor/supervisord.conf
````
