### ISSUE TITLE
unable set environment end or start with quote

### ISSUE THREAD

**Issue by xinke2411** [Supervisor/supervisor#1102]
Config program as 
```
[program:cat]
command=/bin/cat
environment=A="1",B='"2"'
``` 

I want get environment `B = '2'` or `B = "2"`, but quote is striped, how to set environment end or start with quote?
https://github.com/Supervisor/supervisor/blob/85558b4c86b4d96bd47e267489c208703f110f0f/supervisor/datatypes.py#L84

**Comment by No1zzz** [comment]
Supervisor still can't get env from os directly?

**Comment by mnaberez** [comment]
Duplicate of #328
