### ISSUE TITLE
Supervisord doesn't start the process when I have program listening on STDIN

### ISSUE THREAD

**Issue by man0l** [Supervisor/supervisor#1107]
I am invoking the worker with this command

`rabbitmq-cli-consumer -e "/usr/bin/php app/console worker:multivariation_products:fetch:save --env=prod" -c rabbit/proceed_parsed_multivariation_product.conf.dist --pipe
`
The option --pipe listens on STDIN for rabbitMQ messages, but unfortunately supervisor does not start the processs at all. If I start it manually it works great.

Is it possible to make it work, is it a configuration issue?
Thank you for your answers in advance,
Regards, 
Manol.

**Comment by mnaberez** [comment]
Config file with a program that listens on `stdin`:
```
[supervisord]
loglevel = debug

[program:cat]
command = /bin/cat
```

Start `supervisord` in the foreground with that config:
```
$ supervisord -n -c supervisord.conf
2018-06-13 07:53:34,602 INFO Increased RLIMIT_NOFILE limit to 1024
2018-06-13 07:53:34,606 INFO supervisord started with pid 10350
2018-06-13 07:53:35,609 INFO spawned: 'cat' with pid 10353
2018-06-13 07:53:36,611 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Above, `supervisord` starts the program and it stays up.  `supervisord` is able to run a program that listens on `stdin`.  

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
