### ISSUE TITLE
Supervisor workers not responding to jobs in queued.

### ISSUE THREAD

**Issue by BibhuGlobussoft** [Supervisor/supervisor#1113]
I am using supervisor3.3.4 in one of my live project with laravel 5.2v queue and redis, which is working fine for 15-25 days then it stop processing due to which jobs are remain in redis queue only. When I have checked the worker log it is look like [ This ](http://prntscr.com/jzhfnx ) full with 200200

> 200200200200200200200200200200200200200200200200200200200[2018-06-26 05:32:42] Processed: App\Jobs\WebhookHandler
200200200200200200200200200200200200200200200200200200200200200200200200200200200[2018-06-26 05:33:02] Processed: App\Jobs\WebhookHandler
200200200200200200200200200200200200200200200200200200200[2018-06-26 05:33:22] Processed: App\Jobs\WebhookHandler

Here is my configuration file
```
[program:laravelworker]          
process_name=%(program_name)s_%(process_num)02d  
command=php /home/path/artisan queue:work --queue=queue1,queue2,queue3,queue4,default --tries=1 --daemon  
autostart=true  
autorestart=true  
startretries=25  
startsecs=0  
numprocs=150  
user=root  
redirect_stderr=true  
stdout_logfile_maxbytes=5MB  
stdout_logfile=/home/path/worker.log  
stderr_logfile=/home/path/workerError.log
```

This issue is coming for about to 1 year, Every thing I have done to resolve issue but the same issue is coming repeatedly, don't known how to resolve this issue ?

My question is that is worker can run for infinite period or we need to restart the supervisor after some time period ?
And how to make the supervisor run the jobs with out any break?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
