### ISSUE TITLE
http_server allowed IPs feature request

### ISSUE THREAD

**Issue by fitzg2** [Supervisor/supervisor#1114]
Would it make sense? having supervisor across multiple servers it will make a nice mess to add iptables rules for each IP on each server rather to have them only on the configuration file.

**Comment by mnaberez** [comment]
The HTTP server doesn't provide security beyond simple authentication.  It's intended to be used inside a trusted LAN.  If you need more security than it provides (e.g. HTTPS or IP restrictions), please put it behind a proxy server.
