### ISSUE TITLE
what happen if supervisord stoped

### ISSUE THREAD

**Issue by freenux** [Supervisor/supervisor#1115]
what happent if supervisord stoped, it's monitored programming stop or change parent process to init? if stop，it is costly if supervisord stop, if change parent process, restarted supervisor process cannot monitor these processes+

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
