### ISSUE TITLE
Will supervisor change the program master process

### ISSUE THREAD

**Issue by xiazhibin** [Supervisor/supervisor#1116]
Supervisor version: 3.3.3
I use `supervisor` to manage `gunicorn` processes.It works very well, but recently when I send `hub` to `supervisor` to reload `gunicorn`, `gunicorn` logs show me occasionally  that
```
 11155	[2018-07-03 16:16:49 +0000] [25949] [INFO] Handling signal: hup
 11156	[2018-07-03 16:16:49 +0000] [25949] [INFO] Hang up: Master
 11157	[2018-07-03 16:16:52 +0000] [18459] [INFO] Parent changed, shutting down: <Worker 18459>
 11158	[2018-07-03 16:16:52 +0000] [18459] [INFO] Worker exiting (pid: 18459)
 11159	[2018-07-03 16:17:00 +0000] [18458] [INFO] Parent changed, shutting down: <Worker 18458>
 11160	[2018-07-03 16:17:00 +0000] [18458] [INFO] Worker exiting (pid: 18458)
 11161	[2018-07-03 16:17:00 +0000] [18456] [INFO] Parent changed, shutting down: <Worker 18456>
 11162	[2018-07-03 16:17:00 +0000] [18456] [INFO] Worker exiting (pid: 18456)
 11163	[2018-07-03 16:17:00 +0000] [18455] [INFO] Parent changed, shutting down: <Worker 18455>
 11164	[2018-07-03 16:17:00 +0000] [18455] [INFO] Worker exiting (pid: 18455)
 11165	[2018-07-03 16:17:00 +0000] [18457] [INFO] Parent changed, shutting down: <Worker 18457>
```

I have no idea to handle this situation.
Is that `supervisor` changed the `gunicorn` master process?
and how can I deal with this situation?

Here is the supervisor.conf

```
[program:app]
command=gunicorn -c gunicorn.py wsgi:app
directory=/home/xiazhibin
startsecs=1
startretries=3
user=xiazhibin
stopwaitsecs=10
autostart=false
autorestart=false
killasgroup = true
stopasgroup = true
```

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.  We use this issue tracker mainly for bugs in Supervisor itself.

The log above is not from `supervisord` but from another program.  You may want to ask about these log messages on the appropriate support channel for that program.
