### ISSUE TITLE
exceptions.OSError when running on supervisor

### ISSUE THREAD

**Issue by zoha21** [Supervisor/supervisor#1120]
Hello. I am relatively new to supervisor. I have a python script that download an audio to a location then use a function to get the duration of the audio by calling that location. My script works fine when I run it. However, I get an exceptions.OSErro when I run it on supervisor. I am looking for your input to figure out what could be the possible cause of this problem. 

Thank you

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
