### ISSUE TITLE
Documentation does not tell default values for logrotation... which is 10

### ISSUE THREAD

**Issue by kozmaz87** [Supervisor/supervisor#1125]
This is the relevant code
```
  self.add("logfile_backups", "supervisord.logfile_backups",
  "z:", "logfile_backups=", integer, default=10)
```

**Comment by mnaberez** [comment]
http://supervisord.org/configuration.html

> l`ogfile_backups`
> 
>     The number of backups to keep around resulting from activity log file rotation. If set to 0, no backups will be kept.
> 
>     Default: 10
