### ISSUE TITLE
Please release a new version >3.3.4

### ISSUE THREAD

**Issue by dflemstr** [Supervisor/supervisor#1128]
We have code that relies on fixes that have landed into the master branch of this repository but not been released yet.  It would be great to get new releases at regular intervals that include these fixes.

In particular, we would like to have a release that is later than https://github.com/Supervisor/supervisor/commit/85558b4c86b4d96bd47e267489c208703f110f0f

**Comment by mnaberez** [comment]
Duplicate of #1060
