### ISSUE TITLE
README.rst Python 3 Mis-information Bug

### ISSUE THREAD

**Issue by jerryji** [Supervisor/supervisor#1129]
> Supervisor is intended to work on Python 3 version 3.4 or later 

Before Supervisor actually supports Python 3, please remove the above line from README.rst

Thanks.

Jerry

**Comment by vindarel** [comment]
Funnily it is corrected in the 3.3-branch

> Supervisor is known to work with Python 2.4 or later but will not work under any version of Python 3.

**Comment by mnaberez** [comment]
> Before Supervisor actually supports Python 3, please remove the above line from README.rst

You are quoting the README from the git master branch, which is our current development work.  That branch will become Supervisor 4 and has support for Python 3.  It has not been released yet.

The README files in the release 3.x versions (e.g. [Supervisor 3.3.4](https://github.com/Supervisor/supervisor/tree/3.3.4)) indicate that Python 3 is not supported.  These are the versions currently published to PyPI.
