### ISSUE TITLE
error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by thornycrackers** [Supervisor/supervisor#1130]
I'm trying to run the command from the docs:

```
import xmlrpclib
server = xmlrpclib.Server('http://localhost:9001/RPC2')
server.supervisor.getState()
```

But I keep getting:

```
error: [Errno 111] Connection refused
```

I'm running the python script as root so I shouldn't be having some kind of file based permission error. I can also run `supervisorctl` and see all my processes come up no problem so I know that supervisor itself is working. I've also double checked that the xmlrpc section is in my config file:

```
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
```

I've looked over some other sample code that initiates a connection from [cesi](https://raw.githubusercontent.com/gamegos/cesi/b1cf513d6aa0dbfa8604474e4d9db5fd9c3ad4e3/cesi/cesi.py) but I still get the same error. The socket is 0770 ownership is root:www-data. Is there something really simple that I'm missing here? I've also made sure that I've been using python2 .

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by asselinpaul** [comment]
@thornycrackers did you figure this out?

**Comment by thornycrackers** [comment]
@asselinpaul Naw sorry, I gave up.

**Comment by asselinpaul** [comment]
I figured it out for my case.

Supervisor was running using the supervisord.conf in my local repo instead of the one in `/etc/supervisor`. I had the snippet for setting the supervisor server in the wrong `.conf` file and as such, it wasn't being picked up.
