### ISSUE TITLE
https on supervisord.org?

### ISSUE THREAD

**Issue by benbailess** [Supervisor/supervisor#1131]
Not a technical issue per se with supervisor, but rather a _request_ to enable HTTPS, at least opportunistically, the documentation / main site of supervisor (http://supervisord.org/). Currently HTTPS is not available at all on supervisord.org.

**Comment by mnaberez** [comment]
An HTTPS version of the documentation is available at https://supervisord.readthedocs.io

I'm closing this as a duplicate of #947, which is about the mailing list page, but basically the same issue.
