### ISSUE TITLE
Reloading configuration for a monitored process

### ISSUE THREAD

**Issue by EximChua** [Supervisor/supervisor#1133]
Hi,

How do I reload the configuration for a monitored process in Supervisor, short of doing sudo service supervisor reload or restart?

Doing sudo supervisorctl restart monitored-process-name doesn't cause supervisor to pick up the updated monitored process' configuration in the /etc/supervisor/conf.d directory.

I'm using Supervisor 3.3.4 on Ubuntu 16.04.4 LTS.

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.  We use this issue tracker mainly for bugs in Supervisor itself.
