### ISSUE TITLE
supervisor init script bug in start)

### ISSUE THREAD

**Issue by hack2learn** [Supervisor/supervisor#1134]
Hi,

there is an issue with supervisor package start action in /etc/init.d/supervisor.
Current version at the time of this writing: 3.0b2-1ubuntu0.1.

When you try to reinstall the package it fails with this error:
Starting supervisor: invoke-rc.d: initscript supervisor, action "start" failed

here is the start method: 
```
start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --startas $DAEMON -- $DAEMON_OPTS
        test -f $PIDFILE || sleep 1
        if running ; then
             echo "$NAME."
        else
             echo " ERROR."
         fi
        ;;
```
the problem is that it never reaches the ```if running ; then```
Here is the fixed start) action:
```
start)
        echo -n "Starting $DESC: "
        if running ; then
           echo "$NAME. $pid"
           exit 0
        else:
           start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --startas $DAEMON -- $DAEMON_OPTS
           test -f $PIDFILE || sleep 1
           if running ; then
              echo "$NAME."
           else
               echo " ERROR."
           fi
        fi
        ;;
```
Let me know if you have any questions.

best,
Patrick

**Comment by mnaberez** [comment]
> Current version at the time of this writing: 3.0b2-1ubuntu0.1.

Please report this issue to the maintainers of the Ubuntu package that you are using.  Only they can make changes to it.  This project, Supervisor, only publishes Python packages to [PyPI](https://pypi.org/project/supervisor/).  The Ubuntu package you are using is maintained by other people not involved with the Supervisor project.

**Comment by hack2learn** [comment]
Thanks. Will do that.
