### ISSUE TITLE
Support for https/ssl

### ISSUE THREAD

**Issue by psbj** [Supervisor/supervisor#1135]
Could you add support for using ssl certificates so we can connect via https?

**Comment by mnaberez** [comment]
The server is intended to be used inside a trusted LAN. If you need more security than it provides (e.g. HTTPS), please put it behind a proxy server.

**Comment by RenierLewis** [comment]
There is increasing pressure to ensure all traffic is encrypted in transit and at rest. Can this issue be reconsidered?

**Comment by zswanson** [comment]
Are the username and passwords passed with encryption? If not, I agree - this needs to be enabled. Even on a trusted LAN the credentials shouldn't be plain text on the line.

**Comment by Mister-Fil** [comment]
Settings NGINX proxy

```

server {
	listen 80;
	server_name supervisor.mydomain.com;
	return 302 https://supervisor.mydomain.com$request_uri;
}

server {
	auth_basic off;
	listen 443 ssl http2;
	server_name supervisor.mydomain.com;

	ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

	access_log off;

	location / {
		proxy_pass http://127.0.0.1:9001;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

}

```

**Comment by kdallas** [comment]
As per this article: https://www.jfabre.com/set-up-supervisor-web-ui-behind-nginx-with-tail-function-working/
... some additional directives are needed so you can view the log output(s):

`    location / {
        proxy_pass http://127.0.0.1:9001;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
    }
`

**Comment by master-chief-2009** [comment]
I've been exploring the initialization process of the HTTP server within the codebase. My understanding is that the server starts by default with no option to disable this behavior. Could we consider introducing a feature to improve this? Specifically, a flag to enable/disable the HTTP server startup would be beneficial.

At my company, we employ scanners that have identified HTTP ports lacking SSL protection. Despite utilizing a proxy, the unsecured port still needs to be exposed.
