### ISSUE TITLE
Add a way to compare configuration files in 'supervisorctl' command

### ISSUE THREAD

**Issue by sblondon** [Supervisor/supervisor#1138]
I wonder if you would be interested that `supervisorctl` could display the difference status of the configuration files compared to the version in memory. I'd like to have a way to understand why a process is not shown (the user probably forgot to add the process) or why the behaviour has not changed (the user probably forgot to reload the process).

For example:
```
$ sudo supervisorctl files
demo-production-daemon           MODIFIED
demo-production-uwsgi            UPTODATE
demo-production-zeo              UNKNOWN
other-process                    NOTFOUND
```
UPTODATE : no change
MODIFIED : configuration files modified but not reloaded
UNKNOWN : configuration file not added
NOTFOUND: configuration file deleted or renamed

Another way to do it would be to add these statuses in the first column of `supervisorctl status` like with versionning system.
Pro: no new command
Cons:
 - the files not added will not be shown or different from current display
 - break the output compatibility.

```
$ sudo supervisorctl status
M demo-production-daemon           RUNNING   pid 4780, uptime 9:48:16
. demo-production-uwsgi            RUNNING   pid 29316, uptime 1 day, 3:05:27
? demo-production-zeo
! other-process                    RUNNING   pid 25629, uptime 20 days, 23:39:38
```

In the first column, there would be the comparison, inspired by versionning system.

- Do you think it's a good idea?
- If yes, do you think it's doable? I guess there are cases to manage like a configuration file can have several processes inside.

**Comment by mnaberez** [comment]
Similar functionality already exists.  You can instruct `supervisorctl` to reread the configuration files and it will list the differences without applying changes.

Create a config file `supervisord.conf`:

```
[supervisord]
logfile = /tmp/supervisord.log

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat
```

Start `supervisord` in the foreground with that config:

```
$ supervisord -n -c supervisord.conf
```

In a new terminal, run `supervisorctl reread`:

```
$ supervisorctl -c supervisord.conf reread
No config updates to processes
```

Add a section to `supervisord.conf` to with a new process:
```
[program:dog]
command = /bin/dog
```

Run `supervisorctl reread` again:
```
dog: available
```
