### ISSUE TITLE
Update restarts all group processes

### ISSUE THREAD

**Issue by gstrat88** [Supervisor/supervisor#1154]
Update command restarts all processes of a group as we can see here
https://github.com/Supervisor/supervisor/blob/ec495be4e28c694af1e41514e08c03cf6f1496c8/supervisor/supervisorctl.py#L1213

It would be nice if it could work as for ungrouped processes.

**Comment by mnaberez** [comment]
> It would be nice if it could work as for ungrouped processes.

Minimal `supervisord.conf` with one "ungrouped" process called `cat`:

```
[supervisord]
nodaemon=true

[inet_http_server]
port=127.0.0.1:9001        

[supervisorctl]
serverurl=http://127.0.0.1:9001 

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat
```

Start `supervisord` in the foreground with that config:

```
$ supervisord -n -c supervisord.conf
```

In a new terminal, try to `update cat` without changing the config file:

```
$ supervisorctl -c supervisord.conf
supervisor> update cat
supervisor> 
```

Notice there is no error, and no changes.  Now change `supervisord.conf` to change the `cat` process:

```
[program:cat]
command = /bin/dog
```

Try to `update cat` again:

```
supervisor> update cat
cat: stopped
cat: updated process group
supervisor>
```

The change to the "ungrouped" process is detected and updated.

**Comment by EdvardD** [comment]
I don't think the answer resolves the issue.

Here is an example:
```
[supervisord]
logfile = /var/log/supervisord.log

[group:pets]
programs=cat,dog

[program:cat]
command = /bin/cat

[program:dog]
command = /bin/dog
```

The problem is that if we change the command for `program:cat` and do `update pets` it'll restart `dog` program along with `cat` although it didn't change.

On the other hand if the programs weren't grouped and we've change `program:cat` and do `update` it wouldn't restart `dog`.
