### ISSUE TITLE
Tornado + apache2 (WSGI) + supervisord

### ISSUE THREAD

**Issue by loretoparisi** [Supervisor/supervisor#1159]
I'm running **Tornado** application server behind **supervisord** with apache2 mod_wsgi. Everything works apart that I cannot write files to the folder I have specified in the configuration:

```yaml
[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
directory=/tornado_api
stdout_logfile=/var/log/apache2/access.log
stderr_logfile=/var/log/apache2/error.log
redirect_stderr=true
stdout_events_enabled=true
stderr_events_enabled=true
user=root
group=root
```

while in my virtual host I'm calling the wsgi application like

```yaml
WSGIScriptAlias / /tornado_api/config.py
WSGIApplicationGroup %{GLOBAL}
```

when I run my tornado application with python everything is running ok, when I run by `/usr/bin/supervisord` I get the `permission denied` error creating folders or writing files in the `directory=/tornado_api` directory. Why?

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
