### ISSUE TITLE
Supervisor not getting all output of sub-processes

### ISSUE THREAD

**Issue by katsar0v** [Supervisor/supervisor#1164]
Hello, I have following config:

```
[supervisord]
logfile = /var/log/supervisord.log
loglevel = info
pidfile = /var/run/supervisord.pid
nodaemon = true

[program:cron]
command = cron -f
autostart = true
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

[program:php-fpm]
command=/usr/sbin/php-fpm7.2 -F
numprocs=1
autostart=true
autorestart=false
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:mysql]
command=/usr/sbin/mysqld
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
username=www-data
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```

I use `supervisord` in docker and I get these logs:
```
2018-10-22 16:05:37,777 CRIT Supervisor running as root (no user in config file)
2018-10-22 16:05:37,783 INFO supervisord started with pid 1
2018-10-22 16:05:38,784 INFO spawned: 'nginx' with pid 23
2018-10-22 16:05:38,785 INFO spawned: 'php-fpm' with pid 24
2018-10-22 16:05:38,787 INFO spawned: 'mysql' with pid 25
2018-10-22 16:05:40,160 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-10-22 16:05:40,161 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-10-22 16:05:40,161 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

That's my cron config:
```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
*/1 * * * * curl https://localhost:9443/wp-cron.php -k -I
* * * * * echo 1
* * * * * echo 1 >> /var/log/cron.log 2>&1
* * * * * echo "Hello world" >> /dev/stdout 2>&1
# crontab requires empty line at end of file
```

Unfortunately I see nothing in the logs of supervisor. I also do not see the logs from mysql (which has pid 25). When I start the services with a shell script (service {service} start) I can see output from the apps, but using supervisor it does not work.

**Comment by mnaberez** [comment]
> Unfortunately I see nothing in the logs of supervisor.

There are two types of log files that `supervisord` writes.  The first is the main log file that contains messages from `supervisord` itself (configured in the `[supervisord]` section).  The second is the child log files that contain output captured from the processes running under `supervisord`  (configured in the `[program:x]` sections).

In the configuration above, all of the child logs have been configured like this:

```
stdout_logfile=/dev/stdout
```

That is why you are not seeing the output of the child processes on disk.  I'm not sure what configuring that to `/dev/stdout` will do and the result may be operating system dependent.  Normally, these options used to specify that log files on disk that `supervisord` will write to the disk.    If you replace `/dev/stdout` with a file on disk, you will be able to read the child log output from that file.

**Comment by dpc** [comment]
Hi. I'd like to point out that the ability to print sub-processes output as supervisord output is very useful in places like Docker and kubernetes, and possibly other setups. It would be great if `supervisord` had a configuration options or something that can reliably achieve it.

**Comment by melkamar** [comment]
A note for future readers - the reason the output of the cron commands is not picked up by `supervisor` is simply because `cron` does _not_ forward the output of its spawned commands.

See https://unix.stackexchange.com/questions/520170/cron-jobs-printing-to-dev-stdout

> The point of cron is to run commands without a terminal. That means there is no terminal to output stdout to. That's why it is being mailed.

I have not found a way to have the output of cron commands passed back to supervisor through the cron program. It is possible to send the output of the commands directly to supervisor's stdout though (assuming root):

```
* * * * * root sudo -u someuser bash -c '/home/command-to-execute --param' >/proc/1/fd/1 2>&1
```
