### ISSUE TITLE
supervisor python script slowly

### ISSUE THREAD

**Issue by lengyueyang** [Supervisor/supervisor#1167]
When i run python script, it's slowly compare with the local, anyone have some questions?

**Comment by mnaberez** [comment]
There isn't much that Supervisor can do to make a process actually run slower, but it may appear to run slower if you aren't seeing log messages as quickly.  Python might be buffering the output when it is run under Supervisor.  Try running it unbuffered: https://github.com/Supervisor/supervisor/issues/13#issuecomment-1066821
