### ISSUE TITLE
Expand of user home directory not as expected when change 'user' in program section

### ISSUE THREAD

**Issue by crhan** [Supervisor/supervisor#1171]
The problem is after supervisor switch the user. UID and EUID seems to be right, bug home directory doesn't change in the right way. And it will cause some program error: https://github.com/ActiveState/appdirs/blob/0a7725ce30fbe6b7a6992458b0ba55f998195a6f/appdirs.py#L92

```python
os.path.expanduser("~/.local/share")
```

This will cause my program to have a permission error, due to this code will return `/root/.local/share` but not `/home/admin/.local/share`.

### all the below section use this script

```bash
echo "######"
echo $HOME
echo $USER
echo $UID
echo $EUID
echo "######"
```

### case1

This case use sudo -u admin to switch user to admin(uid: 500), here is the supervisor config:

```
[program:test]
command=sudo -u admin bash /tmp/test/expand_home.sh
```

and get the result:

```
######
/home/admin
root
500
500
######
```

Conclusion: When use sudo to switch user. The user dir switch in the right way.

### case2

Use supervisord's user config to switch, see the supervisor config:

```
[program:test]
command=bash /tmp/test/expand_home.sh
user=admin
```

and get the result:

```
######
/root
ruohan.chen
500
500
######
```

Conclusion: User home dir is right but `$USER` is not right. But it's not a big problem

**Comment by mnaberez** [comment]
> Conclusion: User home dir is right but $USER is not right. But it's not a big problem

[Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment):

> Unlike cron, supervisord does not attempt to divine and override “fundamental” environment variables like USER, PATH, HOME, and LOGNAME when it performs a setuid to the user defined within the user= program config option. If you need to set environment variables for a particular program that might otherwise be set by a shell invocation for a particular user, you must do it explicitly within the environment= program config option. An example of setting these environment variables is as below.
