### ISSUE TITLE
difference between service supervisor and supervisord

### ISSUE THREAD

**Issue by Sshuichi** [Supervisor/supervisor#1177]
Hello, 
Sorry if this is not the right place to ask. 
Supervisord, when ran in CLI, take all the env variables that I exported in my ~/.bash_profile into consideration. But when I start the daemon using service supervisor start, it doesn't. 
Anyone can explain to me why is this happening? 
Thanks a bunch.

**Comment by mnaberez** [comment]
[Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment):
> Subprocesses will inherit the environment of the shell used to start the supervisord program. 

...

> No shell is executed by supervisord when it runs a subprocess, so environment variables such as USER, PATH, HOME, SHELL, LOGNAME, etc. are not changed from their defaults or otherwise reassigned.

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
