### ISSUE TITLE
hope to add function when used in docker

### ISSUE THREAD

**Issue by GavinLiu168** [Supervisor/supervisor#1182]
My service is combined with multiprocess and I hope to run it in docker. So I chose supervisor to manage my service.  But at last I find one problem. When child process dead, supervisor will restart it until backoff more than startretries, and then the state of it will be changed to fatal. But I hope to supervisord exit when backoff  of some import process more than startretries, so that the docker will restart.

**Comment by perrinjerome** [comment]
I'm also just a user of supervisor but I would recommend closing this issue and asking on stackoverflow instead.

https://stackoverflow.com/questions/tagged/supervisor+docker

**Comment by alexsilva** [comment]
A event listener would solve this easily.
http://supervisord.org/events.html

**Comment by mnaberez** [comment]
Closing based on suggestions above.
