### ISSUE TITLE
Supervisor start multiple processes instead only one

### ISSUE THREAD

**Issue by igor-nikiforov** [Supervisor/supervisor#1188]
Hello,

I have a program which previously I started running this command:
`root@server:/opt/resources# /opt/resources/grand -b /opt/resources/contact_new`
`/opt/resources/grand daemon started, PID = 2644`

I decided to configure the same in supevisor:
`[program:grand]`

`command=/opt/resources/grand -b /opt/resources/contact_new`
`directory=/opt/resources`
`numprocs=1`
`startsecs=5`
`autostart=true`
`autorestart=true`
`stdout_logfile=/opt/resources/stdout.log`
`stdout_logfile_maxbytes=1MB`
`stderr_logfile=/opt/resources/stderr.log`
`stderr_logfile_maxbytes=1MB`

But instead of starting 1 process supervisor starts 4 and have and error:
`grand                            FATAL     Exited too quickly (process log may have details)`

ps aux:
`root     32699  0.0  0.0  12944   348 ?        S    11:20   0:00 /opt/resources/grand -b /opt/resources/contact_new`
`root     32712  0.0  0.0  12944   348 ?        S    11:20   0:00 /opt/resources/grand -b /opt/resources/contact_new`
`root     32719  0.0  0.0  12944   344 ?        S    11:20   0:00 /opt/resources/grand -b /opt/resources/contact_new`
`root     32738  0.0  0.0  12944   344 ?        S    11:20   0:00 /opt/resources/grand -b /opt/resources/contact_new`

There is nothing in stderr.log and stdout.log only that process started with PID (only 1 but in fact its 4).

**Comment by mnaberez** [comment]
A possible reason is that the program has daemonized; see [Nondaemonizing of Subprocesses](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses) in the documentation.

Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
