### ISSUE TITLE
supervisord error "not an existing directory"

### ISSUE THREAD

**Issue by diepes** [Supervisor/supervisor#1190]
I have supervisord in a docker container starting some services.

The config has a entry childlogdir=/var/log/supervisord

When the container is run with a /var/log bind mounted into it without this directory it fails

For help, use /usr/bin/supervisord -h
Error: /var/log/supervisord is not an existing directory

Is there a way to get supervisord to create this subdirectory at startup ?
It is started as PID=1 in the container.

**Comment by mnaberez** [comment]
Duplicate of #120
