### ISSUE TITLE
Supervisor in Windows

### ISSUE THREAD

**Issue by alexsilva** [Supervisor/supervisor#1191]
Supervisor is an excellent tool for process management but unfortunately it does not work on Windows, so I put a lot of time and effort into making it work in Windows. I present below a version that works in Windows (with some limitations but that will be improved over time).

https://github.com/alexsilva/supervisor

**Comment by mnaberez** [comment]
Thanks for sharing.  You might also want to other users know about your Windows program on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).

**Comment by pifeifei** [comment]
+1  

Hope to support Windows
