### ISSUE TITLE
Supervisor abnormal exit

### ISSUE THREAD

**Issue by cuizhiyang** [Supervisor/supervisor#1193]
System version:
CentOS Linux release 7.2.1511 (Core)

 Abnormal log  (journalctl -ln 20000 -u supervisord.service ) :
Jan 24 22:34:55 web systemd[1]: supervisord.service: main process exited, code=killed, status=9/KILL
Jan 24 22:35:02 web systemd[1]: Unit supervisord.service entered failed state.
Jan 24 22:35:02 web systemd[1]: supervisord.service failed.

In/var/log/supervisor/supervisor. The log in the abnormal log are not found in the same point in time

config: Yum installs the default configuration file

**Comment by mnaberez** [comment]
> supervisord.service: main process exited, code=killed, status=9/KILL

This seems to indicate that `supervisord` was killed, rather than exiting on its own.  It's unlikely that this is a bug in `supervisord` since it has no code to send a SIGKILL to itself.
