### ISSUE TITLE
Supervisor keeps loading configuration file with name extension like .conf.SAVE

### ISSUE THREAD

**Issue by essadek** [Supervisor/supervisor#1194]
I'm running Supervisor on Debian 8 to control a number of Gunicorn servers.
Before making changes on a config file I made a backup with the same file name with additional extension like **CFG_FILE_NAME.conf.SAVE**.

So I edited **CFG_FILE_NAME.conf** to bring some significant changes, however after triggering `reread` and `update` and trying also `relaod`, I have noticed that Supervisor keep reading from **CFG_FILE_NAME.conf.SAVE** and ignore the original **CFG_FILE_NAME.conf**. So I deleted the backup file which brought back the original config live.

AFAIK Supervisor read only files with **.conf** extension, is this a bug or am I missing something ?

**Comment by mnaberez** [comment]
> AFAIK Supervisor read only files with **.conf** extension, is this a bug or am I missing something ?

The main configuration file, usually called `supervisord.conf`, contains an [`[include] section`](http://supervisord.org/configuration.html#include-section-values) that specifies the patterns used to search for other config files.  Check this section in your configuration to see what patterns it has been configured to load.
