### ISSUE TITLE
Is there a way to stop a supervisor-managed task from within Supervisor?

### ISSUE THREAD

**Issue by msoultan** [Supervisor/supervisor#1198]
Hi,
I have a script that is managed by Supervisor and what I'd like to do is be able to stop Supervisor from my script - is that possible?  Right now I've been calling an external shell script that runs my Supervisor stop script, but I wanted to know if there was a way of exiting my script cleanly, or somehow sending a command to Supervisor, such that Supervisor doesn't try and restart it.

An example is if my script detects that another copy is running - I'd like to send out a notification that it's already running and then initiate a stop to the current-running supervisor instance.

Thanks!
Mike

**Comment by mnaberez** [comment]
> I have a script that is managed by Supervisor and what I'd like to do is be able to stop Supervisor from my script - is that possible? Right now I've been calling an external shell script that runs my Supervisor stop script, but I wanted to know if there was a way of exiting my script cleanly, or somehow sending a command to Supervisor

Your program, while running as a subprocess under `supervisord`, can use the XML-RPC interface to call the [`stopProcess()`](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcess) method.  This is what `supervisorctl stop` does under the hood.  One difference is that with the XML-PRC method, you have the ability to pass `wait=False`.  If you do that, `supervisord` will move the subprocess to the `STOPPING` state but the XML-RPC method will return immediately.  Your program can then exit immediately.  As long as your program exits within `stopwaitsecs` and with an expected exit code (`exitcodes`), then it will be a clean exit and the status will be `STOPPED`.

**Comment by msoultan** [comment]
Mike,
Thanks for the info!  I'll give it a try!!
