### ISSUE TITLE
Can I set a limit on the number of restart retries?

### ISSUE THREAD

**Issue by msoultan** [Supervisor/supervisor#1199]
Is there any way to set the number of restart retries, in addition to a delay, when my script crashes and needs to be restarted?  Right now it keeps restarting over and over again without ever ending until I catch it.  I have this script running on hundreds of workstations and when it's sending out a failure email, it can end up sending out thousands of emails - I'd really like that it fails and retries a few number of times and then stops trying...

Thanks!
Mike

**Comment by mnaberez** [comment]
This issue is very similar to #487.  Closing to merge them both into one issue.
