### ISSUE TITLE
Allow for changing http logo

### ISSUE THREAD

**Issue by harlowja** [Supervisor/supervisor#1200]
It'd be nice to allow others to put up a different logo for the supervisor http endpoint; is there any way to do this (without patching out the file?)

**Comment by mnaberez** [comment]
You'd need to patch the file.  I'm afraid we don't plan to add options to allow the web interface to be restyled, sorry.  It's intended only for internal use on a private LAN and it's unlikely that most users will need the ability to restyle it.
