### ISSUE TITLE
Prepend program name to logs

### ISSUE THREAD

**Issue by samson4649** [Supervisor/supervisor#1201]
When running in foreground with multiple processes (ie. a docker container) it would be nice to have the program name prepended to the log output. ie:

[program_1] [ Thu Feb  7 23:37:00 UTC 2019 ] output from promgram 1
[program_1] [ Thu Feb  7 23:37:02 UTC 2019 ] output from promgram 1
[program_2] [ Thu Feb  7 23:37:03 UTC 2019 ] output from a secondary application

**Comment by mnaberez** [comment]
Duplicate of #553
