### ISSUE TITLE
how supervisor event work?

### ISSUE THREAD

**Issue by sunjiansen** [Supervisor/supervisor#1206]
if a process state change like this : exited -> running、running -> exited、exited -> running ... 
cycle the number of restarts I set,my python monitor 60s listens once，and I set PROCESS_STATE_EXITED and PROCESS_STATE_RUNNING, will it always send the signal to me?

**Comment by mnaberez** [comment]
Please see [Events](http://supervisord.org/events.html) for a description of the events system and a state transition diagram.  You may want to set `loglevel = debug` in your config file for development.  This will show the state transitions and the events sent in the log.
