### ISSUE TITLE
supervisorctl should return 1 when upcheck() fails

### ISSUE THREAD

**Issue by jhershberg** [Supervisor/supervisor#1209]
In a number of scenarios, e.g., the unix domain socket specified in --serverurl is not present, supervisorctl will exit with status 0. Standard convention would be to return 1.

Reproducible by running: supervisorctl --serverurl file:///this/path/does/not/exist status

**Comment by mnaberez** [comment]
Duplicate of #24 

This has been fixed in the current master branch, and will be released in Supervisor 4.0.
