### ISSUE TITLE
"supervisorctl reload" fails to re-start program

### ISSUE THREAD

**Issue by jbrehm** [Supervisor/supervisor#121]
Running "supervisorctl reload" on a running supervisord instance will cause program to stop and not re-start.  

I've noticed this happening since upgrading from 3.0a10 to 3.0a12.  Can provide more information if it's not duplicatable.

**Comment by lwtju** [comment]
Just run supervisorctl -c /etc/supervisor/supervisord.conf 
supervisorctl can not find config file

**Comment by omsobliga** [comment]
`supervisord -n` help me find the detail error info, thanks.

**Comment by cyrrill** [comment]
I got the 
```
unix:///var/run/supervisor.sock no such file
```
error when trying to access supervisorctl. To solve this you need to make sure that the supervisor service is running:

```
sudo service supervisor status
```

will tell you if that's your issue, if you get that it't not running, simply start it with
```
sudo service supervisor start
```

I have found that when running supervisor in a Vagrant VM, the service will not autostart for some reason, necessitating a manual service start.

**Comment by relighted** [comment]
Found this error as well on my raspberry pi whith updated Weesy.
```
sudo supervisorctl reload
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
````

Reading above I did:
```
sudo supervisord
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.

```

Shich showed an issue with logging. Indeed I remove * from /var/log/ a day or so back.. 
recreated & after another `sudo supervisord`, all good.

**Comment by enisozgen** [comment]
Thanks @JayH5 its worked for me

**Comment by efusionsoft** [comment]
I had the same issue of .sock file not found. @mistermoe suggestions helped me to the solve the issue.

**Comment by EamonZhang** [comment]
$ sudo supervisorctl reload
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
$ sodu supervisorctl status
unix:///var/run/supervisor.sock no such file

After restart supervisorctl ,this issue be solved!

**Comment by freddong** [comment]
change
[supervisord]
;;;;;;http_port=/var/tmp/supervisor.sock ; (default is to run a UNIX domain socket server)
http_port=127.0.0.1:9001  ; (alternately, ip_address:port specifies AF_INET)

to
[supervisord]
http_port=/var/tmp/supervisor.sock ; (default is to run a UNIX domain socket server)
;;;;;;http_port=127.0.0.1:9001  ; (alternately, ip_address:port specifies AF_INET)

solved my problem

**Comment by efusionsoft** [comment]
If someone still has the issue:

create a file in /etc/supervisord.conf and add the following code
**(Please note, change the user name accordingly )**

```
[unix_http_server]
file = /tmp/supervisor.sock
chmod = 0777
chown= mywebsiteuser:mywebsiteusergroup


[supervisord]
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=10
loglevel = info
pidfile = /tmp/supervisord.pid
nodaemon = false
minfds = 1024
minprocs = 200
umask = 022
user = mywebsiteuser
identifier = supervisor
directory = /tmp
nocleanup = true
childlogdir = /tmp
strip_ansi = false

[supervisorctl]
##serverurl = unix:///tmp/supervisor.sock
serverurl = http://localhost:9001

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/aaweb2015/public_html/artisan queue:work database --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=mywebsiteuser
numprocs=8
redirect_stderr=true
stdout_logfile=/home/mywebsiteuser/worker.log
```

Save and exit the editor.

Find the existing supervisord process and kill it
```
pgrep -fl supervisord
```
Run the following commands and you should have your worker running

```
supervisord -c /etc/supervisord.conf
supervisorctl -c /etc/supervisord.conf reload
supervisorctl -c /etc/supervisord.conf start laravel-worker:*
```

**Comment by rizkyred** [comment]
thanks @omsobliga

**Comment by GustavoMSevero** [comment]
Hi guys!
I have a problem like this.
I followed this link: https://serversforhackers.com/monitoring-processes-with-supervisord, but when I run this command "supervisorctl reread" this mesage appears:
"error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228"
What, exactly it means?
Thank you.

**Comment by desertkun** [comment]
Having this issue using puppet
```
Error: /Stage[main]/Supervisor/Service[supervisor]: Failed to call refresh: Could not restart Service[supervisor]: Execution of 'supervisorctl reload' returned 2: error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
Error: /Stage[main]/Supervisor/Service[supervisor]: Could not restart Service[supervisor]: Execution of 'supervisorctl reload' returned 2: error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
```

Maybe `No such file or directory` has something to do with the issue?

**Comment by shiplu** [comment]
The solution is to 
1. Make sure supervisord is running. Use your OS's service manager (start, /etc/init.d, service etc) to start it
2. Then reload by supervisorctl. 

`supervisorctl` talks to supervisord daemon. If the daemon doesn't exist then this tool can't instruct to anything. When it tries to connect it cant find the socket file

**Comment by rpkilby** [comment]
This has been an issue that's plagued us from time to time on some of our older servers. For rhel/centos, check this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1247877). In short, the supervisor `3.0-1.el7` release places sock file at `/var/tmp/supervisor.sock`, which is cleaned up after 30 days. This is why, for us, the issue appeared intermittent. Fixed by this [commit](http://pkgs.fedoraproject.org/cgit/rpms/supervisor.git/commit/?id=c9f25b2e13eb42d5f3de312414c03c64aaef8958) in the `3.1.3` release.

**Comment by cesarbellob** [comment]
@harph Thanks! 
`sudo service supervisord start` 
it works fine!

**Comment by uniconstructor** [comment]
[This comment](https://github.com/Supervisor/supervisor/issues/121#issuecomment-207699120) helps me a lot, @efusionsoft , thank you.

But I have some improvements for your solution.
1) When I'm launched supervisor with efusionsoft's config, I' got an error:

    Please check that the [rpcinterface:supervisor] section is enabled in the configuration file (see sample.conf).

If you have the same error - add this code after [supervisor] section:

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

2) serverurl = http://localhost:9001 does not work fo me, and I don't have any idea why. Fortunately serverurl = unix:///tmp/supervisor.sock works fine for me.

Here is full version of my /etc/supervisord.conf:

`[unix_http_server]
file  = /tmp/supervisor.sock
chmod = 0777
chown = mywebsiteuser:mywebsiteusergroup

[supervisord]
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=10
loglevel = info
pidfile = /tmp/supervisord.pid
nodaemon = false
minfds = 1024
minprocs = 200
umask = 022
user = mywebsiteuser
identifier = supervisor
directory = /tmp
nocleanup = true
childlogdir = /tmp
strip_ansi = false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = unix:///tmp/supervisor.sock
##serverurl = http://127.0.0.1:9001

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php/home/mywebsiteuser/public_html/artisan queue:work database --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=mywebsiteuser
numprocs=1
redirect_stderr=true
stdout_logfile=/home/mywebsiteuser/worker.log`

After saving config, restart supervisor:
`
pgrep -fl supervisord
# kill all running supervisor processes with "sudo kill {your process PID}"
# launch supervisor with new config
supervisord -c /etc/supervisord.conf
# check the supervisor status 
supervisorctl -c /etc/supervisord.conf status
`

**Comment by andela-sjames** [comment]
This worked for me

`sudo systemctl start supervisor`
`sudo systemctl enable supervisor`
`sudo supervisorctl reload`

**Comment by vedmant** [comment]
Why not to add appropriate error message that supervisord is not running instead of: 
```
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib64/python2.7/socket.py line: 224
```

**Comment by justrau** [comment]
My problem was that worker's log directory did not exist, just like @YAmikep's. Creating the directory solved the problem and supervisor successfully launched and started the workers.

**Comment by rogervila** [comment]
This is how I solved the `unix:///tmp/supervisor.sock no such file` problem on RHEL

```sh
ps -ef | grep supervisord # get supervisord PID
kill -s SIGTERM 1234 # where 1234 is the PID
ps -ef | grep supervisord # check that supervisord is killed
supervisord # restart the daemon
```

**Comment by MarcosBouzon** [comment]
I had the same problem and after I ran `supervisord` the log showed that the problem was coming from an old service that supervisor was trying to start but I deleted that program folder time ago, but not from the supervisor conf.d/ folder. so it was trying to start a program who didn't exist, and this caused the problem.

**Comment by lkm1developer** [comment]
> On Ubuntu10.04, `supervisorctl reload` causes the supervisord process to fail. Subsequent attempts to run `supervisorctl` result in
> 
> ```
> unix:///var/run/supervisor.sock no such file
> ```
> 
> Or the more obscure
> 
> ```
> error: <class 'socket.error'>, [Errno 2] No such file or directory: file: <string> line: 1
> ```
> 
> The supervisord process must be manually restarted with `sudo supervisord`.
> 
> This is really bad.

Thanks,it worked
