### ISSUE TITLE
New state FLAPPING

### ISSUE THREAD

**Issue by mightydok** [Supervisor/supervisor#1210]
I need to monitor and alert program managed by supervisord for flapping, when program die frequently.
Nagios developers describe this state as FLAPPING -  https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html

Is there any way to calculate FLAPPING state in supervisord plugin, or RPC listener?

**Comment by mnaberez** [comment]
> Is there any way to calculate FLAPPING state in supervisord plugin, or RPC listener?

You can write an [event listener](http://supervisord.org/events.html).  This is a program that runs under `supervisord` and receives event notification via `stdin`.  The program can receive notifications when a process starts and stops.  The program could determine "flapping" by tracking how many start/stop events it received within a period of time.
