### ISSUE TITLE
How does supervisor handle "error" in log?

### ISSUE THREAD

**Issue by bigdataplot** [Supervisor/supervisor#1211]
Hi, I am trying to use Supervisor to monitor all my py/bash jobs, still a newbie supervisor user.

A question when running supervisor:

__Q. Does superviosr track log file or exist code??__

Jobs ended with ERROR in log file, but still shows "EXISTED" instead of "ERROR"/"FATAL".

---

Here are two examples:
- 1 Python script:

```python
#!/usr/bin/env python
import sys, time, logging
sys.stdout.flush()

# INIT LOGGING
logging.basicConfig(format='%(asctime)s @%(name)s [%(levelname)s]:    %(message)s', level = logging.DEBUG)

if __name__ == '__main__':
    time.sleep(2)
    logging.info('Custom service started')
    logging.FileHandler('/jobs/log/py_test.log')
    logging.error('Custom service error')
    logging.critical('Custom service dead')
    logging.FileHandler('/jobs/error/py_test_err.log')
    print "2019-09-08 14:43:22 [WARN] Warning message"
    print "2019-09-08 14:43:22 [ERRO] Error message xxxxx"
    time.sleep(3)
    exit(1000)
```

- supervisor conf:

```shell
[program:py_test]
command=python -u py_test.py
directory=/jobs
startsecs=3
exitcodes=0,2
stdout_logfile=/jobs/log/py_test.log
redirect_stderr=false
stderr_logfile=/jobs/error/py_test_err.log
autostart=false
autorestart=false
loglevel=error
```

The python script printed ERROR messages in the output file, from Supervior's Web UI can also see the ERROR logs, but "Status" shows as "EXITED" instead of "ERROR" or "FATAL"

---

I also tried on a shell script, still no luck:

```shell
#!/bin/bash
sleep 2
echo $(date +"%Y-%m-%d %T") " [ERROR] This is an ERROR log message xxxxx"
sleep 3
exit 100
```

- supervisor conf:
```shell
[program:shell_test]
command=bash shell_test.sh
directory=/jobs
startsecs=3
exitcodes=0,2
stdout_logfile=/jobs/log/shell_test.log
redirect_stderr=false
stderr_logfile=/jobs/error/shell_test.log
autostart=false
autorestart=false
loglevel=error
```
The same thing happened to the shell script. No "ERROR" status showed, only "EXITED"

---

Did I do something wrong in the configuration? Any suggestions. Thank you!

**Comment by mnaberez** [comment]
> Q. Does superviosr track log file or exist code??
>
> Jobs ended with ERROR in log file, but still shows "EXISTED" instead of "ERROR"/"FATAL".

Supervisor doesn't have a feature to detect strings like `ERROR` in the log file.  It does monitor the exit status of the process (see `exitcodes` in the [configuration file](http://supervisord.org/configuration.html)).

Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
