### ISSUE TITLE
Logs are doubled to  /var/log/syslog and /var/log/supervisor/supervisord.log

### ISSUE THREAD

**Issue by Nklya** [Supervisor/supervisor#1212]
Hello. 

I've noticed that Supervisor logs are doubled to  /var/log/syslog and /var/log/supervisor/supervisord.log

I tested on `Debian 9` and `supervisor 3.3.1-1+deb9u1`, but I think it's relevant for any OS with systemd.

After a little research, I found that this happens because in Systemd StandardOutput goes by default to journald, which mirrors to syslog. And because of that, I have Supervisor logs both in /var/log/supervisor/supervisord.log and in /var/log/syslog.

Link to documentation https://www.freedesktop.org/software/systemd/man/systemd.exec.html

I propose to add to systemd unit these two lines to suppress log mirroring. 

```
[Service]
...
...
StandardOutput = null
StandardError = null
```

**Comment by mnaberez** [comment]
The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.org/project/supervisor/). Our packages don't have any operating system integration (init scripts, systemd unit files, etc).  If you installed Supervisor using a distribution package manager like apt or rpm, the authors of that package have done the integration. They are third parties that aren't involved with the main Supervisor project.  Please report this issue to the authors of the package you are using.

**Comment by Nklya** [comment]
Oh, thanks for clarification. 
Will ask there)
