### ISSUE TITLE
httpok: try to restart even in FATAL process state

### ISSUE THREAD

**Issue by eoghanmurray** [Supervisor/supervisor#1219]
I'm wondering why httpok doesn't include an option to always try to restart even if the process is not in `ProcessStates.RUNNING`?  
That would be my feature request for an option to add that (or to do it by default).
Do people use a different tool for that job?

My scenario is that a temporary configuration error meant that a key process couldn't start (`startretries` was 3, but as the config was incorrect for around a half hour — so I'd have had have set that quite high to cover the half hour)

As I've an hourly `httpok` running, my assumption was that this would have attempted to restart the process each hour, and (say) 10 hours later the system could be back working without intervention.

I want to see if I'm missing some approach before submitting a PR.

**Comment by mnaberez** [comment]
This is the issue tracker for the `supervisor` package.  The `httpok` program is part of the `superlance` package.  Please report issues for `httpok` in the [`superlance` issue tracker](https://github.com/supervisor/superlance/issues).

**Comment by eoghanmurray** [comment]
Apologies I didn't know there was a distinction
https://github.com/Supervisor/superlance/issues/120

**Comment by mnaberez** [comment]
No problem, thank you for moving it!
