### ISSUE TITLE
Illegal seek error with supervisor 4.0.0 on Python 3.6

### ISSUE THREAD

**Issue by MartinFalatic** [Supervisor/supervisor#1224]
There are other reports of this sort of thing, but despite taking the suggested remedial actions this problem persists and may not be related to them.

First, all this works fine in the Python 2.7 installation. However, when supervisor is installed on Ubuntu Bionic (18.04) using native Python 3.6 and pip3,  it crashes during operation despite taking the steps suggested to disable log rotation (as mentioned in #1103 ).

Lots of details:

`supervisord --version`  outputs `4.0.0`

/usr/local/bin/supervisord

    #!/usr/bin/python3

    # -*- coding: utf-8 -*-
    import re
    import sys

    from supervisor.supervisord import main

    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(main())

/etc/supervisord.conf

    [supervisord]
    pidfile=/tmp/supervisord.pid
    logfile=/dev/stdout
    logfile_maxbytes=0
    nodaemon=true
    nocleanup=true

    [program:testdaemon]
    command=python3 manage.py runpartnerd --batch-size=10 --topic-set=TEST --max-memory=512
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    .....

    There are more [program:] blocks, but they are all quite similar
    and are identical for the logfile parts.

The error itself (seen during operation, as well as if I just run `supervisord` manually):

    Traceback (most recent call last):
    File "/usr/local/bin/supervisord", line 11, in <module>
        sys.exit(main())
    File "/usr/local/lib/python3.6/dist-packages/supervisor/supervisord.py", line 358, in main
        go(options)
    File "/usr/local/lib/python3.6/dist-packages/supervisor/supervisord.py", line 368, in go
        d.main()
    File "/usr/local/lib/python3.6/dist-packages/supervisor/supervisord.py", line 70, in main
        self.options.make_logger()
    File "/usr/local/lib/python3.6/dist-packages/supervisor/options.py", line 1472, in make_logger
        backups=self.logfile_backups,
    File "/usr/local/lib/python3.6/dist-packages/supervisor/loggers.py", line 417, in handle_file
        handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
    File "/usr/local/lib/python3.6/dist-packages/supervisor/loggers.py", line 212, in __init__
        FileHandler.__init__(self, filename, mode)
    File "/usr/local/lib/python3.6/dist-packages/supervisor/loggers.py", line 159, in __init__
        self.stream = open(filename, mode)
    OSError: [Errno 29] Illegal seek

**Comment by MartinFalatic** [comment]
Investigations:

If I remove `logfile=/dev/stdout` from the `[supervisord]` section it appears to work. However, `logfile_maxbytes=0` should be disabling log rotation... yet it is not.

The code appears to always force rotation for the main log:

https://github.com/Supervisor/supervisor/blob/dfdb5cd0c1b4920664fc87955b89b38065b5f8e7/supervisor/options.py#L1470

The dispatcher code for the child logs does NOT do that:

https://github.com/Supervisor/supervisor/blob/ec495be4e28c694af1e41514e08c03cf6f1496c8/supervisor/dispatchers.py#L146

I would expect that changing `rotating=True,` to `rotating=not not self.logfile_maxbytes,` would solve this problem.

**Comment by MartinFalatic** [comment]
I can confirm that this solves the problem for Python 3.6.

**Comment by mnaberez** [comment]
Confirmed the `OSError: [Errno 29] Illegal seek`.  I was able to see this exception only if `logfile` in the `[supervisord]` section was set to `/dev/stdout`.  Setting the child logs to `/dev/stdout` does not cause the exception.  Related: #812

```
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

$ python -V
Python 3.6.7

$ supervisord --version
4.0.0

$ cat supervisord.conf 
[supervisord]
nodaemon = true
logfile = /dev/stdout
logfile_maxbytes = 0

$ supervisord -c supervisord.conf 
Traceback (most recent call last):
  File "/home/username/.local/bin/supervisord", line 11, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/supervisord.py", line 358, in main
    go(options)
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/supervisord.py", line 368, in go
    d.main()
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/supervisord.py", line 76, in main
    self.run()
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/supervisord.py", line 92, in run
    self.options.write_pidfile()
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/options.py", line 1182, in write_pidfile
    self.logger.info('supervisord started with pid %s' % pid)
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/loggers.py", line 327, in info
    self.log(LevelsByName.INFO, msg, **kw)
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/loggers.py", line 345, in log
    handler.emit(record)
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/loggers.py", line 226, in emit
    self.doRollover()
  File "/home/username/.local/lib/python3.6/site-packages/supervisor/loggers.py", line 263, in doRollover
    if not (self.stream.tell() >= self.maxBytes):
OSError: [Errno 29] Illegal seek
```

**Comment by mnaberez** [comment]
Confirmed that the exception does not occur with the fix [above](https://github.com/Supervisor/supervisor/issues/1224#issuecomment-481073613) (and submitted in #1225).  I am not sure why the `not not maxbytes` logic was done for the child logs but not the main log.  It may have been an oversight.  I will test it further and if I do not see any immediate side effects, I will make a point release with this fix.

**Comment by MartinFalatic** [comment]
Well, the child logs had that "not not" construct as some kind of optimization, but the parent never had this capability at all.

**Comment by mnaberez** [comment]
This fix was released in [Supervisor 4.0.1 (PyPI package)](https://pypi.org/project/supervisor/4.0.1/).

**Comment by MartinFalatic** [comment]
Thank you!

**Comment by ayyobro** [comment]
I'm getting this problem again in Docker using:

`supervisord=v4.2.5`
`symfony=6.2`
`docker=v4.24.2`

**Error**
```
2023-11-05 10:14:51 2023-11-05 15:14:51,257 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140507022485264 for <Subprocess at 140507025396432 with name report_visual in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/local/lib/python3.10/dist-packages/supervisor/supervisord.py|runforever|218] [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py|record_output|210] [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py|_log|179] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|info|327] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|log|345] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|emit|227] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|doRollover|264])
```

**config**
```
[program:report_visual]
command=php bin/console report:visual
directory=/var/www
autostart=true
autorestart=true
startretries=5
startsecs=0
user=root
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/www/var/log/%(program_name)s_stderr.log
stdout_logfile=/var/www/var/log/%(program_name)s_stdout.log
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
priority=1
```

**Comment by bdoublet91** [comment]
Hi,
Can we reopen this issue plz, same problem as @ayyobro, I m using loki to pull logs from container stdout but can't setup with latest version of supervisord (4.2.5...)
```
Traceback (most recent call last):
  File "/opt/env/bin/supervisord", line 8, in <module>
    sys.exit(main())
  File "/opt/env/lib/python3.10/site-packages/supervisor/supervisord.py", line 359, in main
    go(options)
  File "/opt/env/lib/python3.10/site-packages/supervisor/supervisord.py", line 369, in go
    d.main()
  File "/opt/env/lib/python3.10/site-packages/supervisor/supervisord.py", line 72, in main
    self.options.make_logger()
  File "/opt/env/lib/python3.10/site-packages/supervisor/options.py", line 1497, in make_logger
    self.logger.critical(msg)
  File "/opt/env/lib/python3.10/site-packages/supervisor/loggers.py", line 339, in critical
    self.log(LevelsByName.CRIT, msg, **kw)
  File "/opt/env/lib/python3.10/site-packages/supervisor/loggers.py", line 345, in log
    handler.emit(record)
  File "/opt/env/lib/python3.10/site-packages/supervisor/loggers.py", line 227, in emit
    self.doRollover()
  File "/opt/env/lib/python3.10/site-packages/supervisor/loggers.py", line 264, in doRollover
    if not (self.stream.tell() >= self.maxBytes):
OSError: [Errno 29] Illegal seek
```

thanks

**Comment by ok2cqr** [comment]
Hi @ayyobro, did you find the solution? I have the same problem and have no idea how to fix it. Thanks.

**Comment by matveybuk** [comment]
> I'm getting this problem again in Docker using:
> 
> `supervisord=v4.2.5` `symfony=6.2` `docker=v4.24.2`
> 
> Running on AWS ECS with Fargate, trying to get the logs to go to cloudwatch since out of the box it only pulls from stdout
> 
> **Error**
> 
> ```
> 2023-11-05 10:14:51 2023-11-05 15:14:51,257 CRIT uncaptured python exception, closing channel 
> <POutputDispatcher at 140507022485264 for 
> <Subprocess at 140507025396432 with name report_visual in state RUNNING> (stdout)> 
> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/local/lib/python3.10/dist-packages/supervisor/supervisord.py|runforever|218]
>  [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py|record_output|210] [/usr/local/lib/python3.10/dist-packages/supervisor/dispatchers.py
> |_log|179] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|info|327]
> [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|log|345] [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|emit|227]
> [/usr/local/lib/python3.10/dist-packages/supervisor/loggers.py|doRollover|264])
> ```
> 
> **config**
> 
> ```
> [unix_http_server]
> file=/tmp/supervisor.sock   ; (the path to the socket file)
> username=nobody
> password=nobody
> 
> [supervisord]
> logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
> logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
> logfile_backups=10           ; (num of main logfile rotation backups;default 10)
> loglevel=info                ; (log level;default info; others: debug,warn,trace)
> pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
> nodaemon=false               ; (start in foreground if true;default false)
> minfds=1024                  ; (min. avail startup file descriptors;default 1024)
> minprocs=200                 ; (min. avail process descriptors;default 200)
> user=root                    ; (default is current user, required if root)
> 
> ; the below section must remain in the config file for RPC
> ; (supervisorctl/web interface) to work, additional interfaces may be
> ; added by defining them in separate rpcinterface: sections
> [rpcinterface:supervisor]
> supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
> 
> [supervisorctl]
> serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
> 
> [eventlistener:stdout]
> command = supervisor_stdout
> buffer_size = 100
> events = PROCESS_LOG
> result_handler = supervisor_stdout:event_handler
> 
> [inet_http_server]
> port = 9001
> username = root
> password = root
> 
> [program:report_visual]
> command=php bin/console report:visual
> directory=/var/www
> autostart=true
> autorestart=true
> startretries=5
> startsecs=0
> user=root
> numprocs=1
> process_name=%(program_name)s_%(process_num)02d
> stderr_logfile=/dev/stderr
> stdout_logfile=/dev/stdout
> stderr_logfile_maxbytes=0
> stdout_logfile_maxbytes=0
> priority=1
> ```

Same problem

**Comment by mpoberezhniy** [comment]
This worked for me https://github.com/Supervisor/supervisor/issues/935#issuecomment-704633124

**Comment by ok2cqr** [comment]
I had the same problem, solutions in previous comments didn't help. 

Solution was easy but really hard to find. The application was running in Docker and the original author set path to the pid file into path, that was mounted to the docker image as a volume. It worked on Linux but when I tried to run the app in macOS, it worked for the first time but when I stopped the docker and started again, I had the same error message like in this issue. I tried everything described above, googled  and still could not run the app again.

Finally, completely desperate, I tried to change location of the pid file to /var/run/supervisor.pid and it works. Supervisor works as expected.  

Hope this helps also to someone else.

**Comment by ElSamhaa** [comment]
I confirm this https://github.com/Supervisor/supervisor/issues/935#issuecomment-704633124 has stopped all `OSError: [Errno 29] Illegal seek` occurrences.
I think this needs to be reopened. From what I understood, supervisor should detect when `/dev/stdout` or `/dev/stderr` are used and disable log rotation accordingly.

**Comment by mnaberez** [comment]
> From what I understood, supervisor should detect when /dev/stdout or /dev/stderr are used and disable log rotation accordingly.

Supervisor (through 4.2.5) does not detect if the logfile is a special file and automatically change options if so.  Supervisor only attempts to realize the configuration as it is given. 

To use a special file like `/dev/stdout`, disable log rotation as directed in [Configuration](https://supervisord.org/configuration.html).  

The rotation options are:

- In `[supervisord]`, `logfile_maxbytes` for the main log
- In `[program:x]`, `stdout_logfile_maxbytes` and `stderr_logfile_maxbytes` for a child log

The default for all of them is 50MB, meaning rotation is enabled by default.  To use a special file like `/dev/stdout`, set the corresponding `_maxbytes` value to `0` instead.
