### ISSUE TITLE
Old versions of supervisord documentation are not accessible

### ISSUE THREAD

**Issue by ernstki** [Supervisor/supervisor#1234]
I'm stuck with a distro-provided version of supervisord at version 2.something, and I'm running into lots of frustrating problems which are probably due to my trying to use 3.x options that aren't supported but don't generate errors, they're just silently ignored.

The documentation for 2.x and 3.x versions of supervisord seems to have disappeared from the Internet. Usually, there's a drop-down for readthedocs.io-hosted documentation which lets you switch which release you're looking at.

Is it possible the project maintainers could switch that on? Or has the build process for the documentation simply diverged too much since the 2.x and 3.x days?

**Edit**: 3.x versions of the documentation (still doesn't help me) _are_ available [through the Wayback Machine](https://web.archive.org/web/20100421004734/http://supervisord.org/index.html), but the captures don't go back far enough for 2.x apparently. Anyway, something seems wrong about expecting people to use the Wayback Machine for this.

**Comment by mnaberez** [comment]
> Usually, there's a drop-down for readthedocs.io-hosted documentation which lets you switch which release you're looking at.
>
> Is it possible the project maintainers could switch that on? Or has the build process for the documentation simply diverged too much since the 2.x and 3.x days?

The build process completely changed.  Supervisor predates the Sphinx documentation generator.  We used to write the documentation in Docbook XML.  I believe that the Supervisor 2.x docs were written in Docbook, and that we switched to Sphinx for the 3.x docs.  

The last Supervisor 2.x release was over 12 years ago.  We do not recommend anyone use it and can not provide any kind of support for it, sorry.
