### ISSUE TITLE
mailing list link broken

### ISSUE THREAD

**Issue by laurent-claustre** [Supervisor/supervisor#1241]
Hi,
the link for subscribing to the mailing-list is broken:
http://lists.supervisord.org/mailman/listinfo/supervisor-users

The following error was encountered while trying to retrieve the URL: http://lists.supervisord.org/mailman/listinfo/supervisor-users

    Connection to 76.74.238.39 failed.

**Comment by mnaberez** [comment]
@mcdonc owns the domain and runs the mailing list server.  He did not provide notice that it would be going down so hopefully it is a temporary issue.  @mcdonc?

Related: #947

**Comment by jwnextopia** [comment]
Experiencing the same thing myself.  Would be nice to have a mailing list up!

**Comment by mnaberez** [comment]
I sent an email to @mcdonc at the two email addresses I have for him.  I never had access to the mailing list server but here is what I could find out about it:

```
$ ping lists.supervisord.org
PING lists.supervisord.org (76.74.238.39): 56 data bytes
64 bytes from 76.74.238.39: icmp_seq=0 ttl=53 time=21.897 ms

$ host 76.74.238.39
39.238.74.76.in-addr.arpa domain name pointer bahia.palladion.com.

$ whois palladion.com | grep 'Admin Email'
Admin Email: tseaver@palladion.com
```

It looks like the mailing list is actually run by @tseaver.  I sent him an email with a link to this issue.

**Comment by mnaberez** [comment]
It's been over a month since the mailing list disappeared.  It has been down all that time and its owners have not responded.  I will remove the links to it from the documentation.
