### ISSUE TITLE
Add clearing stdout/stderr to the RPC interface

### ISSUE THREAD

**Issue by Perseus101** [Supervisor/supervisor#1256]
Currently, the web interface has a button for clearing the stdout log of a process. It would be useful if this function could be made available via a function in the RPC interface.

**Comment by mnaberez** [comment]
[`supervisor.clearProcessLogs()`](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.clearProcessLogs)
