### ISSUE TITLE
Allow environment variables expansion in ALL options

### ISSUE THREAD

**Issue by palmkevin** [Supervisor/supervisor#126]
Issue #46 implements environment variable expansion. Unfortunately this expansion is not executed on all options.

These options for example are not expanded:

[supervisord]
logfile=%(MY_HOME)s/log/supervisord.log
childlogdir=%(MY_HOME)s/log

[include]
files=%(MY_HOME)s/config/supervisor_*.conf

**Comment by pgkelley4** [comment]
This isn't working for me in 3.1.3 either @mnaberez. It does still work under a program section. I tried 3.0, the first release that would have had this code, and it doesn't seem to work there either.

**Comment by mnaberez** [comment]
@eldos-dl @pgkelley4 This feature hasn't been included in a release version yet.  It was merged into the 3.2 and 4.0 development branches.  It will be released with 3.2.  You can see a complete list of changes for any version in the CHANGES.txt file.

**Comment by pgkelley4** [comment]
Thanks @mnaberez. I missed that.
