### ISSUE TITLE
Unknown Error making dispatchers for 'taxaihoagent' : EISDIR

### ISSUE THREAD

**Issue by bambangy** [Supervisor/supervisor#1260]
I have this program configred

`[program:taxaihoagent]`
`command=/home/taxaiho/target/runner/instance-1/run.sh`
`process_name=taxaihoagent`
`stdout_logfile=/home/taxaiho/logs/logs.log`
`stderr_logfile=/home/taxaiho/errs/`
`user=taxaiho`

Supervisored always give me this error, everytime I start this `taxaiho` program

Unknown Error making dispatchers for 'taxaihoagent' : EISDIR

**Comment by mnaberez** [comment]
> ```stderr_logfile=/home/taxaiho/errs/```

`EISDIR` is occurring because this is a directory.  The logfile must be a regular file.
