### ISSUE TITLE
Supervisor does not search path added to $PATH in `~/.profile` for binary in `program.command`

### ISSUE THREAD

**Issue by updogliu** [Supervisor/supervisor#1266]
(System: Ubuntu 18.04. `supervisord` run by user `ubuntu` with `sudo`. `supervisorctl` run by user `ubuntu`.)

I added golang binary path to `PATH` in `~/.profile` via `export PATH=$PATH:$GOPATH/bin`. After that I can run the binaries in `$GOPATH/bin` from a shell without specifying path.

However, when using the binaries in `program.command` I got `ERROR (no such file)`. But `program.command` of binaries in `/usr/local/bin` can be found without problem. Am I missing something?

**Comment by updogliu** [comment]
FWIW, 
`command=echo %(ENV_USER)s , %(ENV_SUDO_USER)s , %(ENV_HOME)s , %(ENV_PATH)s`
shows
`root , ubuntu , /home/ubuntu , /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`
The `HOME` variable is `ubuntu`'s, but not `PATH`.

**Comment by mnaberez** [comment]
[Configuration](http://supervisord.org/configuration.html):

> The user will be changed using `setuid` only. This does not start a login shell and does not change environment variables like `USER` or `HOME`. See Subprocess Environment for details.

[Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment):

> Subprocesses will inherit the environment of the shell used to start the supervisord program. 
...
> Unlike cron, supervisord does not attempt to divine and override “fundamental” environment variables like USER, PATH, HOME, and LOGNAME when it performs a setuid to the user defined within the user= program config option.
