### ISSUE TITLE
supervisor config test functionality may be required

### ISSUE THREAD

**Issue by jos666** [Supervisor/supervisor#1267]
The current problem is that there is a problem with the configuration file. After the **supervisord** is running, use `supervisorctl reload` or `supervisorctl update`. If the configuration file has problems, supervisord will hang. we  need to use the reload or update command to configure the file. If there is an error, it will not be loaded.Thank

**Comment by mnaberez** [comment]
There are no none cases where `supervisord` will hang in response to an `update` command, and I have been unable to duplicate this.  If you are able to provide specific instructions to reproduce, we can reopen.
