### ISSUE TITLE
Stdout from C not printed in log

### ISSUE THREAD

**Issue by martinezcp** [Supervisor/supervisor#1268]
I am trying to save the log of my C application in the stdout file. 

I have tried with printf("hello world..."); and with fprintf(stdout, ....);
Same result. Nothing is printed on the log file. Log file is created as soon as supervisor starts the application.

Application is working fine and not crashing.

If I try to use fprintf(stderr,...); instead, I get data printed in the error log.

This is my config file at this moment:

> [program:my_app]
command=./home/pi/app
stderr_logfile = /home/pi/logs/err/app-stderr.log
stdout_logfile = /home/pi/logs/app-stdout.log
stdout_logfile_maxbytes=0

I tried adding "redirect_stdout=true", "stdout_logfile_maxbytes=20" but I get same results.

**Comment by mnaberez** [comment]
> If I try to use fprintf(stderr,...); instead, I get data printed in the error log.

Your program is probably buffering `stdout`.  Add a call to `fflush()` after printing.

**Comment by martinezcp** [comment]
I already tried with fflush(stdin); after my printf but I got same result.

**Comment by martinezcp** [comment]
It worked with a fflush(stdout); Thank you!
