### ISSUE TITLE
Http server errors out.

### ISSUE THREAD

**Issue by YaphetKG** [Supervisor/supervisor#1276]
I had the supervisor server stood up, and for some reason it fails to extract the server name / http host value from the request headers. This used to work but after a fresh pip install of supervisor it started to give me this error. 
```
ERRO :Server Error: <class 'TypeError'>, unsupported operand type(s) for +: 'NoneType' and 'str': file: /usr/local/src/supervisor/supervisor/http.py line: 328
````

**Comment by mnaberez** [comment]
> This used to work but after a fresh pip install of supervisor it started to give me this error.

What version of Supervisor did you install with `pip`?  

Error message from above:

```
ERRO :Server Error: <class 'TypeError'>, unsupported operand type(s) for +: 
'NoneType' and 'str': file: /usr/local/src/supervisor/supervisor/http.py line: 328
```

Line 328 in Supervisor 4.0.4:

https://github.com/Supervisor/supervisor/blob/44eefd5846b68fab4dc7ce57b9a30629d9aa5c4a/supervisor/http.py#L328

There is no `+` on line 328 in Supervisor 4.0.4 (the latest release version) so you must have installed some other version.

**Comment by YaphetKG** [comment]
my line in pip requirements file was 
`-e git+https://github.com/Supervisor/supervisor@master#egg=supervisor`

**Comment by YaphetKG** [comment]
I will use the pip install supervisor instead, Thanks.

**Comment by mnaberez** [comment]
Reopening so we can fix master.
