### ISSUE TITLE
supervisorctl "-u" option

### ISSUE THREAD

**Issue by jhonaikerf** [Supervisor/supervisor#1281]
# sudo supervisorctl -u root start in:*
in:in_00: ERROR (abnormal termination)

Log:
The "-u" option does not exist.

[program:in]
process_name=%(program_name)s_%(process_num)02d
command=php /home/in/in/artisan queue:work sqs --sleep=3 --tries=3
autostart=true
autorestart=true
user=in
numprocs=1
redirect_stderr=true
stdout_logfile=/home/in/in/worker.log

**Comment by mnaberez** [comment]
> in:in_00: ERROR (abnormal termination)
>
> Log:
> The "-u" option does not exist.

This error appears to be from a program running under `supervisord` rather than from `supervisord` or `supervisorctl`.
