### ISSUE TITLE
processes start one by one and the order is not under my control

### ISSUE THREAD

**Issue by lag1500** [Supervisor/supervisor#1287]
$supervisord -v
4.0.4

CentOS Linux release 7.4.1708 (Core)

First, I know priority config doesn't work which is discussed in [https://github.com/Supervisor/supervisor/issues/122](url).
But in my case, the processes DO NOT start the same time.
supervisord.log is like this:

**2019-10-23 14:29:40,210 INFO spawned: 'helloworldB' with pid 18106
2019-10-23 14:29:43,216 INFO success: helloworldB entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2019-10-23 14:29:43,218 INFO spawned: 'helloworldA' with pid 18120
2019-10-23 14:29:49,216 INFO success: helloworldA entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)**

helloworldA was spawned until helloworldB turned into success state.

And my helloworld.conf:
[group:hwg]
programs=helloworldA,helloworldB

[program:helloworldA] 
directory = /data/dp/cpp
command = /data/dp/cpp/a.out     
autostart = false        
;priority=1
startsecs = 5            
autorestart = true       
startretries = 3         
user = root              
redirect_stderr = true   
stdout_logfile_maxbytes = 50MB  
stdout_logfile_backups = 7
stdout_logfile = /data/dp/cpp/aout.log

[program:helloworldB] 
directory = /data/dp/cpp 
command = /data/dp/cpp/a.out        
autostart = false        
;priority=10
startsecs = 3            
autorestart = true       
startretries = 3         
user = root              
redirect_stderr = true   
stdout_logfile_maxbytes = 50MB  
stdout_logfile_backups = 7 
stdout_logfile = /data/dp/cpp/aout2.log

In the above conf file, the priority is commented and nothing changes if I uncomment them.
I think my case is event worse than the "processes start the same time" because it costs much longer launching time if the process number is bigger...

I don't expect priority config work. I just want processes to start at the same time. At least it is a **REGULAR** behavior.

Anyone can help me? Thanks in advance.

**Comment by mnaberez** [comment]
The configuration above has `autostart = false` in each `[program:x]` so none of them will be started automatically.  The programs have to be started through `supervisorctl`.  

The commands `supervisorctl start all` and `supervisorctl start hwg:*` will both start the programs `helloworldA` and `helloworldB` at the same time.
