### ISSUE TITLE
[Suggestion]: add a list command, add log command

### ISSUE THREAD

**Issue by Nomia** [Supervisor/supervisor#1288]
Hi,

I suggest take a look at `pm2`. Its command line tips and commands are much more intuitive than `supervisor`.

When I use supervisor, I always forgot how to `list` all the programs. Could u give a `list` command, like `supervisorctl list`, or if u can't, there should be a instruction in the `--help` command that tells user how to list all the programs. Of course now I know to list all programs just type `supervisorctl`. But I will never know when I forget that. So I type `supervisorctl --help`, the help didn't help at all.

Second, When I want to see log of a program, I can't find how when I type `supervisorctl --help`. 

So, Wish u can improve `supervisorctl --help` command a little bit. Or give more command, like `supervisorctl list`, `supervisorctl log`.

thx

**Comment by Nomia** [comment]
![image](https://user-images.githubusercontent.com/1707818/67622097-365ee300-f849-11e9-94d2-1fb6e16e0c1f.png)

There is a problem in my `redis` program. But I cannot see the program log in the output. And I cannot find how to see the log in the `supervisorctl --help` command.

**Comment by mnaberez** [comment]
Please see here for a list of commands:
http://supervisord.org/running.html#running-supervisorctl

As mentioned in the output of `supervisorctl --help`, you can use the `help` command to get a list of commands or `help <command>` to get more help for a specific command.  

The commands you are requesting already exist but they have different names (e.g. `status` gives a list of processes, `tail` tails a log file).  Please refer to the references above for more information on using `supervisorctl`.

**Comment by Nomia** [comment]
I got it. The `status` and `tail` called `supervisor action`. But how can I list all the `supervisor action` when I need to use specific one? I have to first run command `supervisorctl` and enter `supervisor>` interactive mode, then I can type `help` command again to get a list action.

But, how can a new `supervisor` user knows that there are two help, one with dash, one without dash. Old user can even forget about it. Because we usually use `supervisor` at the first beginning of project deploy, and will never touch it until there is any problem. So we will forget about the command.

My suggestion is that show the `supervisor action`s right in the `supervisorctl --help` output, instead of burying all the `actions` in the second level, making user hard to find all the common actions.
