### ISSUE TITLE
Supervisor can generate an event on sensugo in case of any process failure and stop?

### ISSUE THREAD

**Issue by masifpak** [Supervisor/supervisor#1289]
I am using supervisor to manage my processes in linux. I have also deployed sensugo for monitoring to monitor process, resources and queues. I just want to ask, supervisor can generate an event by using API of sensugo in case of any process stop or failure?

**Comment by mnaberez** [comment]
Supervisor does not include any built-in support for it but there may be a plugin.  

Please check the [third party plugins list](http://supervisord.org/plugins.html).
