### ISSUE TITLE
Expand system environment variable when running service

### ISSUE THREAD

**Issue by alexlipa91** [Supervisor/supervisor#1291]
Hi, I am quite new to supervisor. I was wondering if it is possible to expand currently defined environment variables in the launch command. An example: I tried to do that 

   `environment = JAVA_HOME="/usr/java/jdk1.8.0_181-amd64",PATH="%{PATH}:%{SPARK_HOME}/bin:%{SPARK_HOME}/sbin",PYTHONPATH="%{SPARK_HOME}/python/:%{PYTHONPATH}",PYTHONPATH="%{SPARK_HOME}/python/lib/py4j-0.10.7-src.zip:%{PYTHONPATH}"` 

but I get an error `ERROR: CANT_REREAD: Format string`

Obviously my first attempt was to try to replace environment variables using $PATH or $SPARK_HOME for example but it didn't work.

**Comment by mnaberez** [comment]
https://github.com/Supervisor/supervisor/blob/18b59a1403778766561ab49b18cf2558e8a4d227/supervisor/skel/sample.conf#L7-L8
