### ISSUE TITLE
Running inside a container, environment variables from the container are not passed to the daemon

### ISSUE THREAD

**Issue by voodoodrul** [Supervisor/supervisor#1292]
When running supervisord inside a Docker container (the entrypoint is apache) and I can verify that the environment variables are set correctly inside the container. However, processes that supervisord invokes only get environment variables from the *HOST*, not the container.

**Comment by mnaberez** [comment]
Supervisor doesn't have any special awareness of Docker containers and doesn't read operating system files like `/etc/environment`.  The environment variables that exist in `supervisord`'s environment at the time it is started are the ones that it uses.  For more information, please see: http://supervisord.org/subprocess.html?highlight=environment#subprocess-environment
