### ISSUE TITLE
Support conditional statements for autostart/autorestart values

### ISSUE THREAD

**Issue by tadasauciunas** [Supervisor/supervisor#1295]
Is it currently possible, and if not, would it be possible to implement a way to support conditional statements which would return a boolean which would then be used as value of autostart and autorestart in supervisor.conf file ?

Example:
```
[program:some_script]
command=sh -c 'sleep 15 && php /var/www/public/myScript.php'
autostart=%(APPLICATION_ENV)s == 'staging'
autorestart=%(APPLICATION_DB)s == 'test'
```

Currently we can just use this:
`autostart=%(APPLICATION_ENV_IS_STAGING)s` 
But then this specific environment variable must be explicitly defined as a boolean value prior to running supervisord, and we don't need it any anywhere else than supervisor configs.

**Comment by mnaberez** [comment]
Implementing a templating language or any kind of conditionals in the configuration file is outside the current scope of this project, sorry.

**Comment by amcastror** [comment]
Hi, sorry for reopening this, but is there a way to "gracefully" stop a process, meaning to allow them to finish their work while preventing them to relaunch?

Thanks a lot.
