### ISSUE TITLE
supervisord error

### ISSUE THREAD

**Issue by rondip-geekyants** [Supervisor/supervisor#1297]
`zsh: /usr/local/bin/echo_supervisord_conf: bad interpreter: /usr/local/opt/python/bin/python2.7: no such file or directory`

How to resolve this?

**Comment by mnaberez** [comment]
There is something wrong with the installation on this system.  This error is occurring before any `supervisord` code is even being reached, so I don't think we will be able to help, sorry.  You will probably need to reinstall `supervisord` somehow.
