### ISSUE TITLE
Supervisor compatibility issue with Python 3.7.4

### ISSUE THREAD

**Issue by prashantochatterjee** [Supervisor/supervisor#1300]
I am installing supervisor==4.1.0 using pip in my Dockerfile on top of base CentOS image with Python 3.7.4:
`
RUN     pip install --upgrade pip && \
        pip install --upgrade supervisor==4.1.0 && \
`

The install works fine:
`
Step 1/13 : FROM <base-image with Python 3.7.4>
 ---> 1f1cfc033803
Step 2/13 : MAINTAINER macaw.io
 ---> Using cache
 ---> 3220216e5e6a
Step 3/13 : RUN ln -s /opt/java/bin/java /usr/bin/java 
 ---> Using cache
 ---> 31fbd1bbe9e3
Step 4/13 : RUN pip install --upgrade pip &&         pip install --upgrade supervisor==4.1.0 &&
.............
Step 13/13 : CMD /usr/bin/supervisord -c /etc/supervisord.conf
 ---> Running in 67b920862196
 ---> 0e953d621435
`

When the container comes up, it complains about version conflict and mandates me to use supervisor==3.1.4. 
`
pkg_resources.VersionConflict: (supervisor 4.1.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('supervisor==3.1.4'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'supervisor==3.1.4' distribution was not found and is required by the application
`

If I use supervisor 3.1.4, it does not build the container citing that 3.1.4 does not work with Python 3 (expected). I am perplexed and had to resort to using a wrapper script that can manage multiple processes. Whats going wrong here??? Appreciate your prompt response.

**Comment by mnaberez** [comment]
> pkg_resources.DistributionNotFound: The 'supervisor==3.1.4' distribution was not found and is required by the application

This error message does not come from Supervisor.   It comes from `pkg_resources` (a part of `setuptools`).  The application you are trying to install has specified in its requirements that it requires `supervisor==3.1.4` but you have installed another version of `supervisor`.  To install a version of `supervisor` other than `3.1.4`, the requirements of the application would need to be changed (e.g. the application's `setup.py` or `requirements.txt` files).

**Comment by prashantochatterjee** [comment]
Thanks for your response @mnaberez. We could not get supervisor working with CentOS7 + Python 3.7.4. We had to update the base image to Ubuntu18.04 + Python3.7.4 to get supervisor 4.1.0 working.
