### ISSUE TITLE
Send process stdout to supervisord stdout?

### ISSUE THREAD

**Issue by nunojpg** [Supervisor/supervisor#1313]
I run supervisor as pid 1 in docker.

I would like that docker logs (supervisord stdout/stderr) would show the output of several of my processes, as journalctl would do for several services.

4.0.0 introduced stdout_syslog ("If true, stdout will be directed to syslog along with the process name.") 

I see this as similar feature "stdout_supervisord" or "stdout_parent".

Have this been discussed or is this already supported in any way?

**Comment by mnaberez** [comment]
Several existing options:

- Install a plugin like [supervisor-stdout](https://github.com/coderanger/supervisor-stdout)
- In the `[supervisord]` section, `loglevel=debug` will include child log output in the main log 
- In a `[program:x]` section, `stdout_logfile=/dev/stdout` (may not work on all systems)

**Comment by nunojpg** [comment]
@mnaberez thanks for the support.

**Comment by nunojpg** [comment]
@mnaberez I find that the best option for me is to use loglevel=debug, while stdout from all the processes is too verbose. I would prefer just stderr since that is what is mostly relevant when a service fails to start.

Can I propose a loglevel of info with processes stdout?
