### ISSUE TITLE
How to create multiple Unix domain Sockets.

### ISSUE THREAD

**Issue by binrebin** [Supervisor/supervisor#1314]
Relatively new to coding. I am deploying Aiohttp -Nginx server to AWS-EC2. I wanted to proxy_pass request to 4 upstream server instances(unix domain sockets). But Supervisord document says nothing about creating multiple sockets. Will be a kind help and a knowledge for others like me.
SUPERVISORD - supervisord.conf
```
[unix_http_server]
file=/var/run/mapp_x.sock
chmod=0777
chown=nobody:nogroup
[supervisord]
user=root
logfile=/var/log/supervisord.log ; main log file; default $CWD/supervisord.log
logfile_maxbytes=50MB        ; max main logfile bytes b4 rotation; default 50MB
logfile_backups=10           ; # of main logfile backups; 0 means none, default 10
loglevel=info                ; log level; default info; others: debug,warn,trace
pidfile=/var/run/supervisord.pid ; supervisord pidfile; default supervisord.pid
nodaemon=false               ; start in foreground if true; default false
minfds=1024                  ; min. avail startup file descriptors; default 1024
minprocs=200    
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
;user=root
serverurl=unix:///var/run/mapp_x.sock
[program:mappserver]
user=nobody
numprocs = 4
numprocs_start = 1
process_name = mapp_%(process_num)s
command=python app.py --path=/var/run/mapp_%(process_num)s
autostart=true
autorestart=true
```
NGINX - nginx.conf
```
http {
    upstream mapp {
       server unix:/tmp/mapp_1.sock fail_timeout=0;
        server unix:/tmp/mapp_2.sock fail_timeout=0;
        server unix:/tmp/mapp_3.sock fail_timeout=0;
        server unix:/tmp/mapp_4.sock fail_timeout=0;
}
server {
        listen 80;
        location / {
            proxy_pass http://mapp;
}  }   }

```
in ERRORs
`At /var/run/ -> only mapp_x.sock, (whatever number I write insted of x) is created. mapp_1.sock, mapp_2.sock, mapp_3.sock doesnt exists
.
error 2: only when user @ [supervisord] is root, unix socket creates. but Supervisor docs says Supervisor shall not run with root:root
`
Thanks in advance

**Comment by mnaberez** [comment]
> But Supervisord document says nothing about creating multiple sockets.

`supervisord` can be controlled over one inet socket ([`[inet_http_server]` section](http://supervisord.org/configuration.html#inet-http-server-section-settings)) and/or one domain socket ([`[unix_http_server]`](http://supervisord.org/configuration.html#unix-http-server-section-settings)).  It can listen on exactly one socket of each type.  It does not support listening on multiple domain sockets.

**Comment by binrebin** [comment]
@mnaberez, Then how can we achieve this if needed. The answer would be help for others also.
