### ISSUE TITLE
Supervisor got from another path the python env

### ISSUE THREAD

**Issue by JosielWirlino** [Supervisor/supervisor#1318]
Supervisor is gettings python env of another dir

**--env**
python3.6
I´m  not using virtual env
Ubuntu 18.04.2 LTS

**/etc/supervisor/conf.d/cerberus-backend.conf**
```
[program:cerberus-backend]
;environment=PYTHONPATH='/usr/.local/bin/'
directory = /var/www/node/project/cerberus/backend
command = python3 manage.py runserver 0:4444
autostart=true
autorestart=true
stderr_logfile=/var/log/error-backend-cerberus.log
stdout_logfile=/var/log/out-backend-cerberus.log
```

Currently when I try to run django automatically I got the message

"No module django found" however is installed, and checking he try load django from /usr/local/lib/python3.6/dist-packages instead of /usr/ **.** local/lib/python3.6/dist-packages, take a look and you will see that the diff is the "dot" /.local -> /local. 

Should be a way to setup it instead of be necessary install everything again like:

`$ python3 -m pip  install --target=/usr/local/lib/python3.6/dist-packages` and necessary move on the django project and app.
Solution got from [StackOverflow](https://stackoverflow.com/questions/55141712/ubuntu-supervisor-import-python-modules-error)

**Comment by mnaberez** [comment]
http://supervisord.org/subprocess.html#subprocess-environment:
> Subprocesses will inherit the environment of the shell used to start the supervisord program. 

...

> No shell is executed by supervisord when it runs a subprocess, so environment variables such as USER, PATH, HOME, SHELL, LOGNAME, etc. are not changed from their defaults or otherwise reassigned. This is particularly important to note when you are running a program from a supervisord run as root with a user= stanza in the configuration. Unlike cron, supervisord does not attempt to divine and override “fundamental” environment variables like USER, PATH, HOME, and LOGNAME when it performs a setuid to the user defined within the user= program config option.

**Comment by JosielWirlino** [comment]
If someone is looking for reason..
it solve the issue
`environment=PYTHONPATH="/home/wirlino/.local/lib/python3.6/site-packages/"`
