### ISSUE TITLE
ERROR (no such file) when trying to start a process

### ISSUE THREAD

**Issue by fawcettjt** [Supervisor/supervisor#1321]
I'm new to using supervisor and am trying to get a dev environment for an application up and running locally on my machine having taken over something developed by someone else previously. When I try to run supervisor and start a process (or multiple processes), I keep getting a very generic message 'ERROR (no such file).'
It doesn't state what file is missing, though, or provide any additional details to help me find out what I'm missing. 

From the output below, supervisor seems to be able to see the two ini files in my directory and provides the import options I want to start. But I cannot start them.

Any recommendations on where I can get a more verbose error output to find out what I'm missing or any reconfiguration that needs to be done here?

$ supervisorctl -c /usr/local/etc/supervisord.ini
hwk_import                       STOPPED   Not started
khc_import                       STOPPED   Not started
supervisor> start hwk_import 
hwk_import: ERROR (no such file)
supervisor> start khc_import 
khc_import: ERROR (no such file)
supervisor> start all
hwk_import: ERROR (no such file)
khc_import: ERROR (no such file)
supervisor>

**Comment by mnaberez** [comment]
> supervisor> start all
> hwk_import: ERROR (no such file)

In the configuration file, find the `[program:hwk_import]` section and look at the `command= ` line under it.  This is what specifies the command it is trying to start.
