### ISSUE TITLE
reread does not respect changes to running services

### ISSUE THREAD

**Issue by jsolomon8080** [Supervisor/supervisor#1322]
A service is running with autorestart=true which would mean that if it crashed or exited on its own, supervisord would restart it. Great.

Then I rewrite the service definition and set autorestart=false and issue a "reread" and supervisord correctly reports that that service has changed.

But now if the service's process crashes or exits, I would want supervisord to respect the new service definition and NOT restart the process but it does restart it.

In general, I want supervisord to apply the output of the reread to the existing process groups.

We are coming from using systemd where "systemctl daemon-reload" behaves this way and it makes sense.

Is this behavior by design or an issue we can address?

**Comment by mnaberez** [comment]
> In general, I want supervisord to apply the output of the reread to the existing process groups.

Use `update` instead of `reread`.  The `reread` command rereads the configuration file but does not change the active configuration.  `update` changes the active configuration.

**Comment by jsolomon8080** [comment]
I don't want update. Update will cause changes to my services most likely restarting it. I just want supervisord to leave my existing service alone but respect the new values for the service I just wrote.

**Comment by jsolomon8080** [comment]
Let me ask another way. How can I change the autorestart property of the service that is already running without restarting the service?

**Comment by mnaberez** [comment]
> How can I change the autorestart property of the service that is already running without restarting the service?

`supervisord` does not have this capability.  This change would not be possible without rewriting the configuration reloading machinery, which was contributed by a user.  The maintainers are unlikely to pursue this at this time.

**Comment by jsolomon8080** [comment]
Got it. Thanks.
