### ISSUE TITLE
supervisorctl update throws UNKNOWN_METHOD xmlrpc error

### ISSUE THREAD

**Issue by vanyakosmos** [Supervisor/supervisor#1324]
```
❯ supervisord
❯ supervisorctl update
error: <class 'xmlrpc.client.Fault'>, <Fault 1: 'UNKNOWN_METHOD'>: file: /Users/Vania/.pyenv/versions/3.7.5/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py line: 656
```

setup:
- python3.7.5
- osx 10.15.3

config:
```
[supervisord]

[supervisorctl]

[inet_http_server]
port = 127.0.0.1:9001

[program:foo]
command = /bin/cat
```

**Comment by mnaberez** [comment]
http://supervisord.org/configuration.html#rpcinterface-x-section-settings:

> In the sample config file, there is a section which is named `[rpcinterface:supervisor]`. By default it looks like the following.
> 
> ```
> [rpcinterface:supervisor]
> supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
> ```
> 
> The `[rpcinterface:supervisor]` section must remain in the configuration for the standard setup of supervisor to work properly. If you don’t want supervisor to do anything it doesn’t already do out of the box, this is all you need to know about this type of section.
