### ISSUE TITLE
Uvicorn webscoket redirected as stderr

### ISSUE THREAD

**Issue by TheBuky** [Supervisor/supervisor#1325]
**Context**
 Using Django with channels behind Nginx as reverse proxy. Everything work to establish communication and response but the supervisor logging catch the Uvicorn log for WebSocket as error and write it in the error file...

**Configuration**

- supervisor.ini
```
[supervisord]

[fcgi-program:uvicorn]
socket = unix:///tmp/my-unix.sock

command = /home/user/.virtualenvs/my-env/bin/uvicorn --fd 0 app.asgi:application
numprocs = 1
process_name = %(program_name)s_%(process_num)02d

stdout_logfile = /home/user/stdout.log
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 10
stdout_events_enabled = false

stderr_logfile = /home/user/stderr.log
stderr_logfile_maxbytes = 1MB
stderr_logfile_backups = 10
stderr_events_enabled = false
```

**Log files**

- stdout.log
```
INFO:      - "GET /home/ HTTP/1.0" 200 OK
INFO:      - "GET /my-page/ HTTP/1.0" 200 OK
```

- stderr.log

```
INFO:     Started server process [666]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on socket /tmp/my-unix.sock (Press CTRL+C to quit)
INFO:     None - "WebSocket /ws/" [accepted]
```

**Problem** 
The line `INFO:     None - "WebSocket /ws/" [accepted]` in **stderr.log** should be redirected in **stdout.log** because the connection is correctly established (and work as well). Maybe just a little problem to handle the request as *success* for *supervisor*  because it's WebSocket request? Not status code and `None` make him think it's error???

**Comment by mnaberez** [comment]
> The line INFO: None - "WebSocket /ws/" [accepted] in stderr.log should be redirected in stdout.log because the connection is correctly established (and work as well). Maybe just a little problem to handle the success and fail connection for WebSocket requests?

When a process running under `supervisord` writes to its `stdout` file descriptor, `supervisord` will record that output in the file configured in `stdout_logfile`.  Similarly, anything a process writes to `stderr` will be written to `stderr_logfile`.

`supervisord` can be instructed to combine the data from both `stdout` and `stderr` into a single logfile.  See the `redirect_stderr` option in the [configuration file](http://supervisord.org/configuration.html).

`supervisord` does not have any special awareness or configuration for Nginx, Django, Uvicorn, or any other program.  If you need a certain program to log in a different way, it has to be addressed in that program.  `supervisord` can't control what a process logs other than what is described above.

**Comment by TheBuky** [comment]
Indeed I had missed the option `redirect_stderr=true` related in the documentation but that not why I would like to do. My real question was about the log `INFO:     None - "WebSocket /ws/" [accepted]` is considered as "error"? It's because of the file descriptor sent by the child process is like that?

**Response:** After check the code of the uvicorn library
```python
class WebSocketProtocol(websockets.WebSocketServerProtocol):
    def __init__(self, config, server_state, _loop=None):
        ...
        self.logger = logging.getLogger("uvicorn.error")
```
Well... The mystake come from uvicorn who use logger`error` for `websocket`
