### ISSUE TITLE
Supervisor 4.1.1 release

### ISSUE THREAD

**Issue by AndreyMZ** [Supervisor/supervisor#1332]
The latest supervisor 4.1.0 was released on 20 Oct 2019 - 4 months ago.
42 commits to master since this tag.

What about releasing 4.1.1?

**Comment by mnaberez** [comment]
Another release is likely to be made relatively soon.  The [changelog](https://github.com/Supervisor/supervisor/blob/master/CHANGES.rst) shows the changes that are planned for it.
