### ISSUE TITLE
Supervisord blocks aioredis in combination with Quart

### ISSUE THREAD

**Issue by famecastle** [Supervisor/supervisor#1334]
I am using the [Quart](https://pgjones.gitlab.io/quart/) web server framework together with aioredis.

aioredis is listening for Redis events and executing certain actions then. For testing purposes, I just issue these Redis PUB/SUB events from the `redis-cli` command line interface.

Now the problem is: if I run my server like `python main.py` everything works well and new events trigger the actions immediately.

However, if I run my `python main.py` command through my supervisord configuration, the event listener is blocking as long as no web server request is being made. This means, if I load a page like `localhost:5000/` then, I will get all previously blocked Redis event messages bundled and at once.

I'm really confused by this behavior. The Quart dev doesn't have an exact idea either. Maybe the problem could have something to do with forking or permissions? (Note: I already tried running my supervisord server with `nodeaemon=true` which didn't help.)

Here's some code:

```python
async def observe_redis_events(channel, action):
    try:
        app.logger.debug(f"Starting redis client to observe '{channel}' events")
        own_redis_db = await aioredis.create_redis((config.redis_host, config.redis_port), db=config.redis_db, encoding="utf-8") # private redis client to observe just the specific events
        target_channels = await own_redis_db.subscribe(channel)
    except Exception as e:
        app.logger.exception("Could not subscribe to redis event channel.")
    app.logger.debug(f"Redis event subscription to channel '{channel}' established.")
    observed_channel = target_channels[0]

    print(f"Waiting on {channel}")
    try:
        while await observed_channel.wait_message():      # <- this will wait for a new message and is blocking to long when used with supervisord (because it somehow waits for a web request to the Quart server!)
            print("Parsing")
            message = await observed_channel.get_json()
            print("Executing Action.")
            await action(**message)
            print("Finished.")
    except Exception as e:
        app.logger.exception("Not so good.")
    
    app.loger.debug(f"Redis event subscription to channel '{channel}' ended.")

@app.before_serving
async def startup():
    asyncio.get_running_loop().create_task(observe_redis_events("game", notify_game_update))
```

The redis-cli command:
`PUBLISH game "{\"info\": \"Hello World!\"}"`
but this can be really just anything.

And here are the relevant parts from my supervisord.conf:

```
[supervisord]
logfile=logs/supervisord.log
logfile_maxbytes=20MB

[unix_http_server]
file=/tmp/supervisor.sock
username=[...]
password=[...]

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
username=[...]
password=[...]
prompt=[...]

[program:server]
command=python main.py
stdout_logfile=logs/%(program_name)s.log
redirect_stderr=true

[group:full_environment]
programs=[...],[...],server
```

P.S.: I run all this in a Python 3.7 venv. My supervisord is installed there and only for that single project. I also stopped all other services to see if it's really the main server which makes the problems or if it's another program which causes the problems on the main server - but it's really just the `main.py` which has problems in combination with supervisord.

Do you have any idea what might be causing those weird problems.

Best regards!

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by famecastle** [comment]
Thanks for your answer. However, don't you consider Redis one of the most popular tools developers use? And asyncio, a python technology (and it's not too uncommon that Supervisord which was written in Python is being used for python applications), is also a very fundamental and new technology which might become even more popular in the future. Somehow Supervisor may be doing something that prevents aioredis from working correctly. Who will I need to talk to, to investigate further and eliminate this problem?

**Comment by mnaberez** [comment]
> Who will I need to talk to, to investigate further and eliminate this problem?

I do not have another suggestion for someone to contact, sorry.  There are only a few people maintaining this repository and we do not have enough bandwidth to assist with installing any particular program under `supervisord`.  Sorry again.
