### ISSUE TITLE
Feature request: JSON logging option

### ISSUE THREAD

**Issue by benzvan** [Supervisor/supervisor#1337]
We have everything going to ELK and it would be really nice to wrap the log messages in json with a sub-second `@timestamp` value to help us see logs in the correct order. Implementation could be either a `-j` flag to log in a canned json format or another flag or environment variable to define a custom log format.

**Comment by mnaberez** [comment]
Closing as there is already an open issue for custom log formatting in #553.  This would likely be handled by the solution to #553.  That issue does not specifically mention JSON but there will be link from that issue back to this one.

**Comment by benzvan** [comment]
Thank you! That would explain why I wasn't able to find an open issue.

**Comment by datangleapin** [comment]
how can i entry issue
