### ISSUE TITLE
Help with configuring supervisord and stunnel

### ISSUE THREAD

**Issue by jzvi12** [Supervisor/supervisor#1338]
I getting `FATAL Exited too quickly (process log may have details ) `when I tried to run supervidor on my Ubuntu 18.04 server.

Below is my config:

```
[program:stunnel1]
command=/usr/bin/stunnel4 /etc/stunnel/stunnel.conf
user=root
autostart=true
autorestart=true
stderr_logfile=/etc/stunnel/stunnel.error.log
```

- logged in as root (sudo su)
- installed via apt-get
- created a conf file under conf.d/ directory
- ran command supervisorctl reread
- ran command supervisorctl update
- Fatal error displyed

**Comment by mnaberez** [comment]
If the process exits too quickly, it may be daemonizing (see [nondaemonizing of subprocesses](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses)).

The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
