### ISSUE TITLE
command name discrepancy

### ISSUE THREAD

**Issue by minusf** [Supervisor/supervisor#1339]
I run multiple `supervisord` instances all controlling only a single project.  Every supervisord is installed in the project's `venv` and uses its own config file.

in all these config files i set the same for the projects:

```
[program:{{ project }}]
directory       = {{ project_dir }}
command         = venv/bin/uwsgi --ini {{ project_dir }}/etc/uwsgi.ini
```

however `ps` output looks like this:

```
/export/apps/project_1/venv/bin/uwsgi --ini /export/apps/project_1/etc/uwsgi.ini
/export/apps/project_1/venv/bin/uwsgi --ini /export/apps/project_1/etc/uwsgi.ini
/export/apps/project_1/venv/bin/uwsgi --ini /export/apps/project_1/etc/uwsgi.ini
/export/apps/project_1/venv/bin/uwsgi --ini /export/apps/project_1/etc/uwsgi.ini
venv/bin/uwsgi --ini /export/apps/project_2/etc/uwsgi.ini
venv/bin/uwsgi --ini /export/apps/project_2/etc/uwsgi.ini
venv/bin/uwsgi --ini /export/apps/project_2/etc/uwsgi.ini
venv/bin/uwsgi --ini /export/apps/project_2/etc/uwsgi.ini
```

Why the difference? Both these projects have in `supervisord.log`:

```
... INFO set current directory: '...'
```

If I want the commands to look the same, should i just use an absolute path `command` and no `directory`?

**Comment by mnaberez** [comment]
The name shown by `ps` is set by the operating system when `supervisord` spawns the command specified by `command=`.  The operating system typically shows the same text as in `command=` but it is up to the operating system.  There are some non-portable ways to try and manipulate the name shown by `ps` but `supervisord` does not do any of them.  

> If I want the commands to look the same, should i just use an absolute path command and no directory?

The `directory=` option in `supervisord.conf` should not affect the name shown by `ps`.  This option tells `supervisord` to change to the specified directory before spawning the process via fork/exec.  It does not normally influence `ps`.

You can try changing the command specified in `command=` and you should see a corresponding change in the output of `ps`.

**Comment by minusf** [comment]
thank you for your answer.  i am aware about how process names are set by the OS and my question wasn't really about manipulating process names as shown by `ps`. it seemed strange to me that the same configuration results in a non-deterministic result and i wasn't sure if the OS is solely to blame.  after all executing a process will result in the same process name everytime, and it's supervisord who is doing the execution...
