### ISSUE TITLE
global default for startsecs

### ISSUE THREAD

**Issue by luto** [Supervisor/supervisor#1341]
The [`startsecs`](http://supervisord.org/configuration.html#program-x-section-example)  configuration value controls how long a program has to stay alive to transition into the `RUNNING` state. This can currently only configured inside the `[program:]` section and there is no global default, except for the hardcoded one 1s.

Are you interested in promoting this to a `[supervisord] startsecs=` configuration, which acts as a fall back for `[program:] startsecs=` and defaults to 1?

**Comment by mnaberez** [comment]
> Are you interested in promoting this to a [supervisord] startsecs= configuration, which acts as a fall back for [program:] startsecs= and defaults to 1?

No.  I think it would be confusing if we "promoted" only one particular option in this way, and I do not think we should "promote" all of them.
