### ISSUE TITLE
SocketManagerTest.test_prepare_socket fails with AssertionError: 128 != 4096

### ISSUE THREAD

**Issue by sbraz** [Supervisor/supervisor#1346]
Hi,
This was initially reported [here](https://bugs.gentoo.org/711538) but I wasn't able to reproduce it. Now I see the issue on one computer but not the others. It is present with Python 3.7 and 3.8.

It can be reproduced with `pytest -vv supervisor/tests/test_socket_manager.py::SocketManagerTest::test_prepare_socket` on the git master:

```
======================================= test session starts ========================================
platform linux -- Python 3.7.7, pytest-5.4.1, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /tmp/supervisor
collected 1 item                                                                                   

supervisor/tests/test_socket_manager.py::SocketManagerTest::test_prepare_socket FAILED       [100%]

============================================= FAILURES =============================================
______________________________ SocketManagerTest.test_prepare_socket _______________________________

self = <supervisor.tests.test_socket_manager.SocketManagerTest testMethod=test_prepare_socket>

    def test_prepare_socket(self):
        conf = DummySocketConfig(1)
        sock_manager = self._makeOne(conf)
        sock = sock_manager.get_socket()
        self.assertTrue(sock_manager.is_prepared())
        self.assertFalse(sock.bind_called)
        self.assertTrue(sock.listen_called)
>       self.assertEqual(sock.listen_backlog, socket.SOMAXCONN)
E       AssertionError: 128 != 4096

supervisor/tests/test_socket_manager.py:207: AssertionError
===================================== short test summary info ======================================
FAILED supervisor/tests/test_socket_manager.py::SocketManagerTest::test_prepare_socket - Assertio...
======================================== 1 failed in 0.12s =========================================
```

**Comment by mnaberez** [comment]
This test [passes on CI](https://travis-ci.org/github/supervisor/supervisor/builds/681651598) on Python 3.4 - 3.8.  I ran it locally on a couple of systems and it passes there as well.  Are you able to give us any more information that might allow us to reproduce it?

**Comment by Ma27** [comment]
@sbraz do you use glibc 2.31? I experienced the same issue there as well.

**Comment by sbraz** [comment]
@mnaberez I'm sorry, it looks like I completely missed your message. I'm afraid I don't have any more info other than the fact that I'm running Gentoo.
@Ma27 yes I am using glib 2.31 too, maybe this is related. What distro do you use?

**Comment by Ma27** [comment]
> What distro do you use?

NixOS, but that's rather irrelevant since we still use glibc 2.30. I'm just working on the glibc-2.31 update and recognized that this broke this package, so I'm fairly certain that this is related.

**Comment by sbraz** [comment]
Nice, I guess I should attempt to bisect glibc to see where exactly it broke.

**Comment by sbraz** [comment]
I haven't really had time to bisect glibc but this is probably caused by [commit 96958e2700f5b4f4d1183a0606b2b9848a53ea44](https://sourceware.org/git/?p=glibc.git;a=commit;h=96958e2700f5b4f4d1183a0606b2b9848a53ea44).

**Comment by Ma27** [comment]
@sbraz Thanks for investigating this.

btw I fixed it like this: https://github.com/NixOS/nixpkgs/pull/79391/commits/f0b6431bc222a9426347a4c0ce8d088fcfc3cfac

**Comment by mnaberez** [comment]
Thank you all for the reports and investigation into this issue.  

I have just committed 48fd49eb857c2eaf5dcb45ff100d23ca7d41b4e9 which I believe will fix it.  I have tested this locally on macOS 10.14.6 where Python's `socket.SOMAXCONN` reports 128 and also on Ubuntu 20.04.1 where `socket.SOMAXCONN` reports 4096.  The tests pass on both systems.

Please try this patch on your systems if you are able.  I intend to make a point release with it in a few days if nobody reports further issues.

**Comment by sbraz** [comment]
@mnaberez Thanks, this works fine here.
