### ISSUE TITLE
How to define and use my own rpcinterface ? 

### ISSUE THREAD

**Issue by pzg250** [Supervisor/supervisor#1350]
Hi, 
I checked the supervisor doc. This setting can create my own rpcinterface.
But where to put my package myrpc ? Thanks in advance.

[rpcinterface:myrpc]  
supervisor.rpcinterface_factory = myrpc.rpc: myinterface

Regards,

**Comment by mnaberez** [comment]
It is described in detail here:
http://supervisord.org/xmlrpc.html

You would create a Python package and install it in the same Python environment where the Supervisor package is installed.  The [`supervisor_cache`](https://github.com/mnaberez/supervisor_cache) package can be used as an example, or check the [plugins list](http://supervisord.org/plugins.html) for more examples.
