### ISSUE TITLE
abnormal termination

### ISSUE THREAD

**Issue by HuangXiaoAIZhu** [Supervisor/supervisor#1356]
supervisord 启动服务报错 abnormal termination

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing Supervisor on individual systems.  An error in the configuration file may cause `supervisord` to refuse to (re)start.  Please check your configuration.

**Comment by HuangXiaoAIZhu** [comment]
/bin/supervisord -c /etc/supervisord.conf 这种方式启动supervisord 服务，去管理进程不会报错，
systemctl start supervisord 这种方式启动supervisord 服务，去管理进程才会报错，如果是配置文件问题 ，能具体说下是哪块的问题吗
