### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by gromgit** [Supervisor/supervisor#1364]
I'm fixing a side issue in the Homebrew `supervisor` formula, but [Homebrew now requires a `license` specification](https://docs.brew.sh/Formula-Cookbook#fill-in-the-license):

> Use the license identifier from the SPDX License List e.g. license "BSD-2-Clause", or use license :public_domain for public domain software.

What exactly is `supervisor` licensed under, with respect to the [SPDX Licenses list](https://spdx.org/licenses/)?

Thanks much!

**Comment by mnaberez** [comment]
To the best of my knowledge, Supervisor is licensed under the [Repoze Public License](https://web.archive.org/web/20190211105114/http://www.repoze.org/LICENSE.txt).  That is what is written in the license and copyright files in this repository.  I don't know much about this license, other than the code describes it as ["BSD-like"](https://github.com/Supervisor/supervisor/blob/4.2.0/setup.py#L6) and also ["BSD-derived"](https://github.com/Supervisor/supervisor/blob/4.2.0/setup.py#L72).  

I don't know how this license would map to the SPDX License List.  As far as I can tell, that license seems to be primarily used (or was used) by the original author's other projects ([Repoze](https://github.com/Repoze) and [Pyramid](https://github.com/pylons/pyramid)).  I suggest first trying to contact the original author (@mcdonc) about it.  He has not been active here for some time.  I last tried to contact him about one year ago (#1241) and he did not reply.  Alternatively, you could possibly ask the "SPDX License List" to add the Repoze Public License to their list.

**Comment by gromgit** [comment]
OK, thanks much @mnaberez!
