### ISSUE TITLE
processes are getting killed when CPU usage is high

### ISSUE THREAD

**Issue by navdeepghai1** [Supervisor/supervisor#1366]
I want this program to keep running even the CPU usage is high

**System and version information:**
Supervisord: 3.3.1
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Conf Settings:**

```
[program:default-worker]
command=/usr/local/bin/<command> args...
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/logs/worker.log
stderr_logfile=/home/logs/worker.error.log
user=<username>
stopwaitsecs=1560
directory=/home/<username>/<dir>
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
```

I am using this program for the data sci task so that It must be using a high CPU.

**Comment by mnaberez** [comment]
`supervisord` does not have any built-in option to kill a process when its CPU usage is high, so the process must be getting killed for some other reason.

**Comment by navdeepghai1** [comment]
Is there any configuration that I can use to avoid such situations happening?
