### ISSUE TITLE
Different invocations for reload and start/restart

### ISSUE THREAD

**Issue by eddie4** [Supervisor/supervisor#1367]
Hello,

I have been googling for this option and asked my colleagues. But we have not found the answer. Is it possible to give different invocations to a script on a reload than on a start/restart, much like one would do in systemd.

ExecStart=/opt/bla.py 
ExecReload=/opt/bla.py this_is_reload=True

Reason is this script reads log files. On startup i want to send all. However on reload i just want to send the new lines after startup.

**Comment by mnaberez** [comment]
https://github.com/supervisor/supervisor/issues/147#issuecomment-52440691
