### ISSUE TITLE
Use SafeConfigParser

### ISSUE THREAD

**Issue by nurkkala** [Supervisor/supervisor#137]
In order to eliminate redundancy in configuration files, it would be handy to be able to use the "magical interpolation" available in the SafeConfigParser syntax. Is there a reason that the current implementation prefers RawConfigParser as the base class for handling options?

**Comment by vitaly-krugl** [comment]
@mnaberez: SaveConfigParser supports both the `[DEFAULT]` section as well as supplying a dict. They are not mutually-exclusive. Anything to help conf files be more robust just seems like it would be the right thing to do.

**Comment by mnaberez** [comment]
> SaveConfigParser supports both the [DEFAULT] section as well as supplying a dict. They are not mutually-exclusive.

I am aware of this but Supervisor's interpolation behavior is not the same as `SafeConfigParser`'s.  For example, if you specify a `%(ENV_FOO)s` in a `[program:x]` section, the environment `FOO` variable will be taken from a) the `environment=` line in that same `[program:x]` section, b) the `[supervisor]` section's `environment=` line, or c) the environment from which `supervisord` was started.
