### ISSUE TITLE
Supervisor manage multi ffmpeg transcode process

### ISSUE THREAD

**Issue by xiangri** [Supervisor/supervisor#1370]
I have multiple ffmpeg processes for transcoding rtmp or udp streams.
It worked most of the time, but occasionally one of the ffmpeg processes will be failure to transcode and keep restarting.  At the same time, I use the same running command to work normally on the command line. 
After `supervisor reload` , two possible outcomes

1.  This process may return to normal, but there will be another process with the same problem.
2. This process is still not working

There are many situations in ffmpeg's error, one of the error:

> [error] Error initializing output stream 2:0 -- Error while opening encoder for output stream #2:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libx264 @ 0x4211d80] [info] frame I:1     Avg QP:27.60  size:  4608
[libx264 @ 0x4211d80] [info] mb I  I16..4: 21.5% 25.0% 53.5%
[libx264 @ 0x4211d80] [info] 8x8 transform intra:25.0%
[libx264 @ 0x4211d80] [info] coded y,uvDC,uvAC intra: 66.1% 84.7% 73.6%
[libx264 @ 0x4211d80] [info] i16 v,h,dc,p: 52% 45%  3%  0%
[libx264 @ 0x4211d80] [info] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 64%  8% 10%  3%  2%  3%  2%  2%  5%
[libx264 @ 0x4211d80] [info] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 18% 21%  5%  6%  6%  6%  6%  7%
[libx264 @ 0x4211d80] [info] i8c dc,h,v,p: 31% 35% 33%  1%
[libx264 @ 0x4211d80] [info] kb/s:552.96
[aac @ 0x42f1ac0] [info] Qavg: 189.691
[aac @ 0x42f1ac0] [warning] 2 frames left in the queue on closing
[libx264 @ 0x421c840] [info] frame I:1     Avg QP:30.69  size:  5730
[libx264 @ 0x421c840] [info] mb I  I16..4: 30.1% 33.3% 36.6%
[libx264 @ 0x421c840] [info] 8x8 transform intra:33.3%
[libx264 @ 0x421c840] [info] coded y,uvDC,uvAC intra: 47.0% 68.2% 44.3%
[libx264 @ 0x421c840] [info] i16 v,h,dc,p: 43% 34% 24%  0%
[libx264 @ 0x421c840] [info] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 55%  9% 23%  3%  3%  3%  2%  1%  2%
[libx264 @ 0x421c840] [info] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 22% 24%  5%  6%  6%  5%  5%  7%
[libx264 @ 0x421c840] [info] i8c dc,h,v,p: 49% 24% 24%  3%
[libx264 @ 0x421c840] [info] kb/s:916.80
[aac @ 0x41d3840] [info] Qavg: 189.691
[aac @ 0x41d3840] [warning] 2 frames left in the queue on closing
[aac @ 0x41e0540] [info] Qavg: 194.382
[aac @ 0x41e0540] [warning] 2 frames left in the queue on closing
[aac @ 0x42baa00] [info] Qavg: 213.019
[aac @ 0x42baa00] [warning] 2 frames left in the queue on closing
[aac @ 0x4248f80] [info] Qavg: 213.019
[aac @ 0x4248f80] [warning] 2 frames left in the queue on closing
[info] Conversion failed!

Can you tell me how to solve it ？Thanks a lot.

**supervisor 4.1.0**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
