### ISSUE TITLE
FATAL: Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by Valkyrurr** [Supervisor/supervisor#1372]
I have been following this as described in Laravel's queue configuration: https://laravel.com/docs/5.8/queues#supervisor-configuration

I have the exact same config on a different server, and `Supervisor` works completely fine in that. The command is just like so: `"php /var/path/app/artisan queue:work --tries=3 --timeout=0"`

Both `stderr_logfile` and  `stdout_logfile` I have set are always empty. Except for the one below from Supervisor's default log folder...

![image](https://user-images.githubusercontent.com/10623125/93776078-c245de80-fc55-11ea-8f34-67de7deb0ef3.png)

I really cannot make sense of it. All errors so far... Only improvement I have so far is by setting `startsecs=0`... the worker "runs" but is always stuck at 0:00:00 up time... suggesting, that the "RUNNING" worker is somewhat stuck... I just don't know why. :(

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
