### ISSUE TITLE
Supervisor won't start after restart Raspberry

### ISSUE THREAD

**Issue by invictusro** [Supervisor/supervisor#1382]
Hello guys so I do have the following supervisord.conf file:
```
[program:gunicorn]
command=/home/pi/api/.venv/bin/gunicorn --config /home/pi/api/gconfig.py main:app
directory=/home/pi/api
autostart=true
autorestart=true

[supervisord]
logfile = /home/pi/api/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=2
loglevel = info
identifier = supervisor
nocleanup = true
childlogdir = /tmp
strip_ansi = false
```
It's inside a virtual environment with Python 3.7 and a Flask APP.
The command alone used like this:

```
cd /home/pi/api
source ./.venv/bin/activate 
supervisor --config supervisord.conf
```

It works fine but It doesn't start after restart even if I use: 
`service supervisor start`

Not sure what to do as this is my first time, maybe I'm doing something wrong. It haven't worked even when my app project was outside virtual environment so not sure what's wrong with this

**Comment by mnaberez** [comment]
> It works fine but It doesn't start after restart even if I use:
> service supervisor start

The Supervisor project itself does not provide any integration with any particular operating system.  The command being used above (`service supervisor start`) is some kind of integration with an init system or similar.  It has not been written by this project.  We do not know how it works or what may be wrong with it.  The authors of that integration may be able to help.

The Supervisor maintainers do not have enough bandwidth to assist with issues about installing or using Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
