### ISSUE TITLE
How to fix error "Error: Invalid user name pythonapp in section"

### ISSUE THREAD

**Issue by hi-Nobody** [Supervisor/supervisor#1385]
Hello, I got a error when I run the command `sudo supervisord -c /etc/supervisor/supervisord.conf`
`Error: Invalid user name pythonapp in section 'program:crypto_arbitrage_produce' (file: '/etc/supervisor/conf.d/CryptoArbitrage.conf')`

Cloud you help me solve this question?
Thanks

- My OS is Ubuntu, 20.04 LTS Minimal

- My supervisord.conf is following

```
; supervisor config file
  
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/home/crypto_arbitrage_produce/logs/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf
```

- My CryptoArbitrage.conf(in /etc/supervisor/conf.d/) is following:

```
[program:ming_crypto]
directory=$HOME/proj/python3/Crypto-Arbitrage
command=$HOME/virtual_envs/flask-produce-bit/bin/python3 app1.py
autostart=true
# the program will restart when happening troubleshooting exit
autorestart=true
# you can stop child processing when you stop its parent's processing
stopasgroup=true
user=pythonapp
# Environment variables ensure that the application runs inside of the
# configured virtualenv.
environment=VIRTUAL_ENV="$HOME/virtual_envs/flask-produce-bit",PATH="$HOME/virtual_envs/flask-produce-bit/bin",HOME="/home/crypto_arbitrage_produce",USER="crypto_arbitrage_produce"
stderr_logfile=/home/crypto_arbitrage_produce/logs/supervisor/flask_CryptoArbitrage.err.log
stdout_logfile=/home/crypto_arbitrage_produce/logs/supervisor/flask_CryptoArbitrage.out.log
```

- My system user name is following:

![擷取2](https://user-images.githubusercontent.com/62271163/98221370-814a2500-1f8a-11eb-8244-77b1728bf4b0.JPG)

**Comment by mnaberez** [comment]
> Error: Invalid user name pythonapp in section 'program:crypto_arbitrage_produce' (file: '/etc/supervisor/conf.d/CryptoArbitrage.conf')

This [error occurs](https://github.com/Supervisor/supervisor/blob/4.2.1/supervisor/datatypes.py#L294-L298) when `supervisord` can't find the named user in the password database using [`pwd.getpwdnam()`](https://docs.python.org/3/library/pwd.html#pwd.getpwnam).  Perhaps a user named `pythonapp` does not exist in the password database on that system.

The Supervisor maintainers do not have enough bandwidth to assist with issues about installing or using Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by hi-Nobody** [comment]
I had got the named user in the password database using pwd.getpwnam().
But I still got the problem.
Cloud you help me?
Thanks
![image](https://user-images.githubusercontent.com/62271163/98309181-ce6add00-2004-11eb-8305-5e7f98805d86.png)

**Comment by bingoabs** [comment]
@hi-Nobody I don't think you action in right way. You choose `pythonapp` as the user in the configure file. But you didn't check the user name by `pwd.getpwnam` function. You can try, and get the result.
