### ISSUE TITLE
self exited process stays in EXIT status forever

### ISSUE THREAD

**Issue by ghost** [Supervisor/supervisor#139]
autorestart=true, but you exit your process (e.g. using some restart internal command) 
supervisord never starts it again no matter what autorestart= is set.

supervisor> status
somejabberbot                   EXITED     Aug 07 02:51 PM

**Comment by mnaberez** [comment]
I wasn't able to duplicate this, so I am closing this issue for now.  Please feel free to comment or open another issue if you see this again.

**Comment by jimfulton** [comment]
FTR, this happened to me.  It didn't involve a supervisord config change.  I too don't know exactly what triggered it.

I was able to clear it by `kill -9` ing the affected processes.

**Comment by marcbarry** [comment]
This is happening to me too.

# supervisorctl status program1
program1                        EXITED    Jul 26 09:36 AM
# date
Thu Jul 26 21:01:31 UTC 2018
# supervisorctl version
3.2.0

If I kill -9 the process, supervisor restarts it correctly. If the process crashes, supervisor it seems does not restart it. no changes made to supervisord config.

**Comment by singhania** [comment]
If a process moves to Exited state, supervisord doesn't restarts it.How to get around with this behaviour.

**Comment by zkelo** [comment]
Same issue for me. How to fix it?
