### ISSUE TITLE
echo_supervisord_conf script should be updated

### ISSUE THREAD

**Issue by haiya512** [Supervisor/supervisor#1399]
my system env:
> OS: centos 6.6
> Python version: 3.7
> supervisor version: 4.2.0

after i installed supervisor by pip, and write example configrations to /etc/supervisord.conf, and started supervisord, when i used command "supervisorctl status", some error happend:
> error: <class 'xmlrpc.client.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 400 Bad Request>: file: path/lib/python3.7/site-packages/supervisor/xmlrpc.py line: 545

this because i did not uncomment these lines:
> ;[inet_http_server]         ; inet (TCP) server disabled by default
> ;port=127.0.0.1:9001

after i uncomment them, it works fine, so i give a suggest that **echo_supervisord_conf should be updated, it just used older version.**
those lines upper should be uncommented by default after version 4.0.0

**Comment by mnaberez** [comment]
The output of this command is not intended to produce a running configuration.  Rather, it is intended as a reference to be used when creating an initial configuration.  It must always be tailored for the system it is installed on.  The decision of whether or not to run an `inet_http_server` was intentionally left to the user.  It has always been this way and is not a recent change in 4.0.0 as indicated above.
