### ISSUE TITLE
Launching process with different user from supervisord which is running as non-root failing  

### ISSUE THREAD

**Issue by aeolusp** [Supervisor/supervisor#1405]
This is related to the fix - #1405 
# Setup:
1) Running `supervisord` as a non-root user for eg. `user1`
2) Launch another process from `supervisor` with another non-root user for eg. `user2`
3) the required capabilities `cap_setuid` and `cap_setgid` assigned for `python` (`supervisord` is script and not executable)

Start `supervisord`
```
# su - user1
[user1@TESTSYS /home/user1]
# /usr/bin/python3 /usr/bin/supervisord -c /home/user1/superv.conf
.
.
supervisor: couldn't setuid to 620: Can't drop privilege as nonroot user
```
Although required capabilities set it is not possible to launch process with different non-root user is `supervisord` is running as a non-root user.

**Comment by mnaberez** [comment]
Copying this into #1405 so it's in one place instead of two.
