### ISSUE TITLE
supervisor.sendRemoteCommEvent does not trigger REMOTE_COMMUNICATION event

### ISSUE THREAD

**Issue by TimurDela** [Supervisor/supervisor#1408]
Either I am not configuring things correctly (in which case documentation should be improved) or there is a problem with REMOTE_COMMUNICATION events.

## what I did
supervisor is setup so the XML-RPC API is working (I can, for instance, turn off all subprocess remotely without problem with `supervisor.stopAllProcesses`.

An eventlistener is configured as follow
```
[eventlistener:test_listener]
command=/home/user/script.sh
events=REMOTE_COMMUNICATION
stdout_logfile=/home/user/log/test_out.log
stderr_logfile=/home/user/log/test_err.log
```

`script.sh` contains the following
```{sh}
#!/bin/sh
echo "READY"
while IFS= read -r line
do
        >&2 echo "$line has been read"
        echo "RESULT 2\nOK"
        echo "READY"
done <&0
echo "RESULT 2\nOK"
```

After updating supervisor, the eventlistener is started.

From my remote I send the following
```
curl -d "<?xml version='1.0'?>
<methodCall>
    <methodName>supervisor.sendRemoteCommEvent</methodName>
    <params>
        <param>
            <value>
                <string>test_listener</string>
            </value>
        </param>
        <param>
            <value>
                <string>7</string>
            </value>
        </param>
    </params>
</methodCall>" http://<IP>:<superviosrPort>/RPC2
```
I get the answer
```{xml}
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><boolean>1</boolean></value>
</param>
</params>
</methodResponse>
```
## what I expected

/home/user/log/test_err.log where I expect to find
```
type:test_listener has been read
7 has been read
```
## what I got
```
ver:3.0 server:supervisor serial:8 pool:test_listener poolserial:8 eventname:REMOTE_COMMUNICATION len:20 has been read
type:test_listener has been read
```
which was written even before the `sendRemoteCommEvent` event.

What is it that I am doing wrong?

**Comment by TimurDela** [comment]
I finally found out what was the problem: echo "RESULT 2\nOK" was interpreted as a single line so the event listener never reached the ACKNOWLEDGED state and the supervisor was offering the events.

It is very difficult to debug the eventlistener without having access to its state. **It would be very nice to have access to the eventlistener state (READY, BUSY, ACKNOWLEDGED or UNKNOWN) when running status**.

In case anyone is interested here is a [working bash event listener for  REMOTE_COMMUNICATION events](https://github.com/TimurDela/supervisorBash).

**Comment by mnaberez** [comment]
All of the eventlistener transitions [are logged at the debug level](https://github.com/Supervisor/supervisor/blob/630424492bb17b82368183467bfd9e2bae125a4a/supervisor/dispatchers.py#L478).  You can set `loglevel = debug` in the `[supervisord]` section of the config file to see these messages when developing an eventlistener.  

I'm going to close this issue since it was resolved and there does not appear to be a bug in `REMOTE_COMMUNICATION_EVENT`.
