### ISSUE TITLE
Setting number of backups to 0 is not unlimited, it's 0 backups.

### ISSUE THREAD

**Issue by rduplain** [Supervisor/supervisor#142]
Several places in the docs indicate that 0 means unlimited backups, not 0 backups. See http://supervisord.org/logging.html, "If logfile_backups is 0, an unlimited number of backups is created."

Reading the implementation of RotatingFileHandler, it's clearly assuming a backupCount of 0 means 0 backups:

    if self.backupCount > 0:
        for i in range(self.backupCount - 1, 0, -1):
            ...

Taking the principle that the documentation is correct, the doRollover implementation needs to be reworked to glob instead of counting backward. That is, counting backward from a very large number would waste millions of cycles on files which do not exist.

The workaround is to explicitly set large numbers in the supervisor configuration. Not too large though, because the handler loops through the range of the backup count.

Regarding globbing, it appears that supervisor includes its own wrapper around filesystem operations, in medusa/filesys.py. Is globbing allowed in this project, or is there alternate solution in mind?

**Comment by mnaberez** [comment]
Corrected documentation for #142 in b0f0a56.  We'd be open to an "unlimited" option if someone wants to submit a pull request.
