### ISSUE TITLE
Supervisor versions info

### ISSUE THREAD

**Issue by fredastaire** [Supervisor/supervisor#1422]
Hi all,

Not sure if this question goes here, but haven't found any where else where to get support, so my apologies if not the correct place.
I've been trying to get info on the different supervisor versions to no avail. Checked documentation and forums/google but to no avail.
The info I'm after is which version is the 'stable' branch, which one is mainline/development, which are not either of those but still supported, ie. getting security updates, which ones are legacy.. and so on. 
I would really appreciate if anyone here can point me in the right direction.

Many thanks,
FA

**Comment by mnaberez** [comment]
> The info I'm after is which version is the 'stable' branch, which one is mainline/development, which are not either of those but still supported, ie. getting security updates, which ones are legacy.. and so on.

There exists currently only [one branch](https://github.com/Supervisor/supervisor/tree/master) on GitHub.  It is used for development and stable releases are tagged from it.  There are not separate branches for stable releases but stable releases are [always tagged](https://github.com/Supervisor/supervisor/tags).

Users wanting stable versions should install them from [PyPI](https://pypi.org/project/supervisor/).  Versions that are believed to be stable are released to PyPI with the classifier `5 - Production/Stable`.  Each release includes a [CHANGES.txt](https://github.com/Supervisor/supervisor/blob/4.2.2/CHANGES.rst) file indicating what was done, and this is also displayed on PyPI.

The current major version of Supervisor 4.x.  This major version was first released about 3 years ago.  This major version receives updates.  The current stable version of Supervisor at the time of writing, [4.2.2](https://pypi.org/project/supervisor/4.2.2/), was released to PyPI about one month ago.  Older major versions such as 3.x and 2.x are no longer supported.
