### ISSUE TITLE
server stops responding when supervisorctl start worker.

### ISSUE THREAD

**Issue by nirvparekh** [Supervisor/supervisor#1424]
Hello,
I newly installed supervisor v4.1.0 on my digitalocean droplet.
I added a worker conf file inside /etc/supervisor/conf.d directory named: _api_dev.conf_

```
[program:api_dev]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/api-dev/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/api-dev/storage/logs/worker.log
stopwaitsecs=3600
```

but when I hit following commands:
```
supervisorctl reread
supervisorctl update
supervisorctl start api_dev:*
```
it starts all 8 processes but then server stops responding to any API call. not even phpmyadmin opening.
every api call returns with 500 error with following error:

> exception: "UnexpectedValueException"
> file: "/var/www/html/tray-api/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php"
> line: 111
> message: "The stream or file "/var/www/html/tray-api/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied"

Then I need to stop worker using `supervisorctl stop api_dev:*`, server starts responding fine.
![api_error png](https://user-images.githubusercontent.com/40424777/112941911-f17d6100-914c-11eb-9a68-431e1fc8139c.jpg)

**Comment by mnaberez** [comment]
> it starts all 8 processes but then server stops responding to any API call. not even phpmyadmin opening.
every api call returns with 500 error with following error:
>
>    exception: "UnexpectedValueException"
>    file: "/var/www/html/tray-api/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php"
>    line: 111
>    message: "The stream or file "/var/www/html/tray-api/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied"

The error message above is not coming from `supervisord` but some other program.  

> Then I need to stop worker using supervisorctl stop api_dev:*, server starts responding fine.

Since `supervisorctl` is executing commands, it means that `supervisord` is still responding normally.  There does not appear to be a bug in `supervisord` here.  The Supervisor developers are not able to help with this issue, sorry.
