### ISSUE TITLE
Feature request: support for logging to systemd journal

### ISSUE THREAD

**Issue by powerpbx** [Supervisor/supervisor#1425]
Apparently supervisor does not support [systemd-journald](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html).  I would prefer to manage my logging there instead of the traditional (legacy) way of saving things in files that are individually managed by separate applications or use syslog.  I would be a nice addition imo.

**Comment by mnaberez** [comment]
`supervisord` has a [plugin](http://supervisord.org/plugins.html) system that allows plugins to be written to support new logging services.  It is not necessary to modify `supervisord` for a plugin to send the logs to `systemd-journal`. I think this would be a good place to start, and if the plugin became very popular, we could look at including in `supervisord`.
