### ISSUE TITLE
Where to find the official sample configuration?

### ISSUE THREAD

**Issue by andygrunwald** [Supervisor/supervisor#1433]
Thanks for this awesome project.

I was reading the doc section [`[rpcinterface:x]` Section Settings](http://supervisord.org/configuration.html#rpcinterface-x-section-settings):

> [...]
> In the sample config file, there is a section which is named [...]

My question: Where do I find the official sample configuration file?

Especially, when there are particular sections must remain in the configuration for the standard setup of supervisor to work properly.

I am happy to create a PR to adjust the documentation and link it, once I know the location.

**Comment by mnaberez** [comment]
http://supervisord.org/installing.html#creating-a-configuration-file

**Comment by andygrunwald** [comment]
Thanks a lot @mnaberez!
Also for taking action in https://github.com/Supervisor/supervisor/commit/1a3e00ff586c1c19a58c654f872546ac36959f33
