### ISSUE TITLE
Getting TypeError: [priority,] message string on supervisor

### ISSUE THREAD

**Issue by vishnuixm** [Supervisor/supervisor#1437]
Getting TypeError on node (node version v10.16.3) application running on ubuntu 16.04. don't know why am getting this error and how to fix this anyone please help us

**log trace:**

> supervisord[9480]: Traceback (most recent call last): 
> supervisord[9480]:   File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 319, in emit 
> supervisord[9480]:     syslog.syslog(msg) 
> supervisord[9480]: TypeError: [priority,] message string 

**supervisor conf file**

```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

```

> **application conf file**

```
[program:nodeapp]
directory=/opt/app/new-repo
command=npm start
autostart=true
autorestart=true
user=nodeapp
environment=HOME="/home/nodeapp",USER="nodeapp",NODE_ENV="production"
stdout_logfile=syslog
stderr_logfile=syslog
```

**Comment by mnaberez** [comment]
What version of Supervisor are you using?

**Comment by vishnuixm** [comment]
@mnaberez Its 3.2.0

**Comment by mnaberez** [comment]
Supervisor 3.2.0 is [over 5 years old](https://github.com/Supervisor/supervisor/blob/4.2.2/CHANGES.rst#320-2015-11-30) and is no longer supported.  There have been many changes and bug fixes since then.  Please upgrade to a more recent [4.x version](https://github.com/Supervisor/supervisor/blob/4.2.2/CHANGES.rst#422-2021-02-26).  If the problem persists on a modern version, we can reopen.
