### ISSUE TITLE
log files fd leaks

### ISSUE THREAD

**Issue by cupen** [Supervisor/supervisor#1440]
I have a supervisord instance that ran for two years. It's reliable, but now I find my disk usage is inching up inexplicable.
The result of `df -h`  is really different than `du -h --max-depth=1  /`.  And the `sudo lsof | grep deleted` show me that there was a lot  deleted log files is still opening.

Here is my supervidord logfile setups
```ini
[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
childlogdir=/tmp
```

Here is the ouput part of  `sudo lsof | grep deleted`. 

```
server      762         hotpotrun 1037r      REG              253,1  52428910     399247 /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)
server      762         hotpotrun 1038r      REG              253,1  52428910     399247 /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)
server      762         hotpotrun 1039r      REG              253,1  17238179     398662 /tmp/xxx-alpha-agent-stdout---supervisor-CkwCq6.log (deleted)
server      762         hotpotrun 1040r      REG              253,1  52428910     399247 /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)
server      762         hotpotrun 1041r      REG              253,1  52428910     399247 /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)
server      762         hotpotrun 1042r      REG              253,1  17238179     398662 /tmp/xxx-alpha-agent-stdout---supervisor-CkwCq6.log (deleted)
server      762         hotpotrun 1043r      REG              253,1  52428910     399247 /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)

.......

```
And `sudo ls -ahl /proc/762/fd`
```
total 0
dr-x------ 2 hotpotrun users  0 Jun  1 18:56 .
dr-xr-xr-x 9 hotpotrun users  0 Jun  1 18:55 ..
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 0 -> pipe:[273129429]
l-wx------ 1 hotpotrun users 64 Jun  1 18:56 1 -> pipe:[273129430]
lrwx------ 1 hotpotrun users 64 Jun  1 18:56 10 -> socket:[273133105]
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1024 -> /tmp/xxx-alpha-agent-stdout---supervisor-deebJ9.log (deleted)
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1025 -> /tmp/xxx-alpha-agent-stdout---supervisor-XGNhxj.log (deleted)
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1026 -> /tmp/xxx-alpha-agent-stdout---supervisor-CkwCq6.log (deleted)
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1027 -> /tmp/xxx-prod-center-stdout---supervisor-ndIFsC.log.1 (deleted)
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1028 -> /tmp/xxx-alpha-agent-stdout---supervisor-CkwCq6.log (deleted)
lr-x------ 1 hotpotrun users 64 Jun  1 18:56 1029 -> /tmp/xxx-alpha-gate-stdout---supervisor-CcT8kx.log.1 (deleted)

...... 

```

The process(pid=762) is not supervisord. It's my business logic process managed by Supervisor.
I don't know why my business logic process(pid=762) holds a lot log files(fd) of other processes. I thought they will be closed after I restart the process(pid=762), than I do it but nothing changed.

Maybe it's a bug of Supervisor? If yes, is there any workaround for it?

BTW: I can't restart the supervisord right now, because it will casue a lot my business logic proceses restarting.

**Comment by mnaberez** [comment]
What version of Supervisor are you using?

**Comment by cupen** [comment]
> What version of Supervisor are you using?

supervisor 3.3.4
python2.7.14
centos 7.9

**Comment by cupen** [comment]
I have some other supervisord instances ran in different hosts, one to one.
By contrast:
 * SupervisorB is OK
     * Supervisor 4.2.2
     * python 3.6.8
     * centos 7.9.2009

* SupervisorC is OK
     * Supervisor 4.0.2
     * python 3.6.8
     * centos 7.9.2009

* SupervisorD log files fd leaks
     * Supervisor 3.3.5
     * python 2.7.14
     * centos 7.9.2009
     
I'll try to reproduce it by print a lot logs.

**Comment by mnaberez** [comment]
In the list above, Supervisor 3.x leaks but Supervisor 4.x does not.  

There were many changes between 3.x and 4.x.  It is possible that some of those changes fixed a leak in 3.x.  However, I don't know that for certain, and I wasn't previously aware of any leak in 3.x.

**Comment by cupen** [comment]
@mondalaci  Yes, I can't repduce it in Supervisor 4.x . 
I'll upgrade all of my Supervisor instances to 4.x .
Thanks.

BTW:
I found a phenomena in my enviroment (Supervisor 3.3.4  python 2.7.14  centos 7.9.2009).  
The logfile's `fd` held by supervisord is shared between parent process(Supervisor) and every child proceses(my business logic processes).  So that I can see every my business logic process holds a lot log files(fd) of other processes, and restart child process will change nothing.

It doesn't reproduce in my other environments.  Maybe it's because my `centos` which was running two years without reboot.  And the kernel of it has been upgraded many times.

I‘ll keep to find the reason. Thanks again.

**Comment by mondalaci** [comment]
@cupen I haven't participated in this conversation, so I assume you wanted to mention someone else.

**Comment by cupen** [comment]
> @cupen I haven't participated in this conversation, so I assume you wanted to mention someone else.

Oh, I'm sorry.
