### ISSUE TITLE
I want to ask about that i restart the Supervisor and the subProcess will not restart

### ISSUE THREAD

**Issue by coasp** [Supervisor/supervisor#1444]
now i used Supervisor to manage my application. But when i restart the Supervisor, the application which managed by Supervisor will be restart.i dont want be that.so, i want to ask how that when i restart the Supervisor,the application will not restart

**Comment by cupen** [comment]
As a daemon process, Supervisor is not use for this case. 
I think you want a feature: supervisord config hot-reload.

BTW: If you really want it, just kill your supervisord which is the parent process of your application, then your application will be [orphen process](https://en.wikipedia.org/wiki/Orphan_process).

**Comment by mnaberez** [comment]
> But when i restart the Supervisor, the application which managed by Supervisor will be restart.i dont want be that.

Supervisor can't be used for this application.   The design of `supervisord` is that the processes it manages run directly under it as child processes.  When `supervisord` exits, those processes exit.  There's no way for `supervisord` to attach to an already-running process, or for `supervisord` to perform an in-place upgrade of itself.  These are out of scope for this project.
