### ISSUE TITLE
how to start dependent processes only when another child process is ready?

### ISSUE THREAD

**Issue by michaelhammann** [Supervisor/supervisor#1445]
Hi,

I am facing some issues with setting the RUNNING state correctly. We need to delay state transition from starting to running. For example if a process needs 10 seconds to come up, the running should only be set when the process is actually running.

Is it possible to achieve this without the startsecs configuration, but only set it when the child process is actually ready?
Would appreciate any ideas on how to get this working or if there is a known workaround at the moment.
 
I am using supervisor 4.2.2. and I also created a suggestion for the implementation here: https://github.com/Supervisor/supervisor/pull/1446

Appreciate your help!

**Comment by mnaberez** [comment]
https://github.com/Supervisor/supervisor/pull/1446#issuecomment-1076707720
