### ISSUE TITLE
program raised "UnicodeDecodeError"

### ISSUE THREAD

**Issue by lastshusheng** [Supervisor/supervisor#1459]
I have a program that works fine when I start at the terminal,but when I start in Supervisor, it raised "UnicodeDecodeError".

This is my config.

```shell
[program:slam_realtime]
killasgroup=true
stopasgroup=true
command=/opt/bslam_web/bito_realtime_api/scripts/start_up.sh
process_name=%(program_name)s
numprocs=1
user=slam
umask=022
autostart=true
autorestart=true
startsecs=10
startretries=3
exitcodes=0,2
stopsignal=INT
stopwaitsecs=10
environment=A="1",B="2",LANG="en_US.utf8",LC_ALL="en_US.UTF-8",LC_LANG="en_US.UTF-8"
serverurl=AUTO
vacuum=true
```

When i run `/opt/bslam_web/bito_realtime_api/scripts/start_up.sh` in terminal,it was all ok!

The information I can provide is as follows:
1. Error occurs when open a file which have Chinese characters 
2. python version is 3.5
3. supervisor version is 3.2.0

This are some screenshots.
![image](https://user-images.githubusercontent.com/49259777/134459270-1cfcac3a-b6ab-434a-b76b-3cd86171669f.png)
![image](https://user-images.githubusercontent.com/49259777/134459341-8499ea3e-e43f-43f9-8069-c7302759adb5.png)
![image](https://user-images.githubusercontent.com/49259777/134459386-1ce543e0-bb68-4689-9f78-55fdee3787b0.png)

**Comment by mnaberez** [comment]
>    Error occurs when open a file which have Chinese characters
>    python version is 3.5
>    supervisor version is 3.2.0

Unicode support in Supervisor was overhauled in [Supervisor 4.0](https://github.com/Supervisor/supervisor/blob/main/CHANGES.rst#400-2019-04-05).  As part of that work, [tests were added](https://github.com/Supervisor/supervisor/blob/4.2.5/supervisor/tests/test_end_to_end.py) to ensure that processes can log Unicode data.  Please upgrade to a newer version.
