### ISSUE TITLE
stopsignal = SIGRTMIN+6 

### ISSUE THREAD

**Issue by gezsops** [Supervisor/supervisor#1466]
stopsignal = SIGRTMIN+6

<Fault 92: "CANT_REREAD: value 'SIGRTMIN+6' is not a valid signal name

who can help me

**Comment by gezsops** [comment]
i want to use kill -40 pid

**Comment by mnaberez** [comment]
> ``` 
> stopsignal = SIGRTMIN+6 
> ```

`supervisord` can't parse arbitrary expressions in its config file.  The `stopsignal` must be specified as the signal's name (`stopsignal = SIGTERM`) or its number (`stopsignal = 15`).

> i want to use kill -40 pid

Setting `stopsignal = 40` may achieve it, assuming `40` is a valid signal for the system and the kernel allows the user `supervisord` runs as to send that signal to a process.
