### ISSUE TITLE
Supervisor not resuming after Docker container is rebuilt

### ISSUE THREAD

**Issue by fdbatista** [Supervisor/supervisor#1467]
Hi.

I have a Redis queue process running in a Docker container, so I installed Supervisor to make sure this queue does not stop.
Anyways, as a result of CI/CD pipelines, this container eventually gets destroyed and rebuilt.

Sometimes I need to manually restart Supervisor after this container has been reloaded. Why is this happening?

This is the config file:

```bash
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=docker exec app php artisan queue:work redis --tries=1
autostart=true
autorestart=true
user=www
numprocs=2
redirect_stderr=true
stdout_logfile=/home/services/app/storage/logs/supervisor.log
```

When this happens, the Supervisor service status shows this:
```
Nov 01 19:20:06 supervisord[16548]: 2021-11-01 19:20:06,136 INFO spawned: 'laravel-worker_01' with pid 16392
Nov 01 19:20:06 supervisord[16548]: 2021-11-01 19:20:06,318 INFO exited: laravel-worker_01 (exit status 1; not expected)
Nov 01 19:20:07 supervisord[16548]: 2021-11-01 19:20:07,319 INFO gave up: laravel-worker_01 entered FATAL state, too many start retries too quickly
```

And the log file shows:
```
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: process_linux.go:103: executing setns process caused: exit status 1: unknown
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: process_linux.go:103: executing setns process caused: exit status 1: unknown
Error response from daemon: Container 8ce00d8fe3091217562b0f9c2297d384a1f40ee9a21fb4c1ade18c9feb6e8d8b is not running
Error response from daemon: Container 8ce00d8fe3091217562b0f9c2297d384a1f40ee9a21fb4c1ade18c9feb6e8d8b is not running
Error: No such container: app
Error: No such container: app
```

This happens eventually. Sometimes Supervisor detects the container is up and running again without problem.

Thanks!

**Comment by mnaberez** [comment]
> ```
> Nov 01 19:20:06 supervisord[16548]: 2021-11-01 19:20:06,136 INFO spawned: 'laravel-worker_01' with pid > 16392
> Nov 01 19:20:06 supervisord[16548]: 2021-11-01 19:20:06,318 INFO exited: laravel-worker_01 (exit status 1; > not expected)
> Nov 01 19:20:07 supervisord[16548]: 2021-11-01 19:20:07,319 INFO gave up: laravel-worker_01 entered FATAL > state, too many start retries too quickly
> ``` 

`supervisord` appears to be behaving normally above.  It repeatedly spawned `laravel-worker_01`, which failed with an unexpected exit status each time.  It kept trying until `startretries` was exceeded, then it gave up spawning as it was configured to do.  Something is going wrong in the `laravel-worker_01` process.  Perhaps the `stdout_logfile` or `stderr_logfile` logfiles for `laravel-worker_01` would give clues.

> Sometimes Supervisor detects the container is up and running again without problem.

`supervisord` doesn't have any knowledge of containers itself.  It can't start them or detect them.  

This does not look like a bug in `supervisord` but rather some other issue in this particular system.  The Supervisor developers do not have enough bandwidth to assist with running particular programs under `supervisord`, sorry.
