### ISSUE TITLE
Allow a custom "stop-command" to manage graceful shutdown of processes

### ISSUE THREAD

**Issue by grandfatha** [Supervisor/supervisor#147]
I am trying to use supervisord to manage instances of playframework applications. The framework supplies commands for starting and stopping instances which allows an application to properly shutdown and the execution of lifecycle events of plugins. An example is the proper closing of Lucene search index, which cannot be opened again if they are shutdown ungracefully, because a "write-lock" file remains the in index directory.

What I would consider a great addition, would be the possibility to specify something like this:

[program:my-play-web-app]
command=/opt/play-1.2.5/play start
stop-command=/opt/play-1.2.5/play stop
directory=/path/to/home-of-play-web-app/

Is there any means that I can do this with supervisord right now? The only workaround I have found is the following:

[program:my-play-web-app]
command=/path/to//home-of-play-web-app/startup.sh
directory=/path/to/home-of-play-web-app/

With startup.sh being:

trap "{ echo Stopping play app; /opt/play-1.2.5/play stop; exit 0; }" EXIT
echo Starting play app
/opt/play-1.2.5/play start

(taken from here: http://stackoverflow.com/questions/7732371/how-to-properly-manage-rabbitmq-with-supervisord )

**Comment by dtoubelis** [comment]
Using some sort of vendor `stop` command that relies on a `pid` file is definitely a step backwards. A better way to achieve the desired result would be to send `'Ctrl-C'` or `'Ctrl-\'` via `STDIN` as described in #555.

**Comment by lifeofguenter** [comment]
+1

**Comment by Fogetti** [comment]
+1

**Comment by ryanchou1991** [comment]
+1

**Comment by alexplakhtyrya** [comment]
+1

**Comment by Jakobud** [comment]
Still not clear to me why its so hard to issue a stop command when a supervised process stops for any reason. I have a perfect example of why it would be useful:

I have a Raspberry Pi bittorrent client. It just sits there and downloads and seeds various torrents via Transmission (bittorrent client). However, it also runs OpenVPN and I don't want it doing any torrent-related activity unless OpenVPN is running and connected.

Ideally I would set up Supervisor to keep OpenVPN running, but in the case that OpenVPN ever crashed or supervisor needed to restart it for any reason, after it crashes it would immediately run the bash command:

`# transmission-remote --torrents all --stop`

In order to stop all the torrent activity. And then I would start them again once OpenVPN makes a connection.

So simply specifying a bash command to run when a process stops or crashes.... it would be extremely useful.

**Comment by LeifW** [comment]
Systemd supports a custom stop command if you'd wanna use that.

**Comment by shuaiming** [comment]
+1

**Comment by infinityhacks** [comment]
+1

**Comment by shatil** [comment]
+1

Any reason this was closed? I don't see this feature yet.

**Comment by israelshirk** [comment]
@shatil read up ^^^^

It's just a design decision to use signals and only a single child process per application/process.  This avoids all sorts of situations like accidental fork-bombing with kill processes and other unexpected behaviors that happen in systemd and similar methodologies.  If the process you're running doesn't handle that, [use a Bash script and `trap` to catch the signal and run a custom command](http://veithen.github.io/2014/11/16/sigterm-propagation.html).

**Comment by shatil** [comment]
Also, some applications start one process, spawn another, and drop privileges. Sending a `kill` signal to the one started by `supervisord` doesn't do anything useful. A shining example is `mysqld_safe` on Alpine Linux, which is easily stopped using `mysqladmin shutdown`, but not `supervisorctl stop mysqld`.

**Comment by dtoubelis** [comment]
`supervisor` has different design goals and it is likely a wrong tool to use with those kind of applications. Instead of forcing square peg into a round hole you may want to try something like  `daemontools`, `runit`, etc.

**Comment by Oloremo** [comment]
That's a shame, honestly. This feature is essential for any service management software.

**Comment by blunt1973** [comment]
Five years later, still no "stop-command" to manage graceful shutdown of processes, that's a shame, honestly.

**Comment by jkryanchou** [comment]
Is there anyone to contribute the feature?

**Comment by StanislavKo** [comment]
+1

**Comment by UnR34L** [comment]
+1

**Comment by dtoubelis** [comment]
You are asking for `supervisor` to be more like `systemd` or `init` but why don't you use `systemd` or `init` instead and leave `supervisor` alone? The absence of stop command is what makes supervisor so awesome. My vote is for "no stop command ever"!

**Comment by Oloremo** [comment]
> The absence of stop command is what makes supervisor so awesome. 

How?..

**Comment by dtoubelis** [comment]
In order to implement stop command one would need to keep track of process pid. This is usually done by storing pid file somewhere in the file system. This creates at least two problems 1) the pid file can be deleted (intentionally/unintentionally/fs corruption) 2) pid file is not deleted upon system crash or ungraceful shutdown (i.e. pull the plug event) and another process started with the same pid id upon reboot. These are rare circumstances but I experience all of this more times than I ever expected.

The only reliable way to monitor the process state is by starting a process from another process (supervisor) and using kernel facilities to control/monitor the child process.

The start/stop/pid approach works in 99% of cases and suitable for generic applications where failures are common occurrence and not a big deal. However, there are applications out there where 99% is not good enough. Think of industrial automation, robots, car controls, flight controls, etc.

There are very few tools that do process control in this way (`runit`, `systemd`, `supervisor`, `inittab`, `pm2`), there are even fewer that do it right and `supervisor` is one of the best. So, not supporting unreliable process control mechanisms, having small footprint and clear design is what sets supervisor apart from the rest and I want it to stay this way.

**Comment by Oloremo** [comment]
> In order to implement stop command one would need to keep track of process pid. 

Hm... no. In order to implement stop command, one would need to add it as a *optional* alternative to the send_signal logic. Custom stop command may not use pid at all.

The only real problem is what to do if stop command won't stop the process? I'd suggest to fallback to SIGKILL here.

**Comment by SilenceM59** [comment]
Ugh... I have to use init.d don't I.

**Comment by tahaykACF** [comment]
+1

**Comment by florianm** [comment]
cough
+1

However - awesome work, thanks for maintaining this package, and I respect the maintainers' design decisions.

**Comment by astorath** [comment]
The fun thing is, supervisord uses stop-command by itself:
https://github.com/Supervisor/initscripts/blob/master/centos-systemd-etcs
 :)

**Comment by rirmak** [comment]
For more than 3 years, people have asked to make it possible to stop applications with a command or script, but nothing has changed. It's sad.

**Comment by israelshirk** [comment]
@rirmak http://www.lmgtfy.com/?q=bash+handle+signal

The Linux Journal one has copy pasta.

**Comment by rirmak** [comment]
> bash+handle+signal
Supervisor 3.3.0:
stopsignal

The signal used to kill the program when a stop is requested. This can be any of TERM, HUP, INT, QUIT, KILL, USR1, or USR2.

**Comment by justinas-kazanavicius** [comment]
+1

**Comment by johnbrannstrom** [comment]
> Also, some applications start one process, spawn another, and drop privileges. Sending a `kill` signal to the one started by `supervisord` doesn't do anything useful. A shining example is `mysqld_safe` on Alpine Linux, which is easily stopped using `mysqladmin shutdown`, but not `supervisorctl stop mysqld`.

I had the problem with supervisor and mysql. I solved that with this small bash script:
```bash
#!/bin/bash

# Start script (that would ordinarily have been entered into supervisor config file)
/usr/bin/mysqld_safe &

# Stop script
stop_script() {
    mysqladmin -u root shutdown
    exit 0
}
# Wait for supervisor to stop script
trap stop_script SIGINT SIGTERM

while true
do
    sleep 1
done
```

**Comment by joesenova** [comment]
I've been looking for a solution for a similar problem.

I have a PHP app that runs consumers on RabbitMQ, startup with supervisor. These run ons EC2/docker.
Once I initiate a scale-down or redeploy with latest code, the EC2 instance/docker gets destroyed. Once this happens supervisor/RabbitMQ does not allow the process to detach as a connection/consumer on the queues it's connected to. Thus I have lots of orphaned consumers/connections on my queues.

I need a graceful shutdown to the consumer processes, so I found a work-around in the meanwhile to assist in doing this. I setup a Python script on Jenkins to check for draining targets on a LB. This allows me to see the instances/dockers that are being destroyed, once I see then I can execute a supervisor stop command via ssh in that script to the IP addresses from the aws cli.

This script runs once I deploy new code and new instances are booted up. But, with auto scale there is not a way to run these jobs as yet. So now I'm forced to run a periodic CRON every 15min or so to have a look for draining targets. This will then catch most of the instances/dockers upon being destroyed from auto scaling.

I hope someone here can use this as a workaround too.

I will let you guys know if I have better solutions/workarounds.

**Comment by israelshirk** [comment]
@joesenova https://google.com/?q=php+catch+signal

Ack after processing: https://www.rabbitmq.com/tutorials/tutorial-two-python.html

**Comment by isayeter** [comment]
+1

A lot of people need this feature.

**Comment by ashutoshpw** [comment]
+1

**Comment by petrmalina** [comment]
Just use systemd. It supports `ExecStop`.

Supervisor example:
```
[program:cat]
command=/bin/cat
process_name=%(program_name)s
numprocs=1
directory=/tmp
umask=022
priority=999
autostart=true
autorestart=unexpected
startsecs=10
startretries=3
exitcodes=0
stopsignal=TERM
stopwaitsecs=10
stopasgroup=false
killasgroup=false
user=chrism
redirect_stderr=false
stdout_logfile=/a/path
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
stderr_logfile=/a/path
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
stderr_events_enabled=false
environment=A="1",B="2"
serverurl=AUTO
```

Systemd example:
```
[Unit]
Description=Cat Service
After=network.target

[Service]
Type=simple
ExecStart=/bin/cat
ExecStop=/bin/kill -s TERM $MAINPID
User=chrism
WorkingDirectory=/tmp
UMask=0022
Restart=on-failure
RestartSec=10
StartLimitIntervalSec=0
StartLimitBurst=3
TimeoutStopSec=10
StandardOutput=file:/a/path
StandardError=file:/a/path
Environment=A=1 B=2

[Install]
WantedBy=multi-user.target
```

You would save the service configuration to a file named cat.service in the `/etc/systemd/system/` directory. After saving the file, you can enable and start the service with:
```
sudo systemctl daemon-reload
sudo systemctl enable cat.service
sudo systemctl start cat.service
```
