### ISSUE TITLE
Comment in config file causes error

### ISSUE THREAD

**Issue by toothless92** [Supervisor/supervisor#1473]
Ubuntu 20.04.3 LTS
Python 3.8.10
Installed supervisor via apt

Hi there,

I was getting an error when I tried to run `sypervisorctl reread` after modifying the config file

The error was:
`error: <class 'PermissionError'>, [Errno 13] Permission denied: file: /usr/lib/python3/dist-packages/supervisor/xmlrpc.py line: 560`

Following the advice in [this comment](https://github.com/Supervisor/supervisor/issues/491#issuecomment-56330912), I removed the comment from [this line](https://github.com/Supervisor/supervisor/blob/bfea3767f805ea351a2bbab0af2c4ee547cfa7db/supervisor/skel/sample.conf#L48) in my config file.  The reread function now works

**Comment by mnaberez** [comment]
> I was getting an error when I tried to run sypervisorctl reread after modifying the config file

Could you please paste the exact contents of the config file that caused the issue?

**Comment by toothless92** [comment]
I'm sorry, this was an issue with my root access, not with supervisord.  I must have confused these two as I was poking around.

Should have realized based on the error message, sorry.  This issue can be closed.
