### ISSUE TITLE
Supervisord starts php-fpm child process indefinitely

### ISSUE THREAD

**Issue by bellaxievmlyr** [Supervisor/supervisor#1475]
This is how I started php-fpm in the supervisord.conf.

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize -c /usr/local/etc/php-fpm.conf
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB

In the php pool file, 
pm = ondemand
pm.max_children = 30
pm.process_idle_timeout = 10s

On the container, I'm watching the processes thru 'top'. I saw one php-fpm master process, and 2 child processes spun up and then killed in 10s, and immediately another 2 child processes spun up and again killed in 10s because they were idle, and it's going on and on... In the meantime, I'm watching the web log, I'm not seeing any HTTP requests coming in as it's a dev server.

Question is why supervisord keeps spinning up 2 child processes each time?

I also tried with pm=dynamic, and I expected more child processes when I was doing a load test on the website, and I set max_children to a large number. But seems the max_children is ignored and there was only 3 child processes all the time.

**Comment by mnaberez** [comment]
> [program:php-fpm]
> command=/usr/local/sbin/php-fpm --nodaemonize -c /usr/local/etc/php-fpm.conf
> autostart=true
> autorestart=true
> numprocs=1
> process_name=%(program_name)s_%(process_num)02d
> stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
> stderr_logfile_maxbytes=10MB
> stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
> stdout_logfile_maxbytes=10MB

...

> Question is why supervisord keeps spinning up 2 child processes each time?

I've tried to reproduce this using the following.  Since `supervisord` doesn't have any special knowledge of `php-fpm` or any other program, I've replaced `php-fpm` with `cat`.  

```
$ cat supervisord.conf 
[supervisord]
loglevel = debug 

[program:cat]
command=/bin/cat
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)02d

$ supervisord -n -c supervisord.conf
2021-12-08 10:20:13,435 INFO supervisord started with pid 79891
2021-12-08 10:20:14,443 INFO spawned: 'cat_00' with pid 79892
2021-12-08 10:20:15,446 INFO success: cat_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Above, `supervisord` claims to have started exactly one process (pid 79892).  I verified that only one process was started with `ps auxwww|grep [b]in/cat`.  I'm unable to duplicate the report that `supervisord` starts 2 processes when `numprocs=1`.

> On the container, I'm watching the processes thru 'top'. I saw one php-fpm master process, and 2 child processes spun up and then killed in 10s, and immediately another 2 child processes spun up and again killed in 10s because they were idle, and it's going on and on... In the meantime, I'm watching the web log, I'm not seeing any HTTP requests coming in as it's a dev server.

This does not sound like a bug in `supervisord` but rather some other issue in this particular system. The Supervisor developers do not have enough bandwidth to assist with running particular programs under supervisord, sorry.
