### ISSUE TITLE
Killing nonexistent process crashes supervisord

### ISSUE THREAD

**Issue by kiatweitan** [Supervisor/supervisor#1477]
When restarting a process that has exited (not long running) with stopsignal=KILL, supervisord crashed on following error:

> 2021-12-07 11:03:02,068 CRIT unknown problem killing task01 (30733):Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supervisor/process.py", line 417, in kill
    options.kill(pid, sig)
  File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1171, in kill
    os.kill(pid, signal)
OSError: [Errno 3] No such process

> Dec  7 11:03:33 prod05 python: detected unhandled Python exception in '/usr/bin/supervisord'
Dec  7 11:03:39 prod05 python: can't communicate with ABRT daemon, is it running? [Errno 2] No such file or directory
Dec  7 11:03:40 prod05 systemd: supervisord.service: main process exited, code=exited, status=1/FAILURE

**Comment by mnaberez** [comment]
Fixed in ae60a73bae050c8b83c5e724a505cfd79e6afdb5 and released in [Supervisor 4.2.2 (2021-02-26)](https://github.com/Supervisor/supervisor/blob/4.2.2/CHANGES.rst#422-2021-02-26).
