### ISSUE TITLE
Is there any way to config X-Frame-Options in supervisor config?

### ISSUE THREAD

**Issue by zhangshunbao** [Supervisor/supervisor#1479]
Is there any way to config X-Frame-Options in supervisor config?

**Comment by mnaberez** [comment]
The web interface does not have any [configuration options](http://supervisord.org/configuration.html#inet-http-server-section-settings) for adding arbitrary headers.  To set arbitrary headers, please run it behind a reverse proxy that has this feature (both Apache and Nginx offer it).
