### ISSUE TITLE
Support for fcgi-programs in groups?

### ISSUE THREAD

**Issue by Einkoro** [Supervisor/supervisor#148]
Supervisord fails to start when I add a fcgi-program to a group and I found the following patch adding support in the mailing list from 2009. Would it be possible to add the patch?

http://lists.supervisord.org/pipermail/supervisor-users/attachments/20090605/98b18fb8/attachment.obj

**Comment by mwicat** [comment]
@mnaberez Any plans to merge this? We use fcgi-program directive to balance traffic between multiple processes but we have separate program invocations for different protocols like xmpp, http etc. (=many fcgi-program directives) which we would like to treat as a group during deployments. Not to mention that treating [fcgi-program] as different entity than [program] despite the only difference being usage of shared sockets is rather hurting cohesiveness...

**Comment by mnaberez** [comment]
This patch looks reasonable but I have not tried it.  It will need test coverage before it can be merged.  I'll leave this issue open.

**Comment by mlowicki** [comment]
@Einkoro are you able to add tests?

**Comment by apollo13** [comment]
@mnaberez I've updated the code and added tests in #1163 -- please tell me what else you'd like to see.
