### ISSUE TITLE
Role of supervisord when serving fcgi requests?

### ISSUE THREAD

**Issue by nicolasfranck** [Supervisor/supervisor#1482]
When I start on or more fcgi worker processes using `supervisord`
on port 9000 ..

```
[fcgi-program:iipserver]
command=/usr/lib64/cgi-bin/iipsrv.fcgi
socket=tcp://0.0.0.0:9000
process_name=%(program_name)s_%(process_num)02d
numprocs=4
numprocs_start=1
autostart=true
autorestart=true
redirect_stderr=true
user=iip
group=iip
environment=MAX_IMAGE_CACHE_SIZE=100,JPEG_QUALITY="90",MAX_LAYERS="-1",MAX_CVT="1000",VERBOSITY="6",LOGFILE="/var/log/iipsrv/iipsrv_%(process_num)02d.log"
```

.. I noticed that it is `python` that is listening to 
port 9000:

```
netstat -lntp
$ Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      964/sshd            
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      763/python          
tcp6       0      0 :::22                   :::*                    LISTEN      964/sshd  
```

Does that mean that `supervisord` acts as the main process that passes all requests down to the fcgi worker processes?
Or do all of the worker processes share the same listener socket (using `SO_REUSEPORT`),
and is the role of `supervisord` only to monitor the existing processes?
Would be handy to know.

**Comment by mnaberez** [comment]
1. ``supervisord`` [creates and binds](https://github.com/Supervisor/supervisor/blob/762f036943d58beec11c24db073e428c8824afd1/supervisor/datatypes.py#L213) the socket specified by ``socket=`` in the config.
2. ``supervisord`` [forks](https://github.com/Supervisor/supervisor/blob/762f036943d58beec11c24db073e428c8824afd1/supervisor/process.py#L241) a child using ``fork()``.
3. The child [``dup2()``](https://github.com/Supervisor/supervisor/blob/762f036943d58beec11c24db073e428c8824afd1/supervisor/process.py#L766)s the socket's fd to fd ``0``.
4. The child [``exec()``](https://github.com/Supervisor/supervisor/blob/762f036943d58beec11c24db073e428c8824afd1/supervisor/process.py#L339)s the FCGI program specified by ``command=`` in the config.
5. The FCGI program [``accept()``](https://web.archive.org/web/20210901203457/http://www.mit.edu/~yandros/doc/specs/fcgi-spec.html#S3)s on fd ``0``.

**Comment by nicolasfranck** [comment]
Ah, interesting! So as long this python program does not execute an `accept()`, it would not interfere with the other requests, and no request data passes `supervisord`.
