### ISSUE TITLE
Unable to run APPSMITH container image in docker swarm but working as standalone

### ISSUE THREAD

**Issue by inmakum19** [Supervisor/supervisor#1487]
Since docker swarm doesn't have root privilege's, permissions related issues are throwing when running image inside a docker swarm.

below are the error's from docker service logs.

After initial error below modification is done in docker file

image

then observed the secondary error

logs
Initial error
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | Load environment configuration
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | Checking environment configuration
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | Init database
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | rm: cannot remove '/etc/letsencrypt/cli.ini': Permission denied
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | Check initialized database
formbuilderui.1.nxlxqh55d5ux@ability-edge-sdk | Mounting Let's encrypt directory
formbuilderui.1.joehd7ao0aez@ability-edge-sdk | rm: cannot remove '/etc/letsencrypt/cli.ini': Permission denied
formbuilderui.1.r1ozq3kz7so5@ability-edge-sdk | rm: cannot remove '/etc/letsencrypt/cli.ini': Permission denied
formbuilderui.1.fqmfftx1x0f3@ability-edge-sdk | rm: cannot remove '/etc/letsencrypt/cli.ini': Permission denied
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Checking configuration file
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Load environment configuration
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Checking environment configuration
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Init database
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Check initialized database
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | Mounting Let's encrypt directory
formbuilderui.1.zr1nngnpgspo@ability-edge-sdk | rm: cannot remove '/etc/letsencrypt/cli.ini': Permission denied

Secondary error(supervisor error)
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Checking configuration file
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Load environment configuration
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Checking environment configuration
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Init database
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Check initialized database
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Mounting Let's encrypt directory
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,707 INFO Included extra file "/etc/supervisor/conf.d/backend.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,707 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,707 INFO Included extra file "/etc/supervisor/conf.d/editor.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,707 INFO Included extra file "/etc/supervisor/conf.d/mongodb.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,708 INFO Included extra file "/etc/supervisor/conf.d/redis.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,708 INFO Included extra file "/etc/supervisor/conf.d/rts.conf" during parsing
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,722 INFO RPC interface 'supervisor' initialized
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | 2021-12-10 12:58:13,723 CRIT Server 'inet_http_server' running without any HTTP authentication checking
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | Error: Cannot open an HTTP server: socket.error reported errno.EACCES (13)
formbuilderui.1.4aqnl6refn06@ability-edge-sdk | For help, use /usr/bin/supervisord -h
formbuilderui.1.urbo9pbc1qal@ability-edge-sdk | Error: Cannot open an HTTP server: socket.error reported errno.EACCES (13)
formbuilderui.1.urbo9pbc1qal@ability-edge-sdk | For help, use /usr/bin/supervisord -h
formbuilderui.1.juc46ui0xq8e@ability-edge-sdk | Error: Cannot open an HTTP server: socket.error reported errno.EACCES (13)
formbuilderui.1.juc46ui0xq8e@ability-edge-sdk | For help, use /usr/bin/supervisord -h
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Checking configuration file
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Load environment configuration
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Checking environment configuration
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Init database
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Check initialized database
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Mounting Let's encrypt directory
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,494 INFO Included extra file "/etc/supervisor/conf.d/backend.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,494 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,494 INFO Included extra file "/etc/supervisor/conf.d/editor.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,495 INFO Included extra file "/etc/supervisor/conf.d/mongodb.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,495 INFO Included extra file "/etc/supervisor/conf.d/redis.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,495 INFO Included extra file "/etc/supervisor/conf.d/rts.conf" during parsing
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,505 INFO RPC interface 'supervisor' initialized
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | 2021-12-10 12:59:14,506 CRIT Server 'inet_http_server' running without any HTTP authentication checking
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | Error: Cannot open an HTTP server: socket.error reported errno.EACCES (13)
formbuilderui.1.p1q9n8k6c9u7@ability-edge-sdk | For help, use /usr/bin/supervisord -h
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Checking configuration file
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Load environment configuration
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Checking environment configuration
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Init database
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Check initialized database
formbuilderui.1.kdbfyouwreh5@ability-edge-sdk | Mounting Let's encrypt directory

Steps To Reproduce

1. Created a new docker image.
2. Pull the image.
3. Create a docker service.
4. Verify the docker service logs.

Below are the list of config files.
[https://github.com/appsmithorg/appsmith/tree/release/deploy/docker/templates](url)

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
