### ISSUE TITLE
supervisorctl status - processes that are starting return 0

### ISSUE THREAD

**Issue by REWRicharddeGroot** [Supervisor/supervisor#1488]
Hello,

I am currently using supervisorctl status as a health check to ensure the system is running.  I am noticing during startup, that when a process is in the starting state, supervisorctl status will return 0.  Even though the process is not running, and may still fail (and has failed, causing bad requests).

I am wondering if there is a way I can work around this?  or why status would return 0 when the process has not yet made it to the running state.

Thank you,

**Comment by mnaberez** [comment]
I'm going to close this issue to merge it into #1223, where other people have requested changes to the exit codes.  I've copied the entire comment into that issue.
