### ISSUE TITLE
Error in directory : couldn't chdir to ... ENOENT

### ISSUE THREAD

**Issue by maomilan** [Supervisor/supervisor#1489]
Hi,
I try to set up the supervisor with Celery and Django.
I have an error on the directory parameter pointing to the django project : couldn't chdir to <directory> ENOENT

- The user defined in  supervisor ( user=... )  is the owner of the directory. 
- The directory have 775 permission .

what is going wrong ?
Thanks for help
Maurizio

[program:djsitecelery]
Command= "<...>env/bin/celery" worker -A djsite --loglevel=INFO
Directory="<...>/**djsite**/"
user=mao
numprocs=1
stdout_logfile=/var/log/celery/djsitecelery.log
stderr_logfile=/var/log/celery/djsitecelery.log
autostart=true
autorestart=true
startsecs=0
stopwaitsecs = 600
killasgroup=true
priority=998

**directory permission** 
drwxrwxr-x 9 mao mao 4096 gen 19 13:11  **djsite**

**Comment by mnaberez** [comment]
> couldn't chdir to ENOENT

The error message would have included the name of the directory:

https://github.com/Supervisor/supervisor/blob/602d6f574a3cba021ec3865bee6ebe20149fff26/supervisor/process.py#L331

`ENOENT` indicates "No such file or directory".  The directory shown in the error message probably does not exist.

The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by altmas5** [comment]
In case someone have this same issue and have already verified that the `directory` path is OK, go and check that there are no leading spaces on the lines of the configuration file for this specific unit or rule for the program.
