### ISSUE TITLE
Chromium crashes in supervisor

### ISSUE THREAD

**Issue by Seriyyy95** [Supervisor/supervisor#1491]
My config is:

```
process_name=%(program_name)s_%(process_num)02d
command= chromium --no-sandbox --enable-logging=stderr --v=1 --incognito
environment=DISPLAY=:1
directory = /var/www/
autostart=true
autorestart=true
numprocs=1
user=www
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```

Chromium outputs only these lines and does not start:

```
[12:12:0122/204049.413830:VERBOSE1:chrome_crash_reporter_client.cc(186)] GetCollectStatsConsent(): is_official_chrome_build is false so returning false
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
```

Version: Chromium 97.0.4692.71 built on Debian 11.2, running on Debian 11.2

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to assist with installing specific programs under Supervisor, sorry. We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by romeoonisim** [comment]
For me, the solution was quite the opposite, I had to specify the user as `root` just because the other user did not have enough permissions. The error messages are not quite helpful either. Mainly is a permissions issue.
