### ISSUE TITLE
Why every child process need to  create pipes and dup std io to main process?

### ISSUE THREAD

**Issue by ppd0705** [Supervisor/supervisor#1500]
I am learning supervisor source code, then  I found that while the main process spawns a child process,  the main process would create pipes and  dup2 stdin/stdout/stderr to those pipes。 I think the behavior would add extra workload to the main process when I don't need to use pipes communication as an event_listener process. It might be better to make pipes dup optional ?

**Comment by mnaberez** [comment]
The pipes are needed to implement core features of `supervisord`, i.e. the stderr/stdout pipes are to used to capture the child process output which is then forwarded to logfiles or syslog and the stdin pipe is used by `supervisorctl fg` to send input to the process.  The pipes can't be made optional or these features would not work.
