### ISSUE TITLE
Is supervisor supported on python 3.9 ?

### ISSUE THREAD

**Issue by sharanyabhat** [Supervisor/supervisor#1503]
Is supervisor supported on python 3.9? I don't see python 3.9 listed out in the official list mentioned, but has anyone tried it out ? Does it work ?

**Comment by mnaberez** [comment]
On Python 3.9 and 3.10, all of the unit and end-to-end tests pass for the current [development branch](https://github.com/Supervisor/supervisor/runs/6085128841) and for [Supervisor 4.2.4](https://github.com/Supervisor/supervisor/runs/4669703423), which is the latest release version [available on PyPI](https://pypi.org/project/supervisor/4.2.4/) at this time.  I've [added classifiers](https://github.com/Supervisor/supervisor/commit/4d8f5018ed4abd6fd9496a4cf0926db9e0bb70df) so PyPI will show these versions as supported after the next release.

**Comment by sharanyabhat** [comment]
Appreciate the quick response @mnaberez . Thanks!
