### ISSUE TITLE
Supervisord doesn't load plugin configured in conf.d/

### ISSUE THREAD

**Issue by piotrkochan** [Supervisor/supervisor#1506]
supervisord.conf:

```
[include]
files = /etc/supervisor/conf.d/*.conf
```

/etc/supervisor/conf.d/wildcards.conf:
```
[ctlplugin:wildcards]
supervisor.ctl_factory = supervisorwildcards.controllerplugin:make_wildcards_controllerplugin
```

Test 1:

```
sudo supervisorctl mrestart *
*** Unknown syntax: mrestart program-1 program-2
```

Test 2: 

Moved contents of wildcards.conf to the supervisord.conf

```
sudo supervisorctl mrestart program-*
program-1: stopped
program-2: stopped
program-1: started
program-2: started
```

Looks like plugins configured in conf.d are totally ignored. I haven't found any warnings or errors.

**Comment by mnaberez** [comment]
This was fixed recently in 6a5efbe77dc5372115064c0ce76c423e3a3e692c and will be included in the upcoming 4.3.0 release.
