### ISSUE TITLE
How can I find where BINDIR Is?

### ISSUE THREAD

**Issue by GuiRitter** [Supervisor/supervisor#1510]
Hi everyone.

I'm following the documentation to set up Supervisor on a VPS running Debian Buster (10). I installed it with `apt-get install supervisor`. Now I'm trying to figure out where is `BINDIR`. I don't remember whether Python came installed with the OS or if I installed it manually or if I installed it with `apt-get`. All I know for sure is that `/usr/local/` has no `py` in it.

I Googled for `BINDIR` but couldn't find how to find it out without having installed Python manually.

Thanks in advance.

**Comment by mnaberez** [comment]
> I'm following the documentation to set up Supervisor on a VPS running Debian Buster (10). I installed it with apt-get install supervisor. Now I'm trying to figure out where is BINDIR. 

In the online [documentation](http://supervisord.org/), `BINDIR` is the directory where `supervisord` and `supervisorctl` are installed.  

I installed the package as described (`apt install supervisor`) on a computer running Ubuntu 18.04 and ran these commands to find `BINDIR`.  Debian Buster (10) should be similar.

```
$ dpkg -L supervisor | grep supervisord
/etc/supervisor/supervisord.conf
/usr/bin/echo_supervisord_conf
/usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/supervisord.py
/usr/lib/python2.7/dist-packages/supervisor/tests/test_supervisord.py
/usr/share/man/man1/echo_supervisord_conf.1.gz
/usr/share/man/man1/supervisord.1.gz

$ which supervisord 
/usr/bin/supervisord
```

Both show `BINDIR` as `/usr/bin`.

Please note that the Supervisor developers only create the [PyPI package](https://pypi.org/project/supervisor/).  The distribution packages installed with programs like `apt` and `rpm` are created by others that aren't part of the Supervisor project itself, so we can't provide support for them.  The Supervisor developers also don't have enough bandwidth to help with installing or using Supervisor on individual systems, sorry.  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by GuiRitter** [comment]
I'm sorry if this question was inappropriate, but I only asked because I saw there were other issues marked with the `question` tag.

Anyway, your answer was enough for me to move ahead and I've finally managed to get a process up and running using `supervisor`. It was actually quite easy. Many thanks!
