### ISSUE TITLE
FileNotFoundError with supervisorctl reload

### ISSUE THREAD

**Issue by M0rtenB** [Supervisor/supervisor#1514]
I'm on MacOS 12.3.1, using Homebrew Supervisor 4.2.4.
Configuration file standard location, I've got four or five processes up running that I used to manage with launchd.
But I'm finding I have to reload Supervisor using launchctl commands, which is cumbersome, due to these errors I get.

`sudo supervisorctl reload` gives me
`error: <class 'FileNotFoundError'>, [Errno 2] No such file or directory: file: /usr/local/Cellar/supervisor/4.2.4/libexec/lib/python3.10/site-packages/supervisor/xmlrpc.py line: 560`

`sudo supervisorctl restart` gives me
`unix:///usr/local/var/run/supervisor.sock no such file`

**Comment by afcrocha** [comment]
Hi, try this
sudo supervisord -c /usr/local/etc/supervisord.conf
or
supervisorctl -c /usr/local/etc/supervisord.conf

supervisorctl status all

**Comment by mnaberez** [comment]
> sudo supervisorctl restart gives me
> unix:///usr/local/var/run/supervisor.sock no such file

The above error indicates that `supervisorctl` has been configured to connect to `supervisord` using a socket file but the file does not exist.  The could mean that `supervisord` is not running or that it is running but the file was deleted.

> But I'm finding I have to reload Supervisor using launchctl commands, which is cumbersome, due to these errors I get.

`supervisorctl` does not have the ability to start `supervisord`. It can only communicate with a `supervisord` instance that is already running.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
One issue that triggers this is that when supervisord starts/restarts, it can't create a logfile due to log dir absence or wrong ownership/permissions on th logs dir. Start bails out on the log creation and doesn't create a socketfile that xmlrpc tries to access.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
Including creating the OS user for supervisord instance if this user doesn't exist. Including creating the systemd unit if systemd exists in the OS.
