### ISSUE TITLE
Is supervisor scalable?

### ISSUE THREAD

**Issue by laimison** [Supervisor/supervisor#1523]
Let's say I have Supervisor installed in a single Docker container.
It's able to spawn processes. It works.

What happens when I increase replicas to 3 Docker containers? This is an attempt to ensure that Supervisor is highly available (it tolerates a loss of one container and spread resources for performance reasons)? If it doesn't support this, are there any plans to accomplish this in the future?

Thanks

**Comment by mnaberez** [comment]
> What happens when I increase replicas to 3 Docker containers?

Supervisor does not have any awareness of Docker containers.  

> This is an attempt to ensure that Supervisor is highly available (it tolerates a loss of one container and spread resources for performance reasons)?

Supervisor can only start/stop its immediate child processes and optionally restart them if they crash.  It does not have any awareness of other Supervisor instances that may be running.

> If it doesn't support this, are there any plans to accomplish this in the future?

This is out of scope for Supervisor.

However, there are some third-party tools for managing multiple instances of Supervisor.  See the [third-party plugins list](http://supervisord.org/plugins.html).
