### ISSUE TITLE
it will restart the tomcat again even the process is fine after using  "kill -9" to end supervisor.

### ISSUE THREAD

**Issue by zhangcunhai** [Supervisor/supervisor#1525]
my config file like this as below:
[program:40platform/]
command=/usr/local/dsa5200/tomcat10040/bin/startup.sh
stdout_logfile=/usr/local/dsa5200/tomcat10040/logs/catalina.out
stderr_logfile=/usr/local/dsa5200/tomcat10040/catalina.out
environment=JAVA_HOME="/usr/java/jdk1.8.0_221",JAVA_BIN="/usr/java/jdk1.8.0_221/bin"
autorestart=true
exitcodes=0,2,9
autostart=true
startsecs=3
priority=1
stopasgroup=true
killasgroup=true

when i restart supervisor after ending  supervisor use ‘kill -9 ',it will restrat the tomcat process again even the tomcat process exists.
Can I avoid this by changing some parameter ?

**Comment by mnaberez** [comment]
> when i restart supervisor after ending supervisor use ‘kill -9 ',it will restrat the tomcat process again even the tomcat process exists.
> Can I avoid this by changing some parameter ?

https://github.com/Supervisor/supervisor/issues/1444#issuecomment-861750080

**Comment by zhangcunhai** [comment]
> > when i restart supervisor after ending supervisor use ‘kill -9 ',it will restrat the tomcat process again even the tomcat process exists.
> > Can I avoid this by changing some parameter ?
> 
> [#1444 (comment)](https://github.com/Supervisor/supervisor/issues/1444#issuecomment-861750080)

thanks for your reply
