### ISSUE TITLE
It is possible to enhance the backoff parameters?

### ISSUE THREAD

**Issue by jseparovic** [Supervisor/supervisor#1528]
When using supervisord to restart a process that is exiting upon start, it seems the backoff procedure just adds 1 second to the backoff forever.
Is it possible to add a config option such as maxbackoff=30 or similar so that we can force a restart attempt at least every 30 seconds even when the process it not starting continually. 
It might be some external system that needs to be fixed in order for the process to start and this could take some time, but supervisor should keep retrying so the process comes back up in a timely manner when the external system is fixed.
If the external system is down for a day

Would like to use something like:
autorestart=true
startretries=2147483647
maxbackoff=30

So that supervisor will retry at least every 30 seconds.

**Comment by jseparovic** [comment]
I created a PR https://github.com/Supervisor/supervisor/pull/1529
Not sure if I added the config variable correctly. It works ok in my setup.

**Comment by mnaberez** [comment]
Continued in #1529
