### ISSUE TITLE
Problem with Python 3.10.4

### ISSUE THREAD

**Issue by rodinmehr** [Supervisor/supervisor#1530]
I am using Supervisord 4.2.4 and Python 3.10.4.
When I want to run this command:
`$sudo supervisorctl`
I get the below error. Any ideas how I can fix the issue?

> /usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
>   warnings.warn(
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 581, in _build_master
>     ws.require(__requires__)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 909, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 800, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (supervisor 4.2.4 (/home/user/.local/lib/python3.10/site-packages), Requirement.parse('supervisor==3.3.1'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/supervisorctl", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 3260, in <module>
>     def _initialize_master_working_set():
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 3234, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 583, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 596, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/local/lib/python3.10/dist-packages/setuptools-62.1.0.post20220509-py3.10.egg/pkg_resources/__init__.py", line 795, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'supervisor==3.3.1' distribution was not found and is required by the application

**Comment by mnaberez** [comment]
> pkg_resources.VersionConflict: (supervisor 4.2.4 (/home/user/.local/lib/python3.10/site-packages), Requirement.parse('supervisor==3.3.1'))

> pkg_resources.DistributionNotFound: The 'supervisor==3.3.1' distribution was not found and is required by the application

This error is not coming from Supervisor, it's coming from [Setuptools](https://pypi.org/project/setuptools/).  A program that you are trying to run has a requirement for Supervisor 3.3.1 but its environment has Supervisor 4.2.4 installed.  

The solution would to either install Supervisor 3.3.1 into this environment so it satisfies that program's requirement, or to change the program so it works with later versions of Supervisor.  Either way, this isn't something the Supervisor developers can help with, as the error occurs before Supervisor is loaded.
