### ISSUE TITLE
What are the possible status values of supervirsorctl status?

### ISSUE THREAD

**Issue by JossWhittle** [Supervisor/supervisor#1533]
Executing ` supervisorctl status` seems to return `RUNNING` or `STOPPED`. 

```
$ supervisorctl status
sshd                             RUNNING   pid 53, uptime 0:02:05
```

Are there other values this field is allowed to have? I cannot find a reference to it's possible values in the documentation or man pages.

Thank you.

Is there any way to easily and robustly assert whether at least one process is not in the `RUNNING` state?

**Comment by mnaberez** [comment]
> Are there other values this field is allowed to have? I cannot find a reference to it's possible values in the documentation or man pages.

http://www.supervisord.org/subprocess.html#process-states

> Is there any way to easily and robustly assert whether at least one process is not in the RUNNING state?

Not that I'm aware of.  `supervisorctl status` outputs one line per process.  If one of the lines does not contain the text `RUNNING`, then the process is not in the `RUNNING` state.
