### ISSUE TITLE
Autorestart with false config

### ISSUE THREAD

**Issue by copyandrun** [Supervisor/supervisor#1534]
I got an amazing issue with this config. the gearsyncd start twice but i cannot find why this one can be restart.

Line 3090: Aug 16 2022 17:31:52.427366 sonic INFO swss#supervisord 2022-08-16 17:31:52,419 INFO spawned: 'rsyslogd' with pid 29
	Line 3146: Aug 16 2022 17:31:53.538926 sonic INFO swss#supervisord 2022-08-16 17:31:53,538 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
	Line 3202: Aug 16 2022 17:31:54.606440 sonic INFO swss#supervisord 2022-08-16 17:31:54,604 INFO spawned: 'gearsyncd' with pid 33
	Line 3203: Aug 16 2022 17:31:54.606605 sonic INFO swss#supervisord 2022-08-16 17:31:54,604 INFO success: gearsyncd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
	Line 3204: Aug 16 2022 17:31:54.612912 sonic INFO swss#supervisord 2022-08-16 17:31:54,612 INFO spawned: 'portsyncd' with pid 34
	Line 3206: Aug 16 2022 17:31:54.628637 sonic INFO swss#supervisord 2022-08-16 17:31:54,627 INFO exited: gearsyncd (exit status 0; expected)
	Line 3220: Aug 16 2022 17:31:54.701767 sonic INFO swss#supervisord 2022-08-16 17:31:54,700 INFO spawned: 'gearsyncd' with pid 43
	Line 3221: Aug 16 2022 17:31:54.701964 sonic INFO swss#supervisord 2022-08-16 17:31:54,701 INFO success: gearsyncd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
	Line 3412: Aug 16 2022 17:31:55.711304 sonic INFO swss#supervisord 2022-08-16 17:31:55,710 INFO success: portsyncd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
	Line 3413: Aug 16 2022 17:31:55.711392 sonic INFO swss#supervisord 2022-08-16 17:31:55,711 INFO exited: gearsyncd (exit status 0; expected)

[program:gearsyncd]
command=/usr/bin/gearsyncd -p /usr/share/sonic/hwsku/gearbox_config.json
priority=3
autostart=false
autorestart=false
startsecs=0
startretries=0
stdout_logfile=syslog
stderr_logfile=syslog
dependent_startup=true
dependent_startup_wait_for=rsyslogd:running

**Comment by copyandrun** [comment]
i make loglevel to debug and found this log. Maybe the gearsyncd program is very fast than supervisor? Since i found that the exit is earlier than the supervisor got the start message. Could you please help me with this question?



	Line 3464: Aug 19 2022 17:22:02.115364 sonic INFO swss#supervisord 2022-08-19 17:22:02,114 INFO spawned: 'gearsyncd' with pid 34
	Line 3465: Aug 19 2022 17:22:02.115816 sonic INFO swss#supervisord 2022-08-19 17:22:02,115 INFO success: gearsyncd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
	Line 3475: Aug 19 2022 17:22:02.126577 sonic NOTICE swss#gearsyncd: :- checkWarmStart: gearsyncd doing warm start, restore count 9
	Line 3475: Aug 19 2022 17:22:02.126577 sonic NOTICE swss#gearsyncd: :- checkWarmStart: gearsyncd doing warm start, restore count 9
	Line 3483: Aug 19 2022 17:22:02.131131 sonic INFO swss#supervisord 2022-08-19 17:22:02,130 DEBG fd 21 closed, stopped monitoring <POutputDispatcher at 140255889400552 for <Subprocess at 140255889498800 with name gearsyncd in state RUNNING> (stdout)>
	Line 3484: Aug 19 2022 17:22:02.131494 sonic INFO swss#supervisord 2022-08-19 17:22:02,131 DEBG fd 23 closed, stopped monitoring <POutputDispatcher at 140255889403520 for <Subprocess at 140255889498800 with name gearsyncd in state RUNNING> (stderr)>
	Line 3485: Aug 19 2022 17:22:02.131696 sonic INFO swss#supervisord 2022-08-19 17:22:02,131 INFO exited: gearsyncd (exit status 0; expected)
	Line 3489: Aug 19 2022 17:22:02.132873 sonic INFO swss#supervisord 2022-08-19 17:22:02,130 - supervisord_dependent_startup - [INFO   ] New event: Service gearsyncd went from STOPPED to STARTING
	Line 3506: Aug 19 2022 17:22:02.152492 sonic INFO swss#supervisord 2022-08-19 17:22:02,149 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      EXITED                          dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3546: Aug 19 2022 17:22:02.213034 sonic INFO swss#supervisord 2022-08-19 17:22:02,211 - supervisord_dependent_startup - [INFO   ] Services not yet running (20): gearsyncd, portsyncd, orchagent, swssconfig, coppmgrd, restore_neighbors, neighsyncd, vlanmgrd, intfmgrd, portmgrd, buffermgrd, enable_counters, vrfmgrd, nbrmgrd, vxlanmgrd, fdbsyncd, tunnelmgrd, fdbtblmgrd, ecmpmgrd, arpmissmgrd
	Line 3548: Aug 19 2022 17:22:02.216495 sonic INFO swss#supervisord 2022-08-19 17:22:02,214 - supervisord_dependent_startup - [INFO   ] Starting service: gearsyncd (State: EXITED)
	Line 3550: Aug 19 2022 17:22:02.219966 sonic INFO swss#supervisord 2022-08-19 17:22:02,219 INFO spawned: 'gearsyncd' with pid 44
	Line 3551: Aug 19 2022 17:22:02.221015 sonic INFO swss#supervisord 2022-08-19 17:22:02,220 INFO success: gearsyncd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
	Line 3579: Aug 19 2022 17:22:02.232914 sonic INFO swss#supervisord 2022-08-19 17:22:02,229 - supervisord_dependent_startup - [INFO   ] New event: Service gearsyncd went from STARTING to RUNNING
	Line 3601: Aug 19 2022 17:22:02.252053 sonic INFO swss#supervisord 2022-08-19 17:22:02,250 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      RUNNING                         dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3628: Aug 19 2022 17:22:02.295876 sonic NOTICE swss#gearsyncd: :- checkWarmStart: gearsyncd doing warm start, restore count 10
	Line 3628: Aug 19 2022 17:22:02.295876 sonic NOTICE swss#gearsyncd: :- checkWarmStart: gearsyncd doing warm start, restore count 10
	Line 3661: Aug 19 2022 17:22:02.336764 sonic INFO swss#supervisord 2022-08-19 17:22:02,335 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      RUNNING                         dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3720: Aug 19 2022 17:22:02.396262 sonic INFO swss#supervisord 2022-08-19 17:22:02,394 - supervisord_dependent_startup - [INFO   ] New event: Service gearsyncd went from RUNNING to EXITED
	Line 3729: Aug 19 2022 17:22:02.420166 sonic INFO swss#supervisord 2022-08-19 17:22:02,412 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      RUNNING                         dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3784: Aug 19 2022 17:22:02.482403 sonic INFO swss#supervisord 2022-08-19 17:22:02,480 - supervisord_dependent_startup - [INFO   ] New event: Service gearsyncd went from EXITED to STARTING
	Line 3790: Aug 19 2022 17:22:02.497941 sonic INFO swss#supervisord 2022-08-19 17:22:02,496 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      RUNNING                         dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3839: Aug 19 2022 17:22:02.550456 sonic INFO swss#supervisord 2022-08-19 17:22:02,549 - supervisord_dependent_startup - [INFO   ] New event: Service gearsyncd went from STARTING to RUNNING
	Line 3845: Aug 19 2022 17:22:02.567583 sonic INFO swss#supervisord 2022-08-19 17:22:02,566 - supervisord_dependent_startup - [INFO   ]  - gearsyncd                      RUNNING                         dependent_startup: True   wait_for: 'rsyslogd:RUNNING'  priority:    3
	Line 3902: Aug 19 2022 17:22:03.274492 sonic INFO swss#supervisord 2022-08-19 17:22:03,273 DEBG fd 23 closed, stopped monitoring <POutputDispatcher at 140255889373280 for <Subprocess at 140255889498800 with name gearsyncd in state RUNNING> (stdout)>
	Line 3903: Aug 19 2022 17:22:03.274492 sonic INFO swss#supervisord 2022-08-19 17:22:03,274 DEBG fd 27 closed, stopped monitoring <POutputDispatcher at 140255889374064 for <Subprocess at 140255889498800 with name gearsyncd in state RUNNING> (stderr)>
	Line 3905: Aug 19 2022 17:22:03.274696 sonic INFO swss#supervisord 2022-08-19 17:22:03,274 INFO exited: gearsyncd (exit status 0; expected)

**Comment by mnaberez** [comment]
> I got an amazing issue with this config. the gearsyncd start twice but i cannot find why this one can be restart.

...

> [program:gearsyncd]
> command=/usr/bin/gearsyncd -p /usr/share/sonic/hwsku/gearbox_config.json
> priority=3
> autostart=false
> autorestart=false
> startsecs=0
> startretries=0
> stdout_logfile=syslog
> stderr_logfile=syslog
> dependent_startup=true
> dependent_startup_wait_for=rsyslogd:running

Supervisor has no option `dependent_startup` or `dependent_startup_wait_for`.  If you are using a plugin that adds these options, the authors of that plugin may be able to help.
