### ISSUE TITLE
error: <class 'xml.parsers.expat.ExpatError'>, not well-formed (invalid token): line 11, column 0: file: /usr/lib/python3.10/xmlrpc/client.py line: 451

### ISSUE THREAD

**Issue by herhor67** [Supervisor/supervisor#1538]
Hello,
I am getting this error when trying to `tail` one of my programs.
```error: <class 'xml.parsers.expat.ExpatError'>, not well-formed (invalid token): line 11, column 0: file: /usr/lib/python3.10/xmlrpc/client.py line: 451```
I assume this is caused by color codes being sent to cout, because all other programs work fine, and even the `tail [...] stderr` for this one works too. Most likely the [ESC] character.

Attaching the log file (redacted possibly sensitive data).
[XXXX-stdout---supervisor.log](https://github.com/Supervisor/supervisor/files/9540688/XXXX-stdout---supervisor.log)

Also I've noticed that it's impossible to add colors to the CTL prompt, they just display as plain characters. Or maybe even crashed, can't remember now.

**Comment by mnaberez** [comment]
Duplicate of #85
