### ISSUE TITLE
Performance penalty for iteratively executing `os.close`

### ISSUE THREAD

**Issue by tyong920** [Supervisor/supervisor#1540]
As per [Python official document on `os.closerange`](https://docs.python.org/3/library/os.html?highlight=os%20close#os.closerange)

`Close all file descriptors from fd_low (inclusive) to fd_high (exclusive), ignoring errors. Equivalent to (but much faster than):
`
```python
for fd in range(fd_low, fd_high):
    try:
        os.close(fd)
    except OSError:
        pass
```

It's better replace with it.
https://github.com/Supervisor/supervisor/blob/906d2adec9bd27d54cdff48bdd12f6cb42bf9546/supervisor/options.py#L1329-L1333

**Comment by mnaberez** [comment]
Continued in #1541
