### ISSUE TITLE
Release 4.2.5 or 4.3

### ISSUE THREAD

**Issue by piotrkochan** [Supervisor/supervisor#1547]
Good morning, the 4.2.4 was released on Dec 30, 2021, that's a long time ago and some new functionalities have been merged since then. When are you going to release a new version? Is there anything stopping the new release?

**Comment by mnaberez** [comment]
Supervisor [usually](https://github.com/Supervisor/supervisor/blob/4.2.4/CHANGES.rst) has one or two feature releases per year, along with whatever bug fix releases are needed between them.  There will be at least one new feature release of Supervisor before the end of the year.  New releases are posted to [PyPI](https://pypi.org/project/supervisor/) when they are available.
