### ISSUE TITLE
CRIT uncaptured python exception, closing channel 

### ISSUE THREAD

**Issue by carey-nan** [Supervisor/supervisor#1548]
supervisord --version
3.3.5

After the service runs normally for a period of time, an error is reported, and the service enters the suspended animation state.

Log output：
CRIT uncaptured python exception, closing channel <POutputDispatcher at 140491736580416 for <Subprocess at 140491736486608 with name OrdersReceive in state RUNNING> (stdout)> (<type 'exceptions.OSError'>:[Errno 14] Bad address [/usr/lib/python2.7/site-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/site-packages/supervisor/dispatchers.py|handle_read_event|230] [/usr/lib/python2.7/site-packages/supervisor/options.py|readfd|1511])

**Comment by mnaberez** [comment]
> supervisord --version
> 3.3.5

Supervisor 3.3.5 is nearly [5 years old](https://github.com/Supervisor/supervisor/blob/4.2.4/CHANGES.rst#335-2018-12-22) and is no longer supported.  Please upgrade to a recent version.
