### ISSUE TITLE
Cyclically output log when running a gunicorn project

### ISSUE THREAD

**Issue by Zhaoyuhang97** [Supervisor/supervisor#1564]
Cyclically output log every 1s when running my gunicorn project.

supervisor log:
    W0106 13:11:41.922928 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:42.923225 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:43.923297 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:44.923517 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:45.923626 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:46.923797 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:47.924369 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:48.924115 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:49.924270 14628 default_variables.cpp:91] Fail to fscanf: Success [0]
    W0106 13:11:50.924449 14628 default_variables.cpp:91] Fail to fscanf: Success [0]

Why is that?
Thanks

**Comment by mnaberez** [comment]
The Supervisor developers also don't have enough bandwidth to help with installing or using Supervisor on individual systems, sorry. We use this issue tracker mainly for bugs in Supervisor itself.
