### ISSUE TITLE
How to run in a specific time frame?

### ISSUE THREAD

**Issue by sh4msi** [Supervisor/supervisor#1565]
Is there a way to start and end the performance between two specific times?

**Comment by LinuxBoi7777** [comment]
what i would do is use it in conjugation with another program like this: https://github.com/dbader/schedule

so it would be something like this: supervisor => schedule (on startup)

**Comment by mnaberez** [comment]
Cron-like functionality is out of scope for Supervisor.

Duplicate of #635
