### ISSUE TITLE
Can't install in Debian 11?

### ISSUE THREAD

**Issue by charleslcso** [Supervisor/supervisor#1579]
From the README, it seems that Debian is not supported.

I can install supervisor 4.2.2-2 in Debian 11, but when I try to systemctl start supervisor I get:

```
root@frappe2:~# /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
  File "/usr/bin/supervisord", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for supervisor
```

Please advise.

**Comment by mnaberez** [comment]
> I can install supervisor 4.2.2-2 in Debian 11

How did you install it?

**Comment by charleslcso** [comment]
Just `apt install supervisor`. 

`root@frappe2-debian11:~# systemctl status supervisor
Unit supervisor.service could not be found.
root@frappe2-debian11:~# apt install supervisor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  supervisor-doc
The following NEW packages will be installed:
  supervisor
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 309 kB of archives.
After this operation, 1738 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 supervisor all 4.2.2-2 [309 kB]
Fetched 309 kB in 0s (2578 kB/s)
Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 29, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package supervisor.
(Reading database ... 38684 files and directories currently installed.)
Preparing to unpack .../supervisor_4.2.2-2_all.deb ...
Unpacking supervisor (4.2.2-2) ...
Setting up supervisor (4.2.2-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/supervisor.service → /lib/systemd/system/supervisor.service.
Processing triggers for man-db (2.9.4-2) ...
root@frappe2-debian11:~# systemctl status supervisor
● supervisor.service - Supervisor process control system for UNIX
     Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-03-12 13:22:04 HKT; 6s ago
       Docs: http://supervisord.org
    Process: 951 ExecStart=/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf (code=exited, status=1/FAILURE)
   Main PID: 951 (code=exited, status=1/FAILURE)
        CPU: 167ms
root@frappe2-debian11:~# /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
  File "/usr/bin/supervisord", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for supervisor
root@frappe2-debian11:~# journalctl -xe
Mar 12 13:21:46 frappe2-debian11 systemd[1]: Stopped Supervisor process control system for UNIX.
░░ Subject: A stop job for unit supervisor.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit supervisor.service has finished.
░░ 
░░ The job identifier is 425 and the job result is done.
Mar 12 13:21:46 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:21:46 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:21:48 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:21:48 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:21:49 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:22:03 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:22:04 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:22:04 frappe2-debian11 systemd[1]: Reloading.
Mar 12 13:22:04 frappe2-debian11 systemd[1]: Started Supervisor process control system for UNIX.
░░ Subject: A start job for unit supervisor.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit supervisor.service has finished successfully.
░░ 
░░ The job identifier is 426.
Mar 12 13:22:04 frappe2-debian11 supervisord[951]: Traceback (most recent call last):
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:   File "/usr/bin/supervisord", line 33, in <module>
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:     sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:   File "/usr/bin/supervisord", line 22, in importlib_load_entry_point
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:     for entry_point in distribution(dist_name).entry_points
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:     return Distribution.from_name(distribution_name)
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
Mar 12 13:22:04 frappe2-debian11 supervisord[951]:     raise PackageNotFoundError(name)
Mar 12 13:22:04 frappe2-debian11 supervisord[951]: importlib.metadata.PackageNotFoundError: No package metadata was found for supervisor
Mar 12 13:22:04 frappe2-debian11 systemd[1]: supervisor.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit supervisor.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 12 13:22:04 frappe2-debian11 systemd[1]: supervisor.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit supervisor.service has entered the 'failed' state with result 'exit-code'.
lines 3240-3305/3305 (END)
`


Thank you and see what I'm missing. I can install and get it run in Ubuntu 22.04.02.

**Comment by mnaberez** [comment]
> Just apt install supervisor.

The Supervisor project only publishes Python packages to [PyPI](https://pypi.org/project/supervisor/) (i.e. packages installed with `pip`).  Other types of packages, such as those installed with `apt` or `rpm`, are created by others not involved with the Supervisor project.  The Supervisor developers don't know how the third-party packages work and are not able to fix them.  

> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: Traceback (most recent call last):
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: File "/usr/bin/supervisord", line 33, in
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: File "/usr/bin/supervisord", line 22, in importlib_load_entry_point
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: for entry_point in distribution(dist_name).entry_points
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: File "/usr/local/lib/python3.10/importlib/metadata/init.py", line 969, in distribution
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: return Distribution.from_name(distribution_name)
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: File "/usr/local/lib/python3.10/importlib/metadata/init.py", line 548, in from_name
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: raise PackageNotFoundError(name)
> Mar 12 13:22:04 frappe2-debian11 supervisord[951]: importlib.metadata.PackageNotFoundError: No package metadata was found for supervisor

This traceback comes from the Python packaging machinery.  No code from Supervisor is reached.

Please report this issue to the authors of the package you are installing.
