### ISSUE TITLE
supervisorctl high cpu freq problem

### ISSUE THREAD

**Issue by V-E-O** [Supervisor/supervisor#158]
I came across this problem when I press Ctrl+C to supervisorctl.
It jump back to shell, but supervisorctrl still leave in process list.

The main issue is if some supervisorctl working in backgroud,
while I execute some command to another supervisorctl instance,
for modify config, reload, stop, restart or kill supervisord,
The supervisorctls in backgroud are crazy running.

Maybe it's hard to replay this issue, but I wonder if you kindly add mutual exclusion to supervisorctl,
or auto-kill feature when supervisord is reloaded?

**Comment by mnaberez** [comment]
There have been many changes since this issue was opened.  Please try a recent version and we can reopen if you find the high CPU problem still exists.
