### ISSUE TITLE
cannot used env for autostart?

### ISSUE THREAD

**Issue by zhangguanzhang** [Supervisor/supervisor#1592]
on centos7
```
$ yum install -y python3-pip
$ pip3 install  supervisor==4.2.4
```
Support expansions of ENV_* vars in all options in https://github.com/Supervisor/supervisor/commit/2d6ca34582a8a07a5dd96ae45ef62cd58a459f4f

```
[program:xxx-demo]
environment=DEMO_AUTO_START=true
command=bash /xxx.sh demo
directory=/opt/%(ENV_PROJECT)s
autostart=%(ENV_DEMO_AUTO_START)s
```

```
error: <class 'xmlrpc.client.Fault'>, <Fault 92: "CANT_REREAD: Format string '%(ENV_DEMO_AUTO_START)s' for 'program:xxx-demo.autostart' contains names ('ENV_DEMO_AUTO_START') which cannot be expanded. 
Available names: ENV_LANG, ENV_LD_LIBRARY_PATH, ENV_PATH, group_name, here, host_node_name, program_name in section 'program:xxx-demo' (file: '/etc/supervisor/conf.d/app.conf')">: file: xmlrpc/client.py line: 656
```

**Comment by mnaberez** [comment]
> ```pip3 install  supervisor==4.2.4```

The source code for this release is tagged [4.2.4](https://github.com/Supervisor/supervisor/tree/4.2.4) in this repository.

**Comment by mnaberez** [comment]
> error: <class 'xmlrpc.client.Fault'>, <Fault 92: "CANT_REREAD: Format string '%(ENV_DEMO_AUTO_START)s' for 'program:xxx-demo.autostart' contains names ('ENV_DEMO_AUTO_START') which cannot be expanded. 
Available names: ENV_LANG, ENV_LD_LIBRARY_PATH, ENV_PATH, group_name, here, host_node_name, program_name in section 'program:xxx-demo' (file: '/etc/supervisor/conf.d/app.conf')">: file: xmlrpc/client.py line: 656

There appears to be no variable `DEMO_AUTO_START` in the environment from which `supervisord` was started.  If the variable were present in the environment, it would have been listed under `Available names:` in message above.  

Environment variables [must be](http://supervisord.org/configuration.html#environment-variables) present in the environment at the time `supervisord` is started.

**Comment by zhangguanzhang** [comment]
> > `pip3 install  supervisor==4.2.4`
> 
> The source code for this release is tagged [4.2.4](https://github.com/Supervisor/supervisor/tree/4.2.4) in this repository.

I changed the describe
