### ISSUE TITLE
 Error: Cannot open an HTTP server: socket.error reported errno.EINVAL (22)

### ISSUE THREAD

**Issue by PawelJi** [Supervisor/supervisor#1606]
Running on OSX sonoma docker image richarvey/nginx-php-fpm:3.1.6 (alpine)

with installed using instruction 
`RUN apk add supervisor`

Stops working after upgrade do sonoma. 
Throws error:   
` Error: Cannot open an HTTP server: socket.error reported errno.EINVAL (22)`

How can I debug it, what should I check?

**Comment by edbentinck** [comment]
I'm getting the same error since a couple of weeks ago.

Supervisor no longer runs correctly (after rebuilding) on containers that I haven't touched in months. Also tried it out on a fresh container using image `php:8.1-fpm` and I get the same error. Not sure how to debug.

**Comment by edbentinck** [comment]
I was able to fix this error by updating the `file` value to the following:
```
[unix_http_server]
file=/tmp/supervisor.sock
```

Previously I was using a custom path without problem, but that now seems to produce the above error.

See if that works for you, @PawelJi
