### ISSUE TITLE
Supervisor - ERROR (MainThread)

### ISSUE THREAD

**Issue by matomatusov** [Supervisor/supervisor#1610]
Hi,
this error started to appear in supervisor. HA is virtual machine Synology.

23-11-04 22:13:21 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:1337//index.c708214f.css: Cannot write to closing transport
23-11-04 22:13:22 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/226.6820fd439963e5465b6a.js: Cannot write to closing transport
23-11-04 22:13:23 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/1486.9f5c58b5413b0650af69.js: Cannot write to closing transport
23-11-04 22:13:23 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/app.5134ec4fafe46667d3cf.js: Cannot write to closing transport
23-11-04 23:23:33 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]

**Comment by mnaberez** [comment]
> 23-11-04 23:23:33 ERROR (MainThread) [supervisor.homeassistant.api] 

This repository is for [Supervisor](http://supervisord.org), which is not related to Home Assistant "Supervisor" component.  Please report this error to the [Home Assistant](https://github.com/home-assistant/supervisor) developers.
