### ISSUE TITLE
Request to enable HTTPS for supervisord.org

### ISSUE THREAD

**Issue by michaelCTS** [Supervisor/supervisor#1614]
Currently supervisord.org is only accessible via HTTP. Chrome and Firefox are increasingly unhappy with HTTP websites, so it would great if the homepage could use HTTPS.

Cheers

**Comment by master-chief-2009** [comment]
I checked in the code:
https://github.com/Supervisor/supervisor/blob/main/supervisor/http.py line 311
            # XXX this will currently never be true
            protocol = 'https'
            
 I should be intrested to add support for https.  Should it be okay to replace http://www.nightmare.com/medusa with some more new like FastApi (https://fastapi.tiangolo.com/) or is it to heavy to run?

**Comment by mnaberez** [comment]
> I should be intrested to add support for https. Should it be okay to replace http://www.nightmare.com/medusa with some more new like FastApi (https://fastapi.tiangolo.com/) or is it to heavy to run? Might not be okay since it will also drop support for python 2.7 and earlier verison of python 3.

This issue is about adding HTTPS to the website http://supervisord.org.  For adding HTTPS to `supervisord`, please leave comments on #1135.  Supervisor is an old and relatively stable program, we're unlikely to make any major changes like dropping Medusa at this point. Please run `supervisord` behind a proxy server if you need HTTPS.

**Comment by michaelCTS** [comment]
What is supervisord hosted on? letsencrypt provides free SSL certs and sometimes it's just a matter of enabling HTTPS on the hosting provider or running [certbot](https://certbot.eff.org/)

**Comment by pandafy** [comment]
The docs are served by [Read the Docs](https://about.readthedocs.com/) which provides a valid SSL certificates on [custom domains](https://docs.readthedocs.io/en/stable/guides/custom-domains.html#adding-a-custom-domain). 

> We provide a validated SSL certificate for the domain, managed by [Cloudflare](https://www.cloudflare.com/). The SSL certificate issuance should happen within a few minutes, but might take up to one hour. See [SSL certificate issue delays](https://docs.readthedocs.io/en/stable/guides/custom-domains.html#ssl-certificate-issue-delays) for more troubleshooting options.

Can the maintainer please double check the settings on Read the Docs?

**Comment by mnaberez** [comment]
> The docs are served by [Read the Docs](https://about.readthedocs.com/) which provides a valid SSL certificates on [custom domains](https://docs.readthedocs.io/en/stable/guides/custom-domains.html#adding-a-custom-domain).

This ticket is about the [supervisord.org](http://supervisord.org) website.  It is not and has never been served by Read the Docs.  It looks similar to Read the Docs because it uses the open source [Sphinx theme from Read the Docs](https://github.com/readthedocs/sphinx_rtd_theme).

**Comment by mnaberez** [comment]
[https://supervisord.org](https://supervisord.org)
