### ISSUE TITLE
Tab completion for task names

### ISSUE THREAD

**Issue by mrx23dot** [Supervisor/supervisor#1616]
What I miss from systemd is finding task names by pressing tab.
It worked great in console

Could we add it?
`supervisorctl task_ tab`

**Comment by mnaberez** [comment]
Tab completion is supported at the `supervisorctl` prompt if the Python environment supports `readline`.  Run `supervisorctl` (no command) to start a `supervisorctl` prompt.

Supervisor is a Python program and only ships Python code. Implementing tab completion for various shells is out of scope of Supervisor.
