### ISSUE TITLE
"Unable to Connect Processes"

### ISSUE THREAD

**Issue by gurgenyegor** [Supervisor/supervisor#1619]
Hi everyone, please help me understand what I'm doing wrong. I am configuring Supervisor to run a few processes. It starts successfully, and I can access it in the browser using localhost:9001. However, when I try to enter a process name or use tail-stdout and tail-stderr, it either displays ERROR: unexpected rpc fault [30] FAILED or fails to open.

Please help me understand what mistake I might be making. I also want to mention that this is within a Docker container. I am using Docker Compose, and in my image, Supervisor is already installed. I mount its configuration file with the Compose file into /etc/supervisor/conf.d/supervisord.conf.

supervisord.conf
```sh
[supervisord]
nodaemon=true
loglevel=debug
logfile_maxbytes=0

[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)
chmod=0700                 ; socket file mode (default 0700)


[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket
serverurl=http://172.16.10.2:9001 ; use an http:// url to specify an inet socket
username=socialhub              ; (default is no username (open server))
password=socialhub              ; (default is no password (open server))

[inet_http_server]          ; inet (TCP) server disabled by default
port=172.16.10.2:9001         ; (ip_address:port specifier, *:port for all iface)
username=user              ; (default is no username (open server))
password=pass 

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:action-tracker]
command=/install-node.sh action-tracker
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/action-tracker.err.log

[program:backend-services]
command=/install-php.sh
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/backend.err.log
```

first page open
![image](https://github.com/supervisorphp/supervisor/assets/149571606/02b0bc2b-6dfe-4234-b654-9036531b5664)

but, when enter process name , give this error
![image](https://github.com/supervisorphp/supervisor/assets/149571606/d84fa6e6-3cc1-4868-b7bc-ee0383c0d106)

**Comment by mnaberez** [comment]
This address bar in the screenshot shows that the `Tail -f Stdout` link was clicked:

> ![grafik](https://github.com/Supervisor/supervisor/assets/52712/b06c566b-0c42-4c44-a2cb-9e41880c9c0a)

However, in the configuration file above, the log has been set to a special file that can't be read:

> stdout_logfile=/dev/stdout

For `supervisord` to be able to read or tail the log, the log must be a normal file on disk that can be read.
