### ISSUE TITLE
Is it possible to add a new choice for placing the config file?

### ISSUE THREAD

**Issue by xmduhan** [Supervisor/supervisor#1625]
Because of using by not root user, need a certain place for config.
```shell
$HOME/.config/supervisor/supervisord.conf
```

**Comment by 153957** [comment]
You can place it anywhere and use the `-c/--configuration FILENAME -- configuration file path (searches if not given)` option when calling supervisor.

That is, if you have control over how it is called..

**Comment by mnaberez** [comment]
> You can place it anywhere and use the -c/--configuration FILENAME -- configuration file path (searches if not given) option when calling supervisor.

As written above, use the `-c` option with both `supervisord` and `supervisorctl` to specific an arbitrary path to the configuration file.
