### ISSUE TITLE
crashmail: missing for EXITED

### ISSUE THREAD

**Issue by mrx23dot** [Supervisor/supervisor#1627]
I'm not getting email when final state is **EXITED**.

Only when crashed and successfully restarted.

```
[eventlistener:crashmail]
command=/usr/local/bin/crashmail -a -m xxx
events=PROCESS_STATE
```

EXITED state means couldn't recover and immediate attention is required.

v4.2.5
debian

**Comment by mnaberez** [comment]
The `crashmail` eventlistener is part of the [`superlance`](https://github.com/Supervisor/superlance) package.  Please report issues with it to that repository.
