### ISSUE TITLE
Export supervisorctl status running process to azure application insight

### ISSUE THREAD

**Issue by Fariz-fx** [Supervisor/supervisor#1630]
I have a python program that generates multiple supervisorctl processess. 
I'm running it in VM, to check whether it is running or not i have to login to VM, instead i want supervisorctl status in azure application insight so that if it is stopped or restarted i can able to setup alert using kql query. Not sure how to achieve it

Let me know if you need any more information

Expectation:

All the supervisorctl status process that i have should be available in azure application insight

**Comment by mnaberez** [comment]
> Expectation:
>
> All the supervisorctl status process that i have should be available in azure application insight

Third party integrations like this are outside of the scope of the Supervisor project.  Instead, developers can write plugins for Supervisor to integrate with third party services using [events](http://supervisord.org/events.html) or the [API](http://supervisord.org/api.html).  A list of [examples](http://supervisord.org/plugins.html) is also available.
