### ISSUE TITLE
Supervisord behavior when receiving a SIGTERM signal

### ISSUE THREAD

**Issue by RazorBach** [Supervisor/supervisor#1649]
In my supervisord config, i have several processes which includes one `process A` that cannot exit on SIGTERM.

After supervisord received the SIGTERM signal ` received SIGTERM indicating exit request` 
I can see some of them are killed while some processes including `process A` are still running. 

I think it's due to the one special `process A` b/c after i  killed -9 this `process A`, all remaining processes are killed immediately.

Does this mean the supervisord processes the SIGTERM signal and sends it to each processes sequentially?

Should it try to send this SIGTERM parallel to each process?

**Comment by mnaberez** [comment]
When `supervisord` receives an exit request, it will wait for its child processes to exit before exiting itself.  It will send the configured `stopsignal` to each process, then wait `stopwaitsecs` for the process to exit. If the process does not exit within the configured time, it will send the `killsignal` to that process. Please see the [configuration fie](http://supervisord.org/configuration.html) for more details on these options.  

To see what signal `supervisord` sends to a process and when, set `loglevel=debug` in the `[supervisord]` section of the config file.  The messages in the log will look like: `killing programname (pid 123) with signal SIGTERM`.
