### ISSUE TITLE
File  `/usr/local/bin/check-for-changes.sh` is not exists

### ISSUE THREAD

**Issue by kolserdav** [Supervisor/supervisor#1660]
The process 
```sh
ps -ef | grep check-for-changes.sh
root     1388852 1387898  0 Sep10 ?        00:24:08 /bin/bash /usr/local/bin/check-for-changes.sh

```
running by `supervisord`
```sh
ps -p 1387898 -o pid,comm
PID COMMAND
1387898 supervisord
```
and it **use lots of cpu time**, but if I want to read it so file ` /usr/local/bin/check-for-changes.sh` is not exists.
Why this file is not found?

**Comment by mnaberez** [comment]
The Supervisor maintainers do not have enough bandwidth to troubleshoot running specific programs under `supervisord`. We use this issue tracker mainly for bugs in `supervisord` itself.
