### ISSUE TITLE
Worker stopped using Supervisor issue

### ISSUE THREAD

**Issue by hardik-biztech** [Supervisor/supervisor#1665]
Used Supervisor version is 3.3.1
The PDF Worker managed by Supervisor has stopped due to a FATAL error with the message: "Exited too quickly". 
Upon investigation, it was determined that the issue originated from an SQL connection refusal when Supervisor attempted to connect to the database.

Error in Supervisor Log:
The error message indicated that the worker exited prematurely due to an SQL connection issue.

Recently, another issue was observed with a different worker that appeared to be in a "running" state. 
Already in a "Running" status but it will automatically restarted using cron which described for the auto-restart worker if it's stop. After auto-restart the worker using supervisor issue occurred. However, this worker was not sending events to third party application as well.

**Comment by mnaberez** [comment]
> The PDF Worker managed by Supervisor has stopped due to a FATAL error with the message: "Exited too quickly".

`supervisord` attempted to start the program but the program exited before the configured [`startsecs`](http://supervisord.org/configuration.html) value, so `supervisord` indicated that it exited too quickly.  `supervisord` tried again and again to restart the program, up until the configured `startretries` value, when it gave up and indicated `FATAL`.

> The error message indicated that the worker exited prematurely due to an SQL connection issue.

`supervisord` does not have any SQL functionality.

> Already in a "Running" status but it will automatically restarted using cron which described for the auto-restart worker if it's stop. 

`supervisord` does not have any cron-like functionality.

The Supervisor developers do not have enough bandwidth to assist with running specific programs und `supervisord`. This issue tracker is mainly used for issues in Supervisor itself.
