### ISSUE TITLE
DOC: document what happens on supervisor restart

### ISSUE THREAD

**Issue by dberardo-com** [Supervisor/supervisor#1670]
it is not clear from the doc how supervisord would deal with restarts... are all child processes going to be automatically killed on restart ? or will they be restarted when the daemon starts again?

or will the process keep running indefinitely regardless of the supervisor state ?

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

To address the GitHub issue about how supervisord deals with restarts, I've added a new section called 'Process Lifecycle' in the docs/running.rst file. This section explains:

1. How supervisord attempts to stop child processes when it's restarted or stopped
2. The use of stop signals and wait times
3. What happens to processes when supervisord restarts
4. How to configure processes to always restart with supervisord

This addition should provide clear documentation on how supervisord manages child processes during restarts and shutdowns, addressing the concerns raised in the issue.

You can review changes in this commit: https://github.com/mark-addams001881/Supervisor-supervisor-1670/commit/a6ba550fe23bd9c9354a83a4a111f9e657994368.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by dberardo-com** [comment]
Thanks for the super quick answer.

I am starting supervisor using procd on an embedded Linux distribution (openwrt) and I am using the kill command to stop the Daemon.

I am running some "sleep" programs in supervisor to test and I notice that there are more sleep process running than desired number of programs (3 in my example).

Should I kill supervisor with a specific signal? Is there a way for supervisor to recognize orphaned processes and not restarting them if they already running?

**Comment by mnaberez** [comment]
> it is not clear from the doc how supervisord would deal with restarts... are all child processes going to be automatically killed on restart ?

Programs that run under `supervisord` are [children](https://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses) of the `supervisord` process.  They exist only for the lifetime of the `supervisord` process (unless accidentally orphaned).  When `supervisord` shuts down, it sends the [`stopsignal`](https://supervisord.org/configuration.html) to the program and wait for it to exit.  If it does not exit within `stopwaitsecs`, the `killsignal` will be send to force the program to exit.  

> or will they be restarted when the daemon starts again?

When `supervisord` starts, it starts any program with `autostart = true`.  Programs can also be started or stopped using `supervisorctl`.

> or will the process keep running indefinitely regardless of the supervisor state ?

When configured properly, programs run under `supervisord` only live for as long as `supervisord` lives.

> Should I kill supervisor with a specific signal? 

To shut down `supervisord`, one of the [signals](https://supervisord.org/running.html#signal) it expects to receive indicating an exit request, e.g. `SIGTERM`, should be sent to it. When `supervisord` receives an exit request, it will shut down its subprocesses and then exit. 

The `supervisord` process should never be killed with `SIGKILL`.  Doing so will cause the OS to immediately terminate `supervisord`, orphaning any processes running under it, which will be reparented to init.

> Is there a way for supervisor to recognize orphaned processes and not restarting them if they already running?

No. `supervisord` is designed such that its subprocesses its direct children.  It relies on this to log the `stdout`/`stderr` of the process and to receive notification from the OS when they exit.
