### ISSUE TITLE
Sending SIGKILL to supervisord does not terminate children

### ISSUE THREAD

**Issue by swisspol** [Supervisor/supervisor#168]
On Linux running supervisor 3.0b1, sending a SIGKILL to the supervisord process does not terminate all its child processes i.e. the processes started through the configuration file.

**Comment by MustafaBaquari** [comment]
I was trying to achieve the same thing. Sending SIGTERM instead of SIGKILL worked for me.
I would prefer the "SIGTERM" over "SIGKILL with negated process ID" since  it allows graceful shutdown.
