### ISSUE TITLE
supervisorctl perform start or stop but return with XMLRPC Error

### ISSUE THREAD

**Issue by sboisson** [Supervisor/supervisor#178]
supervisorctl on same machine than daemon seems to process start and stop command successfully, but return an XMLRPC error when the the command was executed successfully

Running supervisor-3.0b1 on Python 2.6 CentOS;
Tried with and without user/password in supervisors.conf

Steps:

```
# supervisorctl status myservice
myservice                       RUNNING    pid 6831, uptime 0:02:35

# supervisorctl stop myservice
error: <class 'xmlrpclib.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 500 Internal Server Error>: file: /usr/lib/python2.6/site-packages/supervisor-3.0b1-py2.6.egg/supervisor/xmlrpc.py line: 471

# supervisorctl status myservice
myservice                       STOPPED    Dec 03 09:57 AM

# supervisorctl stop myservice
myservice: ERROR (not running)

# supervisorctl start  myservice
error: <class 'xmlrpclib.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 500 Internal Server Error>: file: /usr/lib/python2.6/site-packages/supervisor-3.0b1-py2.6.egg/supervisor/xmlrpc.py line: 471

# supervisorctl start  myservice
myservice: ERROR (already started)
```

**Comment by Jeckyli** [comment]
Just ran into same issue. 

The workaround I eventually figured out is not to start supervisor daemon with custom conf file location. Putting the `supervisord.conf` under `/etc` and start directly with `supervisord` cmd.

**Comment by buhuipao** [comment]
I have meet the same errror, like this:
```
 <class 'xmlrpclib.ProtocolError'>, <ProtocolError for 127.0.0.1/RPC2: 500 Internal Server Error>: file: /usr/lib/pymodules/python2.7/supervisor/xmlrpc.py line: 474
```
when I excute some command , like below:
```
supervisor> restart fusion_check
FAILED: attempted to kill fusion_check with sig SIGTERM but it wasn't running
fusion_check: ERROR (already started)
supervisor> stop fusion_check
FAILED: attempted to kill fusion_check with sig SIGTERM but it wasn't running
```
now, My server havn't started, but in supervisor , it look like this:
```
fusion_check                     RUNNING    pid 0, uptime 1:44:02
```
Please help me with this error, thank you!

**Comment by jesoonluo** [comment]
I have the same error info, that is I use the username, but don't unlocked password in unix_http_server, you can set you passwd when you set username unlocked.

**Comment by jesoonluo** [comment]
@buhuipao 你先直接把supervisor的进程杀了设置好了再重启，那是你*.conf设置里面用了用户名却没用密码。

**Comment by marzdgzmn** [comment]
> Just ran into same issue.
> 
> The workaround I eventually figured out is not to start supervisor daemon with custom conf file location. Putting the `supervisord.conf` under `/etc` and start directly with `supervisord` cmd.

Tried, this and now it's workingo n CentOS 7

**Comment by max-young** [comment]
use this command: `ps aux | grep supervisor`, find your process, kill it, then restart supervisord.
