### ISSUE TITLE
Supervisor is creating mutliple program log files instead of one

### ISSUE THREAD

**Issue by nellessen** [Supervisor/supervisor#204]
I am using a supervisor configuration with 4 child processes that are supposed to write into the same logfile _myapp.log_. This is working until  the first cycle of log files (the time `stdout_logfile_maxbytes` is reached). After that supervisor creates 4 new file _myapp.log1_, _myapp.log2_, _myapp.log3_ and _myapp.log4_.
I am using version 3.0a8-1.1 (Ubuntu version string).

Here is my config:

```
; supervisor config file

[supervisord]
logfile=/var/log/supervisord/supervisord.log    ; supervisord log file
logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
logfile_backups=10                              ; number of backed up logfiles
loglevel=error                                  ; info, debug, warn, trace
pidfile=/var/run/supervisord.pid                ; pidfile location
nodaemon=false                                  ; run supervisord as a daemon
minfds=1024                                     ; number of startup file descriptors
minprocs=200                                    ; number of process descriptors
;user=root                                      ; default user
childlogdir=/var/log/tornado/                   ; where child log files will live

[supervisorctl]
serverurl=unix:///var/run//supervisor.sock ; use a unix:// URL  for a unix socket

[unix_http_server]
file=/var/run//supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:main]
process_name = main-%(process_num)s
command = python /srv/www/myapp/app.py --port=%(process_num)s
directory=/srv/www/myapp/
stdout_logfile = /var/log/tornado/myapp.log
autorestart=true
redirect_stderr=true
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=50
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
loglevel=info
numprocs = 4
numprocs_start = 8000
```

**Comment by joshribakoff** [comment]
I read the note in the documentation but it doesn't make sense. By "2 processes" do you mean 2 supervisor worker processes? Or 2 separate installations of supervisor?

Supervisor is a single process, I expect it to accumulate output from all my workers & log it to 1 file. What I'm seeing is that after log rotations occurs, output is split across many files. For example, a single worker may output 10 lines, the 1st line seems to be logged to my-log.log.1, the 2nd line of output (from the same process) gets logged to my-log.log.2, etc... which is useless. Is this the same bug we're talking about here?

**Comment by mnaberez** [comment]
> I read the note in the documentation but it doesn't make sense. By "2 processes" do you mean 2 supervisor worker processes? Or 2 separate installations of supervisor?

It means processes running under a supervisord instance.  That terminology is used consistently throughout the documentation.

> Supervisor is a single process, I expect it to accumulate output from all my workers & log it to 1 file.

This is not supported when log rotation is enabled.
