### ISSUE TITLE
Tail showing bytes instead of lines.

### ISSUE THREAD

**Issue by Uland** [Supervisor/supervisor#210]
I consider line-based tail to be much more useful. The partially shown lines are annoying and misleading. Also in typical use case I would like to see similar number of lines no matter how long they are (usually one line = one log message). Also bytes approach is likely to have issues with Unicode (multibyte chars).

This applies to both CLI and Web UI.

**Comment by mnaberez** [comment]
It's probably too late to change this, sorry.  It's worked like this since 2007 and a lot of scripts have been written that expect the current behavior.
