### ISSUE TITLE
`tail` command fails with certain program names

### ISSUE THREAD

**Issue by jeffminard-ck** [Supervisor/supervisor#222]
I experienced this problem:

```
==> Press Ctrl-C to exit <==
http://127.0.0.1:9001/logtail/mbus0:0/stdout Cannot read, status code 410
```

When I removed the `process_name=%(process_num)s` directive for that program, the process name became simpler and the tail command now works. I am guessing that it's failing due to the `:` character. URL encoding at some point in the chain has been left out perhaps?

**Comment by NoUsername** [comment]
same issue, any hints on what causes this and/or how this can be solved?

**Comment by fsboehme** [comment]
same issue. i'm doing the same thing as the poster of this (from 2009!): http://plope.com/software/collector/277

>I was thinking of invoking supervisord every hour from cron, since something kills it on my system.
If supervisord is running, and you run supervisord again, it correctly fails to start. However supervisorctl sessions to the existing one no longer work:

>$ supervisorctl tail -f squeaktrunkbot
unix:///tmp/supervisor.sock/logtail/squeaktrunkbot/stdout Cannot read, status code 410

any suggestions?

**Comment by Reamon** [comment]
I also got same issue.

**Comment by mnaberez** [comment]
From the [original report](https://github.com/Supervisor/supervisor/issues/222#issue-12035230):
> When I removed the process_name=%(process_num)s directive for that program, the process name became simpler and the tail command now works. I am guessing that it's failing due to the : character. URL encoding at some point in the chain has been left out perhaps?

The character `:` was disallowed in 333551999058dc5b11fe83863b6cc2259c6a3128 for a different reason a few months after this report.  [Supervisor 3.0](https://github.com/Supervisor/supervisor/blob/3.1.3/CHANGES.txt#L97-L102) won't let you have this character in the process name.

*For other users seeing `Cannot read, status code 410`: this can also occur if the log file for the process doesn't exist on disk, which is the intended behavior.*
