### ISSUE TITLE
exit code allway zero

### ISSUE THREAD

**Issue by ramary** [Supervisor/supervisor#24]
I want to use the exit code for nagios but it's allways 0.

ecample 1:
zope@plone:~> ./bin/supervisorctl status
http://127.0.0.1:9001 refused connection
zope@plone:~> echo $?
0

Could you change exit LSB conform ?
http://refspecs.linuxfoundation.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

example 2:
./bin/supervisorctl status
balancer                         RUNNING    pid 23753, uptime 0:00:50
instance0                        RUNNING    pid 23751, uptime 0:00:50
instance1                        EXITED     Jun 26 05:40 PM
varnish                          RUNNING    pid 23754, uptime 0:00:50
zeo                              RUNNING    pid 23750, uptime 0:00:50
zope@plone:~> echo $?
0

**Comment by exi** [comment]
This ticket is years old and concerns a serious shortcoming. Could we bump it's priority or provide some kind of sensible workaround?

**Comment by gdm85** [comment]
@exi I have been using @lukeweber's patch, but obviously already switching to [runit](http://smarden.org/runit/) for the long term/production.

**Comment by rtwair** [comment]
Labeling this as an enhancement makes absolutely no sense.

+1 - definitely a bug

**Comment by neutrinus** [comment]
+1

This issue makes us cry at least once a week. As supervisord is not returning anything but 0, ansible has to parse the "human" strings to check the state.

**Comment by mattwiller** [comment]
+1 — this is a serious issue that makes it very difficult to integrate supervisor with our deployment infrastructure

**Comment by castarco** [comment]
+1 - That's a serious bug. This shoudn't be seen as a low priority enhancement

It difficults the integration of supervisord with other automatization tools (rather than checking the return code, the only generic way to know if the command failed is to analyze the supervisorctl output to stdout....).

**Comment by vvanscherpenseel** [comment]
+1, this is a bug

**Comment by lukeweber** [comment]
+1 for getting this fixed. It's pretty unusable for production for me without the patch. I've been using my patched version for a year now in production. @mnaberez would you merge this if there were tests or is there some other holdup? At 4 years pending I'm a bit curious why it's still not done. I recall it looking like a bit of a rewrite would be in order to test exit codes adequately.

**Comment by mnaberez** [comment]
>  @mnaberez would you merge this if there were tests or is there some other holdup?

I'm not sure what you are referring to.  This is an issue not a pull request.  As far as tests, no, this project doesn't typically merge patches that are untested.

**Comment by msabramo** [comment]
@lukeweber has a commit with a patch (lukeweber@04d47d0), but he has not filed a pull request I think.

I know of at least two PRs - mine (https://github.com/Supervisor/supervisor/pull/620) and one from @GotenXiao (https://github.com/Supervisor/supervisor/issues/292).

Mine needs tests which I have not gotten to yet. I have not looked at the changes from @GotenXiao or @lukeweber. I guess I'm curious which of the 3 is closest to what is desired and then I'll focus on the best one if I get some time.

**Comment by msabramo** [comment]
At first glance, lukeweber@04d47d0 looks comprehensive and seems to have tests, so maybe it's a better starting point than my own PR.

@lukeweber: Do you want to submit a PR?

**Comment by lukeweber** [comment]
@mnaberez -  
1. Is supervisorctl.py code used for anything besides single commands or interactive mode(two states), or is it reused in libraries (third state - not interactive, raise exceptions and don't exit on errors)?

Implementation could be the following that I think would work for both:

1. implement handle_error(message=None, fatal=False)
1. Wrap any output that contains "Error" or "ERROR" in supervisorctl.py with a handle_error(message=...) method.
1. Wrap any blank "raise" with handle_error(fatal=True)
1. Add an option exit_on_error in main() in  supervisorctl.py defined as !interactive
1. Create duplicate tests for all tests that check for different Exceptions in test_supervisorctl.py to check for SystemExit when options.exit_on_error = True

Handle error example code:
   ```python
    def handle_error(self, message=None, fatal=False):
        if message:
            self.ctl.output(message)

        if self.ctl.options.exit_on_error:
            raise SystemExit(2)
        elif fatal:
            raise
   ```

**Comment by mnaberez** [comment]
@lukeweber I'm not sure why you keep calling me out on this thread.  I haven't looked at this much, sorry.

**Comment by lukeweber** [comment]
Sorry picked it up from somewhere.

**Comment by lukeweber** [comment]
Lets get this merged: https://github.com/Supervisor/supervisor/pull/641

**Comment by lukeweber** [comment]
Would be cool if anyone wanted to test out the latest code. It's just such a chunk would feel better if a few people ran through some real world cases.

**Comment by gdm85** [comment]
@lukeweber what about adding some script-based integration tests? I can see that a simple command like ``sh -c 'sleep 3 && true'`` and ``sh -c 'sleep 3 && false'`` could do the job

**Comment by tschottdorf** [comment]
also very surprised that such a basic thing isn't working yet. Ping https://github.com/cockroachdb/cockroach-prod/issues/59

**Comment by c0b** [comment]
+1 for a severe bug of supervisorctl

from 2011 till now 2016 why isn't the available PR not merged yet?

**Comment by nocive** [comment]
+1 in which version of supervisor will this be available?
pretty shocking this took 5 years to be fixed...

**Comment by AaronOpfer** [comment]
Also curious what version of supervisor this bug will be fixed in.

Thanks supervisor contributors for making such a useful tool!

**Comment by mnaberez** [comment]
This has been merged into the master branch which will be Supervisor 4.0.

**Comment by pawelad** [comment]
Is there any chance of backporting it to 3.x version? I'd be happy to help.

**Comment by kujiy** [comment]
I use `supervisorctl status cron | grep RUNNING` instead for a while on 3.x. It returns `1` when got Fatal.

**Comment by talawahtech** [comment]
Hi, the current docs say the following: 

> `supervisorctl status all` would return non-zero if any single process was not running

However this doesn't seem to be the case when I try it. Are the docs incorrect or is there something else going on. Is there any version of supervisor where supervisorctl returns non-zero exit codes?

**Comment by MaxDeepCoder** [comment]
I still have this problem! I don't know how to fix it!
