### ISSUE TITLE
 error: <class 'socket.error'>, [Errno 101] Network is unreachable: file: /usr/lib64/python2.6/socket.py 

### ISSUE THREAD

**Issue by leeqiang** [Supervisor/supervisor#249]
```
   [user@xx] supervisorctl
   error: <class 'socket.error'>, [Errno 101] Network is unreachable: file: /usr/lib64/python2.6/socket.py line: 567
```

What's wrong ?

**Comment by zzlyzq** [comment]
same as you

**Comment by zzlyzq** [comment]
Hi, boddy:

I have solved my problem, I think there are 2 points you should try:
1. install a python 2.7, maybe you should use virtualenv for supervisor
2. if supervisord.conf was not in the normal place ,such /etc/supervisord.conf, you should add '-c xxx.conf' for your supervisorctl command, complete command line is "supervisorctl -c supervisord.conf"

Good luck.

**Comment by LockGit** [comment]
@zzlyzq wonderful

**Comment by dave-newson** [comment]
I resolve this (and similar messages) by simply adding supervisorctl socket settings to my `supervisord.conf` file.
```
[supervisorctl]
serverurl = unix:///var/run/supervisor.sock

[unix_http_server]
file = /var/run/supervisor.sock
```
Possibly not directly related, but this was one of few google results related to the topic.
