### ISSUE TITLE
Add supervisorctl commands to documentation

### ISSUE THREAD

**Issue by grillermo** [Supervisor/supervisor#250]
There is a nice intro on how to run it on the docs, and configs and everything, but nowhere it says what it does, what it is, and why do you want it.
Or maybe i skipped some part of the docs.

**Comment by oryband** [comment]
:+1: it is terrible that the docs are missing any `supervisorctl` documentation
please add

**Comment by mnaberez** [comment]
@oryband Pull request welcome.

**Comment by VynceMontgomery** [comment]
@mnaberez of course, the reason people find this issue is that they don't know what it does. Bit of a chicken-and-egg problem, y'see. ("Pull requests welcome" makes a lot less sense as a response to requests for documentation.)

**Comment by mnaberez** [comment]
@VynceMontgomery At a `supervisorctl` prompt, `help` lists all commands and `help <command>` shows specific help for a command.  All of the commands are implemented in one file, [supervisorctl](https://github.com/Supervisor/supervisor/blob/3.1.3/supervisor/supervisorctl.py).  We'd certainly appreciate a pull request if someone is up to spending a little time on it, hopefully this provides a starting point.

**Comment by Somebi** [comment]
Is this fixed? Bump if not. Very frustrating.

**Comment by mnaberez** [comment]
Fixed in #866.
