### ISSUE TITLE
Not receiving PROCESS_STATE_RUNNING for all processes

### ISSUE THREAD

**Issue by swinton** [Supervisor/supervisor#252]
I have an event listener, defined as follows in `processlistener.py`:

```python
import sys

from supervisor.childutils import listener

def write_stdout(s):
    sys.stdout.write(s)
    sys.stdout.flush()


def write_stderr(s):
    sys.stderr.write(s)
    sys.stderr.flush()


def main():
    while True:
        headers, body = listener.wait(sys.stdin, sys.stdout)
        body = dict([pair.split(":") for pair in body.split(" ")])

        write_stderr("Headers: %r\n" % repr(headers))
        write_stderr("Body: %r\n" % repr(body))

        if headers["eventname"] == "PROCESS_STATE_RUNNING":
            write_stderr("Process state running...\n")


if __name__ == '__main__':
    main()
```

In my `supervisord.conf`, I have:

```
[program:theprogramname]
command=/bin/cat              ; the program (relative uses PATH, can take args)
process_name=%(program_name)s_%(process_num)s ; process_name expr (default %(program_name)s)
numprocs=1                    ; number of processes copies to start (def 1)

[eventlistener:theeventlistenername]
command=python processlistener.py    ; the program (relative uses PATH, can take args)
process_name=%(program_name)s_%(process_num)s       ; process_name expr (default %(program_name)s)
numprocs=1                           ; number of processes copies to start (def 1)
events=PROCESS_STATE_RUNNING         ; event notif. types to subscribe to (req'd)
```

With this configuration, I am expecting my event listener to be notified whenever a process managed by Supervisor enters the `RUNNING` state. However, this is not the case. When I kill `theprogramname` with a `SIGINT` signal, the process is restarted by Supervisor, but my listener doesn't get notified of this.

I've noticed though, that the listener does get notified for `PROCESS_STATE_EXITED` events.

**Comment by mnaberez** [comment]
I was able to duplicate this but the issue is with the eventlistener script above not `supervisord`.  The script does not acknowledge the event so it doesn't receive the next one.

Adding acknowledgement to the script above:

    def main():
        while True:
            headers, body = listener.wait(sys.stdin, sys.stdout)
            body = dict([pair.split(":") for pair in body.split(" ")])
    
            write_stderr("Headers: %r\n" % repr(headers))
            write_stderr("Body: %r\n" % repr(body))
    
            if headers["eventname"] == "PROCESS_STATE_RUNNING":
                write_stderr("Process state running...\n")
    
            # acknowledge the event
            write_stdout("RESULT 2\nOK") 

After this change, the script performs as expected.  For more information, see the [eventlistener protocol](http://supervisord.org/events.html#event-listener-notification-protocol) section of the manual.
