### ISSUE TITLE
Expose stderr process logs in the web UI (tail)

### ISSUE THREAD

**Issue by wodow** [Supervisor/supervisor#254]
Feature suggestion: support e.g. `http://localhost:9001/tail.html?processname=extractor&stream=stderr` and add links on the status homepage.

**Comment by dovy** [comment]
Yea... 2013. When is this going to ever happen?

**Comment by ihipop** [comment]
any update on this issue?

**Comment by gnanet** [comment]
To add my 2 cents from the mentioned **duplicate**:

> 
> I saw in the docs that over RPC the stderr can be retrieved, so i was looking at the source, to find a solution.
> 
> I found out, that the HTTP-interface does respect a channel parameter in the logtail_handler like http://supervisor-host:9001/logtail/processname/stderr
> 
> 
> 
> so it is only a question of displaying the right link for "tail -f err", with only a few lines to replicate tailf [L262-L266](https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py#L262) to maybe tailferr in web.py and adding the channel:
> 

```
tailferr = {
        'name':'Tail -f stderr',
        'href':'logtail/%s/stderr' % processname,
        'target':'_blank'
        }
```

This would at least solve one part. Displaing the tail of stderr, would need more changes, by adding a view, decision how it is linked, etc...

So if there is a real need, i would try my best on a fork, and a PR

**Comment by LuisMayo** [comment]
Is this issue really closed?
As I see it a88a193 only adds a tail -f stderr option but not a tail.html (no -f) option for stderr.
Thanks.
