### ISSUE TITLE
Feature request: Support infinite stopwaitsecs

### ISSUE THREAD

**Issue by lukenowak** [Supervisor/supervisor#27]
stopwaitsecs parameter gives "time to finish" to process. I'd like to have possibility to have infinite (eg: -1) stopwaitsecs which would result in just sending configured stopsignal and ignoring process response (lets say: if I asked to stop, application will stop...sooner or later).

Of course starting such application later could lead to issues, but this is expected.

What do you think about it?

**Comment by arnuschky** [comment]
I would be interested in this feature. It's very useful for services that might get stuck and require some manual intervention to prevent data-loss before being killed.

**Comment by ukinau** [comment]
I also would be interested in this. Do you have the plan to support it or discuss it ?

**Comment by calvinwyoung** [comment]
+1 I'd like to see this implemented as well

**Comment by prox2k** [comment]
+1

**Comment by jfly** [comment]
+1
