### ISSUE TITLE
config file location not as documented

### ISSUE THREAD

**Issue by nphilipp** [Supervisor/supervisor#271]
According to the docs, supervisor looks for its configuration file in these places:

```
#. :file:`$CWD/supervisord.conf`

#. :file:`$CWD/etc/supervisord.conf`

#. :file:`/etc/supervisord.conf`
```

However, there are two additional, undocumented places where it looks first:

```
        here = os.path.dirname(os.path.dirname(sys.argv[0]))
        searchpaths = [os.path.join(here, 'etc', 'supervisord.conf'),
                       os.path.join(here, 'supervisord.conf'),
                       'supervisord.conf', 'etc/supervisord.conf',
                       '/etc/supervisord.conf']
```

i.e. ../etc/supervisord.conf and ../supervisord.conf relative to the executable. This breaks using $CWD/supervisord.conf in the case where /bin/supervisord exists and is in the path (in which case it prefers /etc/supervisord.conf over the local configuration file).

**Comment by mnaberez** [comment]
Fixed in 5bf7bc92d450c5378a0d05a66040b21b666caddb.
