### ISSUE TITLE
Supress warning of inclusion of extra files

### ISSUE THREAD

**Issue by glarrain** [Supervisor/supervisor#272]
When extra files are included because they match option `files` in section `include`, supervisor adds a parsing warning. Why? The log level is wrong, it should be info, since nothing "wrong" is happening that we should tell the user/dev about.

I noticed this problem because these warnings ("Included extra file xyz during parsing") pollute my logs a lot: I have 6 files for inclusion thus I get 6 of these not useful lines in my log file **each time I reload**.

https://github.com/Supervisor/supervisor/blob/master/supervisor/options.py#L546

**Comment by blueyed** [comment]
Fixed in https://github.com/Supervisor/supervisor/commit/5545fa4af5c12efe7b4493c38711f45e63c00eb2.

This issue can be closed.
