### ISSUE TITLE
"environment" config option doesn't accept "%" character even when quoted

### ISSUE THREAD

**Issue by kisamoto** [Supervisor/supervisor#291]
When setting the `environment=` parameter in a configuration file, the `%` sign returns a `Error: Format string 'KEY="%"' for 'environment' is badly formatted` error.

e.g.

Okay: `environment=SECRET_KEY="*wi4h$kqxp84f3w6uh8w@l$0(+@x$3cr&)z^lmg+pqw^6wkyi"`

Broken: `environment=SECRET_KEY="*wi4h$kqxp84f3w6uh8w@l$0(+@x$3cr&)z^lmg+pqw^6wky%i"`

Broken:`environment=FOO="%"`

Broken: `environment=FOO="\%"`

**Comment by chinmaybhoir** [comment]
Hi,

I faced a similar issue with config in `environment=` parameter inside `[supervisord]` block.

I have a parameter with `%` sign. I tried the suggested solution (using 2 `%` signs), but I haven't been able to resolve the issue.

The sample string to try with: `x1it3km%2BTVmkRsQ`
Getting following error for this string

> Error: Format string 'SECRET="x1it3km%2BTVmkRsQ"' for 'supervisord.environment' is badly formatted: unsupported format character 'B'

Any ideas?

**Comment by simo97** [comment]
@chinmaybhoir it is the case... it consider %2 like a special caracter or something like that.... In my cas i was on Django so i just remove every % in the key and it worked fine

**Comment by sumanthratna** [comment]
It would be amazing if % could automatically escape `%s` in strings (e.g., `%(ENV_SECRET_KEY)` currently expands to `x1it3km%2BTVmkRsQ`, which is invalid, but I'd like for it to expand to `x1it3km%%2BTVmkRsQ`. This way, I wouldn't have to change my Django secret key in order to make supervisor happy.
