### ISSUE TITLE
clean environment if program gets run under different user

### ISSUE THREAD

**Issue by guettli** [Supervisor/supervisor#307]
Please clean some environment variables, if a program gets run under a different user.

For example HOME=/root drives my shell crazy. 

I checked the user-id with the "id" command, it is the new (non root) user, but "cd ~/" tries to change to /root.

I think USER=root should be change (or deleted), too.

**Comment by mnaberez** [comment]
In commit fd12cfa, I added a note to the `user=` option docs about `HOME` specifically with a link to [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment) page.  I'm going to close this issue since it should be well documented now.
