### ISSUE TITLE
supervisorctl slow exit after fg

### ISSUE THREAD

**Issue by trollfred** [Supervisor/supervisor#327]
Hello! It is strange but I got supervisorctl stuck for a few seconds if I exit after 'fg' command. As I can see via strace, it is stuck at
futex(0xbab110, FUTEX_WAIT_PRIVATE, 0, NULL
It looks like this http://asciinema.org/a/6776

rt_sigaction(SIGWINCH, {SIG_DFL, [], SA_RESTORER, 0x7f25b1078ed0}, {0x7f25abd41f20, [], SA_RESTORER|SA_RESTART, 0x7f25b1078ed0}, 8) = 0
write(1, "\n", 1
)                       = 1
futex(0xbab110, FUTEX_WAIT_PRIVATE, 0, NULL

<<<
THIS IS WHERE THE PAUSE IS
<<<

) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f25b1078ed0}, {0x7f25b13932c0, [], SA_RESTORER, 0x7f25b1078ed0}, 8) = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by ihipop** [comment]
any update on this issue
