### ISSUE TITLE
reread and update ignore changes to event listeners

### ISSUE THREAD

**Issue by borntyping** [Supervisor/supervisor#339]
If I change the configuration file for an event listener:

```
$ nano /etc/supervisor/conf.d/event_listener.conf
$ supervisorctl reread
No config updates to processes
$ supervisorctl update
$
```

If I change the configuration file for a program:

```
$ nano /etc/supervisor/conf.d/program.conf
$  sudo supervisorctl reread                    
riemann-dash: changed
$ sudo supervisorctl update                         
riemann-dash: stopped
riemann-dash: updated process group
```

**Comment by Kinghack** [comment]
still not saved..

**Comment by gdelnegro** [comment]
Hi guys, I've changed my configuration file, and did 

> supervisorctl stop crashmailbatch
supervisorctl remove crashmailbatch
supervisorctl update

With the following in the config file:

> [eventlistener:crashmailbatch]
command=/bin/bash -c "/usr/local/bin/crashmailbatch -t email@company.com -f email@company.com -i 10 -s \"supervisor $HOSTNAME\""
events=PROCESS_STATE,TICK_60

However, crashmailbatch stopped working, I've killed a process, and it didn't sent an error email. There's nothing in the supervisord.log. I rolled back to the previous config, and it still don't send emails.

Anyone knows what can I do?

Best regards

**Comment by mkonecny** [comment]
Also just discovered this confusing behaviour. Was on 3.0 and upgraded to 3.2 but no luck! In the interim, would be great to document this behaviour.

**Comment by maihde** [comment]
I have made a fix available here: https://github.com/Supervisor/supervisor/pull/777

**Comment by maxiwheat** [comment]
Go this issue too while using superlance, kinda annoying, however @gdelnegro did provide an easy workaround.

**Comment by rachid804** [comment]
In my case the workers files are not included, so i had to add 
```
[include]
files = /etc/supervisor/conf.d/*.conf

```
 at the end of /etc/supervisord.conf and restart the daemon

**Comment by mr-karan** [comment]
Got bumped into this issue. As a quick fix, I renamed `eventlistener` process group and `reread` picked it up
