### ISSUE TITLE
Feature request: display logs for a process in a web page

### ISSUE THREAD

**Issue by michaelveloz** [Supervisor/supervisor#34]
ok, if an application has a problem and then you click on the link to do a "tail", you only see like 15 lines which is almost useless. 

You could consider going to the stderr log file that supervisord creates, but that's owned by supervisord and I can't even read.

So here are some options to make looking at log content actually useful:
1. Mod supervisord to have another html link per process named "view stderr" or "view stdout" .. when clicked these would display the content of the corresponding log file on an html page
2. Alter supervisord to allow the user to specify on startup how many lines to pass to "tail -f" .. so when one clicks that link in the supervisord UI, you get more than the current 15 or so lines
3. On the html page in which supervisord shows tail's output, add an html button titled "go back more" that, when clicked, stops the tail, and restarts it, but passes it a larger number than before so more content is shown (alternatively you could have a text box there that lets the user enter how many lines they'd like to go back and see)

**Comment by carolinux** [comment]
@mnaberez Hi, did this get addressed? I would also like to have a larger tail.

<img src=http://ny-image3.etsy.com/il_570xN.194417475.jpg />
