### ISSUE TITLE
Optional logging of a specified file descriptor's output, rather than just stdout and stderr

### ISSUE THREAD

**Issue by itamarst** [Supervisor/supervisor#379]
The output in stdout and stderr is hard to control - exceptions on startup may result in traceback, C libraries may write to stderr sometimes, etc.. Some applications may wish to log in a particular format (in my case JSON  message per line) and having random unrelated junk show up in the log file would be unfortunate.

The obvious solution is for application-managed logs to be written out to a different file descriptor (e.g. 3) to ensure no potential clashes with hard-to-prevent output on stdout/stderr. This would require supervisord be able to write out logs for arbitrary file descriptors rather than just stdout and stderr.

**Comment by mnaberez** [comment]
It would require a fair bit of reworking to supervisord internals to allow for arbitrary streams, and there would need to be some way to configure all the various logging options for those streams.  It's possible but we probably won't implement this unless we get a pull request for it.
