### ISSUE TITLE
stdout_logfile issue. Incorrectly logging to multiple files

### ISSUE THREAD

**Issue by TanmayaAPYL** [Supervisor/supervisor#411]
Here is our program's config:
[program:test]
process_name=%(process_num)s
command=node /test/test/app.js %(process_num)s
directory=/test/test
environment=TEST_ENV=production,NODE_ENV=production,LD_LIBRARY_PATH=/usr/local/lib
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/test.log
stderr_logfile=/var/log/test.err
numprocs=4
numprocs_start=3000

Open file descriptors:
python     8501       root    4r      REG              202,1   5102636       7655 /var/log/test.log
python     8502       root    4r      REG              202,1  33901917      33336 /var/log/test.err
superviso 13373       root    6w      REG              202,1   8141059       8678 /var/log/test.log.3
superviso 13373       root   27w      REG              202,1   5102636       7655 /var/log/test.log
superviso 13373       root   28w      REG              202,1  33901917      33336 /var/log/test.err
superviso 13373       root   30r      REG              202,1   7502878        956 /var/log/test.log.1
superviso 13373       root   32w      REG              202,1   6940502      33176 /var/log/test.log.2
superviso 13373       root   37w      REG              202,1  33901917      33336 /var/log/test.err
superviso 13373       root   41w      REG              202,1  33901917      33336 /var/log/test.err
superviso 13373       root   43w      REG              202,1  33901917      33336 /var/log/test.err

We end up having logs in any of test.log,test.log.1 or test.log.2, instead of expected test.log alone.

OS - Ubuntu 12.04
supervisor - 3.0a8-1.1

**Comment by safecat** [comment]
same problem occurs, if the program have multiple processes and backups, when processes concurrent write to "stderr_logfile_maxbytes", they will trigger the rotate almost same time, error occurs:
expected: .log -> .log.1, both processes write to .log
error: .log-> .log.1, (almost same time) .log.1 -> .log.2, processes write to .log and .log.1

Request to reopen the issue, please @mnaberez
