### ISSUE TITLE
' supervisor restart' causes Bad Request (400) error

### ISSUE THREAD

**Issue by mik-ro** [Supervisor/supervisor#412]
After restarting my django app: supervisorctl restart [process] I've got Bad Request(400) error when visiting my site. The app is under nginx with gunicorn and supervisor.

I remember to had the same problem some time ago and restarting supervisor from some specific folder on the server had helped. I've tried to restart supervisor from different locations, however it doesn't help.

**Comment by pawarkishor** [comment]
When you change `DEBUG` setting to `False`, you must also set `ALLOWED_HOSTS`.
You may simply make Django accept requests by allowing localhost:

`ALLOWED_HOSTS = ['127.0.0.1']`

This will work if gunicorn is running on same machine and it is bound to `127.0.0.1`
