### ISSUE TITLE
Program templates/inheritance

### ISSUE THREAD

**Issue by jonashaag** [Supervisor/supervisor#42]
Sometimes you may want many similar program configurations. It'd be great if you could use "inheritance", like so

``` ini
[program:foo-base]
; ... options ...
abstract = true

[program:foo1]
parent = foo-base

[program:foo2]
parent = foo-base
```

or like this

``` ini
[program-template:foo-base]
; ... options ...

[program:foo1]
template = foo-base
```

**Comment by WoLpH** [comment]
Is there any way to do this within the configs yet?

Inheriting from group doesn't work either yet :(

**Comment by cjmielke** [comment]
+1 for inheriting from a group

**Comment by beasteers** [comment]
+1 for inheriting from from groups/program wildcard definitions!

**Comment by webdevilopers** [comment]
Was this ever implemented?

**Comment by WoLpH** [comment]
> Was this ever implemented?

Nope. The suggested solution is to generate your config files using an external templating engine such as jinja2

**Comment by webdevilopers** [comment]
Too bad. Indeed we write our config files manually once. Thanks for the quick response!
