### ISSUE TITLE
Stdin support

### ISSUE THREAD

**Issue by espdev** [Supervisor/supervisor#434]
Does supervisor support the communication via standard input?

For example, I have a program that expects some data from `stdin`:
```
$ foo --login username
Enter password:
``` 
I have to set the password here. I want to send password through standard input automatically. How can I run this program via supervisor?

Now I do so:
```
#!/bin/bash
# /home/user_name/run_command

exec < password_file
foo --login username
```
```
[program:foo]
command = /home/user_name/run_command
user = user_name
```

**Comment by mnaberez** [comment]
> Does supervisor support the communication via standard input?

There is not a program option to do this.

> Now I do so:

Writing a shell stub is probably a good solution for this.
