### ISSUE TITLE
Running Supervisord for Multiple Subdomain using Laravel in one Server

### ISSUE THREAD

**Issue by devanthonyp** [Supervisor/supervisor#436]
Do you experience to run php artisan queue:listen in terminal using supervisord?

Currently my problem is i have 2 laravel application in my server..
1. a.domain.com
2. b.domain.com

i setup different supervisord conf, but then when i start calling queue from
a.domain.com the logs will show from b.domain.com, it should be in a.domain.com.
i setup properly the directory but still it happens frequently.

What do you think the problem with this?...

**Comment by aespejo** [comment]
@mailightkun have you solved this problem?
