### ISSUE TITLE
Force restart a process after 'n' hours

### ISSUE THREAD

**Issue by liquidmetal** [Supervisor/supervisor#448]
I'm running into a situation where a certain process should be restarted once every week. I don't think this is a feature that exists in supervisor yet - but would be very useful.

This can be achieved by introducing a new setting in the program section

```
...
force_restart: <value>
...
```

This means, supervisord would keep track of the duration it has been running - and restart it after `<value>` hours. This would be achieved by sending the termination signal and then starting the process again.

**Comment by jeanolivier225** [comment]
Read this article if you have root access to your server, it's work's i tried and it work's perfectlly
https://medium.com/@kariukidennisde/supervisor-periodic-restart-be46a05f4419
