### ISSUE TITLE
Supervisor process refusing commands from supervisorctl

### ISSUE THREAD

**Issue by tomhogans** [Supervisor/supervisor#459]
`$ supervisorctl restart celeryd
http://localhost:9001 refused connection`

But it looks like the process is still running:

`$ ps aux | grep "supervisord"
ubuntu    1444  0.2  0.4  58920 10088 ?        Ss   14:53   0:32 /usr/bin/python /usr/local/bin/supervisord`

So I kill that process (1444).  After verifying that the process is no longer running, I try to restart supervisord:

`$ supervisord
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /usr/local/bin/supervisord -h`

Has anyone encountered this problem before?

**Comment by WorldException** [comment]
I have this error too.
Solution:
make symbolic link conf file. New version supervisor try search in /etc.
```bash
ln -s /etc/supervisor/supervisord.conf /etc/supervisord.conf
```

**Comment by Daniel15** [comment]
@WorldException's fix (adding a symlink) worked for me too. Are newer supervisor versions looking in /etc/supervisord.conf rather than /etc/supervisor/supervisord.conf?

**Comment by mnaberez** [comment]
> Are newer supervisor versions looking in /etc/supervisord.conf rather than /etc/supervisor/supervisord.conf?

As of Supervisor 3.2.0 (current stable version), no version of Supervisor has ever searched for the config file `/etc/supervisor/supervisord.conf`.  

However, some distributions have packaged Supervisor for installation with a system package manager (e.g. `apt-get`).  These packages are not created by the Supervisor project itself and often include patches that modify Supervisor.  As noted in [configuration](http://supervisord.org/configuration.html), some distribution packages have been seen where Supervisor has been modified to search in `/etc/supervisor/supervisord.conf`.

The confusion occurs when changing from a distribution package (`apt-get install supervisor`) to the official PyPI package (`pip install supervisor`).

**Comment by Daniel15** [comment]
Interesting... I've been using the Debian supervisor package. Perhaps they changed some of their patches. I guess I should blame the Debian package maintainers instead. Thanks! :stuck_out_tongue:
