### ISSUE TITLE
supervisord crashes when SIGCHLD interrupts writing to the log

### ISSUE THREAD

**Issue by jstewmon** [Supervisor/supervisor#461]
When supervisord has many child processes which end in rapid succession, it is possible for the write to the log stream (in `Handler.emit`) to be interrupted and subsequently for the write to sys.stderr (in `Handler.handleError`) to be interrupted, causing the parent to crash with `IOError: [Errno 4] Interrupted system call`.

This scenario can easily be handled within `Handler.emit` by continuing to write the unwritten bytes until the entire message has been written to the log:
```python
    def emit(self, record):
        try:
            msg = self.fmt % record.asdict()
            pos = self.stream.tell()
            while 1:
                try:
                    written = self.stream.tell() - pos
                    self.stream.write(msg[written:])
                    break
                except UnicodeError:
                    self.stream.write(msg.encode("UTF-8"))
                except IOError as e:
                    if not e.errno == errno.EINTR:
                        raise
            self.flush()
        except:
            self.handleError(record)
```

This solution avoids log corruption by writing the entire message, even when multiple writes are required, and, more importantly, it prevents supervisord from crashing.

**Comment by mnaberez** [comment]
Since this only seems to happen on OS X when run in the foreground (unlikely as a production setup for Supervisor), and the bug has been reported to Python itself, I am going to close this issue.
