### ISSUE TITLE
dropping privileges ist marked as CRIT

### ISSUE THREAD

**Issue by jsilence** [Supervisor/supervisor#492]
Trying to use supervisord with vagrant/ubuntu14.04.
When setting user=vagrant in config file a critical error apperas in the logfile:
     CRIT Set uid to user 1000

The supervisord process appears to start and also the required program is started and monitored. 
But when using  "service supervisor start" to start the demon an error is shown:
    vagrant@vagrant-ubuntu-trusty-64:~$ sudo service supervisor start
    Starting supervisor:  ERROR.

**Comment by mnaberez** [comment]
The message `Starting supervisor: ERROR` doesn't come from Supervisor itself, it comes from the init script.  If `supervisord` attempted to start, its log file may have information that can help you troubleshoot.

You can ask general questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).
