### ISSUE TITLE
does supervisorctl actually require the configuration file?

### ISSUE THREAD

**Issue by YAmikep** [Supervisor/supervisor#498]
Hi,

I am not sure whether this is a bug or if I misunderstood the documentation.

No matter where I run `sudo supervisorctl status`, it works, even though I do not define the configuration file with `-c` and the configuration file is not in the defaults location.

```
vagrant@vagrant-ubuntu-trusty-64:~$ pwd
/home/vagrant
vagrant@vagrant-ubuntu-trusty-64:~$ sudo find / -iname "supervisord.conf"
/etc/supervisor/supervisord.conf
vagrant@vagrant-ubuntu-trusty-64:~$ sudo supervisorctl status
redis                            RUNNING   pid 5253, uptime 0:00:13
```

To find the configuration file, the doc says that it will use the first file it finds in these locations:
- `$CWD/supervisord.conf`
- `$CWD/etc/supervisord.conf`
- `/etc/supervisord.conf`

The only `supervisord.conf` file I have is `/etc/supervisor/supervisord.conf` which is not one of those.

Shouldn't I get an error message asking for the configuration file with the `-c` option?

Then, I understood why it works. `supervisorctl` uses the TCP socket to get the status of the programs running because when I remove the following section, I do not get the status of the programs anymore but an error `http://localhost:9001 refused connection`

```
[inet_http_server]
port = 127.0.0.1:9001
```

So it looks like `supervisorctl` actually does not need the configuration file when there is a TCP socket, is that correct?

Thanks

**Comment by liquidmetal** [comment]
It seems like this is intended. You need a configuration file if you're trying to connect to supervisord hosted on a different port number. If you're using `http://localhost:9001` - it'll just work.

**Comment by jvanasco** [comment]
Ubuntu patches the supervisor on installation and adds `/etc/supervisor/supervisord.conf` to the search path.  IIRC, the only way to get that file is to install the supervisor package through `apt-get install`

If you are using the ubuntu version of supervisor, it is referencing that file.  

If you are using a source version of supervisor, it's probably relying on the default values and you're just lucky that some things overlap.

**Comment by chiragvartak** [comment]
Since Supervisor 3.3.0, `/etc/supervisor/supervisord.conf` is in the search path. Also:

> Many versions of Supervisor packaged for Debian and Ubuntu included a patch that added /etc/supervisor/supervisord.conf to the search paths. The first PyPI package of Supervisor to include it was Supervisor 3.3.0.

Source: [Supervisor Configuration File](http://supervisord.org/configuration.html)
