### ISSUE TITLE
web interface 500 error

### ISSUE THREAD

**Issue by stormlifter** [Supervisor/supervisor#50]
The web interface gives me

---

Error response

Error code 500.

Message: Internal Server Error. 

---

Which really isn't giving me a lot to work with. It is properly asking for username/password, but as soon as I type the right one in it shows that error page.

**Comment by alivcor** [comment]
For anyone who installed it using the [py3 fork](https://github.com/orgsea/supervisor-py3k) ;

I ran supervisor again as:
`./supervisord -c /home/mydir/anaconda3/bin/supervisord.conf -n --loglevel=trace`

Saw the following as cause of the error:

`TRAC :Server Error: <class 'FileNotFoundError'>, [Errno 2] No such file or directory: '/home/rdwdald/anaconda3/lib/python3.6/site-packages/supervisor/ui/status.html': file: /home/rdwdald/anaconda3/lib/python3.6/xml/etree/ElementTree.py line: 586`
