### ISSUE TITLE
allow forwarding stderr/stdout of all child processes to the main stderr/stdout of the supervisord process

### ISSUE THREAD

**Issue by stefanfoulis** [Supervisor/supervisor#511]
This would be very useful for docker containers, where most logging happens through stderr/stdout of the main process being started.

**Comment by vellamike** [comment]
DEBUG needs to be lowercase

**Comment by mnaberez** [comment]
> DEBUG needs to be lowercase

The example above works on at least 3.0b2 (released in 2013).  The logging level is now [case insensitive](https://github.com/Supervisor/supervisor/commit/928028b8a055327206bcb5f30f16e8b94a4c79af) for consistency with other config file datatypes.  Consider upgrading to a more recent version for this and other fixes.
