### ISSUE TITLE
Program launched tries to write config in /root/ not /home/user/

### ISSUE THREAD

**Issue by arthurlutz** [Supervisor/supervisor#519]
Am using supervisor to run beets web in an virtualenv using vex https://pypi.python.org/pypi/vex

```
[program:beets-web]
command=/usr/bin/vex beets beet web
user=arthur
```

It was outputting that it could not write in ```/root/.vexrc``` indicating that it was running as root. 

After adding 

```
environment=HOME=/home/arthur/
directory=/home/arthur/
```

It then was outputting the following error log 

```
Error: virtualenvs directory '/root/.virtualenvs' not found. Create it or use vex --make to get started.
```

I've just commented environment and directory and restart supervisord and it seems to be running fine. Submitting the bug anyway in case this is an issue.

**Comment by mnaberez** [comment]
This is explained in [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment).  In commit  fd12cfa2e041dc87b3bd9c10157518a8a092f3af, I added a note to the `user=` option docs with a link to that page.
