### ISSUE TITLE
Child processes using subprocess.Popen silently failing

### ISSUE THREAD

**Issue by fesk** [Supervisor/supervisor#540]
Apologies in advance if this is obvious, but I've been staring at it for quite some time.

Supervisor (3.0a8 on Debian 7.4, minimal other stuff running) is controlling a child python script, which itself calls in supporting modules (all normal there).  The child is started using;

```
[program:process_app]
command=/usr/bin/python /opt/process/processapp.py
directory=/opt/process/
user=www-data
autostart=True
autorestart=True
startsecs=5
startretries=2
redirect_stderr=True
```

Inside this is a call to another module, which does this on init;

```
output, error = subprocess.Popen(["/usr/local/bin/excel2csv"],
                                         stdout=subprocess.PIPE,
                                         stderr=subprocess.PIPE).communicate()
```

The sole purpose of this is purely to check whether the command is there and if so whether it supports a specific flag - it's then used by another method in the class.  The file it's calling definitely exists, and when run directly from the command line (same user / path / command as supervisor), there's no problem (as the same user etc.).  If it's not there, the error is caught and dealt with as you'd expect.

However, when run under supervisor, nothing happens - everything works right up to the subprocess call, then nothing happens afterwards; there's nothing on stdout or stderr for the managed process, there's nothing in supervisor's main log file, the child doesn't die or change status or anything - it effectively just becomes unresponsive.

We had a related issue with a UWSGI managed app, which we solved using its close-on-exit flag.

When you look at running processes using ps, you can see that the child process is still running.

I can't figure out if this is a bug with supervisor or whether it's something stupid I'm doing (or should / shouldn't be doing).

Any help would be much appreciated.

**Comment by mnaberez** [comment]
If you're still having this issue, please try asking questions on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).

`supervisord` should capture whatever the process writes to its stdout.  If you are seeing no output, your program may be buffering it.  Try to run without buffering (`python -u`).

**Comment by saurabhprakash** [comment]
We're facing similar issue, Above post didn't had any replies, Any reason why it would happen.
It works fine without supervisor, but fails with it. Please let us know any thing on this.
