### ISSUE TITLE
How to use the %(ENV_sth)s?

### ISSUE THREAD

**Issue by yitudaodi** [Supervisor/supervisor#551]
This is my config:
command=python -u do.py --host=%(ENV_DO_HOST)s

I use the virtualenv, and I do not get the DO_HOST in /etc/.bashrc

How can I get DO_HOST to use it in the command?

Please help.

**Comment by mnaberez** [comment]
Please ask questions about installing and using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).

A short Python program may help you troubleshoot it:

    import os, sys, time
    sys.stdout.write("sys.argv:\n%r\n\n" % sys.argv)
    sys.stdout.write("os.environ:\n%r\n\n" % os.environ)
    sys.stdout.flush()
    time.sleep(10) # wait at least startsecs 

You can then use `supervisorctl tail` to see what the program is receiving as command line args and environment under Supervisor.
