### ISSUE TITLE
Stop process by sending Ctrl-C via STDIN

### ISSUE THREAD

**Issue by dtoubelis** [Supervisor/supervisor#555]
I'm trying to use `supervisor` for managing bunch of java processes and they all have 2-3 layers of wrapper scripts. When `supervisor` is trying to stop these processes it actually sends signal to the top level shell and it has no effect on child processes, so `supervisor` is effectively not capable of stopping this kind of processes. The startup scripts provided by vendors and modifying them is not an good option. Monitoring PID file produced by script is another option but PIDs are not reliable.

Here is an idea - would it be possible to add a `'stopsignal=Ctrl-C'` option (also `'Ctrl-\'` for `SIGQUIT`) to the configuration and make `supervisor` to send `'Ctrl-C'` via `STDIN`? This would solve this problem right away.

**Comment by mnaberez** [comment]
We have decided that [this is out of scope](https://github.com/Supervisor/supervisor/issues/147#issuecomment-52440691) for this project.

**Comment by dtoubelis** [comment]
I respectfully disagree. The problem described in #555 is somewhat similar to mine but I agree that proposed solution is cumbersome. However, this is a big issue that makes `supervisor` unusable for large group of applications, so the problem is still not solved. What I'm suggesting is a way more elegant solution for it. Sending `Ctrl-C` via `STDIN` is quite simple and I could do it in 30 minutes or less in `C` or `Java`. Unfortunatelly I'm not as proficient with `python`. I urge you to reconsider.

**Comment by mnaberez** [comment]
You can send `SIGINT` or `SIGQUIT` to a process using `stopsignal` (e.g. `stopsignal=SIGINT`).  However, we aren't planning to add methods of stopping a process other than sending a signal.  

You can use the XML-RPC interface to send things to the stdin of a process:

    $ python
    >>> import xmlrpclib
    >>> s = Server('http://localhost:9001/RPC2')
    >>> s.supervisor.sendProcessStdin("processname", "quit\nyes\n")

However, that isn't going to become a new way to stop programs, sorry.  If your programs can't be stopped by sending a signal, it might be worth looking into Supervisor alternatives.

**Comment by dtoubelis** [comment]
`supervisor` was actually one of those alternatives I was exploring ;-) ...back to square 1 then :-(

**Comment by wbolster** [comment]
Fwiw, "sending ctrl-c to stdin" is not how processes work. Ctrl-C is handled by your shell, and will result in a signal to be delivered to the foreground process. It's _not_ the same as writing a few bytes to a process's stdin.

**Comment by dtoubelis** [comment]
Actually if an input stream attached to a process and you send 0x03 code into it then linux TTY driver will generate TERM signal in the attached process. I'm not sure if this is still true for headless processes as it may require pseudo-terminal in order to work, but this may lead to a solution when process ID is derived from an input stream and then TERM signal send directly to that process. I think it may be worth exploring.

**Comment by caseyjlaw** [comment]
I found my way here trying to use supervisor to run commands remotely using ssh. Since the signal kills the ssh, my remote command was left hanging. For those interested, a solution for my case:
```
ssh -t -t remoteserver 'command'
```

The two -t forward the signal properly, though caveats described at http://unix.stackexchange.com/questions/40023/get-ssh-to-forward-signals.

**Comment by sixtyfive** [comment]
Any googlers ending up here not going through ssh like @caseyjlaw ... got it to work (a jruby app started via rvm in my case) by simply prepending the command with `exec`.

**Comment by Lukasz032** [comment]
> if an input stream attached to a process and you send 0x03 code into it then linux TTY driver will generate TERM signal in the attached process.

Correction: that'd be SIGINT (signal 2), not SIGTERM (signal 15).
