### ISSUE TITLE
Support set tags for process?

### ISSUE THREAD

**Issue by hengyunabc** [Supervisor/supervisor#556]
like this:
```
[program:tomcat-test]
command = /opt/tomcat/%(program_name)s/bin/catalina.sh run
autorestart=true
redirect_stderr = true
#stdout_logfile = /opt/logs-tomcat/%(program_name)s.log
stdout_logfile = /opt/tomcat/%(program_name)s/logs/catalina.log
user = tomcat
tags = product,tomcat,tag1,tag2
```
Users can query tags through xmlrpc.

It will be more easy to manager many process from different machines.

**Comment by mnaberez** [comment]
We're probably not going to add another way to organize processes anytime soon, sorry.  Both the XML-RPC interface and `supervisorctl` support plugins.  It may be possible to implement something like this as a plugin.
