### ISSUE TITLE
Option to delay subsequent retries after unsuccessful start

### ISSUE THREAD

**Issue by tobiasstein** [Supervisor/supervisor#561]
Hi,
i would be nice if there was an option in the context of the program to specify the delay between a failed startup attempt and its subsequent retries.

The background is that some resources can be missing temporarily e.g. during system startup (mysql is started later than supervisor in Debian). During normal operation dependencies of the programs like mysql, can take some time for (re-)initialization. An option could delay this retries, which would much more often be successful.

**Comment by vvanscherpenseel** [comment]
Isn't this a duplicate of #487?

**Comment by tobiasstein** [comment]
Absolutely right - two guys same idea ^^
I'll close this issue.
