### ISSUE TITLE
Supervisor web UI shows incomplete HTML with a lot of processes

### ISSUE THREAD

**Issue by jippi** [Supervisor/supervisor#564]
I just upgraded from `3.1.3` to current `dev-master` ( 681f00e74cce66e80d381788b86ed27a57e49984 )

When I try to access the HTTP server, the output is never fully sent to the client (both Chrome and curl), it simply just stalls halfway through the list and never completely flushes to the socket.

I had the same issue with a 3.x version as well, where upgrading to 3.1.3 fixed it, so not sure if its a regression in 4.x-dev 

The response headers I get is

```
HTTP/1.1 200 OK
Content-Length: 255245
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Medusa/1.12
Pragma: no-cache
Cache-Control: no-cache
Date: Mon, 26 Jan 2015 14:08:11 GMT
Content-Type: text/html

```

and then HTML output galore, though it never actually finishes 

The last lines I get is

```
        <tr class="shade">
            <td class="status"><span class="statusnominal">starting</span></td>
            <td><span></span></td>
            <td><a href="tail.html?processname=XXXXX" target="_blank">XXXXX:04</a></td>
            <td class="action">
              <ul>
                <li>
                  <a class="hidden" href="#" name="#">Action</a>
                </li>
              <li>
                  <a class="hidden" href="#" name="#">Action</a>
```

**Comment by jippi** [comment]
Using current stable I get

```
HTTP/1.1 200 OK
Content-Length: 293945
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Medusa/1.12
Pragma: no-cache
Cache-Control: no-cache
Date: Tue, 27 Jan 2015 21:30:12 GMT
Content-Type: text/html
```

as response, with the 100% identical config

**Comment by mnaberez** [comment]
What version of Python are you using?

**Comment by jippi** [comment]
-> python --version
Python 2.7.3

**Comment by BCSTechno** [comment]
:+1: 

Python version : Python 2.7.3
supervisor version : 3.0
