### ISSUE TITLE
tail -f exits immediately on python3

### ISSUE THREAD

**Issue by sontek** [Supervisor/supervisor#565]
If I do something like:

```
supervisorctl tail -f etl_process_updates_worker
```

It'll grab the first line of output and then exit

**Comment by mnaberez** [comment]
For anyone with Python 2 and 3 porting experience willing to spend some time looking at Supervisor, I would appreciate some help solving this issue.  See also [comments on #471](https://github.com/Supervisor/supervisor/pull/471#issuecomment-113371325) solving this issue.

**Comment by zjjott** [comment]
so why the pr have no merge
