### ISSUE TITLE
Supervisor does not accept valid INI files

### ISSUE THREAD

**Issue by ondrejmirtes** [Supervisor/supervisor#566]
Values in INI files can contain quotation marks around them:

```
[supervisord]
logfile = "/foo/supervisord.log"
loglevel = "WARN"
user = "ondrej"
```

Supervisor parses these files incorrectly, leaving the quotation marks in values themselves. This leads to strange errors as

```
"Error: The directory named as part of the path "/foo/supervisord.log" does not exist."
```

Where /foo is an existing and accessible directory, or:

```
Error: bad logging level name '"WARN"'
```

**Comment by fprochazka** [comment]
:+1: this seems like a bug to me

**Comment by lcosmin** [comment]
Just hit the same issue myself. +1

**Comment by abhi1010** [comment]
I am having the same issue as well.

**Comment by georgepsarakis** [comment]
supervisor uses ConfigParser and the parsing seems consistent. Quotes are part of the values and thus retained.

Can you think of a case that the quotes would be required? Generally only leading whitespace is removed, everything else is retained.

**Comment by mnaberez** [comment]
@georgepsarakis is correct that Supervisor uses the ConfigParser module to parse the file.  This restriction comes from ConfigParser.  It's unlikely we'll change this, so I've added a note to the top of the example config file.
