### ISSUE TITLE
supervisorctl restart <process> failed!

### ISSUE THREAD

**Issue by jianfengye** [Supervisor/supervisor#572]
I have a simple process written by Go:

```go
package main

import (
	"fmt"
	"html"
	"log"
	"net/http"
)

func main() {

	http.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
	})

	log.Fatal(http.ListenAndServe(":8081", nil))
}
```

and I use supervisor hang it up:

```go
 [program:testhttp]
 command=/home/yejianfeng/gocode/bin/http
 autostart=true
 autorestart=true
 user=yejianfeng
 log_stdout=true
 log_stderr=true
 logfile=/tmp/testhttp.log
 logfile_maxbytes=100MB
 logfile_backups=30
 startsecs=3
```

1 star supervisord
2 supervisorctl restart testhttp
3 I got the error :

```
INFO stopped testhttp (exit status2)
INFO received SIGCLD indicating a child quit
```

and the process stoped but not start

How can I resolve that?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
