### ISSUE TITLE
not setting uid on python process causes user installation scheme to break.

### ISSUE THREAD

**Issue by bartekrychlicki** [Supervisor/supervisor#587]
Hi, I am not entirely sure if this is a bug but I believe this is an unexpected behaviour.

I am running supervisor 3.1.3 as root calling a python process as a different system user, expecting to use libraries installed via [Alternate installation: the user scheme](https://docs.python.org/2/install/#alternate-installation-the-user-scheme). I expect `site.USER_BASE` to be `/home/my_user/.local` and I'm getting `/root/.local`. An easy way to replicate:

```
[program:weird_user_base]
command=python -m site --user-base
directory=/home/my_user
stdout_logfile=/tmp/weir_user_base.log
user=my_user
```

 I understand that this has something to do with setuid. If this behaviour cannot be changed the user installation scheme just wont work.

**Comment by mnaberez** [comment]
This is explained in detail in [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment).  You can set `site.USER_BASE` or any other environment variable using an `environment=` line as shown on that page.
