### ISSUE TITLE
Childprocess of a subprocess

### ISSUE THREAD

**Issue by amodpandey** [Supervisor/supervisor#595]
Hi,

I run a script which runs in foreground. This script executes a java child process. When I terminate my script (Ctrl+C) the child process gets terminates and then I get the prompt back.

I expected the same behavior with supervisord. I used TERM and QUIT signal. When stop is called only the script is terminated and the child java process is left running under process id 1.

I did read this 'If a process created by supervisord creates its own child processes, supervisord cannot kill them.'

But why it is not possible to send the term signal to the child process. Getting behavior similar to what we see with the terminal.

kill <SIGNAL> -- -<parent pid>

This might have been answered somewhere but I could not find one.

# supervisorctl version
3.0a8

Regards
Amod

**Comment by amodpandey** [comment]
Changing the script to run java through exec solved my problem. But it would nice to have answer for the above question.

**Comment by mnaberez** [comment]
> But why it is not possible to send the term signal to the child process. 

The `stopasgroup` and `killasgroup` options added in Supervisor 3.0b1 will send the signal to the process group.  The [manual page](http://supervisord.org/configuration.html#program-x-section-settings) describes these options.

**Comment by amodpandey** [comment]
I do not see the desired behavior

Version
----------
# supervisord -v
3.1.3

Conf
------
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true

Process
-----------
root      19127     1      0 14:34 ?        00:00:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
user1   19356 19127  0  14:35 ?       00:00:00 /bin/sh /usr/bin/catalina.sh run
user1   19367 19356 99 14:35 ?       00:00:06 /usr/bin/java BLAH

Stop
-------
supervisorctl stop myapp

Process exists
---------------------
user1   19367     1  2 14:35 ?        00:00:07 /usr/bin/java BLAH

Am I missing anything?

Thanks for your help.

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker for bugs in Supervisor itself.

**Comment by apuppy** [comment]
> > But why it is not possible to send the term signal to the child process.
> 
> The `stopasgroup` and `killasgroup` options added in Supervisor 3.0b1 will send the signal to the process group. The [manual page](http://supervisord.org/configuration.html#program-x-section-settings) describes these options.

Using the following two lines and child process killed properly. Thank you.
```
stopasgroup=true
killasgroup=true
```
