### ISSUE TITLE
Logs missed from application

### ISSUE THREAD

**Issue by tsipa** [Supervisor/supervisor#598]
Im running containers with supervisord and i've noticed that first few seconds has been lost

everything that happen inside container before supervisor says
>>Attaching to container blah-blah-blah

have been lost.

It seems like supervisor logger attaching to the process not right after start but with some delay. Is it possible to change supervisor behavior?
I've tried to reduce startsecs to 0 and tried to disable or enable stdout_events_enabled

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.
