### ISSUE TITLE
This project doesent depend on a specific version of meld?

### ISSUE THREAD

**Issue by willejs** [Supervisor/supervisor#601]
The version of meld should be pinned, and not to the latest. A minor patch to meld just broke supervisor 3.1.3 for me.

https://github.com/Supervisor/meld3/issues/21

**Comment by mcdonc** [comment]
It depends on Meld > 0.6.5 which works in new installs.  I think your error is related to some Python packaging issue, not Supervisor or Meld.  I commented on https://github.com/Supervisor/meld3/issues/21.
