### ISSUE TITLE
Handle single quotes in command

### ISSUE THREAD

**Issue by kkebb** [Supervisor/supervisor#605]
Hello,

I am trying to handle single quotation in the command value of the [program:x], is there a way to do so?

This is the error message that I see:
Error: Format string '/usr/bin/curator --host localhost delete indices --older-than 10 --time-unit hours --timestring %Y.%m.%d' for 'command' is badly formatted

**Comment by mnaberez** [comment]
It looks like you also asked this question in #607, please see that issue for a solution.
