### ISSUE TITLE
command - variables defined are available outside

### ISSUE THREAD

**Issue by amodpandey** [Supervisor/supervisor#606]
The following command works
command=/srv/data/at/uts/tomcat/bin/catalina.sh run >> "$CATALINA_OUT" 2>&1

The CATALINA_OUT is defined inside catalina.sh without export. So how is this variable accessible outside in the command. I change the variable value inside catalina.sh and the change is reflected.

But if I run the same command from command prompt it would not find value for CATALINA_OUT.

Please help me understand.

# supervisord -v
3.1.3

**Comment by mnaberez** [comment]
Please ask general questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
