### ISSUE TITLE
Error format string for command variable

### ISSUE THREAD

**Issue by kkebb** [Supervisor/supervisor#607]
I am getting an error against the command variable in supervisord.conf file.

This is the error that I am getting:

Error: Format string '/usr/bin/curator --host localhost delete indices --older-than 10 --time-unit hours --timestring %("%Y.%m.%d")s' for 'command' contains names which cannot be expanded.

**Comment by mnaberez** [comment]
Supervisor uses the `%()s` syntax for its own expansions (see [config file](http://supervisord.org/configuration.html) for examples), and it looks like your program also uses this same syntax.  

A workaround is to put your command in a shell script `start_curator.sh`:

    #!/bin/sh
    exec /usr/bin/curator --host localhost delete indices --older-than 10 --time-unit hours --timestring %("%Y.%m.%d")s

Set `program = /path/to/start_curator.sh` in the config file.

You can ask general questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.
