### ISSUE TITLE
Creating a Homebrew formula and __init.py__ goes missing

### ISSUE THREAD

**Issue by deployable** [Supervisor/supervisor#608]
I am putting together a homebrew formula for supervisor and ran into a small problem setting it up. 

[Homebrew](http://brew.sh/) provides a python install task [`setup_install_args`](https://github.com/Homebrew/homebrew/blob/5cd4c94134cf89c97a2cb2c16b415906285086e1/Library/Homebrew/language/python.rb#L78-L94) which is slightly different to a plain `python setup.py install`. Using this method works for all of supervisors dependencies but not for supervisor itself. 

When installing with the `--single-version-externally-managed` option, supervisors main `__init__.py` file doesn't exist so python can't load the supervisor module and throws an `ImportError`

With a regular install you get a `supervisor-3.1.3-py2.7.egg` directory in `site-packages`

With `--single-version-externally-managed` you get a `supervisor` directory and an `egg-info` (and of course no `supervisor/__init__.py`)

The `--single-version-externally-managed` option is [documented as an 'old-style installation'](https://pythonhosted.org/setuptools/setuptools.html#install-run-easy-install-or-old-style-installation) so you might not care but just thought I'd note it anyway due to the others supporting it

I'm just doing the manual install for supervisor to work around it.

**Comment by mnaberez** [comment]
The package is valid as-is and I see you worked around the Homebrew issue in https://github.com/deployable/homebrew/commit/30ed48dae20dc7e784a7a7d2981db07a23280596 already so I am going to close this issue.
