### ISSUE TITLE
CLI driven commands return exit 0 despite failure to connect to supervisor daemon 

### ISSUE THREAD

**Issue by jamesmulcahy** [Supervisor/supervisor#610]
jenkins@HOSTNAME:~$ supervisorctl maintail
unix:///var/run/supervisord.sock no such file
jenkins@HOSTNAME:~$ echo $?
0
jenkins@HOSTNAME:~$ supervisorctl status
unix:///var/run/supervisord.sock no such file
jenkins@HOSTNAME:~$ echo $?
0

It'd be nice if an error such as that led to a non-zero exit code

**Comment by mnaberez** [comment]
Duplicate of #24.
