### ISSUE TITLE
Supervisor can not start docker container

### ISSUE THREAD

**Issue by netroby** [Supervisor/supervisor#614]
I want to using supervisor to auto start docker container at the host machine.

here is my configure

```
[program:elastic]
command=/usr/bin/docker start -a tender_feynman
process_name=docker
redirect_stderr=true
autostart=true
autorestart=true
startretries=5
priority=10
stopsignal=KILL

```

this will never working.

supervisorctl stop elastic  not working
supervisorct start elastic not working

**Comment by mnaberez** [comment]
Please ask general questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
