### ISSUE TITLE
Programs launched from .sh files (as commands) are not stopped properly

### ISSUE THREAD

**Issue by EugenyPavlenko** [Supervisor/supervisor#616]
Hello!

Maybe this is trivial issue and this software is not supposed for that, but I am doing like that:
1) I have a command like:
command=..../startBroker.sh
(.sh file is relatively big)

2) inside this startBroker.sh I am calling Java class with certain arguments. This class is in fact "server", which listens for connections, outputs something, etc.

3) The output of the "server" is shown in "tail -f" window, that means that supervisor actually catches "server".

4) but when I am trying to stop this command (via stop button in web-interface) I see that the server is still in processes list... The same happens with other applications which are run from .sh files.

5) Of cource, "restart all" also does not work for this commands.

So, is it a problem of SV? is the any workaround or configuration options to actually bind SV not on the command itself, but on command which is executed inside .sh file?

Thanks in advance, any comment is appreciated.

**Comment by mnaberez** [comment]
Please ask general questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
