### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by evilangelmd** [Supervisor/supervisor#617]
Starting supervisord: /usr/lib/python2.6/site-packages/supervisor-3.1.3-py2.6.egg/supervisor/options.py:383: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  return pkg_resources.EntryPoint.parse("x="+spec).load(False)

**Comment by peterfox** [comment]
Got this problem as well, unsure of the cause

**Comment by itnihao** [comment]
maybe you python version is 2.6,use 2.7 OK 
```
pip2.7 install supervisor
```

**Comment by awong07** [comment]
I got same problem. It's suppose to be compatible with python 2.4+

**Comment by itorres** [comment]
Is there any possibility of this patch being backported in the 3.x series?
