### ISSUE TITLE
Update version after aptitude/apt-get installing

### ISSUE THREAD

**Issue by liminspace** [Supervisor/supervisor#621]
Hi!
How I can update supervisor version after aptitude/apt-get installing?
I want save init.d script and config files.
Thanks.

PS: Why Debian 8 doesn't have new supervisor's version?

**Comment by mnaberez** [comment]
The distribution packages aren't created or maintained by the Supervisor project itself, so unfortunately we can't answer these questions.  You may be able to get help on an issue tracker or mailing list for the distribution you are using.  There may also be users on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list who use your same distribution package and may be able to help.
