### ISSUE TITLE
docs mention installation with `easy_install`; should be replaced with `pip`

### ISSUE THREAD

**Issue by skebanga** [Supervisor/supervisor#623]
http://supervisord.org/installing.html

the page is confusing, since it says "if you've got internet access, install using `easy_install`"

Page should be updated to use `pip` not `easy_install`, or at the very least, demote `easy_install` to be below `pip`

**Comment by souravsingh** [comment]
I will add about using pip in the rst document.

**Comment by mnaberez** [comment]
Fixed in #1137
