### ISSUE TITLE
Support virtualenv

### ISSUE THREAD

**Issue by halitalptekin** [Supervisor/supervisor#632]
Maybe supervisor can support virtualenv directly. For example,
    
    [program:project]
    command = python app.py
    directory = /home/app/
    virtualenv_path = /home/.venv/app/

Thanks.

**Comment by mnaberez** [comment]
> virtualenv_path = /home/.venv/app/

What would this do?

**Comment by halitalptekin** [comment]
Say that 'this app uses virtualenv and this is the path. you run all of the codes in this environment'.

**Comment by mnaberez** [comment]
How would this be implemented?  What would Supervisor do after forking to achieve this?

**Comment by msabramo** [comment]
I don't think it's needed. Just invoke the binary in the virtualenv. 

And supervisor is used outside of the Python world where there is no virtualenv.

**Comment by mnaberez** [comment]
I agree with @msabramo on this, and since there hasn't been any more feedback, I'll close this issue.
