### ISSUE TITLE
Problem with logs directory on OSX

### ISSUE THREAD

**Issue by DataGreed** [Supervisor/supervisor#634]
Whenever I rub supervisord, i get this output:

> greedbook:deploy datagreed$ supervisord -c dev.conf 
> Error: The directory named as part of the path {{ settings.SUPERVISOR.logs_directory }}/supervisord.log does not exist.

Where is settings.SUPERVISOR.logs_directory configured?..

I used pip ti install supervisor system-wide

**Comment by mnaberez** [comment]
Your `supervisord.conf` file must have a line similar to this:

    [supervisord]
    logfile = {{ settings.SUPERVISOR.logs_directory }}/supervisord.log

The `{{ settings.SUPERVISOR.logs_directory }}` syntax isn't something that `supervisord` understands.  Please see the [online manual](http://supervisord.org/configuration.html#supervisord-section-settings) or the [example file](https://github.com/Supervisor/supervisor/blob/3.2-branch/supervisor/skel/sample.conf) for the correct usage.

**Comment by DataGreed** [comment]
Whoa, that's true. My bad, thank you!
