### ISSUE TITLE
Add simple cron-like feature to Supervisor

### ISSUE THREAD

**Issue by klahnakoski** [Supervisor/supervisor#635]
I would like a cron manager with the process-monitoring features of Supervisor.  Here are the options I have considered:

1. Make an event listener (using TICK_*) - unfortunately they must resort to command line arguments that replicate the supervisor process parameters; it seems to be a ugly hack.
2. Find an application that does what I want - This is a fine choice if I am not using Supervisor already, but having two applications with similar monitoring features but different configuration styles, is an extra learning barrier with little incremental gain.
3. Make an app that uses one configuration style and uses Supervisor and cron in background to provide features I want - Definitely reduces the learning curve, but does not solve the cron-does-not-manage-the-process problem, and might be a lot of work.
4. Make a cron-manager - implementing the process-monitoring features of Supervisor is a lot of effort.
5. **Add cron-like features to Supervisor!** - All the benefits of process monitoring, all the benefits of cron, and same configuration style for minimal learning curve.

I propose adding a `startintervalsecs`** to the `[program:x]` section that controls the start timing of the program.  I have a [non-working prototype](https://github.com/klahnakoski/supervisor/commit/ededa91f488f20cbfe99f330518a068d30b049cb) that demonstrates my intent.

I would appreciate feedback on this idea.  Since I am new to this codebase, I would also like suggestions on how best to test this feature.

Thank you

-------------------
** I assume the word "restart" assumes the process has failed, which is not the case of cron; where the process is expected to exit.

**Comment by mnaberez** [comment]
This question was asked once before a few years ago, the developers discussed it at length, and decided it was outside the scope of Supervisor.  This is outside the scope of Supervisor and will not be implemented, sorry.
