### ISSUE TITLE
be able to specify a custom shutdown/stop command/script in the [program:x] config section

### ISSUE THREAD

**Issue by rafaeltuelho** [Supervisor/supervisor#639]
In the [program:x] configuration sections there are two properties related to stop process. According to documentation Supervisord pass the SIGTEM (or other signal) to the managed child process. 

Some applications/services requires custom steps (eg. cleanup resources) before to gracefully. I such scenario would be nice have the ability to specify a custom command/script in the [program:x] config. section.

Somethnig like:
```
[program:myprogram]
...
stopcommand=/service/path/service_shutdown.sh
...
```

That make sense?

**Comment by mnaberez** [comment]
Duplicate of #147.

**Comment by rafaeltuelho** [comment]
ops! sorry :-/

**Comment by AngeIII** [comment]
@mnaberez We understand that this is duplicate, however 5 years.. why still no such command available?

**Comment by mnaberez** [comment]
> We understand that this is duplicate, however 5 years.. why still no such command available?

https://github.com/Supervisor/supervisor/issues/147#issuecomment-52440691

**Comment by Lzjing-1997** [comment]
12 years ~
