### ISSUE TITLE
Unable to start process

### ISSUE THREAD

**Issue by kracekumar** [Supervisor/supervisor#646]
Here is my `workers-staging-post-signup.conf`
```conf
[program:workers_post_signup]
environment=WORKER_CONFIG="/opt/sws/sws_workers/config/staging.py"
command=NEW_RELIC_CONFIG_FILE=/opt/sws/sws_workers/newrelic.ini /usr/local/bin/newrelic-admin run-program /usr/bin/python /opt/sws/sws_workers/app.py post_signup
directory=/opt/sws/sws_workers/
stdout_logfile=/opt/sws/log/workers_post_signup.log
stderr_logfile=/opt/sws/log/workers_post_signup_err.log
redirect_stderr=true
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=1MB
#process_num=1
program_name=workers_post_signup
#numprocs=5
#numprocs_start=1
#process_name=%(program_name)s-%(process_num)s
autostart=false
autorestart=false
startsecs=10
stopwaitsecs=600
```

Starting the supervisor `sudo supervisorctl start workers_post_signup` gives 
`workers_post_signup: ERROR (no such file)`

I am using default `supervisiord.conf` with `files = /etc/supervisor/conf.d/*.conf /opt/sws/sws_workers/config/supervisor/workers-staging-*.conf`

Any help ?

**Comment by mnaberez** [comment]
> command=NEW_RELIC_CONFIG_FILE=/opt/sws/sws_workers/newrelic.ini /usr/local/bin/newrelic-admin run-program /usr/bin/python /opt/sws/sws_workers/app.py post_signup

`supervisord` is not a shell, so it does not interpret the `NEW_RELIC_CONFIG_FILE=` as a shell would.  Use `environment=` to set the environment instead.

Please use the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users) for asking general questions about using Supervisor.  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by kracekumar** [comment]
Thanks @mnaberez.
