### ISSUE TITLE
What are allowed characters for program/group name?

### ISSUE THREAD

**Issue by kottenator** [Supervisor/supervisor#647]
Hi!

I didn't find it in docs - what are the allowed characters for program/group name?

For example can I name it like:
```ini
[program:my-app:profile]
[program:my-app::profile]
[program:my-app==profile]
[program:my-app profile]
[program:my-app.profile]
```
?

**Comment by mnaberez** [comment]
[Since version 3.0](https://github.com/Supervisor/supervisor/blob/master/CHANGES.txt#L185-L187), `supervisord` will [refuse to start](https://github.com/Supervisor/supervisor/blob/3.1.3/supervisor/datatypes.py#L16-L22) if a disallowed character is used in a program or group name.

**Comment by kottenator** [comment]
Ok, as I can see, `" "` and `":"` are forbidden. However, `"=="` and `"."` are allowed. Am I right?

**Comment by mnaberez** [comment]
Minimal `supervisord.conf`:

    [supervisord]
    logfile = /tmp/supervisord.log
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:ca==t]
    command = /bin/cat
    autostart = false
    
    [program:ca.t]
    command = /bin/cat
    autostart = false

Start `supervisord` in the foreground with that config:
    
    $ supervisord --version
    3.1.3
    $ supervisord -n -c /path/to/supervisord.conf

Start and stop processes:

    $ supervisorctl -c /path/to/supervisord.conf
    ca.t                             STOPPED   Not started
    ca==t                            STOPPED   Not started
    supervisor> start ca.t
    ca.t: started
    supervisor> stop ca.t
    ca.t: stopped
    supervisor> start ca==t
    ca==t: started
    supervisor> stop ca==t
    ca==t: stopped

**Comment by kottenator** [comment]
Sounds good for me! Thank you for the quick answer! ;)
