### ISSUE TITLE
Supervisorctl fails to discover globally installed controller plugin from within virtualenv

### ISSUE THREAD

**Issue by htch** [Supervisor/supervisor#652]
It seems like there are issues with discovering controller plugins from within virtualenv.

Steps to reproduce:

1. Install supervisor globally (i used apt-get)
2. Install a plugin globally with pip (eg mr.laforge: ```pip install mr.laforge```)
3. Activate controller plugin: add the following lines to supervisord.conf and restart supervisor

        [ctlplugin:laforge]
        supervisor.ctl_factory = mr.laforge.controllerplugin:make_laforge_controllerplugin

5. Make sure that the plugin works: ```supervisor kill``` will display usage screen
5. Create and activate virtualenv: ```mkvirtualenv testenv``` (provided that you have virtualenv and virtualenvwrapper installed)
6. Notice that supervisor fails to discover the controller plugin now:

        $ supervisorctl kill
        Error: mr.laforge.controllerplugin:make_laforge_controllerplugin cannot be resolved within
        [ctlplugin:laforge]
        For help, use /root/.virtualenvs/testenv/bin/supervisorctl -h

It looks like a bug with supervisor, unless it is expected behaviour for supervisorctl command to function in different ways in different virtual environments (but i doubt that it is so).

**Comment by mnaberez** [comment]
> It looks like a bug with supervisor, unless it is expected behaviour for supervisorctl command to function in different ways in different virtual environments (but i doubt that it is so).

Supervisor plugins are Python packages and Supervisor [uses setuptools to import them](https://github.com/Supervisor/supervisor/blob/3.1.3/supervisor/options.py#L383).  It can import whatever packages are installed in its environment.  

In your description above, the following probably happens also:

    # your virtualenv where supervisorctl can't import the plugin

    $ testenv/bin/python
    Python 2.7.10
    >>> import mr.laforge
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named mr.laforge
    >>>

There isn't anything we can do to affect this, either setuptools can import the package or it can't.  

The solution is to make the `mr.laforge` package available in the Python environment where Supervisor is installed (e.g. by installing it in your virtualenv with `testenv/bin/pip install mr.laforge`).

**Comment by htch** [comment]
Yeah i figured that much, it's just that no one expects supervisorctl to behave differently in different virtual environments (especially not if there are many of them on one machine), even if the tooling doesn't support this (i'm not sure if it cannot be circumvented though), it still should be a bug. That was my rationale anyway. This is a very minor issue either way though.
