### ISSUE TITLE
Feature: allow service name wildcards with supervisorctl commands and cli

### ISSUE THREAD

**Issue by zerthimon** [Supervisor/supervisor#655]
Currently, restarting services with similar name isn't possible:
```
supervisorctl stop service_\*
service_*: ERROR (no such process)
```
It would be nice if supervisor could handle wildcarded service names.
Supporting a regex expressions is preferred, but even a simple glob expression (fnmatch) would be enough for most users.

**Comment by mnaberez** [comment]
The [supervisor-wildcards](https://github.com/aleszoulek/supervisor-wildcards) plugin can be installed to add this functionality.
