### ISSUE TITLE
send INT signal to program and wait it stop

### ISSUE THREAD

**Issue by eromoe** [Supervisor/supervisor#658]
I'am using a crawler , which have a scheduler and start 3 fetcher and 5 processor one time.
In terminal, I press `Ctrl + C` would stop it elegent.
But when I use supervisor to manager the crawler ,`stop crawler ` stop it immediately which against my expect.`stopwaitsecs` seems not work too.
How could I achieve my purpose ?
my conf is like : 
```
[program:crawler]
.....
autostart=true
autorestart=true
; killasgroup=true
stopsignal=INT
stopwaitsecs=10
```

**Comment by mnaberez** [comment]
Please ask general questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
