### ISSUE TITLE
__init__.py not installed

### ISSUE THREAD

**Issue by draganHR** [Supervisor/supervisor#660]
`__init__.py` is missing after installing supervisor.
Issue occures when installing latest and old versions.

    # pip install supervisor
    ...
    # find  /usr/lib/python2.6/site-packages/supervisor -name __init__.py
    /usr/lib/python2.6/site-packages/supervisor/medusa/__init__.py
    /usr/lib/python2.6/site-packages/supervisor/tests/__init__.py

**Comment by mnaberez** [comment]
Supervisor 3.x is a [namespace package](https://github.com/Supervisor/supervisor/blob/3.1.3/setup.py#L81).  This was changed in 98c56768b83618d6c398a6927aaa3d976b217247 on the master branch.  Supervisor 4.0 will not be a namespace package.
