### ISSUE TITLE
Problem with start on boot

### ISSUE THREAD

**Issue by Suvitruf** [Supervisor/supervisor#679]
I have `/etc/init.d/supervisord` (from here https://github.com/Supervisor/initscripts) And it works...but only sometimes =/

Sometimes after server reboot supervisord doesn't start properly. And when I'm trying to get status, got `unix:///var/run/supervisor.sock`.

So, when this problem occurred only if I start it manually with script like this:

    sudo service supervisord  stop &
    sleep 5 &&\
    sudo service supervisord  start &

It restarted without problem.

We have a lot server, and they should fast init after reboot, cause we are using them for game backend. How can I solve this problem?

P.S. Ubuntu 14.04

**Comment by mnaberez** [comment]
Please ask this question on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by tersmitten** [comment]
We have a similar problem on Ubuntu 12.04
