### ISSUE TITLE
restart limit 

### ISSUE THREAD

**Issue by karthiklml** [Supervisor/supervisor#680]
I am using supervisord to ensure my app related daemons. I like to limit the supervisor restart attempts . 
example . if my daemon get failed . supervisor need to restart only 5 times. 
Could any one share the config settings for this requirements .

Thanks .

**Comment by mnaberez** [comment]
Please ask this question on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
