### ISSUE TITLE
Don't pipe to stdin

### ISSUE THREAD

**Issue by mholt** [Supervisor/supervisor#686]
Is there a way to disable piping to stdin of a process?

If not, I would like to request that feature. Some programs act on the stdin pipe, if there is one, and will wait for data to be sent through the pipe and then closed before unblocking.

Basically, opening a pipe is a deliberate action that should only happen if the user requires it. Without the ability to toggle the pipe, supervisord becomes unusable because it breaks such programs.

**Comment by mnaberez** [comment]
> Is there a way to disable piping to stdin of a process?

There's not a config file option to do this.  You should be able to do it with something like this:

    bash -c 'exec /bin/cat 0<&-'

Replace `/bin/cat` with your program.  The `0<&-` closes stdin.  The `exec` replaces the `bash` process with your program so it runs directly under `supervisord`.

Minimal `supervisord.conf`:

    [supervisord]
    logfile = /tmp/supervisord.log
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:cat]
    command = /bin/bash -c 'exec /bin/cat 0<&-'
    startsecs = 0
    autorestart = false

Start `supervisord` in the foreground with that config:

    supervisord -c /path/to/supervisord.conf -n

Run `supervisorctl` to see that it's closed:

    $ supervisorctl -c /path/to/supervisord.conf status
    cat                              EXITED    Nov 10 02:00 PM
    $ supervisorctl -c /path/to/supervisord.conf tail cat stderr
    cat: stdin: Bad file descriptor

> If not, I would like to request that feature. Some programs act on the stdin pipe, if there is one, and will wait for data to be sent through the pipe and then closed before unblocking.
>
> If not, I would like to request that feature. Some programs act on the stdin pipe, if there is one, and will wait for data to be sent through the pipe and then closed before unblocking.

It's interesting that this hasn't come up before, but people may just be doing something like the above.  A config file option for this would probably be good.

**Comment by mholt** [comment]
Thanks for the answer - I didn't know that trick!

Also thanks for supervisor - makes most things easier for sure. :+1:
