### ISSUE TITLE
[Errno 13] Permission Denied when do RPC call from django app under apache

### ISSUE THREAD

**Issue by denisvolokh** [Supervisor/supervisor#687]
Hi, 

I have this problem when I am not able to call any rpc function from django app under apache.

But if I do from simple script everything is working.

`server = xmlrpclib.Server("http://192.168.23.32:9001/RPC2")` 
`processes = server.supervisor.getAllProcessInfo()`

Where should I look?

Thanks.

**Comment by denisvolokh** [comment]
I noticed that I can connect to server but have error when call function, for example:
`server.supervisor.getAllProcessInfo()`

and the error is [Errno 13] Permission denied

**Comment by mnaberez** [comment]
> I noticed that I can connect to server but have error when call function

Instantiating `xmlrpclib.ServerProxy` doesn't connect:

    >>> import xmlrpclib
    >>> xmlrpclib.ServerProxy('http://badservername')
    >>>

Notice there is no error.  It will only try to connect when you make a call.

> `server.supervisor.getAllProcessInfo()`
> and the error is [Errno 13] Permission denied

I can see how this could happen if you were using a domain socket.  The solution there be to check the permissions on the socket file in `[unix_http_server]`.  I haven't seen this happen for `http`, but in either case the request is being blocked by the operating system and isn't reaching `supervisord`.
