### ISSUE TITLE
Is  supervisor not compatible with python3 ?

### ISSUE THREAD

**Issue by codepython** [Supervisor/supervisor#689]
it seems not work fine with python3

**Comment by mnaberez** [comment]
[README.rst](https://github.com/Supervisor/supervisor/blob/362ede268a7daf9745316a310f9213e4c63982a6/README.rst):
> **Supervisor does not work on Python 3.**  This is the master branch,
> has work-in-progress support for Python 3.  Supervisor is very likely
> to crash, cause subprocesses to hang, or otherwise behave unexpectedly
> when run on Python 3.  See [issues running Supervisor on Python 3](https://github.com/Supervisor/supervisor/labels/python%203>).
> It may also have regressions on Python 2 as a result of attempts to
> add Python 3 support.  Help from developers with Python 3 porting
> experience is is needed.  **Do not use this branch on any production system.**

**Comment by troygrosfield** [comment]
@mnaberez, I've been using supervisor (master, 4.x) in prod with python 3 for a few months now without issues.  What's the plan for releasing 4.0?  Is there a timetable set?

**Comment by mnaberez** [comment]
Supervisor has some pretty significant issues running on Python 3 that are tagged [python3](https://github.com/Supervisor/supervisor/labels/python%203).  All of those are blocking a release.  I strongly suggest you revert to a stable 3.x release until these are resolved.  One of the more significant issues running on Python 3 are encoding problems.  If a process happens to emit something that is not valid UTF-8, it will crash supervisord immediately.

**Comment by troygrosfield** [comment]
Can't revert to stable 3.x as I'm running python 3.  Any idea on a timeline for when 4.0 will be released?  You guys have a great piece of software and python 3 has been out for quite some time now.

**Comment by mnaberez** [comment]
We'll probably make a release shortly after the issues tagged [python 3](https://github.com/Supervisor/supervisor/labels/python%203) have been resolved.

**Comment by warunakithruwan** [comment]
you can use supervisor dev version for python3. this is not a stable version. I think stable version will be released next few months. 
`$ pip install git+https://github.com/Supervisor/supervisor.git`
try this method
