### ISSUE TITLE
CRIT Set uid to user in logs

### ISSUE THREAD

**Issue by ngton** [Supervisor/supervisor#693]
This shouldn't be a CRIT level message, it's INFO at most.

As per the documentation:

user

If supervisord is run as the root user, switch users to this UNIX user account before doing any meaningful processing. This value has no effect if supervisord is not run as root.

A CRIT message should not be generated for documented functionality that is working as designed.

**Comment by mnaberez** [comment]
I think logging this at the `INFO` level would be fine.  `Set uid to 502` is a success message and similar success messages like increasing rlimits are logged at `INFO` already.

**Comment by lxlang** [comment]
:+1:

**Comment by enumag** [comment]
How can I install supervisor 3.3.4 on Alpine (there is a package only for 3.3.3)? Or how can I suppress this CRIT error until a newer package is available?
