### ISSUE TITLE
Change misleading log message "CRIT Can't drop privilege as nonroot user"

### ISSUE THREAD

**Issue by ngton** [Supervisor/supervisor#697]
This log message is unnecessarily incomprehensible and misleading to a user. It should be changed to explain the real issue and tell the user how to resolve the  issue.

As discussed here:

https://github.com/Supervisor/supervisor/issues/695#issuecomment-157989942

This log message should be changed to say something like "user parameter invalid as non-root user, ignoring. Please remove from configuration file". 

Changing the message would allow a user to easily understand that this isn't actually a CRITICAL level problem, functionality is unaffected and tell them how to resolve it.

This also makes it consistent with the message (Which is actually a genuine CRIT) you get when you try to run as root without the user parameter:

"CRIT Supervisor running as root (no user in config file)"

**Comment by mnaberez** [comment]
Please stop opening issues for this.  I'm not willing to keep going around and around with you on this.  In the near 10 years that this message has existed, you are the only one who has found it to be "unnecessarily incomprehensible and misleading".  You set `user=` to drop privileges, it couldn't drop privileges it, and it said "can't drop privileges".  Let's move on, please.
