### ISSUE TITLE
Please move images (ui) from /usr/lib to /usr/share

### ISSUE THREAD

**Issue by oorestisime** [Supervisor/supervisor#699]
Hello,

Supervisor installs gif files (from the ui) in /usr/lib. In /usr/lib normally there are libraries essential for the binaries in /bin/ and /sbin/ and according to the Filesystem Hierarchy Standard, architecture-independent files need to be placed within /usr/share instead. Plus this is generating some lintian (tool for automatically checking bugs or policy violations) warnings for the package in Debian https://lintian.debian.org/maintainer/orestis@oioannou.com.html#supervisor . 

Might be better to put all the ui components in /usr/share?

Thanks,

Orestis

**Comment by mnaberez** [comment]
The Supervisor project itself only publishes Python packages to [PyPI](https://pypi.python.org/pypi/supervisor). Our packages are installed with `pip` or `easy_install`.  Our packages don't have the behavior you described (a Python package installer will store all the Supervisor files in the `site-packages` directory of the Python installation).

The distribution packages (`deb`, `rpm`) are created by others that aren't involved with the project.  Please report this issue to the maintainers of the package that you are installing.
