### ISSUE TITLE
Unused test?

### ISSUE THREAD

**Issue by JensRantil** [Supervisor/supervisor#70]
I just ran a coverage analysis of the test cases and noted that `tests/test_process.py: SubprocessTests. dont_test_spawn_and_kill` is never executed because it does not follow the correct `UnitTest` naming convention. Removing prefix `dont_` makes the test fail. Should it be removed?

**Comment by NetWilliam** [comment]
There is a race condition check in the dont_test_spawn_and_kill and we don't test here for why? I've met a problem probably has something to do with the race condition of process state. @mnaberez

**Comment by mnaberez** [comment]
> There is a race condition check in the dont_test_spawn_and_kill and we don't test here for why?

That comment in `dont_test_spawn_and_kill` means a possible race condition in the test itself, not `supervisord`.  The test isn't run normally because it spawns actual subprocesses.
