### ISSUE TITLE
how to make a proper log config to relocate log dir and control log file size?

### ISSUE THREAD

**Issue by eromoe** [Supervisor/supervisor#702]
I have seen http://supervisord.org/configuration.html#program-x-section-settings
says:
```
It is not possible for two processes to share a single log file (stdout_logfile) 
when rotation (stdout_logfile_maxbytes) is enabled. 
This will result in the file being corrupted.
```
So, a single log file is not allowed.

But I need relocate the logfile directory in `/mnt/apps/logs/`.I haven‘t seen any other way to relocate log file directory without `stdout_logfile` and `stderr_logfile`.

My purpose is simple:
1.relocate all log files to  `/mnt/apps/logs/`.
2.I don't mind log file is separated by `numprocs` or not.
3.But need control the log file size and buckup size.

If i set 
`stderr_logfile_maxbytes=0`
`stderr_logfile_maxbytes=0`

After the file grow big, delete the log file manually, supervisor would not log anymoe

How do I alter my current config below for my purpose? 
```
[program:result_worker]
directory=/mnt/apps/udbswp/
process_name=%(program_name)s_%(process_num)02d
numprocs=20
command=xxxx   result_worker
stdout_logfile=/mnt/apps/logs/result_worker.log
stderr_logfile=/mnt/apps/logs/result_worker.log
stdout_logfile_backups=2
stderr_logfile_backups=2
autostart=true
autorestart=true
redirect_stderr=true
```

**Comment by mnaberez** [comment]
> If i set
stderr_logfile_maxbytes=0
stderr_logfile_maxbytes=0
>
> After the file grow big, delete the log file manually, supervisor would not log anymoe

Sending signal `SIGUSR2` to the `supervisord` process will cause it to reopen its main log file and its child process log files ([reference](http://supervisord.org/running.html#signal-handlers)).

**Comment by eromoe** [comment]
@mnaberez 
delete log file and signal `SIGUSR2` need  create a crontab job.
 Anyway without create a crontab job ?
