### ISSUE TITLE
Install 3.2.0 as service on Ubuntu

### ISSUE THREAD

**Issue by Daemon22** [Supervisor/supervisor#705]
How can I install the latest version 3.2.0 as service on Ubuntu machine?
(When I do apt-get install supervisor I get 3.0b2 installed)

**Comment by tersmitten** [comment]
You can install it using `pip` but that does not include an init script. You can get one from [this repo](https://github.com/Supervisor/initscripts).

**Comment by tersmitten** [comment]
If you're an Ansible user you can also [use this role](https://github.com/Oefenweb/ansible-supervisor).

**Comment by Daemon22** [comment]
I will try that, thanks

**Comment by mnaberez** [comment]
I'm going to close this issue since the question was answered.  For further help, please join the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).
