### ISSUE TITLE
[Debian] Systemd loading configuration twice (x-post)

### ISSUE THREAD

**Issue by cricket007** [Supervisor/supervisor#708]
I'm not sure the process around here, but I opened an issue in this repository https://github.com/Supervisor/initscripts/issues/35. 

This repo's issue tracker seems more active, so I'm willing to close that and migrate here, if necessary.

**Comment by mnaberez** [comment]
The user contributed init scripts are not part of the main Supervisor project.  Feel free to open issues in that repository but please do not open issues for init scripts in this repository.
