### ISSUE TITLE
Elementtree vs. xml.etree.Elementtree in stdlib?

### ISSUE THREAD

**Issue by schplat** [Supervisor/supervisor#710]
From what I can tell, since Python 2.5 Elementtree has been available in the stdlib.  As such, pypi is no longer hosting links to the project, so, a straight pip install elementtree no longer works, rather you have to do pip install elementtree -i http://effbot.org/downloads#elementtree.  From an automation standpoint, it's a bit annoying.

So the question becomes, can supervisor easily use the stdlib implementation of elementtree?  If so, how.  If not, how large of an undertaking is it?

For RHEL 5 based systems, that run pre-2.5, there could still be a fallback to the downloaded elementtree, it should essentially come down to a try/except/finally block.

At this point, Python 2.5 and earlier is pretty much unsupported/use at your own risk.  There is still a large footprint of RHEL6 machines out there, so 2.6 has a fairly large foorprint as well., but outside of that most everyone should be on 2.7/3.X

**Comment by schplat** [comment]
n/m, I went digging, and found it's already doing this.  So it's an issue with something else in our automation doing this.

Apologies.

**Comment by mnaberez** [comment]
> So the question becomes, can supervisor easily use the stdlib implementation of elementtree? 

On Python 2.5 or later, Supervisor should be able to use the stdlib implementation since 57d4fd597b236e4bb1054afaa86156be0b5b7d8a.  This change was included in Supervisor 3.0a7 (released in May 2005).
