### ISSUE TITLE
Strange chdir error when running scripts in supervisor

### ISSUE THREAD

**Issue by tianshuo** [Supervisor/supervisor#711]
I'm using `node-github-hook` with a `bash` script file on `ubuntu`.

    #!/bin/bash
    cd /server
    pwd >&2
    whoami >&2
    git pull readonly master >&2
    gitbook install /server >&2
    gitbook build /server /var/www/server >&2

Somehow `pwd` is the directory and `whoami` is the user, but when running `gitbook install` it gives a error: `Error: EACCES: permission denied, mkdir '/root/.gitbook'`
So somehow when running this script, the script is not changed into the directory. This is a strange situation that only happens when using `supervisor`. The supervisor script is:

    [program:githubhook]
    command = githubhook --verbose --port=8888 --secret=XXX push:XXXX /usr/local/bin/makedocs.sh
    user=push
    directory = /server

**Comment by tianshuo** [comment]
Fixed by adding `HOME=/home/push/` to supervisor. Maybe supervisor could do this automatically?

**Comment by mnaberez** [comment]
Please see [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment) in the documentation:

> No shell is executed by supervisord when it runs a subprocess, so environment variables such as USER, PATH, HOME, SHELL, LOGNAME, etc. are not changed from their defaults or otherwise reassigned. This is particularly important to note when you are running a program from a supervisord run as root with a user= stanza in the configuration. Unlike cron, supervisord does not attempt to divine and override “fundamental” environment variables like USER, PATH, HOME, and LOGNAME when it performs a setuid to the user defined within the user= program config option. If you need to set environment variables for a particular program that might otherwise be set by a shell invocation for a particular user, you must do it explicitly within the environment= program config option. An example of setting these environment variables is as below.

> [program:apache2]
> command=/home/chrism/bin/httpd -c "ErrorLog /dev/stdout" -DFOREGROUND
> user=chrism
> environment=HOME="/home/chrism",USER="chrism"
