### ISSUE TITLE
question about timestamping

### ISSUE THREAD

**Issue by r2evans** [Supervisor/supervisor#713]
I'm relatively new to supervisor, so this isn't as much an issue as it is a question of unintended consequences.

The desired behavior is that some logs have a timestamp automatically prepended to each line of output. To implement this for stdout is trivial in a shell script, but doing the same for stderr simultaneously is a little problematic. StackOverflow has [some](http://stackoverflow.com/questions/9112979/pipe-stdout-and-stderr-to-two-different-processes-in-shell-script) [posts](http://stackoverflow.com/questions/17261296/write-to-file-descriptor-3-without-writing-to-disk) discussing bash and simultaneous redirection, but none of them (untouched or with slight adjustments) worked for me, occasionally resulting in abandoned processes.

Other scripting languages likely have significantly less-complex methodologies for doing this, but it occurred to me that this feature can go into the process management as well as an optional filter for each process. I can (somewhat) see the argument that this could/should be the client program's responsibility. But, then again, if I have python scripts, bash scripts, C programs, etc, I have to potentially reimplement it (differently) in each program. It seems to me that "implement once, reuse many times" is applicable here, where it doesn't matter if the client supports it, the `supervisord` will optionally augment.

I came across [this email](https://www.mail-archive.com/supervisor-users@lists.supervisord.org/msg01163.html) to the Supervisor-users email list just over two years ago, and have seen no replies or related discussion since. There was also [another email](https://www.mail-archive.com/supervisor-users%40lists.supervisord.org/msg00633.html) 5 years ago with a similar intent, but quickly squashed as "not interested".

I applied Dameon's patch, and with the exception of one typo (replace `process.config` with `config`), it appears to be working fine for those commands I've identified with `timestamp=true`. Besides the maintainers' preference on this issue (I'm not discarding it), are there second-order effects that making this change will have on my supervisor's behavior? (I've seen none so far.)

I'm using supervisor-3.0b2-1 on ubuntu-14.04.3.

**Comment by mnaberez** [comment]
> I applied Dameon's patch, and with the exception of one typo (replace process.config with config), it appears to be working fine for those commands I've identified with timestamp=true. Besides the maintainers' preference on this issue (I'm not discarding it), are there second-order effects that making this change will have on my supervisor's behavior? (I've seen none so far.)
>
> I'm using supervisor-3.0b2-1 on ubuntu-14.04.3.

This is a pretty old version of Supervisor (3.0b2 was released 2013-05-28) and nobody currently involved with the project has used the patch that you have applied.  I don't think we can answer this question, sorry.  You might try asking the patch author or the mailing list.
