### ISSUE TITLE
stopwaitsecs not working

### ISSUE THREAD

**Issue by papiveron** [Supervisor/supervisor#721]
Hi,

I'm using supervisor to run and monitor a ruby process running under **sidekiq** framework.

I want to run several worker processes and can't use the **numprocs** directive because it doesn't fit my need as I don't just run a command, but a full command line with some configuration.

Then I write a bash script to wrap my workers launch and execution, and set this wrapper under **supervisor**.
Here is my settings.
Supervisor version :
```
admin@bastion-prod:~ $ apt-cache policy supervisor 
supervisor:
  Installed: 3.0a8-1.1+deb7u1
  Candidate: 3.0a8-1.1+deb7u1
  Version table:
     3.0r1-1~bpo70+1 0
        100 http://http.debian.net/debian/ wheezy-backports/main amd64 Packages
 *** 3.0a8-1.1+deb7u1 0
        500 http://http.debian.net/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
```

The wrapper script:
```
admin@bastion-prod:~ $ cat home/admin/workers-scripts/worker-api.sh
#!/bin/bash
CMD=$1
RAILS_DIR='/var/tct-api'
PIDDIR=$RAILS_DIR/tmp/pids
PIDFILE=$PIDDIR/sidekiq.pid
NUMPROCS=4
TIMEOUT=60
export RAILS_ENV=production
source /usr/local/rvm/scripts/rvm
mkdir -p $PIDDIR

cd $RAILS_DIR
trap stop_function  SIGHUP SIGINT SIGTERM SIGQUIT SIGKILL

start_function(){
 # LOGFILE=$RAILS_DIR/log/sidekiq.log

  echo "Cleaning up all running sidekiq processes before starting new ones..." >> "/tmp/start_sidekiq"
  if [ ! -d $(dirname $PIDFILE) ]; then
    echo "It seems like the sidekiq pids file does not exist, switching to /tmp"
    PIDFILE="/tmp/sidekiq.pid"
  fi
  pids=$(ps -ef | grep sidekiq | grep busy | grep -v grep | awk '{print $2}')
  for pid in $pids
  do
    echo $pid > $PIDFILE
    bundle exec sidekiqctl stop $PIDFILE
  done

  echo "Starting $NUMPROCS sidekiq process(es) ..."
  for i in `seq 1 $NUMPROCS`
  do
    echo "Starting sidekiq process number $i ..."
    #bundle exec sidekiq -L $LOGFILE -C config/sidekiq.yml &
    bundle exec sidekiq -C config/sidekiq.yml -i $i &
  done
}

stop_function(){
  echo "Stopping all sidekiq processes ..." >> "/tmp/stop_sidekiq"
  if [ ! -d $(dirname $PIDFILE) ]; then
    echo "It seems like the sidekiq pids file does not exist, switching to /tmp" /"tmp/stop_sidekiq"
    PIDFILE="/tmp/sidekiq.pid"
  fi
  echo "What happened here?? ..." >> "/tmp/stop_sidekiq"
  #pids=$(/bin/ps -ef | grep "sidekiq" | grep busy | grep -v grep | awk '{print $2}')
  pids=$(ps -ef | grep sidekiq | grep busy | grep -v grep | awk '{print $2}')
  #pids=$(/bin/ps -ef | grep "sidekiq" | grep "busy" | awk '{print $2}')
  echo "pids : $pids ..." >> "/tmp/stop_sidekiq"
  for pid in $pids
  do
    echo "Killing process $pid ..." >> "/tmp/stop_sidekiq"
    echo $pid > $PIDFILE
    bundle exec sidekiqctl stop $PIDFILE
    echo "Process $pid stopped ..." >> "/tmp/stop_sidekiq"
 done

  exit
}

case "$CMD" in

  start)
    start_function

    ;;

  stop)

    stop_function

    ;;

  restart)

    stop_function && start_function;

    ;;

  *)

    #echo $"Usage: $0 {start|stop|restart} given cmd : $@"; exit
    echo $"Usage: $0 {start|stop|restart}"; exit

esac

#An inifinite loop to wait for supervisord signal to terminate sidekiq process gracefully

while true
do
        echo "Wainting for supervisord signal to stop.."
        sleep 10
done
(END)
```
The debugging comments in the code is for troubleshooting, please don't mention it. But I found the issue which is that worker processes fork themselves and create child process to consume works, and supervisor doesn't wait for all process to stop. After **15 seconds** it kills the wrapper process which is the parent of worker process, leaving remaining workers processes orphan and their parent becomes the **init** process. When this happen I have to kill remaining processes by hand, by running the wrapper directly in the command line using the **stop** switch..
Starting process always work fine, but restarting or stopping them don't work, the supervisor restart creates additional process to remaining ones.
I've tried the same mechanism in a preproduction environment where workers has less work to do before leave and it works perfectly.

I then add the **stopwaitsecs** parameter in my supervisor configuration like this:
```
[program:worker-api]
command=/home/admin/workers-scripts/worker-api.sh "start"
stdout_logfile=/var/log/tct/worker-api/worker-api.out
stdout_logfile_backups=15
stderr_logfile=/var/log/tct/worker-api/worker-api.err
stderr_logfile_backups=15
topwaitsecs=300
```
But it still doesn't work and supervisor don't wait more than **15 seconds** for the wrapper to stop gracefully.
And whent I use the wraper stop switch in the cli like this :
```
admin@bastion-prod:~ $ /home/admin/workers-scripts/worker-api.sh stop
```
it works.
Can someone please help me to solve the issue? The supervisor documentation says this :

> stopwaitsecs

    The number of seconds to wait for the OS to return a SIGCHILD to supervisord after the program has been sent a stopsignal. If this number of seconds elapses before supervisord receives a SIGCHILD from the process, supervisord will attempt to kill it with a final SIGKILL.

    Default: 10

    Required: No.

    Introduced: 3.0

So for me I have the good version of the software. Do you have ever encounter this issue and please what's the best way to manage that?

Thanks.
Regards.

**Comment by fuhrysteve** [comment]
Sounds like a few issues here:

1. check out the documentation for `killasgroup` and `stopasgroup`
http://supervisord.org/configuration.html#program-x-section-settings

2. I think the supervisor documentation for `stopwaitsecs` is inaccurate. It says that it says SIGINT immediately then SIGKILL after it waits, however I've found that in order to get that behavior, I need to add:

```
stopsignal=INT
```

**Comment by mnaberez** [comment]
> I think the supervisor documentation for stopwaitsecs is inaccurate. It says that it says SIGINT immediately then SIGKILL after it waits, 

The [documentation](http://supervisord.org/configuration.html) for `stopwaitsecs` does not say this.  It says that supervisord will first send `stopsignal`.  It does not mention `SIGINT`.

> however I've found that in order to get that behavior, I need to add:
>
> stopsignal=INT

The documentation for `stopsignal` says that its default value is `TERM`.  If you want supervisord to send `SIGINT` instead, then you have to set `stopsignal=INT` as you are doing.

**Comment by fuhrysteve** [comment]
Thanks for the correction @mnaberez - I looked in my comments and my memory is off. It is actually celery (async task processor) whose docs are wrong about signal handling.

As it happens, here's what I had written down about that issue:
https://groups.google.com/forum/#!topic/celery-users/t8g5KvIvQZ8
https://github.com/celery/celery/issues/2700

In any case, it sounds like @papiveron may be interested in `stopasgroup` & `killasgroup`

**Comment by mnaberez** [comment]
> Look at the first line of my wrapper script
>
> trap stop_function  SIGHUP SIGINT SIGTERM SIGQUIT SIGKILL
>
> I catch all signals that supervisord can send.

This may be the problem.  You can't trap `SIGKILL`.  If supervisord sends `SIGKILL` to your process, the kernel will terminate it immediately.  Your script won't have any opportunity to clean up its children.

> Now why should I use stopasgroup or/and killasgroup ?

You can't because [you are using 3.0a8](https://github.com/Supervisor/supervisor/issues/721#issue-133966230).  This version of Supervisor is six years old and does not have these options (see the [changelog](http://supervisord.org/changes.html)).  There have been many improvements and fixes since 3.0a8.  I would recommend upgrading to a newer version.

> So for me the stopwaitsecs is not working.

There's not enough information in this ticket to tell what effect `stopwaitsecs` is having.  Look at supervisord's main log file.  A message will be written to the log when supervisord sends a signal to one of its subprocesses.  You can see which signals are being sent and when.

**Comment by papiveron** [comment]
Yes @mnaberez ,

I know the **SIGKILL** signal can't be catch, but it doesn't matter here, I just put it in the list but I also know supervisord can't send a **SIGKILL** before the **stopwaitsecs** time is elapsed.

I will have a look at the log file and make more accurate tests.

Regards.

**Comment by mnaberez** [comment]
Python program `ignore_sigterm.py` to ignore the `SIGTERM` signal:

    import signal
    import time
    
    signal.signal(signal.SIGTERM, signal.SIG_IGN)
    
    while True:
       time.sleep(1)

Minimal `supervisord.conf`:

    [supervisord]
    logfile = /tmp/supervisord.log
    loglevel = debug
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:ignore_sigterm]
    command = python /path/to/ignore_sigterm.py
    autostart = true
    autorestart = false
    startsecs = 0
    stopsignal = TERM
    stopwaitsecs = 10

Run `supervisord` in the foreground with that config:

    $ supervisord --version
    3.2.1
    $ supervisord -n -c /path/to/supervisord.conf
    2016-02-29 11:17:40,183 INFO RPC interface 'supervisor' initialized
    2016-02-29 11:17:40,183 CRIT Server 'inet_http_server' running without any HTTP authentication checking
    2016-02-29 11:17:40,184 INFO supervisord started with pid 50538
    2016-02-29 11:17:41,191 INFO spawned: 'ignore_sigterm' with pid 50541
    2016-02-29 11:17:42,195 INFO success: ignore_sigterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Stop the `ignore_sigterm` process with `supervisorctl`:

    $ supervisorctl -c /path/to/supervisord.conf stop ignore_sigterm

Log output from `supervisord`:

    2016-02-29 11:17:46,356 DEBG killing ignore_sigterm (pid 50541) with signal SIGTERM
    2016-02-29 11:17:46,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:48,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:50,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:52,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:54,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:56,356 WARN killing 'ignore_sigterm' (50541) with SIGKILL
    2016-02-29 11:17:56,356 DEBG killing ignore_sigterm (pid 50541) with signal SIGKILL
    2016-02-29 11:17:56,356 INFO waiting for ignore_sigterm to stop
    2016-02-29 11:17:56,357 DEBG fd 12 closed, stopped monitoring <POutputDispatcher at 4326163736 for <Subprocess at 4325418576 with name ignore_sigterm in state STOPPING> (stderr)>
    2016-02-29 11:17:56,357 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 4326163088 for <Subprocess at 4325418576 with name ignore_sigterm in state STOPPING> (stdout)>
    2016-02-29 11:17:56,357 INFO stopped: ignore_sigterm (terminated by SIGKILL)
    2016-02-29 11:17:56,357 DEBG received SIGCHLD indicating a child quit

Above, we can see that `supervisord` sent `SIGTERM`, then waited `stopwaitsecs` of 10 seconds, then sent `SIGKILL`.

Since the above works and I can't see anything in this issue to indicate a problem with `stopwaitsecs`, I am going to close this issue.

**Comment by papiveron** [comment]
Hi,

The problem is solved, and effectively, the **stopwaitsecs** works. As you can see in my post above, I forgot the **"s"** at the beginning of the parameter in my configuration.

Thank for your time.
