### ISSUE TITLE
Web Interface: Error response code 500 internal server error.

### ISSUE THREAD

**Issue by ergatides** [Supervisor/supervisor#728]
Hello,

I believe that I have checked all the existing issues related to the error and my issue appears to be different.

I have installed 3.2.1 via pip / easy_install on CentOS.
Everything is working fine apart from the web interface.

In the log, I get:
`Server Error: <type 'exceptions.AttributeError'>, 'NoneType' object has no attribute 'startswith': file: /usr/lib/python2.6/site-packages/supervisor/http.py line: 897`

As python is not my forte any help would be appreciated.
The web interface is prompting me for user/pass before I get this error.

Thank you.

**Comment by ergatides** [comment]
False alarm... config typo... apologies.

Thanks!

**Comment by mnaberez** [comment]
> False alarm... config typo... apologies.

@ergatides What was the config typo that caused this?  If we can reproduce this, we might be able to give a better error for next time.  It [looks like](https://github.com/Supervisor/supervisor/blob/3.2.1/supervisor/http.py#L897) it might be related to the password.

**Comment by ergatides** [comment]
@mnaberez Yes, of course, sorry... this can be improved.

When I was editing /etc/supervisord.conf, just before exiting vim I mistakenly typed an extra character in the password key. For example:

```
username=user
;password=123
passyword=abcdef
```
I would have thought that this would equate to a blank password being expected but obviously in the presence of a correct username definition (if self.dict.has_key(username)), a password definition is assumed to also be defined.

Maybe checking for both and a more meaningful error in the log in the absence of either would suffice to debug the problem easier.

Thank you.
