### ISSUE TITLE
gracefull restart for a group

### ISSUE THREAD

**Issue by freeseacher** [Supervisor/supervisor#731]
Hi! 
Is it possible to add command for gracefull restart. i have several daemons written in python and django and sometimes i need to restart my app for applying new code. 
It will be great iа ш can restart them one by one. somethng like
```restart web:* gracefull ```
witch will kill them one by one. so i will allways have at least one still working

tnx!

**Comment by freeseacher** [comment]
any news ?

**Comment by mnaberez** [comment]
Duplicate of #53.
