### ISSUE TITLE
Supervisorctl signal doesn't send signal to stopping processes

### ISSUE THREAD

**Issue by kefuzhao** [Supervisor/supervisor#734]
Our processes listen to different signal to implement soft/hard kill. Firstly, a soft kill will do "supervisorctl stop all" to make the process in stopping state. Then, we can choose to hard kill the processes at any given time by sending them SIGKILL signals. 

The issue is that supervisorctl signal only sends signals to the process that's RUNNING. When a signal is in STOPPING state, there is no other way to stop it forcibly other than waiting the stopwaitsec out. It would be great that if supervisorctl signal can extend its target to processes with STOPPING state.

**Comment by mikeyg123** [comment]
+1 this.  During core hours we need processes to stop gracefully which may include several minutes to finish up the current task.
Outside core hours we need the option to bring down processes quickly for upgrade etc.  Sending a sigkill doesn't work as supervisor restarts the process and requesting stop followed by a sigkill results in the "NOT_RUNNING" failure and doesn't actually signal the process.

This PR adds a set of SIGNALLABLE_STATES used to decide if a signal can be sent
https://github.com/Supervisor/supervisor/pull/854

**Comment by mnaberez** [comment]
Fixed in b59f9f15bd9332b2cfebd0a8b6ebf68aedcb25aa.
