### ISSUE TITLE
unix:///var/run/supervisor.sock no such file on Ubuntu 16.04

### ISSUE THREAD

**Issue by khotkevych** [Supervisor/supervisor#735]
Supervisor is not starting on the new version of Ubuntu:

```
$ sudo apt-get install supervisor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  supervisor-doc
The following NEW packages will be installed:
  supervisor
0 upgraded, 1 newly installed, 0 to remove and 203 not upgraded.
Need to get 0 B/252 kB of archives.
After this operation, 1,398 kB of additional disk space will be used.
Selecting previously unselected package supervisor.
(Reading database ... 171645 files and directories currently installed.)
Preparing to unpack .../supervisor_3.2.0-2_all.deb ...
Unpacking supervisor (3.2.0-2) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-3ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up supervisor (3.2.0-2) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-3ubuntu1) ...
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Xenial Xerus (development branch)
Release:	16.04
Codename:	xenial
```

```
$ supervisord -v
3.2.0
```

```
$ apt-cache policy python
python:
  Installed: 2.7.11-1
  Candidate: 2.7.11-1
  Version table:
 *** 2.7.11-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
$ supervisorctl restart
unix:///var/run/supervisor.sock no such file
```

**Comment by mnaberez** [comment]
> Supervisor is not starting on the new version of Ubuntu:
>
>    $ sudo apt-get install supervisor

Please report this issue to the maintainers of the package that you are installing.

The Supervisor project only creates the Python packages that are published to [PyPI](https://pypi.python.org/pypi/supervisor).  The various distribution packages like the one you are installing are created by others that aren't involved with the project.  That installation process was created by them and only they can fix it.

**Comment by sgornick** [comment]
This was a great help to me:

https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

> To tell systemd to start services automatically at boot, you must enable them.
> 
> To start a service at boot, use the enable command:
> 
> sudo systemctl enable application.service


`$ sudo systemctl enable supervisor.service`

**Comment by tersmitten** [comment]
What about `/run`?

**Comment by itservices-tanger** [comment]
apt-get install upstart-sysv 
this will reconfigure your newly installed ubuntu so it becomes the ubuntu you are used to.

**Comment by xolox** [comment]
Sorry for adding more noise to a bug report that should never have made it upstream, however:

> Please report this issue to the maintainers of the package that you are installing.

I was bitten by this packaging bug in Ubuntu a few days ago and was astonished to find that this issue was never reported to the package maintainers, even though Ubuntu 16.04 was released quite a while ago and this breaks backwards compatibility and expected behavior. This is why I decided to report this issue to the package maintainers in [bug 1594740](https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740).

I'm not so sure that this will be fixed in Ubuntu 16.04 but at least now there's a central place to gather complaints and document workarounds. If anyone was bitten by this issue, consider voicing your concern in [bug 1594740](https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740) to convince the package maintainers to fix this issue. Thanks!

**Comment by kamihouse** [comment]
On Ubuntu 16+ it seems to been caused by the switch to `systemd`, we can do this workaround:

```
# Make sure Supervisor comes up after a reboot.
sudo systemctl enable supervisor

# Bring Supervisor up right now.
sudo systemctl start supervisor
```

**Comment by xolox** [comment]
Yesterday a fix for this issue [was released](https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740/comments/31) to [xenial-updates](http://packages.ubuntu.com/xenial-updates/supervisor) as a result of [bug 1594740](https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740) so new installations of Supervisor on Ubuntu 16.04 should no longer run into this issue!

**Comment by Freid001** [comment]
@xolox are you able to help me with this issue - http://stackoverflow.com/questions/42998383/supervisor-start-all-not-working

Thanks

**Comment by shlugood** [comment]
I meet the proble on Centos7, anyone know how to fix it? 
error msg: unix:///var/run/supervisor/supervisor.sock no such file

**Comment by AlexRiina** [comment]
I'm not sure this was the original issue, but I ended up here because I had a leftover /etc/init.d/supervisor which was silently exiting when testing to see if there was a `$DAEMON` to start. I forgot that I was mostly using the pip installed version. After I removed that file and switched to starting supervisord via `sudo supervisord -c /etc/supervisor/supervisord.conf` supervisor is running happily again

**Comment by heyakyra** [comment]
I have supervisor installed from the default fedora repositories: `sudo dnf install supervisor`

but when I run it I still get `unix:///run/supervisor/supervisor.sock no such file`

```
$ which supervisorctl
/usr/local/bin/supervisorctl              
```

```
$ dnf info supervisor                                                
Last metadata expiration check: 0:00:13 ago on Sat 20 Jun 2020 09:57:37 PM UTC.           
Installed Packages                                                                        
Name         : supervisor                                                                 
Version      : 4.2.0                                                                      
Release      : 3.fc32                                                                     
Architecture : noarch                                                                     
Size         : 2.9 M                                                                      
Source       : supervisor-4.2.0-3.fc32.src.rpm                                            
Repository   : @System                                                                    
From repo    : updates                                                                    
Summary      : A System for Allowing the Control of Process State on UNIX                 
URL          : http://supervisord.org/                                                    
License      : BSD and MIT                                                                
Description  : The supervisor is a client/server system that allows its users to control a
             : number of processes on UNIX-like operating systems.                        
```
