### ISSUE TITLE
Infinite "Pending" status for *.gif files

### ISSUE THREAD

**Issue by JensRantil** [Supervisor/supervisor#74]
I am not sure if this is something that should be reported to supervisor, or further to the Medusa project.

When opening up the frontpage of supervisor in Google Chrome (15.0.874.121) and/or Chromium (17.0.917.0 (Developer Build 106870 Linux) Ubuntu 10.04), certain *.gif files are being shown as "Pending" in "Network" listing of the developer tools. They are never downloaded.

The issue cannot be reproduced on Firefox.

Can anybody reproduce this?

**Comment by mnaberez** [comment]
We never marked this issue as resolved but it has been open for years with no further reports.  In that time, there have been many changes to both `supervisord` and browsers.  Whatever conditions that caused this to happen may no longer exist.  I am going to close this issue for these reasons.  We can reopen if issue is seen again.
