### ISSUE TITLE
Error sending signals through signal command

### ISSUE THREAD

**Issue by roshanr95** [Supervisor/supervisor#740]
I'm using v3.2.3 installed through pip...

```
supervisor> status
backend                          RUNNING   pid 2420, uptime 0:00:43
supervisor> signal HUP backend
error: <type 'exceptions.ValueError'>, Unknown result code 1 for backend: file: /usr/local/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 765
```

**Comment by roshanr95** [comment]
I fixed it by removing supervisor completely and setting it up again... Can close this issue if you want.

**Comment by mnaberez** [comment]
> `error: <type 'exceptions.ValueError'>, Unknown result code 1 for backend: file: /usr/local/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 765`

Fault code `1` is [`UNKNOWN_METHOD`](https://github.com/Supervisor/supervisor/blob/3.2.3/supervisor/xmlrpc.py#L19) meaning `supervisorctl` sent the XML-RPC method `supervisor.sendSignal()` but `supervisord` did not implement this method.  

This likely happened as a result of an upgrade.  If you upgraded the `supervisor` package from an earlier version, but did not restart `supervisord`, the older version of `supervisord` without the signal command implementation would still be running.

**Comment by akimvital** [comment]
I have same problem after restarting supervisor and vithout upgrade:
2016-09-26 12:34:38,773 ERRO 127.0.0.1:Server Error: <type 'exceptions.ValueError'>, need more than 1 value to unpack: file: /usr/local/lib/python2.7/dist-packages/supervisor-3.2.3-py2.7.egg/supervisor/htt
