### ISSUE TITLE
Suggestion- expand default location for `supervisord.conf`

### ISSUE THREAD

**Issue by jvanasco** [Supervisor/supervisor#743]
I suggest adding `/etc/supervisor/supervisord.conf` to the list of config file locations that are searched.

At least Debian & Ubuntu patch supervisor to use this unofficial location, which can make the docs confusing and lead to unintended consequences.

**Comment by mnaberez** [comment]
Duplicate of #414.  The path was already added in 3ed820a8c94efe412688a7453c2c583331426e13.

**Comment by jvanasco** [comment]
sorry, this didn't show up in my search. (I really did search first)
