### ISSUE TITLE
FATAL  can't find command 'ssserver'

### ISSUE THREAD

**Issue by edionwong** [Supervisor/supervisor#748]
i'm a new learner. I can run "ssserver -c /etc/shadowsocks.json -d start" on my xshell to start shadowsocks ,but,i fail to start  ssserver through supervisorWhen i type "supervisorctl ",it give me "FATAL  can't find command 'ssserver'". Here is my shadowsocks.conf:
[program:shadowsocks]
command = ssserver -c /etc/shadowsocks.json
user = root
autostart = true
autoresart = true
stderr_logfile = /var/log/supervisor/ss.stderr.log
stdout_logfile = /var/log/supervisor/ss.stdout.log

**Comment by mnaberez** [comment]
> i'm a new learner. I can run "ssserver -c /etc/shadowsocks.json -d start" on my xshell to start shadowsocks ,but,i fail to start ssserver through supervisorWhen i type "supervisorctl ",it give me "FATAL can't find command 'ssserver'". Here is my shadowsocks.conf:
>
>     [program:shadowsocks]
>     command = ssserver -c /etc/shadowsocks.json

The command above is relative so `supervisord` will search the `PATH` in its environment for the command.  `supervisord` is saying that it can't find the command, so the directory containing `ssserver` must not be in the `PATH` in `supervisord`'s environment.

Change the command to be absolute (`command = /path/to/ssserver`) or add the directory containing `ssserver` to the `PATH` in `supervisord`'s environment.
