### ISSUE TITLE
Line breaks in logs are ignored because of fixed length buffer

### ISSUE THREAD

**Issue by neumayer** [Supervisor/supervisor#749]
Currently supervisor reads a fixed lenght buffer from stdout. The content of this buffer is then flushed to files (if set up to do so). This leads to files ending in or starting with incomplete log lines, which comes apparent when logrotation is on.

This is a problem for every setup that wants to use supervisor to redirect a process' stdout to files and these files to be shipped off by another process (i.e. a logstash setup). I want to use a file based buffer to be more in control of network outages.

I have a commit adding a new mode (similar to the capture mode) that respects line breaks before flushing via buffer manipulation (i.e. keep text after the last line break in the buffer for the next flush operation. This also means that this new mode is independent from capture mode, i.e. capture mode won't work with respecting newlines.

Any pointers, opinions, ideas? Honestly, I'm a bit surprised that no one else has experienced this before (at least according to "the Internet"). Has this ever been discussed before?

**Comment by neumayer** [comment]
https://github.com/Supervisor/supervisor/pull/751

**Comment by mnaberez** [comment]
Closing this in favor of #751.
