### ISSUE TITLE
unknown error making dispatchers for 'celerybeat': ESPIPE

### ISSUE THREAD

**Issue by zentavr** [Supervisor/supervisor#753]
I'm trying to run celery inside the docker container, using supervisord.
Here is the config of the supervisord:
```
[inet_http_server]
port = :9001

[supervisord]
nodaemon = true
directory = /srv/arena//arena
logfile=/dev/null

;; We have a lonely celerybeat here
[program:celerybeat]
command=celery beat --app=arena.celerybeat:app --loglevel=INFO
process_name = celerybeat
user = idle
autostart = true
startsecs = 15
autorestart = true
;; we do not need this as we redirecting errors to stderr of the docker
;; redirect_stderr = true
directory = /srv/arena/
stopwaitsecs = 600
killasgroup = true
;; redirect stderr and stdout of programm:x to stderr/stdout of docker
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
```

I tried to remove `user = idle` - no luck. Celery cannot be spawned. Supervisord says that:
`unknown error making dispatchers for 'celerybeat': ESPIPE`

When I comment the:
```
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
```
...celery gets spawned, but the files appear in /tmp. I do want to redirect the stderr/stdout to the /dev/std** because when I'm spawning the container - i use docker's log driver to forward the log streams to the ELK cluster.

**Comment by zentavr** [comment]
The code is the latest code of master branch

**Comment by cageowner** [comment]
Hi! Did you manage to resolve the issue? Im having a similar issue with a simple nginx-gunicorn-flask in a docker container setup. Like you I am using the master branch and importantly, python3. Logging to a file works fine but not to stdout/err. I am also using root as per docker default

**supervisord.conf:**
```
[supervisord]
nodaemon=true

[program:gunicorn]
command=/usr/local/bin/gunicorn --config gunicorn_cfg.py myproject:app
redirect_stderr=true

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:nginx]
command=/usr/sbin/nginx

stdout_logfile=/tmp/example.log
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

**supervisor error log at start**
```
... CRIT Supervisor running as root (no user in config file)
... WARN For [program:gunicorn], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
... INFO supervisord started with pid 5
... INFO spawnerr: unknown error making dispatchers for 'gunicorn': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'nginx': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'gunicorn': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'nginx': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'gunicorn': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'nginx': ESPIPE
... INFO spawnerr: unknown error making dispatchers for 'gunicorn': ESPIPE
... INFO gave up: gunicorn entered FATAL state, too many start retries too quickly
... INFO spawnerr: unknown error making dispatchers for 'nginx': ESPIPE
... INFO gave up: nginx entered FATAL state, too many start retries too quickly...
```

**Comment by mnaberez** [comment]
> Like you I am using the master branch and importantly, python3.

Supervisor doesn't work on Python 3 yet ([see the note in readme](https://github.com/Supervisor/supervisor/blob/154cb4c84f28ac3e0ac1ce5409faea65c15d2d02/README.rst)).  Can you try it on a released (3.x) version?

**Comment by zentavr** [comment]
@cageowner - unfortunately I'd dropped supervisord in our project. We switched to `runit` and a couple of wrappers around it. In my case we had Docker as you can see from my first post. The problem is that docker ideology expects a single process in the container and using supervisord is a some kind of hack. So, I'd found somewhere in the internet that:

>  End result is that the `/dev/stdout` for the different job was pointed to the different device.
>
> `/proc/self/fd/1` and should have been `/proc/1/fd/1` because as docker only expects one process to be running this is the only stdout it monitor

even if you send somehow the logs to `/dev/stdout` or `/dev/stderr` for 2nd..3rd..etc processes - docker won't flow them to the logdriver

**Comment by zentavr** [comment]
@cageowner: with `runit` you can set up a custom script/soft which will accept the log stream via STD INPUT. The script for `runit` is something like this:
```
#!/usr/bin/env python

'''
A simple script which takes stdin and writes it to a logfile
so that stdout/err of programs can be captured
'''

import argparse
import sys
import os


def main():
    parser = argparse.ArgumentParser(description='Log Forwarder')
    parser.add_argument('--stdout', default='/dev/stdout', dest='stdout_file', help='STDOUT file to use')

    args = parser.parse_args()
    f = os.open(args.stdout_file, os.O_NONBLOCK + os.O_WRONLY)

    for line in iter(sys.stdin.readline, ''):
        os.write(f, line.encode())


if __name__ == '__main__':
    main()
```

I spin up that as root with suid bit.

**Comment by cageowner** [comment]
@mnaberez Yes I did notice that in the readme, and my expectations were not for it to reliably work on Python 3. I had tried supervisor 3.x on Python 3 and as expected it did not work. Using Python 2.x would not be preferred for me. 

The master supervisor seems to mostly work for me on Python 3, except for the aforementioned logging issue, but as per @zentavr, this may just be a dockerism rather than a supervisor issue? Just in case you want to look further, I had uploaded the repo [here](https://github.com/cageowner/simple-flask-stack-python3).

**Comment by mnaberez** [comment]
Removing the [python 3 label](https://github.com/Supervisor/supervisor/labels/python%203) since this issue doesn't seem specific to Python 3.

**Comment by hathawsh** [comment]
This issue is likely to be related to this pull request: https://github.com/Supervisor/supervisor/pull/812

**Comment by mnaberez** [comment]
Adding [python 3 label](https://github.com/Supervisor/supervisor/labels/python%203) again based on #812.

**Comment by mnaberez** [comment]
This is likely fixed by #812, which has now been merged.  I'll close this issue for now.  Please leave a comment if that doesn't fix it for you and we can reopen.

**Comment by GregEremeev** [comment]
I try to run supervisord in a docker container to demonize celery.
And I have a similar problem - `spawnerr: unknown error making dispatchers for 'celery_worker_1': EACCES`

supervisord --version: 4.0.0.dev0 (git commit: ec495be4e28c694af1e41514e08c03cf6f1496c8)
python --version Python 3.6.2

**Comment by Martingoodnews** [comment]
Very much impressive, you gave a full detailed blog on Apps Only Available in USA and it was very helpful to me. I would like you to also check out my blog for more similar contents on this topic. So feel free to check-in. https://www.makeoverarena.com/apps-only-available-in-usa
