### ISSUE TITLE
Kill supervisord or fire command on restart limit

### ISSUE THREAD

**Issue by logankp** [Supervisor/supervisor#755]
Is there currently an option to fire a command or have supervisor kill itself on the restart limit being exceeded? We run supervisor in Docker containers and would like to have the ability to have our container management system (Marathon) restart the container automatically. This is currently impossible because supervisor keeps the container running even when the services is monitors have died.

If there is currently not an option for this, I would be willing to contribute this feature if acceptable.
Thanks!

**Comment by mnaberez** [comment]
> Is there currently an option to fire a command or have supervisor kill itself on the restart limit being exceeded?

There is not a built-in feature for this.

> If there is currently not an option for this, I would be willing to contribute this feature if acceptable.

This can be written as an [eventlistener](http://supervisord.org/events.html#event-listeners-and-event-notifications) without modifying `supervisord`.  If the process exceeds `startretries`, the process will transition to the `FATAL` state.  The eventlistener can listen for the [`PROCESS_STATE_FATAL`](http://supervisord.org/events.html#process-state-fatal-event-type) event and then send the [`shutdown()`](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.shutdown) command.  There are many example eventlisteners on the [plugins](http://supervisord.org/plugins.html) page.
