### ISSUE TITLE
Why queue process take Memory so much ?? 

### ISSUE THREAD

**Issue by rizkyred** [Supervisor/supervisor#756]
Hei i have problem here, i have about 45 threads. And do some job and it takes about 1.7GB memory, after that i try to remark all my code in job process, in function handle (on my job), but still take much memory (about 1,1-1,2GB). my question is what should i setting for my server or program so it not take so much memory ??

fyi im using ubuntu server with nginx, supervisor, and beanstalkd for queue process

**Comment by mnaberez** [comment]
You may be able to reduce the amount of memory being used on your system by running fewer processes.  You can ask `supervisord` to run fewer processes by removing `[program:x]` sections from `supervisord.conf`, or to run fewer copies of a single program by reducing the [`numprocs`](http://supervisord.org/configuration.html) setting in a `[program:x]` section.  

Beyond that, you'll have to troubleshoot the processes themselves and see what can be changed about them.  `supervisord` can't increase or decrease the amount of memory your process uses.  `supervisord` just spawns the process and the process uses whatever memory it uses.

**Comment by rizkyred** [comment]
So its all about my php script ?? 
in command = php /home/forge/app.com/artisan queue:work --sleep=3 --tries=3 --daemon
can you give me suggestion how to set this, because i have no idea why it takes about 258.392 virtual memory, and 1.4% per php. without source im just do nothing and call the jobs.
