### ISSUE TITLE
can supervisor do 100++ number of process

### ISSUE THREAD

**Issue by rizkyred** [Supervisor/supervisor#757]
Hei,

i set numprocs=150, save and call 
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start laravel-worker:*

and still processing, stuck at "sudo supervisorctl start laravel-worker:*".
my question is, can supervisor do more than 100 process ??

**Comment by mnaberez** [comment]
[Supervisor 3.3.0](https://github.com/Supervisor/supervisor/blob/3.3.0/CHANGES.txt#L4-L10) or later should be able to do this.

**Comment by rizkyred** [comment]
Hei mike im using ubuntu 14 now, is any other way to install latest version on my server now ?
