### ISSUE TITLE
Unexpected behavior with supervisorctl

### ISSUE THREAD

**Issue by Cobraeti** [Supervisor/supervisor#759]
Hi,
I am facing a strange behavior when running `supervisorctl status`.
Imagine you have at least one process named `azertyuiop`. I don't have any `azertyuiop` group and after some test it seems that I can't have a group named like a single process (which is a logical behavior).
When I run `supervisorctl azertyuiop azertyuiop:*` I get this output:
```
azertyuiop RUNNING pid...
azertyuiop RUNNING pid...
```
This strange behavior is really interesting for what I am trying to do as I don't always know if I execute that command for a single process or for a group of processes. This output shows that this information doesn't matter, so I could always run `supervisorctl status azertyuiop:*` whithout knowing if `azertyuiop` is a group or a single process.
I would like to know if it was written so or if you might change this in future releases? As I would like to be able to shorten my code thanks to that behavior ^^
Thanks

**Comment by mnaberez** [comment]
> I would like to know if it was written so or if you might change this in future releases? As I would like to be able to shorten my code thanks to that behavior 

There are no current plans to change how `supervisorctl` works.  If we do make a breaking change sometime in the future, we will bump the major version and note it in the changelog.
