### ISSUE TITLE
Can't get my go app to be served with supervisor!

### ISSUE THREAD

**Issue by xDinomode** [Supervisor/supervisor#767]
I require a go app to be served with supervisor 
My app is inside /work/src/github.com/xdinomode/shrimpcoder/app.go 

here's my supervisord conf

```
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0770                       ; sockef file mode (default 0700)
chown=root:supervisor           ;

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

```

and my conf.d/app.conf

no clue how to set this up btw
```
[program:app]
command=go build /work/src/github.com/xdinomode/shrimpcoder/app.go
user=ubuntu
directory=/work/src/github.com/xdinomode/shrimpcoder
redirect_stderr=true
stdout_logfile=/var/log/supervisor/app.log # the name of the log file.
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
```

**Comment by mnaberez** [comment]
> I require a go app to be served with supervisor
> My app is inside /work/src/github.com/xdinomode/shrimpcoder/app.go 

There isn't enough information here to tell what might be happening.  `supervisord` writes a main log file and also writes `stdout` and `stderr` log files for programs running under it.  You should look in all of these log files.  They will probably have messages that will help you troubleshoot.  

> no clue how to set this up btw

The [configuration guide](http://supervisord.org/configuration.html) lists all the available options and explains what they do.

We use this issue tracker mainly for bugs in Supervisor itself.  For installing or using Supervisor, please ask your question on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  The list is active and there are usually people there who can help with troubleshooting.
