### ISSUE TITLE
supervisord process exits with status 0 regardless of shutdown condition

### ISSUE THREAD

**Issue by misakwa** [Supervisor/supervisor#775]
**supervisor version**: 3.3
**python version**: 2.7

Whenever I terminate the supervisord process, it exits with status 0. I tried running it in the foreground and killed it in another shell process but it still doesn't register the status code I expected. I was expecting `128 + n` as documented [here](http://www.tldp.org/LDP/abs/html/exitcodes.html).

This is currently an issue when using supervisor to manage collaborating processes in a docker container and you instruct supervisor to exit when one of the processes turns fatal. It may not be a major issue, but having a zero status on all occasions can be a pain sometimes.

**Comment by misakwa** [comment]
I have already looked at [supervisord.Supervisor:runforever](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L183), [supervisord.Supervisor:run](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L86), [supervisord.Supervisor:main](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L58),  [supervisord:main](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L352), and [supervisord:go](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L372-L377) which seems to catch `ExitNow` and just ignores it. It might be better to check for the signal during the `runforever` loop and raise a `SystemExit` with the right code to avoid masking the exitcode. I'll be more than willing to submit a fix t get it reviewed.

**Comment by mnaberez** [comment]
> This is currently an issue when using supervisor to manage collaborating processes in a docker container and you instruct supervisor to exit when one of the processes turns fatal.

From `supervisord`'s perspective, nothing is wrong here.  Subprocesses routinely go up, down, and fatal but that doesn't indicate any problem with `supervisord` that should influence its exit status.  I think the key phrase here is "and you instruct supervisor to exit".  Nothing wrong happened with `supervisord` itself, you asked it to exit and it exited cleanly, so you got exit status 0.  If `supervisord` itself actually crashes, Python will set a non-zero exit code.

**Comment by misakwa** [comment]
I understand how you mean. I assumed it was standard for processes to exit with a non zero code unless they ran to completion. Is there anyway to make supervisord exit with a non-zero status?

**Comment by misakwa** [comment]
To add to your point about instructing it to exit (cleanly), it still exits with 0 when you `kill -9`.

**Comment by mnaberez** [comment]
> it still exits with 0 when you kill -9

There is no opportunity for `supervisord` to set an exit code or do anything else during `kill -9` because the kernel terminates the process immediately.

**Comment by misakwa** [comment]
I think I may have added additional information that was irrelevant to the question I was trying to ask. Let me clarify a bit more: Why does supervisord exit with a zero status when terminated? 
Regardless of the signal that is sent to the supervisord process, it always exits with a 0 status code.

Scenario:
1. Run supervisord in the foreground `$ supervisord -n` in one shell
2. Send a termination signal in another shell `$ kill -9 <pid-of-supervisord>`
3. Try `echo $?` in 1 above
4. Expected >128 but got 0

@mnaberez

**Comment by misakwa** [comment]
You could also try a `Ctrl+C` in 1 after starting the supervisord process and then `echo $?`. It will still return a 0 exitcode.

**Comment by mnaberez** [comment]
> $ kill -9 <pid-of-supervisord>

A process (`supervisord` or otherwise) can't trap `SIGKILL`.  The kernel terminates the process immediately.  There is nothing `supervisord` can do to influence the exit status in this case.

> You could also try a Ctrl+C in 1 after starting the supervisord process and then echo $?. It will still return a 0 exitcode.

This causes `supervisord` to receive `SIGTERM`, which requests `supervisord` to perform its normal shutdown procedure (same as the `shutdown` command).  This can be observed in the main log file (it will say something like `received SIGTERM indicating exit request`).  If `supervisord` shuts down cleanly, it will exit with status 0.  If it crashes during shutdown, Python will set the exit status to non-zero.

**Comment by misakwa** [comment]
>A process (supervisord or otherwise) can't trap SIGKILL. The kernel terminates the process immediately. There is nothing supervisord can do to influence the exit status in this case.

It should return a non-zero status in this case, but it doesn't. I'm not sure how the signal handlers are installed, but could they be doing something to influence the exit status?

```

**Comment by misakwa** [comment]
I tried this simplistic snippet here and I am able to successfully get non-zero statuses for all signals I sent to the process.

```python
#!/usr/bin/env python
import sys
import time

def try_eternal():
    while True:
        print 'Eternal executing...'
        time.sleep(1)

if __name__ == '__main__':
    try:
        try_eternal()
    except (SystemExit, KeyboardInterrupt):
        sys.exit(1)
```

Signals tried
```bash
$ kill -9 <pid> # returns 137
$ kill -6 <pid> # returns 134
$ kill -2 <pid> # returns 1 same as Ctrl+C
```

**Comment by misakwa** [comment]
[supervisord.Supervisor:handle_signal](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L298-L320) just logs messages in the [supervisord.Supervisor:runforever](/Supervisor/supervisor/blob/3.3.0/supervisor/supervisord.py#L256) loop where it is called.

**Comment by misakwa** [comment]
@mnaberez I think this is a bug in the run loop of supervisor. It just does nothing to set the exit status. The only exception raised in the runloop (runforever) is `ExitNow` which is ignored by the main entry point when `go` is called. Supervisord itself is doing a superb job sending the signals to the child processes it manages, but doesn't set one for itself when it should.

**Comment by mnaberez** [comment]
> I think this is a bug in the run loop of supervisor. It just does nothing to set the exit status. 

See the [explanation above](https://github.com/Supervisor/supervisor/issues/775#issuecomment-227009560).  If `supervisord` exits cleanly, it will set exit status 0.  If `supervisord` crashes, Python will set the exit status to non-zero.  Subprocess states do not influence the `supervisord` exit status in a special way.  `SIGTERM` means exit request to `supervisord`, it will perform its shutdown procedure and exit with status 0 if it exited cleanly.  There's not a way to influence the exit status on `SIGKILL` because we can't trap it.  I feel like this thread just keeps going around and around about "it has bugs" and "it should do something else" but I can't see anything concrete to indicate `supervisord` does anything other than what we document it should do.

**Comment by misakwa** [comment]
I appreciate your patience. I understand that this is most likely documented behaviour that I'm missing. However, I am not referring to the state of the subprocess influencing supervisord's exit status. I am referring to the exit status that the process manager (supervisord) itself puts out when it is killed. Unless there is something in the logic that causes the system to think that the process manager exited successfully, `kill -9` shouldn't return a 0 status. Most (if not all) processes will exit with a non-zero status when you send a SIGKILL.
I'll refrain from further comments and accept it as expected behaviour, but I do think that it should be modified to return a non-zero status as most do especially for a SIGKILL.
Thanks again for your patience on this one.

**Comment by mnaberez** [comment]
> kill -9 shouldn't return a 0 status. Most (if not all) processes will exit with a non-zero status when you send a SIGKILL.

There is no way to trap `SIGKILL`.  The kernel will terminate `supervisord` immediately, so there's no way for us to run more code that would set the exit status.  If there is some way to influence the exit status on `SIGKILL`, I don't know how to do it.  Feel free to post it here.

Putting that aside for a moment, you should never send `SIGKILL` to the `supervisord` process.  If `supervisord` has subprocesses when you `SIGKILL` it, those subprocesses will be orphaned.  If `supervisord` has pending log messages when you `SIGKILL` it, those will not be written.  You should request `supervisord` to perform its shutdown procedure and exit cleanly by signalling it with `SIGTERM` or issuing the `shutdown` command.  If `supervisord` takes too long to shut down, the log will show why.  The usual reason is that a subprocess is not exiting and `supervisord` is waiting the `stopwaitsecs` period.  The solution is to fix the subprocess or lower `stopwaitsecs`.  I don't think I've ever sent `SIGKILL` to a release version of `supervisord`.  That should only be needed if there's a bug in `supervisord` that causes it to become unresponsive, which is rare.
