### ISSUE TITLE
supervisor 3.0 @ character in environment variable don't let supervisor to start

### ISSUE THREAD

**Issue by brukau** [Supervisor/supervisor#779]
It fails with
`error: <class 'xmlrpclib.Fault'>, <Fault 92: 'CANT_REREAD: Unexpected end of key/value pairs'>`

**Comment by mnaberez** [comment]
Quote the value as described the [documentation](http://supervisord.org/configuration.html):
> Values containing non-alphanumeric characters should be quoted (e.g. KEY="val:123",KEY2="val,456").

`environment=` is parsed by [`dict_of_key_value_pairs`](https://github.com/Supervisor/supervisor/blob/3.0/supervisor/datatypes.py#L80-L98):

    Python 2.7.11 (default, Dec  5 2015, 14:44:53) 
    >>> from supervisor.options import VERSION
    >>> VERSION
    '3.0'
    >>> from supervisor.datatypes import dict_of_key_value_pairs
    >>> dict_of_key_value_pairs('email=contact@example.com')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "supervisor/datatypes.py", line 95, in dict_of_key_value_pairs
        raise ValueError, "Unexpected end of key/value pairs"
    ValueError: Unexpected end of key/value pairs
    >>> dict_of_key_value_pairs('email="contact@example.com"')
    {'email': 'contact@example.com'}
