### ISSUE TITLE
Remove obsolete http_username, http_password from skel/sample.conf

### ISSUE THREAD

**Issue by jvanasco** [Supervisor/supervisor#782]
These lines in the config file seem wrong

https://github.com/Supervisor/supervisor/blob/master/supervisor/skel/sample.conf#L52-L53

```
[supervisorctl]
...
;username=chris              ; should be same as http_username if set
;password=123                ; should be same as http_password if set
```

I think they are supposed to read
```
[supervisorctl]
...
;username= user              ; should be same as username if set in unix_http_server or inet_http_server
;password=123                ; should be same as password if set in unix_http_server or inet_http_server
```

**Comment by mnaberez** [comment]
Yes, it looks like we missed updating these comments.  `http_username` and `http_password` are [old options](https://github.com/Supervisor/supervisor/blob/2.2b1/src/supervisor/options.py#L474-L477) that were [removed in Supervisor 3](https://github.com/Supervisor/supervisor/blob/3.0a3/CHANGES.txt#L169-L184).
