### ISSUE TITLE
supervisorctl reload with additional argument should exit or prompt

### ISSUE THREAD

**Issue by jkrauska** [Supervisor/supervisor#783]
On more than one occasion I've accidentally typed:
 supervisorctl reload mydaemon

Where the intent was to /restart/ mydaemon, but instead I end up restarting ALL daemons and supervisord.

Sysvinit scripts and systemd use the keyword 'reload' to reload a single service.

I'd like to propose that it supervisorctl receives  reload $FOO, that is not blindly do a full reload but instead prompt that 'reload does not take an extra argument, maybe you meant restart?' or something similar.

**Comment by jkrauska** [comment]
`--- supervisorctl.py.save	2016-07-12 18:32:35.222454366 +0000
+++ supervisorctl.py	2016-07-12 18:35:00.894632913 +0000
@@ -802,2 +802,7 @@
     def do_reload(self, arg):
+        if arg:
+            self.ctl.output('Error: reload given with a process name. Maybe you meant restart?')
+            self.help_reload()
+            return
+
         if self.ctl.options.interactive:`

**Comment by mnaberez** [comment]
> I'd like to propose that it supervisorctl receives reload $FOO, that is not blindly do a full reload but instead prompt that 'reload does not take an extra argument, maybe you meant restart?' or something similar. 

I agree, it should give an error if it receives incorrect arguments.  Other `supervisorctl` commands do better argument checking.

**Comment by jkrauska** [comment]
https://github.com/Supervisor/supervisor/pull/784

**Comment by jkrauska** [comment]
Any interest in merging this?

**Comment by mnaberez** [comment]
Fixed in 51caeb7eed819dceacf86e988739e022c7f78cd1.
