### ISSUE TITLE
How to get supervisor to run automatically when Ubuntu reboots?

### ISSUE THREAD

**Issue by vgoklani** [Supervisor/supervisor#785]
I installed via "pip install supervisor" and enabled it via

/opt/anaconda/bin/python /opt/anaconda/lib/python2.7/site-packages/supervisor/supervisord.py -c /etc/supervisor/supervisord.conf

but unfortunately supervisor doesn't restart when the system reboots. How do I fix this?

Please note that I previously installed supervisor as a service on Ubuntu, which was much easier to run, but I kept hitting this bug: unix:///var/run/supervisor.sock no such file which hasn't yet been fixed, so I"m using this as a work-around: https://github.com/Supervisor/supervisor/issues/735

**Comment by mnaberez** [comment]
The Supervisor project itself doesn't provide init scripts.  There is a repository of user-contributed init scripts at [supervisor/initscripts](https://github.com/Supervisor/initscripts).  You can also ask on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).
