### ISSUE TITLE
Option to read config from HTTP endpoint

### ISSUE THREAD

**Issue by alainrichardt** [Supervisor/supervisor#786]
Hi There,

Would anyone be interested in a configuration option in supervisord.conf, so that it could pull it's config from an HTTP endpoint?

I was thinking something like this:
[configserver]
configsource = http://somehost.info/config?machine=hostname

The GET HTTP request would send the machines hostname as a parameter, and the expected return would be pain text that would be parsed like a normal supervisor config file (same format as files in /etc/supervisor/conf.d )

I need this for my own systems, but I wanted to ask the question here to get a discussion going - if nobody wants this, I'll just fork the code and implement for myself.  If not, I'll implement and open a pull request

**Comment by mnaberez** [comment]
I think this is out of scope for the core Supervisor package but we'd be happy to add a link to the [third party page](https://github.com/Supervisor/supervisor/blob/154cb4c84f28ac3e0ac1ce5409faea65c15d2d02/docs/plugins.rst) if you make a plugin or fork.
