### ISSUE TITLE
Searching for command in PATH ignores changes made by environment=

### ISSUE THREAD

**Issue by dongweiming** [Supervisor/supervisor#787]
I write a supervisord.conf，program section like this:

```
[program:xxx]
environment=PATH=%(ENV_HOME)s/.virtualenvs/venv/bin:%(ENV_PATH)s
command=gunicorn -w 3 xxx.app:app -b 0.0.0.0:8000
...
```

but it's fail. supervisor told me:

```
can't find command 'gunicorn'
```

but i can find it:

```
❯ ll ~/.virtualenvs/venv/bin/gunicorn 
-rwxrwxr-x 1 ubuntu ubuntu 245 Jun 12 05:39 /home/ubuntu/.virtualenvs/venv/bin/gunicorn
```

Does I used the wrong way?

**Comment by dongweiming** [comment]
@mcdonc @mnaberez

**Comment by mnaberez** [comment]
Minimal `supervisord.conf`:

    [supervisord]
    logfile = /tmp/supervisord.log
    loglevel = debug
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:env]
    command = env
    environment = PATH=%(ENV_HOME)s/.virtualenvs/venv/bin:%(ENV_PATH)s
    autostart = true
    autorestart = false
    startsecs = 0

The program section above runs `env`, which prints its environment.  It has the same `environment =` line as [your description](https://github.com/Supervisor/supervisor/issues/787#issue-165983340).

Start `supervisord` in the foreground with that config:

    $ supervisord --version
    3.3.0
    $ supervisord -n -c /path/to/supervisord.conf
    2016-07-17 20:45:32,708 INFO Increased RLIMIT_NOFILE limit to 1024
    2016-07-17 20:45:32,738 INFO RPC interface 'supervisor' initialized
    2016-07-17 20:45:32,738 CRIT Server 'inet_http_server' running without any HTTP authentication checking
    2016-07-17 20:45:32,738 INFO supervisord started with pid 21602
    2016-07-17 20:45:33,743 INFO spawned: 'env' with pid 21606
    2016-07-17 20:45:33,749 DEBG 'env' stdout output:
    TERM_PROGRAM_VERSION=361.1
    CVS_RSH=/usr/bin/ssh
    PATH=/home/mnaberez/.virtualenvs/venv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:...

The above output from `env` shows that `PATH` was updated from `environment =`.

I'm going to close this issue since I don't see a bug here.  The [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment) section of the documentation may be helpful.  You can also get help on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).

**Comment by mnaberez** [comment]
Summary of above:
- Subprocess environment is set as expected with `environment=PATH=%(ENV_HOME)s/.virtualenvs/venv/bin:%(ENV_PATH)s` ([tested](https://github.com/Supervisor/supervisor/issues/787#issuecomment-233224771))

- `command=` searches the `PATH` before changes in `environment=` are applied. ([notes](https://github.com/Supervisor/supervisor/issues/787#issue-165983340))

**Comment by dongweiming** [comment]
@mnaberez [tested](https://github.com/Supervisor/supervisor/issues/787#issuecomment-233224771) is very enlightening. but in my environment it's not works. I am very confused it.

I will show my use way:

1.  install supervisor:

```
❯ sudo pip install supervisor
```

2. create virtual env and install gunicorn:

```
❯ cd /tmp
❯ virtualenv venv
❯ source venv/bin/activate 
(venv) ❯ pip install gunicorn
```

3. now, gunicorn is available:

```
(venv) ❯ which gunicorn
/tmp/venv/bin/gunicorn
(venv) ❯ which supervisord
/usr/local/bin/supervisord
```

4. then, i start supervisor:

```
(venv) ❯ sudo supervisord -n -c supervisord.conf --loglevel debug
2016-07-19 16:24:23,018 CRIT Supervisor running as root (no user in config file)
2016-07-19 16:24:23,036 INFO RPC interface 'supervisor' initialized
2016-07-19 16:24:23,036 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2016-07-19 16:24:23,037 INFO supervisord started with pid 2522
2016-07-19 16:24:24,039 INFO spawnerr: can't find command 'gunicorn'
2016-07-19 16:24:25,042 INFO spawnerr: can't find command 'gunicorn'
2016-07-19 16:24:27,074 INFO spawnerr: can't find command 'gunicorn'
```

You can see, something wrong

**Comment by mnaberez** [comment]
>     2016-07-19 16:24:27,074 INFO spawnerr: can't find command 'gunicorn'

`supervisord` searches for `command=` in the current `PATH`, but it does not consider changes to `PATH` that may have been specified in the `environment=`.  I think it is reasonable to do so, that's why I have reopened this issue.

**Comment by dongweiming** [comment]
@mnaberez Any chance of a release? seems i'm having to wait times between this being made available :/

**Comment by mnaberez** [comment]
No, there is no schedule.  I don't know when someone will patch it, or when a release will be made that includes it.

**Comment by vimagick** [comment]
This feature is useful.

**Comment by w-Bro** [comment]
> @mnaberez [tested](https://github.com/Supervisor/supervisor/issues/787#issuecomment-233224771) is very enlightening. but in my environment it does not works. I am very confused it.
> 
> I will show my use way:
> 
> 1. install supervisor:
> 
> ```
> ❯ sudo pip install supervisor
> ```
> 
> 1. create virtual env and install gunicorn:
>    ```
>    ❯ cd /tmp
>    ❯ virtualenv venv
>    ❯ source venv/bin/activate 
>    (venv) ❯ pip install gunicorn
>    ```
> 2. now, gunicorn is available:
>    ```
>    (venv) ❯ which gunicorn
>    /tmp/venv/bin/gunicorn
>    (venv) ❯ which supervisord
>    /usr/local/bin/supervisord
>    ```
> 3. paste supervisord.conf file：
>    ```
>    ❯ cat supervisord.conf 
>    [supervisord]
>    logfile = /tmp/supervisord.log
>    loglevel = debug
>    
>    [inet_http_server]
>    port = 127.0.0.1:9001
>    
>    [supervisorctl]
>    serverurl = http://127.0.0.1:9001
>    
>    [rpcinterface:supervisor]
>    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
>    
>    [program:env]
>    command = gunicorn --version
>    environment = PATH=/tmp/venv/bin:%(ENV_PATH)s
>    autostart = true
>    autorestart = false
>    startsecs = 0
>    ```
> 4. then, i start supervisor:
>    ```
>    (venv) ❯ sudo supervisord -n -c supervisord.conf --loglevel debug
>    2016-07-19 16:24:23,018 CRIT Supervisor running as root (no user in config file)
>    2016-07-19 16:24:23,036 INFO RPC interface 'supervisor' initialized
>    2016-07-19 16:24:23,036 CRIT Server 'inet_http_server' running without any HTTP authentication checking
>    2016-07-19 16:24:23,037 INFO supervisord started with pid 2522
>    2016-07-19 16:24:24,039 INFO spawnerr: can't find command 'gunicorn'
>    2016-07-19 16:24:25,042 INFO spawnerr: can't find command 'gunicorn'
>    2016-07-19 16:24:27,074 INFO spawnerr: can't find command 'gunicorn'
>    ```
> 
> something wrong happened!
> 
> ```
> ❯ supervisord --version
> 3.3.0
> ```

@dongweiming it seems have been a long time, i have same question with you, how could you solve this?
