### ISSUE TITLE
Error: Exited too quickly

### ISSUE THREAD

**Issue by AlvinLv0** [Supervisor/supervisor#788]
Start supervisor subprocess still FATAL :  Exited too quickly(process log may have detail);

Logs error content as follows: 
**_supervisor: couldn't chdir to /home/mtime/mx.common.sms.task/mx.common.sms.task: ENOENT
supervisor: child process was not spawned_**

Conf file is no problem:
_[program:mx.common.sms.task]
directory = /home/mtime/mx.common.sms.task/mx.common.sms.task
command = /usr/local/bin/jctl run 
autostart=true
autorestart=true
startsecs=3
startretries=3
stopwaitsecs=5
user = mtime
redirect_stderr = true
stdout_logfile = /home/mtime/optools/supervisor/logs/mx.common.sms.task.log_

 Do not use supervisor can be normally started, Please help to see where the problem ,thanks!

**Comment by mnaberez** [comment]
> supervisor: couldn't chdir to /home/mtime/mx.common.sms.task/mx.common.sms.task: ENOENT

The error message says the directory specified in `directory = ` does not exist.

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
