### ISSUE TITLE
how do i put my rsync server to supervisor

### ISSUE THREAD

**Issue by wanghonglei5181** [Supervisor/supervisor#790]
i have servral of rsync server,for example.
rsync --daemon --config=/etc/rsync1873.conf --port 1873
rsync --daemon --config=/etc/rsync1874.conf --port 1874
................
rsync --daemon --config=/etc/rsync1879.conf --port 1879
how do i migrate all of these to supervisor

errors;
supervisor> start all
rsync:rsync1874: ERROR (spawn error)
rsync:rsync1873: ERROR (spawn error)

**Comment by mnaberez** [comment]
> rsync --daemon --config=/etc/rsync1879.conf --port 1879

Processes run under `supervisord` [must not daemonize](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses).

Please ask questions about configuring and running Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
