### ISSUE TITLE
No api equivalent of the update command?

### ISSUE THREAD

**Issue by mikeyg123** [Supervisor/supervisor#792]
Hi

We want to emulate the behaviour of the supervisorctl update command via the xml-rpc api - i.e. re-read config and then restart any process for which the config has changed (without touching other supervised processes).

However the api functions reloadConfig() and addProcessGroup() do not appear to do what we need. In fact they seem to do very little.

Is this an oversight?

**Comment by mnaberez** [comment]
[`supervisorctl`](https://github.com/Supervisor/supervisor/blob/154cb4c84f28ac3e0ac1ce5409faea65c15d2d02/supervisor/supervisorctl.py) itself is implemented using the same XML-RPC API, so the necessary functions are there, see the source under `do_update` for how to do it.

**Comment by mikeyg123** [comment]
Excellent thank you!

**Comment by sieben** [comment]
@mnaberez Would it be possible to perform such task by importing supervisor as a library? Would it be possible to perform tasks such as reread, update start and stop without performing directly XML-RPC calls?

**Comment by mnaberez** [comment]
> Would it be possible to perform such task by importing supervisor as a library? Would it be possible to perform tasks such as reread, update start and stop without performing directly XML-RPC calls?

No.  Supervisor was always designed to be a client/server system, where a client (such as `supervisorctl`) sends commands to the server (`supervisord`).  Making it work in a different way would be a significant effort and is not planned.

**Comment by sieben** [comment]
OK,  would it be possible to use supervisorctl in a Python scripts such as : 

```
from supervisor import supervisorctl
my_instance = supervisorctl('http://localhost:9001/RPC2')
my_instance.do_update()
```

**Comment by sieben** [comment]
@mnaberez ping :-)

**Comment by mnaberez** [comment]
```
from supervisor.supervisorctl import (
  ClientOptions,
  Controller,
  )

options = ClientOptions()
options.realize()

controller = Controller(options)
controller.onecmd('update')
```

**Comment by sieben** [comment]
Excellent :-) Do you think this could be documented on the website ( http://supervisord.org/api.html )? I think it would be useful for python-dev that want to have the full power of supervisorctl right from their python code without passing through the XML-RPC.

**Comment by sieben** [comment]
@mnaberez I got another question. Is there a way to get through the Controller objects information about the current state of the process? I've used controller.onecmd but such function doesn't return anything, it simply print the results.

**Comment by mnaberez** [comment]
> Is there a way to get through the Controller objects information about the current state of the process?

[Do it like all the built-in `supervisorctl` commands do](https://github.com/Supervisor/supervisor/blob/3.3.1/supervisor/supervisorctl.py#L607-L608).  Use the method `get_supervisor()` to return an XML-RPC proxy object and then call `getProcessInfo(name)` or `getAllProcessInfo()` on it.

**Comment by ichux** [comment]
> ```
> from supervisor.supervisorctl import (
>   ClientOptions,
>   Controller,
>   )
> 
> options = ClientOptions()
> options.realize()
> 
> controller = Controller(options)
> controller.onecmd('update')
> ```

Thanks so much for the above. I did alter is a bit to taste since mine uses authentication:

```from supervisor.supervisorctl import ClientOptions, Controller

options = ClientOptions()
options.read_config("/home/piccl/supervisord.conf")
options.configroot.supervisorctl.username = "username"
options.configroot.supervisorctl.password = "usernamepassword"
options.realize()

controller = Controller(options)
controller.onecmd("update")
```

**Comment by maikelf** [comment]
I am trying to do reread and update. I am using node js. Using xmlrpc I can do reloadConfig (reread), but I not foud  how to do update. I have read the documentation from http://supervisord.org/api.html but I dont found any reference for update command
