### ISSUE TITLE
program started by supervisord not responding 

### ISSUE THREAD

**Issue by iammehrabalam** [Supervisor/supervisor#795]
programs started by supervisord not responding  after sometime (not fixed) and  after refresh or restart from webui working fine.

program configuration is below

```
[program: celeryworker]
command=celery worker -A project.celery_tasks 
directory=/project/path
autostart=true
autorestart=true
stderr_logfile=/project/path/logs/celery_error.log
stdout_logfile=/project/path/logs/celery_info.log
user=root
environment=C_FORCE_ROOT="celery_worker1"
```
is there any way to deal with this issue?

**Comment by mnaberez** [comment]
Please ask this question on the [celery-users mailing list](https://groups.google.com/forum/#!forum/celery-users) or maybe the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
