### ISSUE TITLE
Documentation for api reloadConfig incomplete

### ISSUE THREAD

**Issue by mikeyg123** [Supervisor/supervisor#797]
The documentation for the reloadConfig() api method on the web site doesn't describe the list of added/changed/removed groups in the returned structure.
Also details for addProcessGroup() and removeProcessGroup() don't really describe what they do.  Some information about the concept of pending changes which get accepted by calling {add, remove}ProcessGroup() would really help people. Only after looking at the source code were we able to understand what they do and how useful they are and build a UI which lets users individually examine pending changes and apply them.

**Comment by mnaberez** [comment]
`reloadConfig` docs added in 219f7af0ac8b0b1965b00793a923a22addfadbaa.
