### ISSUE TITLE
Smart string expressions like %(process_num+1)

### ISSUE THREAD

**Issue by razvanphp** [Supervisor/supervisor#801]
For example there is a program that requires `process_num` to be passed from 1 to N, instead of 0 indexed.

If there is already a way to do this with pyton expressions, please let me know how.

Thank you!

**Comment by mnaberez** [comment]
You can change it from 0-based to N-based using [`numprocs_start`](http://supervisord.org/configuration.html).  

I don't think we should evaluate arbitrary expressions inside the config file.  If you need to do this, please use something else to generate the config file.
