### ISSUE TITLE
child process logging output is very delayed

### ISSUE THREAD

**Issue by engelhardtw** [Supervisor/supervisor#803]
I have to wait 10-15 minutes before my child process logs have any content.  Is there a way to flush out the logging buffer immediately or to control it's size?

**Comment by mnaberez** [comment]
Example program dots.py:

    import sys
    import time

    while True:
        sys.stdout.write(".")  # no newline
        sys.stdout.flush()
        time.sleep(0.25)

Minimal supervisord.conf:

    [supervisord]
    logfile = /tmp/supervisord.log

    [inet_http_server]
    port = 127.0.0.1:9001

    [supervisorctl]
    serverurl = http://127.0.0.1:9001

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [program:dots]
    command = python /path/to/dots.py
    startsecs = 0
    autostart = true
    autorestart = false
    stdout_logfile = /tmp/dots.log

Start `supervisord` in the foreground with that config:

    $ supervisord --version 
    3.3.0

    $ supervisord -n -c /path/to/supervisord.conf

Dots in real time through `supervisorctl`:

    $ supervisorctl -c /path/to/supervisord.conf tail -f dots

Dots in real time through the log file:

    $ tail -f /tmp/dots.log

The example above shows a recent version of `supervisord` should log subprocess output almost immediately after it receives it.  

Your subprocess may be buffering its output.  If that is the case, `supervisord` can't log the output until the subprocess flushes its buffer.  Try to disable output buffering or add an explicit flush (like `sys.stdout.flush()` above).
