### ISSUE TITLE
TP connect() failed

### ISSUE THREAD

**Issue by s26** [Supervisor/supervisor#808]
I am using gearman in production successfully in background(nohup) process.

What I want is multiple workers. For that I have used supervisor and create two processes.

After using supervisor I am getting `Mailer Error: SMTP connect()` failed. It is not showing any error message on supervisor process's log file.

I have stopped my backgrouond process before starting supervisor processes.

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
