### ISSUE TITLE
Syslog facility

### ISSUE THREAD

**Issue by TuxOtaku** [Supervisor/supervisor#814]
Hey guys,

So I noticed there is some form of support for syslog, but I can't seem to find any information on how to configure the syslog facility which supervisor should log to? Is there a default value? Can this be configured at all, or has this portion of the syslog protocol simply not been implemented as part of supervisor?

**Comment by mnaberez** [comment]
> So I noticed there is some form of support for syslog, but I can't seem to find any information on how to configure the syslog facility which supervisor should log to?

The facility is not configurable ([implementation](https://github.com/Supervisor/supervisor/blob/625da4d07cce1a38f1f76905191f54cfe56a945f/supervisor/loggers.py#L326-L353)).

> Is there a default value?

It uses the defaults of the Python [`syslog` module](https://docs.python.org/2/library/syslog.html).

> Can this be configured at all, or has this portion of the syslog protocol simply not been implemented as part of supervisor?

There are open pull requests to improve syslog support that will probably be merged in the future.  They have the [syslog label](https://github.com/supervisor/supervisor/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20label%3Asyslog).
