### ISSUE TITLE
Can not use supervisorctl with nodaemon=true

### ISSUE THREAD

**Issue by muhlpachr** [Supervisor/supervisor#819]
With [supervisord] nodaemon=true unix socket defined in [supervisorctl] serverurl is not created.
It make sense to use supervisorctl for nodaemon operation e.g. inside Docker container.

**Comment by mnaberez** [comment]
> With [supervisord] nodaemon=true unix socket defined in [supervisorctl] serverurl is not created.

The  [`[unix_http_server]`](http://supervisord.org/configuration.html#unix-http-server-section-settings) section tells `supervisord` how it should create the socket file.

The [`[supervisorctl]`](http://supervisord.org/configuration.html#supervisorctl-section-settings) section tells `supervisorctl` how it should connect to `supervisord`.
