### ISSUE TITLE
supervisorctl pid <proc> returns exit status 0 for crashed process

### ISSUE THREAD

**Issue by jippi** [Supervisor/supervisor#820]
Hi

Running latest dev-master (`git+https://github.com/Supervisor/supervisor.git@625da4d07cce1a38f1f76905191f54cfe56a945f`) running `supervisorctl pid users_php-fpm_0` for a process that has crashed return `0` and exit code `0` 

Running the `pid` command for something non-crashed returns correct PID

Running the `pid` command for something non-existing yields a proper error and exit code

**Comment by mnaberez** [comment]
That all sounds fine.  What do you think it should do?

**Comment by jippi** [comment]
I would have expected output to `stderr` and `exit code != 0` :)

**Comment by mnaberez** [comment]
> I would have expected output to stderr and exit code != 0 :) 

You want a non-zero exit status from `supervisorctl pid` if `supervisord` recognizes the process name but the process has no pid (not `STARTING/`RUNNING`).  That sounds reasonable to me.

> What I did was kill -HUP $(supervisorctl pid <prod>) and expected it to work or abort if the proc was not running or non-existent

You can also use the `signal` command since Supervisor 3.2.0.

cc @lukeweber

**Comment by jippi** [comment]
Thanks @mnaberez :)
