### ISSUE TITLE
class 'socket.gaierror'...

### ISSUE THREAD

**Issue by gour** [Supervisor/supervisor#822]
Hell, 
I'm using supervisor-3.3.1 on my hosting provider which uses CentOS.

Web UI works and I can (re)start/stop procs etc., but when I'm trying _supervisorctl_ I get the following:

```
$ supervisorctl -c ~/path/to/supervisor/supervisord.conf 
error: <class 'socket.gaierror'>, [Errno -2] Name or service not known: file: /usr/lib64/python2.7/socket.py line: 553
```

Any hint?

**Comment by mnaberez** [comment]
A hostname you have written in the config file [can't be resolved](http://stackoverflow.com/a/23777462) to an IP address.

Printing this error is the best we can do in this case, so I'm closing this issue.
