### ISSUE TITLE
supervisor 2.1.9 install by yum on centos6.5 , parameters 'directory' in supervisord.conf does not work

### ISSUE THREAD

**Issue by will835559313** [Supervisor/supervisor#824]
this is my part of /etc/supervisord.conf
```sh
[program:celery_worker]
directory = /data/celery
command=/usr/local/python27/bin/celery worker -A famulei -l info -f /data/celery/famulei.log -Q celery,famulei
user=www
autostart=true
autorestart=true
startsecs=5
startretries=5
log_stdout=true
log_stderr=true
logfile=/tmp/celery_worker.log
```
when I run the supervisord I got a error that  tell me cant not import the module that write by myself

when I cd /data/celery and then run the commad above can work well
please help me

**Comment by AlphaSRE** [comment]
directory=

**Comment by AlphaSRE** [comment]
try
directory=/data/celery

**Comment by will835559313** [comment]
I try it again and I also got that error

**Comment by mnaberez** [comment]
Supervisor 2.1 was released [over 9 years ago](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L1321) and is no longer supported.  Please upgrade to a newer version.

**Comment by will835559313** [comment]
centos6.5 user python 2.6.6 , so could you tell which version of supervisor should I use

**Comment by mnaberez** [comment]
The current stable release, [Supervisor 3.3.1](https://pypi.python.org/pypi/supervisor/3.3.1), supports Python 2.6.

**Comment by will835559313** [comment]
ok! thank you very much ! I will try it
