### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by AlphaSRE** [Supervisor/supervisor#825]
只想让work用户通过supervisor.sock控制program中user=work的进程，而不是控制所有进程，如何实现？

**Comment by mnaberez** [comment]
Can you please ask this question in English?

**Comment by zjjott** [comment]
@AlphaSRE speak English 😄 
obviously,supervisord and supervisorctl only have one configure so they can control all of the program

**Comment by AlphaSRE** [comment]
Thanks
