### ISSUE TITLE
How to add process num of program without restart running process of program

### ISSUE THREAD

**Issue by wgjak47** [Supervisor/supervisor#826]
For example, I have a program config like this:
```
[program:foo]
user=foo
command=/usr/bin/python foo.pyc
process_name=%(program_name)s_%(process_num)02d
numprocs=10
priority=1
startsecs=8
autostart=false
autorestart=true
stdout_logfile=/home/foo/log/supervisor/%(program_name)s_stdout.log
stderr_logfile=/home/foo/log/supervisor/%(program_name)s_stderr.log
stderr_capture_maxbytes=1MB
directory=/home/foo/bin
startretries=3
```
if I change the numprocs, like numproces = 20, then I have to run supervisorctl update and the running process of program foo will stop. This is not what I want...So Is there any way to add process num without restarting whole program?

**Comment by mnaberez** [comment]
No, but there is a request for such a feature in #177.
