### ISSUE TITLE
show hostname on web interface page

### ISSUE THREAD

**Issue by ccurvey** [Supervisor/supervisor#828]
I'm using Supervisor on a whole bunch of machines (thank you, BTW) and it would be really nice to have the current hostname displayed right on the webpage.  (Yes, I'm too lazy to look up-and-left to the URL bar.)

**Comment by mnaberez** [comment]
Code for the web interface is in [web.py](https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py) and the [ui/](https://github.com/Supervisor/supervisor/tree/master/supervisor/ui) directory.  Feel free to submit a PR for this.
