### ISSUE TITLE
Pip installation lacks __init__.py file

### ISSUE THREAD

**Issue by azmeuk** [Supervisor/supervisor#830]
Hi. It seems that pip installations do not install `__init__.py`. So if you run a python scripts depending on supervisor, with `python -Wall` (for instance, some django tests with `django-supervisor` installed) you can have the following warnings:

```
  file, filename, etc = imp.find_module(subname, path)
/usr/lib64/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '.../env/lib/python2.7/site-packages/supervisor': missing __init__.py
```

```
virtualenv env
source env/bin/activate
pip install supervisor
ls env/lib/python2.7/site-packages/supervisor
```

Is there a problem with the pip installation ?

**Comment by mnaberez** [comment]
Duplicate of #660.
