### ISSUE TITLE
my program fails even when i run with user root

### ISSUE THREAD

**Issue by mkhetan** [Supervisor/supervisor#833]
Hi,

I have a program that I have to run after logging in as root. It does not run successfully even if i run it as "sudo my_program". I want to run it as part of supervisor. I set the user as root in the supervisord.conf for this program but still it fails when i try to run it through supervisor ( the same way it fails when i run it as "sudo my_program" ) . Please help! It is blocking my project. As an alternative, I am running it with nohup. But, not happy with that.

Thanks,
Mayank

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
