### ISSUE TITLE
event=PROCESS_STATE_EXITED,PROCESS_STATE_STOPPED, Kill child process.child process&event listener all die

### ISSUE THREAD

**Issue by kite-nubia** [Supervisor/supervisor#834]

**Comment by kite-nubia** [comment]
.conf:

[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)

[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)
username=user              ; (default is no username (open server))
password=123               ; (default is no password (open server))

[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001 ; use an http:// url to specify an inet socket
username=user              ; should be same as http_username if set
password=123                ; should be same as http_password if set


[program:test]
command=python test.py
process_name=%(program_name)s ; process_name expr (default %(program_name)s)
directory=/home/ringear
user=ringear                   ; setuid to this UNIX account to run the program
redirect_stderr=true          ; redirect proc stderr to stdout (default false)

[eventlistener:alarm]
user=ringear                   ; setuid to this UNIX account to run the program
command=python /home/ringear/eventlistener.py    ; the program (relative uses PATH, can take args)
events=TICK_60             ; event notif. types to subscribe to (req'd)
stderr_logfile=/home/ringear/err.log        ; stderr log path, NONE for none; default AUTO
stdout_logfile=/home/ringear/out.log         ; stdout log path, NONE for none; default AUTO

**Comment by kite-nubia** [comment]
test.py:

import time

def test():
    while True:
        time.sleep(60)

if __name__ == '__main__':
    test()

**Comment by kite-nubia** [comment]
eventlistener.py:

import sys
from supervisor import childutils

def write_stdout(s):
    sys.stdout.write(s)
    sys.stdout.flush()

def write_stderr(s):
    sys.stderr.write(s)
    sys.stderr.flush()

def do_something():
    f = open('/home/ringear/tttt.txt', 'a')
    f. write('!!!!@@@@\n')
    f.close()

err_states = ['PROCESS_STATE_EXITED', 'PROCESS_STATE_STOPPING']

def main():
    while 1:
        # headers, payload = childutils.listener.wait()
        # write_stderr(headers+payload+'\n')
        # childutils.listener.send(headers)
        # if headers['eventname'] == 'PROCESS_STATE_EXITED':
        #     do_something()
        # childutils.listener.ok(sys.stdout)
        # transition from ACKNOWLEDGED to READY
        write_stdout('READY\n')
        line = sys.stdin.readline()
        write_stderr(line)
        do_something()
        headers = dict([x.split(':') for x in line.split()])
        data = sys.stdin.read(int(headers['len']))
        write_stderr(data)
        write_stdout('RESULT 2\nOK')

if __name__ == '__main__':
    main()

**Comment by kite-nubia** [comment]
when i kill a child process, i think it should do_something .but the child process&event listener process all die.just why?

**Comment by kite-nubia** [comment]
and it really do_something,but in err.log it has a row whitout any word. in out .log it only has 'ready'
ps: event = TICK_60 it also die after a minute

**Comment by mnaberez** [comment]
What version of Supervisor are you using (`supervisord --version`)? 
What version of Python (`python -V`)?

**Comment by kite-nubia** [comment]
@mnaberez 
python3.4
supervisord --version4.0.0.dev

ps: use ubuntu14.04

**Comment by mnaberez** [comment]
> python3.4
> supervisord --version4.0.0.dev

This is the same as #663.  See https://github.com/Supervisor/supervisor/issues/663#issuecomment-252465751 for a simpler way to reproduce than the above.
