### ISSUE TITLE
supervisorctl fg always raises INCORRECT_PARAMETERS on Python 3

### ISSUE THREAD

**Issue by mnaberez** [Supervisor/supervisor#836]
Start `supervisord` in the foreground with a subprocess running:

```
$ python --version
Python 3.5.2

$ cat supervisord.conf
[supervisord]
loglevel = blather
nodaemon = true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat

$ supervisord -c supervisord.conf
```

In another terminal, start `supervisorctl fg` and type something followed by return:

```
$ supervisorctl -c supervisord.conf fg cat
==> Press Ctrl-C to exit <==
hi
ERROR: <Fault 2: 'INCORRECT_PARAMETERS'>
Exiting foreground
$
```

Tested on 427eb2bc6b08f788573deb91d1391d93f8b58a1b.  Note that in earlier versions, `fg` swallowed most XML-RPC faults so it would fail silently.  The cause of `INCORRECT_PARAMETERS` is the same as https://github.com/Supervisor/supervisor/issues/835#issue-181898879.   Once that is fixed, we should try the above again to be sure `supervisorctl fg` is also fixed.

**Comment by JockDaRock** [comment]
what is the progress of getting supervisor to play well with Python 3???

**Comment by mnaberez** [comment]
> what is the progress of getting supervisor to play well with Python 3???

Issues that still need to be resolved are tagged [python 3](https://github.com/Supervisor/supervisor/labels/python%203).

**Comment by AlJohri** [comment]
if I wanted to support supervisor getting python3 support via [bountysource](https://www.bountysource.com/) which issue would be a good one to donate to? @mnaberez

**Comment by mnaberez** [comment]
> if I wanted to support supervisor getting python3 support via bountysource 

This project is not current participating in any bounty websites and is also not currently soliciting monetary donations.  If the project participates in any bounties or seeks donations, it will be indicated on [supervisord.org](http://supervisord.org) or the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.  Please do not enroll the project in such websites yourself; the project developers can do this themselves if they decide to do so.

**Comment by AlJohri** [comment]
cool, thanks for the heads up!
