### ISSUE TITLE
reread always reparses the config file

### ISSUE THREAD

**Issue by mikeyg123** [Supervisor/supervisor#837]
Hi
We regularly poll reread via the xml api. From profiling it appears that this always re-parses the config which adds a noticable amount of cpu load to every host.

Can it be changed so that reread short-cuts loading and parsing the config if it can see that the file modification timestamps have not changed.  This would require caching the list of included files but shouldn't be too hard and would save us precious cycles

Thanks
MIkeG

**Comment by mnaberez** [comment]
No.  I don't think we should add all the complexity some sort of caching mechanism, config file hashing, or timestamp comparison, or whatever for something that isn't going to affect that vast majority of users ever.  If you are rereading the config file that often, or your config file is that large, or the performance is that sensitive, Supervisor (and probably Python) is not the right tool for you.
