### ISSUE TITLE
Running sshd behind supervisor isn't reliable

### ISSUE THREAD

**Issue by elijahchancey** [Supervisor/supervisor#840]
I'm using a docker container to run sshd and I use this as a bastion/jump server for connecting to other servers in my network. Child processes spawned by sshd are constantly reaped by supervisord. Is it possible to disable this behavior?

I ran ps from within the docker container that I was currently ssh'd into.
```
ubuntu@d557bfbcd84b:~$ ps uaxw
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.9  50936 19256 ?        Ss   20:30   0:00 /usr/bin/python /usr/local/bin/supervisord -c /etc/supervisor/sshd.conf
root         7  0.0  0.3  74452  7760 ?        S    20:30   0:00 /usr/sbin/syslog-ng -F
root         8  0.0  0.2  65520  6068 ?        S    20:30   0:00 /usr/sbin/sshd -D
root        20  0.0  0.3  90468  6764 ?        Ss   20:31   0:00 sshd: ubuntu@pts/0
ubuntu      28  0.0  0.1  19912  3784 pts/0    Ss   20:31   0:00 -bash
root        46  0.0  0.3  90352  6352 ?        Ss   20:31   0:00 sshd: root
ubuntu      48  0.0  0.1  36084  3304 pts/0    R+   20:31   0:00 ps uaxw
```

A few minutes later, my ssh session was disconnected
```
ubuntu@d557bfbcd84b:~$ Connection to bastion.company.com closed by remote host.
Connection to bastion.company.com closed.
```

I ssh'd into the bastion server and checked the supervisord logs:
```
Last login: Mon Oct 24 20:31:06 2016 from 10.0.51.132
ubuntu@d557bfbcd84b:~$ tail /var/log/supervisor/supervisord.log
2016-10-24 20:30:43,502 CRIT Supervisor running as root (no user in config file)
2016-10-24 20:30:43,522 INFO RPC interface 'supervisor' initialized
2016-10-24 20:30:43,526 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2016-10-24 20:30:43,527 INFO supervisord started with pid 1
2016-10-24 20:30:44,529 INFO spawned: 'syslog' with pid 7
2016-10-24 20:30:44,530 INFO spawned: 'sshd' with pid 8
2016-10-24 20:30:45,587 INFO success: syslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-10-24 20:30:45,587 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-10-24 20:32:50,408 INFO reaped unknown pid 28
```

Supervisord reaped pid 28, which was the bash process spawned by sshd on behalf of my ubuntu user.

Is it possible to disable or alter the child pid reaping behavior? Can sshd be configured to be more compatible with supervisord?

Thanks!

**Comment by mnaberez** [comment]
> Is it possible to disable or alter the child pid reaping behavior? 

There isn't a message in the log above indicating that `supervisord` sent signals to any of its subprocesses (e.g. as a result of the stop command), so `supervisord` isn't trying to request that any process exit.  Your processes must be exiting on their own for some other reason.

The `reaped unknown pid` message comes from `supervisord` calling `waitpid(-1)` ([here](https://github.com/Supervisor/supervisor/blob/3.3.1/supervisor/supervisord.py#L285) and [here](https://github.com/Supervisor/supervisor/blob/3.3.1/supervisor/options.py#L1316)).  It just means a child process exited, but it doesn't mean `supervisord` did something to cause that exit.

> Can sshd be configured to be more compatible with supervisord?

`supervisord` doesn't have any special knowledge of the kinds of programs it is running.  It just spawns and monitors all processes the same way.  I'm afraid we don't have enough resources to help troubleshoot every program.  You could ask on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  You might also want to look into `sshd`'s log file to see if it has any clues.

**Comment by elijahchancey** [comment]
Ahh, another case of correlation not implying causation. Thanks for clearing this up!
