### ISSUE TITLE
Start all processes in a group from the web interface

### ISSUE THREAD

**Issue by razvanphp** [Supervisor/supervisor#843]
Title says it all I guess, can this be easily detected? and is this command available through RPC already?

I'm new to python, but I could try a pull request if I am guided in the right direction.

Thank you!

**Comment by mnaberez** [comment]
> Title says it all I guess

The "restart all" button on the web interface will start all processes.  If the processes are stopped when the button is pressed, they will be started.  

> is this command available through RPC already?

The [XML-RPC documentation](http://supervisord.org/api.html#process-control) shows how to start processes via XML-RPC.
