### ISSUE TITLE
readonly HTTP interface

### ISSUE THREAD

**Issue by Johnlon** [Supervisor/supervisor#844]
I want supervisorctl to be the only means of making change to the system.
At the same time I want the inet web api turned on so that I can use 3rd party tools like cesi, and these tools must not have write access.

I couldn't figure out where in the http or xml rpc code to put in a rule that says requests on the inet interface are not permitted to make changes.

If someone could point me at the right location please.

Clearly supervisorctl needs to be unaffected. It's just the web api's need locking down such that only read only ops are permissible.

**Comment by mnaberez** [comment]
I'm afraid this is out of scope for Supervisor, sorry.  In the past we've rejected the occasional feature request for adding more sophisticated access controls, user levels, etc.  We don't plan to implement anything like the read-only mode described here.
