### ISSUE TITLE
Using supervisor from apt-get with uwsgi installed with pyenv python yields command not found

### ISSUE THREAD

**Issue by igozali** [Supervisor/supervisor#847]
Hi, 

I'm having a hard time using supervisor (3.0b2) installed through apt-get (Ubuntu 14.04) to run uwsgi (which is installed using python 2.7.12, which is in turn installed using `pyenv`). 

I get the following error lines in `/var/log/supervisord.log`.

```
2016-11-08 19:15:59,253 INFO spawnerr: can't find command 'uwsgi'
2016-11-08 19:16:01,256 INFO spawnerr: can't find command 'uwsgi'
2016-11-08 19:16:04,261 INFO spawnerr: can't find command 'uwsgi'
```

My uwsgi binary is located in /usr/local/pyenv/shims/uwsgi, which is not part of the standard secure_path variable inside the /etc/sudoers file.

Since I'm starting supervisor through the Ubuntu `service` command (i.e. `sudo service start supervisor`), what I'm understanding is that supervisor is being started as root.

The curious thing is that I've modified both /etc/environment and the secure_path in /etc/sudoers to include /usr/local/pyenv/shims, and yet when running supervisor through the `service` command, supervisor still doesn't pick up those paths.

I can work around this by specifying the absolute path to my uwsgi binary in my application supervisor configuration, but I was wondering why my modifications to secure_path and /etc/environment are not picked up by supervisor in this context? Also, what would be the best way to add PATHs when running programs by supervisor?

Thank you!

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by igozali** [comment]
Apologies, thanks for that!
