### ISSUE TITLE
__hash__ method for ProcessConfig?

### ISSUE THREAD

**Issue by wgjak47** [Supervisor/supervisor#848]
Hi, I am trying to wirte a plugin for the #177 , I try to use the **set** the difference set between new Process configs and old Process config:
```
# for num increased
new_process_configs = new_config.process_configs
old_process_configs = old_config.process_configs
if set(old_process_configs).issubset(new_process_configs):
    difference = set(new_process_config - old_process_config)
```

It's doesn't work because there is custom \__eq\__ function for class ProcessConfig but no custom \__hash\__ function.

**Comment by mnaberez** [comment]
This isn't needed for anything inside `supervisord`, so please write the plugin a different way or feel free to submit a PR for it.
