### ISSUE TITLE
Supervisorctl looking for a HTTP server at port 9001 when it should listen on a domain socket

### ISSUE THREAD

**Issue by alanoe** [Supervisor/supervisor#850]
I am using supervisor 3.2.0 and I have the following supervisord.conf file:

[unix_http_server]
file=/tmp/supervisor.sock   ; (the path to the socket file)

[supervisord]
logfile=/tmp/supervisor.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=2           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisor.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false               ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket

([program] sections ....]

I start supervisor server using

$ supervisord -c supervisord.conf

and then try to restart a program using

$ supervisorctl -c supervisord.conf restart <program_name>
http://localhost:9001 refused connection

From http://supervisord.org/configuration.html, it seems that my config file is correct and I do not understand why supervisorctl is looking for a http URL in the restart command. 

Oddly, this happens randomly.

**Comment by mnaberez** [comment]
Here is what I tried to reproduce this (no `supervisord` running):

```
$ cat /tmp/supervisord.conf 
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL for a unix socket

$ supervisorctl -c /tmp/supervisord.conf
unix:///tmp/supervisor.sock no such file

$ supervisorctl -c /tmp/supervisord.conf restart foo
unix:///tmp/supervisor.sock no such file
```

This is using Supervisor 3.3.1 but there weren't any changes in config file loading between 3.2.0 and 3.3.1.  I'm going to close this for now, but if you can provide instructions that will reproduce your report then we can reopen.
