### ISSUE TITLE
In 3.3.1 "reread" fails to have any effect

### ISSUE THREAD

**Issue by JulesAU** [Supervisor/supervisor#855]
Make changes to a conf file.

```
]# supervisorctl reread;
someprocess: changed
```

Then do it again and see the same result
```
]# supervisorctl reread;
someprocess: changed
```

If at this point I restart `someprocess`, the updated config is not used.

In previous versions of supervisor, `reread` was having the desired effect of updating the config state.

**Comment by mnaberez** [comment]
`reread` rereads the config file and makes `supervisord` aware of the changes, but does not change `supervisord`'s active configuration.  After `reread`, use the `avail`/`add`/`remove` commands to make changes to the active configuration, or you can also use the `update` command.  

There is an open issue (#720) for us to add documentation for the config reloading commands.
