### ISSUE TITLE
space+semicolon interpreted as comment even if quoted

### ISSUE THREAD

**Issue by lciti** [Supervisor/supervisor#857]
In the configuration file,
`command = bash -c 'while : ; do echo Hello; sleep 10; done'`
throws a cryptic error
`spawnerr: can't parse command "bash -c 'while :": No closing quotation`.
It took me a while (pun not intended :-D ) to understand the problem: the first semicolon effectively starts a comment even if it's inside single quotes. Once I figured this out, it was an easy fix:
`command = bash -c 'while :; do echo Hello; sleep 10; done'`
works like a charm.
I think it may be worth making the parser understand that " ;" (space+semicolon) does not start a comment when within quotes. Alternatively, this behaviour could be better documented in the docs and/or in the sample configuration file.

**Comment by mnaberez** [comment]
> I think it may be worth making the parser understand that " ;" (space+semicolon) does not start a comment when within quotes. 

Supervisor parses the config file using [ConfigParser](https://docs.python.org/2/library/configparser.html).  There doesn't seem to be an obvious way we can make it handle this case.  It might require writing another parser, which is out of scope.

> Alternatively, this behaviour could be better documented in the docs and/or in the sample configuration file.

I'll add a note to the docs and sample config file.

**Comment by lciti** [comment]
Thanks!
