### ISSUE TITLE
supervisor怎么实现java端调用呢？

### ISSUE THREAD

**Issue by zhaoyexing** [Supervisor/supervisor#859]
现在我想开发基于java的客户端，想要调用supervisor的rpcxml api,但是看官方文档中无demo，怎么实现呢，谢谢啦。

**Comment by mnaberez** [comment]
Can you please ask this question in English?

**Comment by zhaoyexing** [comment]
Now I want to develop java based client, want to call rpcxml API supervisor, but look at the official document no demo, how to achieve it, thank you.

**Comment by mnaberez** [comment]
There is [XML-RPC documentation](http://supervisord.org/api.html) available that lists the available methods.  The [server source code](https://github.com/Supervisor/supervisor/blob/3.3.1/supervisor/rpcinterface.py) may also be helpful.  We do not have any specific examples of using the XML-RPC API from Java, but some users have [reported](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L124-L128) using the [Apache XML-RPC package](https://ws.apache.org/xmlrpc/xmlrpc2/) for Java.

**Comment by zhaoyexing** [comment]
Thank you for my question,I write a example with Java ,
Maven:
        <dependency>
            <groupId>fr.turri</groupId>
            <artifactId>aXMLRPC</artifactId>
            <version>1.9.0</version>
        </dependency>
Java code:

 public static void main(String[] args) {
        try {
            XMLRPCClient client = new XMLRPCClient(new URL("http://127.0.0.1:9001/RPC2"));
            client.setLoginData("root", "root123");
            Object version = client.call("supervisor.getAPIVersion");
            Object[] methods = (Object[]) client.call("system.listMethods");
            Object allConfigInfo = client.call("supervisor.getAllConfigInfo");
            System.out.println(version.toString());
            System.out.println(allConfigInfo.toString());
            for (Object o : methods) {
                System.out.println(o);
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (XMLRPCException e) {
            e.printStackTrace();
        }
    }

Thank you
