### ISSUE TITLE
new tool dealing with Multiple Supervisor Instances

### ISSUE THREAD

**Issue by julien6387** [Supervisor/supervisor#867]
please add a reference to 'Supervisors: A Control System for Distributed Applications ' in Supervisor documentation, at Third Party Applications and Libraries.
https://github.com/julien6387/supervisors

it's written in python 2.7 and is used as a plugin of Supervisor.

**Comment by julien6387** [comment]
Ok, I will think about changing the name. Something like 'supvisors' is different enough ?

I do not see it as a total replacement (excepting the web ui, somehow).
On the contrary, I think it looks like many things on the third party page. It includes a dashboard for multiple instances and plugins (additional XML-RPC, extended supervisorctl).
Supervisor is really running behind and all of its functionalities can still be used.

I have just used the extensions provided by Supervisors to hang directly on events and to add my own functionalities inside the supervisor daemon. That's the way a plugin works.

Finally, I see it more as a 'natural development' to deal with multiple instances of Supervisor.

**Comment by mnaberez** [comment]
> Ok, I will think about changing the name. Something like 'supvisors' is different enough ?

Yes, I think so.

> I do not see it as a total replacement (excepting the web ui, somehow).
On the contrary, I think it looks like many things on the third party page. It includes a dashboard for multiple instances and plugins (additional XML-RPC, extended supervisorctl).
Supervisor is really running behind and all of its functionalities can still be used.

It's difficult to tell this from the repository code alone.  If it can function as a dashboard for normal Supervisor instances, it would be fine to add it to the "Dashboards and Tools for Multiple Supervisor Instances" section of the [third party page](https://github.com/Supervisor/supervisor/blob/master/docs/plugins.rst).  Can you submit a PR for that?

**Comment by julien6387** [comment]
OK, I'll do it once renamed. thanks.

**Comment by mnaberez** [comment]
Thanks, I'll close this again and will watch for the PR.
