### ISSUE TITLE
The cpu usage of supervisord becomes high when program stdout is heavy.

### ISSUE THREAD

**Issue by echo-of-wind** [Supervisor/supervisor#870]

**Comment by mnaberez** [comment]
If the logging performance of supervisord is not adequate for your application, you probably need to use another program instead.  Logging was profiled and an effort was made to improve its performance in 2007.  This work [was released](https://github.com/Supervisor/supervisor/blob/3.3.1/CHANGES.txt#L968) in 3.0a3.  We thought performance was adequate, and didn't see a way to get more performance without major changes.  Nobody is working on trying to make larger changes around logging now.  The master branch, which contains unreleased changes for Python 3 support, makes logging even slower than the released versions.  It's unlikely that logging performance can be improved unless someone comes forward and rewrites it.

**Comment by dongjunjie** [comment]
![image](https://user-images.githubusercontent.com/10395782/62280899-5d428e80-b47f-11e9-8053-9a23ea3adae4.png)
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                 
25661 root      20   0  300844   9360   3340 S 184.1   0.0   2:35.14 rsyslogd                                                                                                                                                                                                
 1907 root      20   0   37908  18896   4584 R  72.2   0.0  15:53.04 supervisord 

Can anyone help optimize this problem?
