### ISSUE TITLE
Feature request: load program env vars from a file

### ISSUE THREAD

**Issue by jhoblitt** [Supervisor/supervisor#882]
Many software packages include a "sysconf" file (`/etc/default/<foo> /etc/sysconfig/<foo>`) of environment variables for their init scripts.  It would be a great convenience if `supervisor` had the ability to initialize a program's environment from this well known format.  Essentially, an equivalent to systemd's [`EnvironmentFile`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=).

**Comment by mnaberez** [comment]
Duplicate of #242.
