### ISSUE TITLE
Exact behavior of `supervisorctl reload` is not documented

### ISSUE THREAD

**Issue by mnieber** [Supervisor/supervisor#888]
I would like to know whether `supervisorctl reload` restarts all tasks. Could this be documented?

**Comment by mnaberez** [comment]
Please ask questions about using or installing Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.  We use this issue tracker mainly for bugs in Supervisor itself.

The `reload` command stops any processes that are running under `supervisord`.  This can be observed by starting a process and issuing the command.
