### ISSUE TITLE
Exited too quickly (process log may have details)

### ISSUE THREAD

**Issue by imKota** [Supervisor/supervisor#891]
config：
```
[program:gearmand]
command=/usr/local/sbin/gearmand -q mysql --mysql-host localhost --mysql-user root --mysql-password pass --mysql-db gearman -d
autostart=true
autorestart=true
stopsignal=KILL
numprocs=1
stdout_logfile=/Users/kota/Downloads/gearmantest.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/Users/kota/Downloads/gearmantest.error.log
stderr_logfile_maxbytes=10MB
```

**Comment by mnaberez** [comment]
Please ask questions about using or installing Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.

> command=/usr/local/sbin/gearmand -q mysql --mysql-host localhost --mysql-user root --mysql-password pass --mysql-db gearman -d

The `-d` option tells [`gearmand` to daemonize](http://gearman.info/gearmand.html#cmdoption-gearmand-d).  Processes running under `supervisord` [should not daemonize](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses).

**Comment by ghxter** [comment]
You are starting it with -d. Programs run under Supervisor must not daemonize. This is explained in Nondaemonizing of Subprocesses. Run it in the foreground instead.

FYI:https://github.com/Supervisor/supervisor/issues/578
