### ISSUE TITLE
Crash on system time change (Debian)

### ISSUE THREAD

**Issue by emmertf** [Supervisor/supervisor#895]
When the system time gets changed on Debian 8 "Jessie" (3.16.39-1+deb8u1), the supervisor daemon crashes leaving it's supervised processes orphaned. This occures on manual time changes as well as on automatic ones ("systemd[1]: Time has been changed" in syslog). Version: 3.0r1-1.

Steps to reproduce:
1. Run supervisor with some constantly restarting processes
2. `service ntp stop`
3. `date --set 00:00:00` (or some other time - also works with just a few seconds difference)
4. Watch how supervisor crashes
5. `service ntp start` (to restore your time)

Note that I use high frequency restarts on jobs that die a lot - so the time is likely to get changed during a restart:

```
numprocs=50
autostart=true
autorestart=true
startsecs=0
stopsignal=KILL
stopwaitsecs=0
```

supervisord.conf
```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf
```

**Comment by mnaberez** [comment]
> Version: 3.0r1-1.

This [was fixed](https://github.com/Supervisor/supervisor/blob/3.2.0/CHANGES.txt#L36-L39) in Supervisor 3.2.0, which was released on 2015-11-30.  Please upgrade to a newer version of Supervisor.

**Comment by emmertf** [comment]
Since this is the most recent version of debian stable it still affects tons of systems. Would be great to get a fix in the debian stable repo.

**Comment by mnaberez** [comment]
> Since this is the most recent version of debian stable it still affects tons of systems. Would be great to get a fix in the debian repo.

The Supervisor project only publishes Python packages to [PyPI](https://pypi.python.org/pypi/supervisor).  The packages for Debian, and all the other distribution packages, are created and maintained by other people who aren't involved with the Supervisor project.  Please report this issue to the maintainers of the package you are installing, since only they can fix it.
