### ISSUE TITLE
supervisor doesn't work with httpie, the same code works with curl

### ISSUE THREAD

**Issue by pointedhat32167** [Supervisor/supervisor#908]
with gunicorn, both of these following two work
tmp = os.popen('http http://www.yahoo.com').read()
tmp = os.popen('curl http://www.yahoo.com').read()

but when runing gunicorn with supervisor
only tmp = os.popen('curl http://www.yahoo.com').read() returns result,
tmp = os.popen('http http://www.yahoo.com').read() returns null

tried both python 2.7 and 3
and with subprocess.getoutput() or os.system() or commands.getstatusoutput()
other command line command like 'ls -l' works
only httpie won't work
it's the same, some help is needed

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.
