### ISSUE TITLE
environment is not work

### ISSUE THREAD

**Issue by yyblove** [Supervisor/supervisor#909]
I set a demo.conf
`
[program:demo]
environment=MY_PATH="/opt/jdk1.8.0_112/bin"
command=%(MY_PATH)s/java -jar /opt/demo-0.0.1-SNAPSHOT.jar
autorestart=true
startretries=10
user=root
redirect_stderr=true
stdout_logfile=/var/log/supervisor/demo.log
`

then I start it , but I get a wrong message:

`Error: Format string '%(MY_PATH)s/java -jar /opt/demo-0.0.1-SNAPSHOT.jar' for 'program:demo.command' contains names ('MY_PATH') which cannot be expanded. Available names: ENV_CVS_RSH, ENV_G_BROKEN_FILENAMES, ENV_HISTCONTROL, ENV_HISTSIZE, ENV_HOME, ENV_HOSTNAME, ENV_JAVA_HOME, ENV_LANG, ENV_LC_CTYPE, ENV_LESSOPEN, ENV_LOGNAME, ENV_LS_COLORS, ENV_MAIL, ENV_OLDPWD, ENV_PATH, ENV_PWD, ENV_QTDIR, ENV_QTINC, ENV_QTLIB, ENV_SELINUX_LEVEL_REQUESTED, ENV_SELINUX_ROLE_REQUESTED, ENV_SELINUX_USE_CURRENT_RANGE, ENV_SHELL, ENV_SHLVL, ENV_SSH_ASKPASS, ENV_SSH_CLIENT, ENV_SSH_CONNECTION, ENV_SSH_TTY, ENV_TERM, ENV_USER, ENV__, group_name, here, host_node_name, process_num, program_name in section 'program:demo' (file: '/etc/supervisord.conf')
For help, use /usr/bin/supervisord -h`

what is it ?

**Comment by mnaberez** [comment]
The environment variable `MY_PATH` must be present in the environment at the time that `supervisord` is started, or set in an `environment=` line in `supervisord.conf`.  See [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment).

Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.
