### ISSUE TITLE
Have a method to restart a program with changed config

### ISSUE THREAD

**Issue by nilstoedtmann** [Supervisor/supervisor#910]
Requirement: `/etc/supervisor/conf.d/myprogram.conf` might or might not have changed. I need to restart _myprogram_ regardless, non-interactively. If `myprogram.conf` did change, I want _myprogram_ to use its new config after restart.

Current methods (tested with supervisor 3.0 on Debian):
 
`supervisorctl reread; supervisorctl update` : Only restarts if config has changed
`supervisorctl reread; supervisorctl restart myprogram`:  Restarts with old config
`supervisorctl reread; supervisorctl update; supervisorctl restart myprogram`: Restarts twice if config has changed
`supervisorctl reload`: Restarts all supervised programs, not just _myprogram_
  
The exit codes of `supervisorctl [reread|update]` seem to not give any hint of whether some config has changed.

I think the correct solution would be to make sure that `supervisorctl reread; supervisorctl restart myprogram` uses the new config.

----
Context: We package _myprogram_ together with `/etc/supervisor/conf.d/myprogram.conf` as Debian package. We need to restart it via the package's `postinst` script - using the new config, if it has changed.

**Comment by mnaberez** [comment]
> I think the correct solution would be to make sure that supervisorctl reread; supervisorctl restart myprogram uses the new config.

`reread` rereads the config file to make `supervisord` aware of the changes, but does not alter the running config.  The running config can then be altered with `add`/`remove`.  

The `update` command performs `reread` then automatically does `add`/`remove`.  It sounds like you can change `reread` to `update` to achieve what you are asking.

**Comment by nilstoedtmann** [comment]
Same problem though: `update` does not restart if the config did not change. Please re-open.

**Comment by mnaberez** [comment]
Please write an [eventlistener](http://supervisord.org/events.html) if none of the existing options work for you.  I'm hesitant to pile on more config reloading commands on top of the pile that already exists.

The eventlistener system is used to watch external things and send commands to `supervisord`, e.g. `memmon` in [superlance](https://github.com/supervisor/superlance) watches memory and restarts processes.  You can write an eventlistener to watch files and issue restarts too.

**Comment by nilstoedtmann** [comment]
Removed unnecessary `reread` from issue description.
