### ISSUE TITLE
XML-RPC API method reloadConfig not returning boolean value

### ISSUE THREAD

**Issue by ssoerensen** [Supervisor/supervisor#915]
I'm seeing this weird issue, when calling reloadConfig, the return value is ton of empty arrays.

shouldn't it simply return a boolean:

`<value><boolean>1</boolean></value>`

Supervisor version: 3.13

Communications dump: https://pastebin.com/eMLb2RuA

**Comment by mnaberez** [comment]
Fixed in a1da6452ca3f4f9d8012d55f6686a771ffecf126.
