### ISSUE TITLE
Why did the worker in the Supervisor stop trying to restart?

### ISSUE THREAD

**Issue by Win32Sector** [Supervisor/supervisor#916]
I have got supervisord 3.0b2

I ran the worker into the Supervisor in 2 instances.

The developer corrected the code and the worker stopped working, as there is a log.

But after 25 seconds the worker tried to start.

> 2017-04-05 21:15:32,599 INFO exited: test_worker_01 (exit status 0; expected)
> 2017-04-05 21:15:33,015 INFO spawned: 'test_worker_01' with pid 19905
> 2017-04-05 21:15:33,025 INFO exited: test_worker_00 (exit status 0; expected)
> 2017-04-05 21:15:33,400 INFO spawned: 'test_worker_00' with pid 19908
> 2017-04-05 21:15:33,673 INFO exited: test_worker_01 (exit status 0; not expected)
> 2017-04-05 21:15:34,059 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:35,062 INFO spawned: 'test_worker_01' with pid 19997
> 2017-04-05 21:15:35,063 INFO spawned: 'test_worker_00' with pid 19998
> 2017-04-05 21:15:35,715 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:35,989 INFO exited: test_worker_01 (exit status 0; not expected)
> 2017-04-05 21:15:37,992 INFO spawned: 'test_worker_01' with pid 20099
> 2017-04-05 21:15:37,993 INFO spawned: 'test_worker_00' with pid 20100
> 2017-04-05 21:15:38,654 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:38,949 INFO exited: test_worker_01 (exit status 0; not expected)
> 2017-04-05 21:15:41,953 INFO spawned: 'test_worker_01' with pid 20189
> 2017-04-05 21:15:41,954 INFO spawned: 'test_worker_00' with pid 20190
> 2017-04-05 21:15:42,732 INFO exited: test_worker_01 (exit status 0; not expected)
> 2017-04-05 21:15:43,124 INFO gave up: test_worker_01 entered FATAL state, too many start retries too quickly
> 2017-04-05 21:15:43,124 INFO success: test_worker_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2017-04-05 21:15:43,134 INFO exited: test_worker_00 (exit status 0; expected)
> 2017-04-05 21:15:44,136 INFO spawned: 'test_worker_00' with pid 20250
> 2017-04-05 21:15:44,789 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:45,791 INFO spawned: 'test_worker_00' with pid 20329
> 2017-04-05 21:15:46,792 INFO success: test_worker_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2017-04-05 21:15:47,070 INFO exited: test_worker_00 (exit status 0; expected)
> 2017-04-05 21:15:48,073 INFO spawned: 'test_worker_00' with pid 20393
> 2017-04-05 21:15:48,741 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:49,743 INFO spawned: 'test_worker_00' with pid 20417
> 2017-04-05 21:15:50,396 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:52,399 INFO spawned: 'test_worker_00' with pid 20470
> 2017-04-05 21:15:53,202 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:56,207 INFO spawned: 'test_worker_00' with pid 20565
> 2017-04-05 21:15:56,869 INFO exited: test_worker_00 (exit status 0; not expected)
> 2017-04-05 21:15:57,871 INFO gave up: test_worker_00 entered FATAL state, too many start retries too quickly

I had to run it manually. Why could he stop trying to start?

**Comment by mnaberez** [comment]
Please ask questions about installing or using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
