### ISSUE TITLE
how to add variable enviroment on supervisor

### ISSUE THREAD

**Issue by buyongji** [Supervisor/supervisor#920]
below is my supervisror.conf

; ==================================
; celery worker supervisor example
; ==================================
[program:exchange_cn_celery_worker]
; Set full path to celery program if using virtualenv
command=celery -A run_celery.celery worker

directory=/var/www/viabtc_exchange_cn_web/
user=root
numprocs=1
environment=FLASK_CONFIG=%(ENV_FLASK_CONFIG)s

when i run supervisorctl update: it error below;
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: Format string 'FLASK_CONFIG=%(ENV_FLASK_CONFIG)s' for 'environment' contains names which cannot be expanded">: file: /usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 947

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by buyongji** [comment]
I find the reason. my supervisor version is 3.0. update to 3.3.1. then works. thx.
