### ISSUE TITLE
Python3: has_key(), long, and unicode

### ISSUE THREAD

**Issue by cclauss** [Supervisor/supervisor#923]
W601 .has_key() is deprecated, use 'in'
* https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py#L89

F821 undefined name 'long'
* https://github.com/Supervisor/supervisor/blob/master/supervisor/medusa/auth_handler.py#L93

**Comment by mnaberez** [comment]
> W601 .has_key() is deprecated, use 'in'
>
>    https://github.com/Supervisor/supervisor/blob/master/supervisor/web.py#L89

`self.request` is a medusa `Request` object ([`has_key` method](https://github.com/Supervisor/supervisor/blob/1f916d5c174654912a94f035d9baa922aa148110/supervisor/medusa/http_server.py#L87-L87)).
