### ISSUE TITLE
How to deal with when  the supervisord process self exit?

### ISSUE THREAD

**Issue by xuanskyer** [Supervisor/supervisor#925]
if supervisord process exit , jobs processes still living .
how to deal about this ?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

If the process you are running under `supervisord` spawns children and those children aren't getting killed, you might want to look at the [`stopasgroup` and `killasgroup` options](http://supervisord.org/configuration.html).
