### ISSUE TITLE
Expanding env variables using service supervisor start doesnt work

### ISSUE THREAD

**Issue by feliara8** [Supervisor/supervisor#926]
Hi,

I want to expand some aws variables like this:

environment=AWS_REGION=%(ENV_AWS_REGION)s,AWS_DEFAULT_REGION=%(ENV_AWS_DEFAULT_REGION)s,AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=%(ENV_AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)s
user=supervisor

Those env variables exists on root user.
But when i service supervisor start this errors appear:

root@47e895d420af:/etc# service supervisor start
Starting supervisor: Error: Format string 'AWS_REGION=%(ENV_AWS_REGION)s,AWS_DEFAULT_REGION=%(ENV_AWS_DEFAULT_REGION)s,AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=%(ENV_AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)s' for 'environment' contains names ('ENV_AWS_REGION') which cannot be expanded. Available names: ENV_LANG, ENV_LANGUAGE, ENV_LC_ADDRESS, ENV_LC_ALL, ENV_LC_COLLATE, ENV_LC_CTYPE, ENV_LC_IDENTIFICATION, ENV_LC_MEASUREMENT, ENV_LC_MESSAGES, ENV_LC_MONETARY, ENV_LC_NAME, ENV_LC_NUMERIC, ENV_LC_PAPER, ENV_LC_TELEPHONE, ENV_LC_TIME, ENV_PATH, ENV_PWD, ENV_TERM, group_name, here, host_node_name, process_num, program_name in section 'program:grabbity'

Weird thing, is when i run supervisord -c supervisor.conf it can read those variables

**Comment by mnaberez** [comment]
In the error message above, you can see "Available names:" which lists the environment variables that are in `supervisord`'s environment.  The names you are using like `AWS_DEFAULT_REGION` are not in that list, so they are not in `supervisord`'s environment.  You need to put those into `supervisord`'s environment at that time that `supervisord` starts (see [Subprocess Environment](http://supervisord.org/subprocess.html#subprocess-environment)).

**Comment by feliara8** [comment]
[supervisord]
loglevel=debug
environment=AWS_REGION=%(ENV_AWS_REGION)s,AWS_DEFAULT_REGION=%(ENV_AWS_DEFAULT_R
EGION)s,AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=%(ENV_AWS_CONTAINER_CREDENTIALS_R
ELATIVE_URI)s

[program:grabbity]
autorestart=true
autostart=true
command=mono Grabbity.exe
directory=/opt/grabbity
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s-%(host_node_name)s.log
environment=AWS_REGION=%(ENV_AWS_REGION)s,AWS_DEFAULT_REGION=%(ENV_AWS_DEFAULT_R
EGION)s,AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=%(ENV_AWS_CONTAINER_CREDENTIALS_R
ELATIVE_URI)s
user=supervisor


This is my conf file, and i still have the same issue

**Comment by mnaberez** [comment]
Please see https://github.com/Supervisor/supervisor/issues/926#issuecomment-296246823.  If that is not enough help, please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by mkingbe** [comment]
same, issue here any solution ?
