### ISSUE TITLE
why here have a space in the place of supervisor.medusa.http_server.http_server ()  class defined

### ISSUE THREAD

**Issue by htlhenry** [Supervisor/supervisor#927]
I'm reading the source code of supervisor, i want to know the implement of supervisor handle processes。
when i read the supervisor.medusa.http_server.http_server() class, i find the function define with space between `()` , like `class http_server (asynore.dispatcher)`, and that module is many function like that. that is not PEP8 style, it confuse me, what consideration for that?

**Comment by mnaberez** [comment]
Medusa was written before PEP 8 existed.  The Supervisor developers did not write Medusa.
