### ISSUE TITLE
supervisor uwsgi - uwsgi: ERROR (spawn error)

### ISSUE THREAD

**Issue by nijojames92** [Supervisor/supervisor#941]
I've django application running with uwsgi and nginx. I was using uwsgi python package to configure uwsgi manually. Now i need to switch to supervisor to run the uwsgi process. I create the supervisor config and started the uwsgi processes and the site is working but i'm getting the following error when i start the uwsgi process using supervisorctl command

uwsgi:uwsgi_00: ERROR (spawn error)

But there are 8 processes created in the server. I'm not sure why i'm getting this error then.

I'm attaching my supervisor config and uwsgi.ini file

   [program:uwsgi]
   command=/var/www/django/virtual/bin/uwsgi --ini /var/www/django/uwsgi.ini 
   user=root
   process_name = %(program_name)s_%(process_num)02d
   autostart=true
   autorestart=true
   stderr_logfile=/var/www/django/super.log
   stdout_logfile=/var/www/django/super.log
   
Uwsgi.ini file

   [uwsgi]
    master          = true 
    socket          = /tmp/uwsgi.sock
    chmod-socket    = 666
    chdir           = /var/www/django/webserver_test
    wsgi-file       = /var/www/django/webserver_test/Django_app/wsgi.py
    virtualenv      = /var/www/django/virtual
    pythonpath      = /var/www/django/virtual/bin/python
    vacuum          = true
    enable-threads  = true
    daemonize= /var/www/django/uwsgi.log

Supervisor error log:

2017-05-29 09:49:50,953 INFO spawned: 'uwsgi_00' with pid 20819 2017-05-29 09:49:50,978 INFO exited: uwsgi_00 (exit status 0; not expected) 2017-05-29 09:49:51,979 INFO gave up: uwsgi_00 entered FATAL state, too many start retries too quickly 2017-05-29 10:01:52,874 INFO spawned: 'uwsgi_00' with pid 20993 2017-05-29 10:01:52,906 INFO exited: uwsgi_00 (exit status 0; not expected) 2017-05-29 10:01:53,914 INFO spawned: 'uwsgi_00' with pid 20998 2017-05-29 10:01:53,932 INFO exited: uwsgi_00 (exit status 0; not expected) 2017-05-29 10:01:55,941 INFO spawned: 'uwsgi_00' with pid 21005 2017-05-29 10:01:55,966 INFO exited: uwsgi_00 (exit status 0; not expected) 2017-05-29 10:01:58,976 INFO spawned: 'uwsgi_00' with pid 21013 2017-05-29 10:01:58,994 INFO exited: uwsgi_00 (exit status 0; not expected) 2017-05-29 10:01:59,995 INFO gave up: uwsgi_00 entered FATAL state, too many start retries too quickly

And the server configuration is 1 core, 2GB RAM

IS it possible to reduce the number of processes created by supervisor

**Comment by mnaberez** [comment]
```
daemonize= /var/www/django/uwsgi.log
```

It looks like you have configured this program to daemonize, but programs run under `supervisord` [should not daemonize themselves](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses).

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by nijojames92** [comment]
Hi

Can you please tell me how there is uwsgi spawn error when we daemonize
uwsgi.

*Regards

Nijo James
Devops Engineer
SayOne Technologies Pvt Ltd.
T: +91 4844037171
www.sayonetech.com <http://www.sayonetech.com/>*

**Comment by mnaberez** [comment]
> Can you please tell me how there is uwsgi spawn error when we daemonize uwsgi.

`supervisorctl` will show spawn error whenever a program exits quicker than `startsecs`.   If a program daemonizes itself, `supervisord` sees it as exiting.  Programs run under `supervisord` [should not daemonize themselves](http://supervisord.org/subprocess.html#nondaemonizing-of-subprocesses).  

If you still have questions, feel free to ask them on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  This issue tracker is mainly used for bugs in Supervisor itself.

**Comment by nijojames92** [comment]
Thanks, its fixed now.

*Regards

Nijo James
Devops Engineer
SayOne Technologies Pvt Ltd.
T: +91 4844037171
www.sayonetech.com <http://www.sayonetech.com/>*
