### ISSUE TITLE
Supervisor not install on Python3.6

### ISSUE THREAD

**Issue by vBlackOut** [Supervisor/supervisor#943]
i'm used the fedora 26 and python3.6 defaulty
Collecting supervisor
  Using cached supervisor-3.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.6.1 (default, May  9 2017, 15:52:14)
    [GCC 7.1.1 20170503 (Red Hat 7.1.1-1)].  Please install using a supported version.

**Comment by mnaberez** [comment]
Supervisor is not yet compatible with Python 3, as noted in the [README](https://github.com/Supervisor/supervisor/blob/master/README.rst).  Python 3 issues are being tracked under the [python 3](https://github.com/Supervisor/supervisor/issues?q=is%3Aopen+is%3Aissue+label%3A%22python+3%22).

**Comment by zyv** [comment]
@mnaberez run into this problem half a year later - the currently released version is supervisor 3.3.4; unreleased 4.0 is apparently Python 3 compatible. Could you please tell what are the release plans for 4.0? Is there any alternative to running from git in the meantime? Many thanks!

**Comment by alejandrohdo** [comment]
I have installed in a virtual environment with python3.6, how much I try to execute by `supervisorctl start celeryd`, example and throw something at me
`FileNotFoundError: [Errno 2] No such file or directory: '/home/omar/Desktop/virtual_envs/env_celery/lib/python3.6/site-packages/supervisor-3.0b2.dev0-py3.6.egg/supervisor/version .txt '`

Who had a similar problem and how could it be solved?, thanks

**Comment by Madi7** [comment]
@alejandrohdo I have the same issue and I couldn't solve it yet, Im seriously thinking about using circus instead

**Comment by axd1967** [comment]
do you have this line in your supervisord config:
```
; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

```
