### ISSUE TITLE
supervisor not killing (sub-)program started with shell script

### ISSUE THREAD

**Issue by chzhong** [Supervisor/supervisor#944]
When I start a java program with a bash script, the java program will not be stopped/killed when I send stop/shutdown to supervisorctl. I have `killasgroup` set to true.

Here is my `supervisor.conf`:
```
[program:java_app]
command=bin/start.sh
killasgroup=true
```

Here is my `start.sh`:
```
#!/bin/sh
# Find Java, setup JVM options, classpath, etc...
java $JVM_OPTS -cp $CLASSPATH -jar lib/app.jar "$@"
```
`app.jar` contain a simple HTTP server and runs at foreground.

When I try `supervisorctl -c supervisor.conf start java_app`. The app starts correctly and keeps running.
But when I use `supervisorctl -c supervisor.conf stop java_app`, only the shell (`sh`) is terminated by the java program still running. The same thing happens if I use `shutdown`.

Any know how to resolve this?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
