### ISSUE TITLE
Mailing list page has invalid SSL cert

### ISSUE THREAD

**Issue by ckonstanski** [Supervisor/supervisor#947]
https://lists.supervisord.org/mailman/listinfo/supervisor-users is unreachable in browsers with up-to-date security restrictions.

lists.supervisord.org uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is not valid for the name lists.supervisord.org. Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by mnaberez** [comment]
@mcdonc owns the domain and runs the mailing list server.  Maybe he could get a free [Let's Encrypt](https://letsencrypt.org/) certificate for it.  @mcdonc?
