### ISSUE TITLE
PY3 treated as oddness

### ISSUE THREAD

**Issue by enedil** [Supervisor/supervisor#950]
As pointed out in [this article](https://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/), there is no reason to run some different code when supervisor is run under Python 3. Python 2 should be treated as unusual. This will be more beneficial since the change is already happening and it will prevent the need of change in the future, when Python 4 eventually appears.

**Comment by mnaberez** [comment]
I don't know what to do with this request, other than to ask you please look at the instances that the `PY3` constant is actually used.  Outside of the `compat` module, it's only used in a few places where there seemed to be no alternative.  We will review pull requests.
