### ISSUE TITLE
Need help with stdout_logfile

### ISSUE THREAD

**Issue by RainbowTraveller** [Supervisor/supervisor#953]
Could not access mailing list, so asking my question here.

I have a child program being managed by supervisord. Can I redirect the `stdout_logfile` logs to a file as well as stdout. I do not want to use syslog. It should be something simple like  `tee`

e.g `tee /var/log/httpd/error_log | some java program reading from stdout`

**Comment by mnaberez** [comment]
The [supervisor-stdout](https://github.com/coderanger/supervisor-stdout) plugin will send the child process output to supervisord's stdout.  It can be used together with the normal logfile options.

**Comment by RainbowTraveller** [comment]
Well that is not what I am looking for. I am able to get child processes log already in a file when I set
