### ISSUE TITLE
new "autostart" and "autorestart" commands?

### ISSUE THREAD

**Issue by acasademont** [Supervisor/supervisor#955]
Hi!

I find myself often in the situation that I need to restart the currently running programs, which are the ones marked with the `autostart` flag. Unfortunately, there's no way to just start o restart the programs with that flag. The workaround right now is a full "reload", but that also creates new log files, which is something we don't really want (maybe the issue should be with the auto naming of the log files...). Would it be reasonable to add those "autostart" and "autorestart" commands? I can work on a patch but I wanted to gather some opinions before.

**Comment by mnaberez** [comment]
It's pretty easy to add new `supervisorctl` commands as [plugins](http://supervisord.org/plugins.html).  Not everything needs to go into the core, and this use case (a "restart" command that only restarts processes with the "autostart" option set) sounds like it's probably a better fit for a plugin.
