### ISSUE TITLE
Vectorised Supervisor logo?

### ISSUE THREAD

**Issue by davidjb** [Supervisor/supervisor#960]
Is the Supervisor logo available in a vectorised (eg SVG) format?  I'm working on a web dashboard project and an SVG would make it look great on high-DPI displays.  The highest resolution image I can find is the project's avatar at https://github.com/Supervisor.

**Comment by mnaberez** [comment]
There is not, but please don't use the project's logo on your third party dashboard anyway.  It may confuse the dashboard as being part of the main project.
