### ISSUE TITLE
supervisor conflict of APScheduler get_jobs method

### ISSUE THREAD

**Issue by wanghaiqing2015** [Supervisor/supervisor#961]
Supervisor 3.1.3
APScheduler 3.3.1

Flask web framework: 
@jsonrpc.method('my_get_jobs')
def my_get_jobs(host_id):
         print cron.get_jobs()

get_jobs()  will hang, but not use Supervisor , it can work .

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for bugs in Supervisor itself.
