### ISSUE TITLE
Supervisor tells me my tornado program was EXITED every time I try to start it.

### ISSUE THREAD

**Issue by Jackeriss** [Supervisor/supervisor#965]
But if I run my program without supervisor, it won't exit. This tornado program will process some data for about 4s before starting ioloop.
The issue will not happen when I remove this process.
 The config file:
```
[program:Typora]
directory = /home/www/Typora
command = /home/www/Typora/venv/bin/python3 main.py --env=prod --port=8101
startsecs = 0
autorestart = false
stdout_logfile = /var/log/supervisor/Typora.log
stderr_logfile = /var/log/supervisor/Typora.err
```

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list. We use this issue tracker mainly for issues in Supervisor itself.
