### ISSUE TITLE
Start and stop processes at the same time

### ISSUE THREAD

**Issue by maxgalbu** [Supervisor/supervisor#966]
When I restart using `supervisorctl restart program:*` supervisord waits for every process to stop, waits another 2-3 seconds, then starts processes one by one. 

When I run `supervisorctl update`, the processes are stopped one by one, but are restarted all together.

Is there any way to start the processes all together, with a configuration param? If not, this is a feature request :)

**Comment by FAKERINHEART** [comment]
supervisorctl restart all

**Comment by mnaberez** [comment]
Duplicate of #723
