### ISSUE TITLE
Passing in command line flags to program in Supervisor

### ISSUE THREAD

**Issue by sidak** [Supervisor/supervisor#967]
I am planning to use Supervisor to start my experiments on a remote machine programmatically via the XML-RPC API interface. While I have written down the details of the program that I would like the run (like command, directory, autostart, etc.) in a .conf file, I would like to run this program with different command line flags (such as num_iterations, dataset, config yml, and others). Is there a way provided by this API  or Supervisor in general? 

Also, is it a good idea to use Supervisor in this manner? 

I would love to hear your suggestions on these matters. Thank you so much! :smile:

**Comment by mnaberez** [comment]
The built-in XML-RPC interface does not allow this.  Programs and their options must be defined in a configuration file, and `supervisord` reads the file.  There is at least [one plugin](https://github.com/mnaberez/supervisor_twiddler) that allows arbitrary program definitions to be created via XML-RPC.

**Comment by sidak** [comment]
Thanks @mnaberez
