### ISSUE TITLE
Caching Python Code on Program

### ISSUE THREAD

**Issue by Maktech07** [Supervisor/supervisor#971]
I have just recently started using supervisor and have enjoyed it. The only issue I am seeing is code updates are not being seen. The program I am running is a made up of a couple python files. The command is "python <path>/<program_file>.py". Python is mapped correctly in the config and the program runs. The issue is the only output I am seeing is the same as when I first started it. 

I have updated a number of the python files and done all the various paths to get it to update:
- stop and start the program in supervisorctl
- make modifications to the conf file, reread and update
- shut down and restarted the service
- I have made a new conf pointing to the same files
- I have moved the files to new directory and changed the conf file

In each case I am getting the same logs as the first time I ran. Are the files being cached somewhere?

Any suggestions would be greatly appreciated.

Thank you.

**Comment by mnaberez** [comment]
> Are the files being cached somewhere?

No.  `supervisord` uses fork/exec to run the command given in `command=` in the config file.  It is similar to if you typed the command at a shell prompt.  `supervisord` doesn't know if the command being run is a Python program.  It does not have any sort of Python code caching feature or other ability to influence the behavior of the programs that it launches.

**Comment by Maktech07** [comment]
Thank you for the answer about the caching but, any diagnosis of why I am not getting the code changes on each run?
