### ISSUE TITLE
sdtout not logged during process graceful shutdown

### ISSUE THREAD

**Issue by shmish111** [Supervisor/supervisor#979]
Supervisord does not collect stdout and stderr after process shutdown has been initiated, see https://stackoverflow.com/questions/3533371/signal-passing-to-managed-processes-using-supervisord

**Comment by mnaberez** [comment]
This was fixed in e19cbc185dfad045c8775750d36ab8ceed4c4dfb and [released ](https://github.com/Supervisor/supervisor/blob/3.3.3/CHANGES.txt#L473-L475) in Supervisor 3.0a10 (2011-03-30).  Please upgrade to a newer version.
