### ISSUE TITLE
How to conect to multiple supervisor processes on multiple hosts

### ISSUE THREAD

**Issue by freeseacher** [Supervisor/supervisor#981]
As said in docs
```
The command-line client piece of the supervisor is named :program:`supervisorctl`. It provides a shell-like interface to the features provided by :program:`supervisord`. From :program:`supervisorctl`, a user can connect to different :program:`supervisord` processes, get status on the subprocesses controlled by, stop and start subprocesses of, and get lists of running processes of a :program:`supervisord`.
```

But as far as i can test i can only connect to one instance. 
`./bin/supervisorctl -s http://serv1:9009 -s http://serv2:9009 -s http://serv3:9009`
I with to connect to something about 50 instances simultaniosly and start/stop programs. 

as far as i can see there is the project called `supervisorclusterctl` but it feels bit of overengineered.
Am i miss something ?

**Comment by mnaberez** [comment]
`supervisorctl` only connects to one `supervisord` instance at a time.  

Connecting to multiple instances at once is not currently a goal of this project, but check the [plugins list](http://supervisord.org/plugins.html) for third party add-ons that might help.

**Comment by freeseacher** [comment]
So docs have to be updated to reflect that.
