### ISSUE TITLE
Supervisor Not Logging program output

### ISSUE THREAD

**Issue by gauravgargtech** [Supervisor/supervisor#982]
I am running Supervisor on EC2 instance with Centos 6.6, and it's not logging output of program in mentioned files, Please guide me if I am doing something wrong, However same config is working fine on my local Ubuntu machine ,

[program:consumeOtherEmails]
command=php index.php --controller=consumers --action=consumeOtherEmails
process_name=consumer4
directory=/var/www/html/jenkins/api/app/webroot/
numprocs=1
priority=999
autostart=true
autorestart=true
startretries=80000
stopwaitsecs=2
redirect_stderr = true
stdout_logfile=/var/logs/consumers/consumer4.log
stdout_logfile_maxbytes=50MB

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
