### ISSUE TITLE
Memory Usage in 'supervisorctl status' output

### ISSUE THREAD

**Issue by paskyorg** [Supervisor/supervisor#983]
I think it would be very useful to show memory usage in 'supervisorctl status' output.

I looked at [souce code](https://github.com/Supervisor/supervisor/blob/219f7af0ac8b0b1965b00793a923a22addfadbaa/supervisor/rpcinterface.py#L598) to add this feature, but I don't know how do it.

Somebody could help me? Thanks!

**Comment by mnaberez** [comment]
Supervisor has a plugin system (the `[rpcinterface:x]`, `[ctlplugin:x]`, and `[eventlistener:x]` sections in the config file).  A `memory` command or similar could be added as a `supervisorctl` plugin without modifying `supervisord` or `supervisorctl`.
