### ISSUE TITLE
Failure to parse command line string containing colon (:)

### ISSUE THREAD

**Issue by jleveque** [Supervisor/supervisor#986]
I need supervisor to run a command in which one of the arguments is itsef a format string which contains a colon. However, supervisor errors out upon parsing supervisor.conf with the following error:

`Error: Format string [...] for [...] is badly formatted: unsupported format character ':' (0x3a) at index 30`

I tried enclosing the argument list in quotes to no avail. Is there a workaround for this?

**Comment by mnaberez** [comment]
> Is there a workaround for this?

Possibly.  What is the exact `command=` line from the config file that it is rejecting?

**Comment by jleveque** [comment]
Here is an example command line:

`command=/usr/sbin/dhcrelay -d -q -a %h:%p %P -i Vlan1000 192.168.0.1`

The problem lies in the colon in the format string provided by the `-a %h:%p %P` argument.

**Comment by mnaberez** [comment]
supervisord uses the `%` character for its own format strings in the config file. You can still use the `%` character but you must escape it like `%%`:
```
command=/usr/sbin/dhcrelay -d -q -a %%h:%%p %%P -i Vlan1000 192.168.0.1
```

**Comment by jleveque** [comment]
Ah, thank you. I was focused on the colon due to the error message; I didn't realize the percent sign was the real culprit.
