### ISSUE TITLE
Consult a command written

### ISSUE THREAD

**Issue by Woophp** [Supervisor/supervisor#989]
My start command is like that

LD_PRELOAD="/usr/lib64/libtcmalloc.so" python x.py

But I issued this command can not be recognized by supervisord
command=LD_PRELOAD="/usr/lib64/libtcmalloc.so" python x.py

**Comment by mnaberez** [comment]
```
environment = LD_PRELOAD="/usr/lib64/libtcmalloc.so"
command = python x.py
```
