### ISSUE TITLE
Validation of a configuration file

### ISSUE THREAD

**Issue by sieben** [Supervisor/supervisor#990]
Is there a way of validating a configuration file that is imported? When I reread/update my configuration and there is an error inside a newly included file, supervisor goes into an error state. Is there a way to avoid this? Is there a python function that I could import that could tell me if a configuration file is valid or not?

**Comment by mnaberez** [comment]
> Is there a way of validating a configuration file that is imported?

I'm afraid that doing some sort of larger pre-check on the config than we do now would require a substantial rewrite of how options are parsed.  I don't think the project maintainers are willing to do this but we'd review pull requests.  

> When I reread/update my configuration and there is an error inside a newly included file, supervisor goes into an error state.

The effects of loading an invalid configuration really depend on what's wrong with the configuration.  For example, if you specify an invalid process name, you might get an error message.  If you specify an invalid socket file, `supervisorctl` may no longer be able to communicate with `supervisord` at all.  

There's probably cases that we can handle better than we do now, and we'd review pull requests for those, but there's always going to be options where you don't know if it will work until you try to do it (e.g. binding to a socket or switching to a user).
