### ISSUE TITLE
Allow disabling the "clear log" functionality

### ISSUE THREAD

**Issue by ppihus** [Supervisor/supervisor#992]
I searched the documentation and could not find a possibility to disable the "Clear log" functionality or modify its behaviour. So I guess my ticket is rather a feature request, not an issue.

I find the `stdout_logfile` very useful. In my environment no logs should ever be lost, yet today I realised that if one clicks the "Clear log" button in Supervisor web interface, then the actual log on the disk is also emptied. There seems no way to disable this clearing functionality or affect its behaviour.

Is there a chance that this kind of configuration option would soon end up in Supervisor or I'll have to make some changes in how we're logging the output of our applications?

Application is running and logging.  Latest log is 1691byes.
```
[root@log]# ls -ltr application_log*
-rw-r--r-- 1 root root 1048917 Sep  5 19:49 application_log.5
-rw-r--r-- 1 root root 1049419 Sep  7 18:42 application_log.4
-rw-r--r-- 1 root root 1048812 Sep 10 08:04 application_log.3
-rw-r--r-- 1 root root 1049016 Sep 15 02:15 application_log.2
-rw-r--r-- 1 root root 1048657 Sep 18 12:05 application_log.1
-rw-r--r-- 1 root root    1691 Sep 18 12:22 application_log
```

Now I press "Clear log" in the Web interface. Probably just to clear the clutter in browser window. However, this also affects the actual log file on disk and a dummy web interface user such as I shouldn't have this power:

```
[root@log]# ls -ltr application_log*
-rw-r--r-- 1 root root 1048917 Sep  5 19:49 application_log.5
-rw-r--r-- 1 root root 1049419 Sep  7 18:42 application_log.4
-rw-r--r-- 1 root root 1048812 Sep 10 08:04 application_log.3
-rw-r--r-- 1 root root 1049016 Sep 15 02:15 application_log.2
-rw-r--r-- 1 root root 1048657 Sep 18 12:05 application_log.1
-rw-r--r-- 1 root root       0 Sep 18 12:22 application_log
```
As you can see, all the previous log files stay the same size, but latest one is erased.

**Comment by mnaberez** [comment]
In the past, there have been a few requests to enable/disable some features (always different ones) or add some way to have different types of users with different permissions.  The developers decided all of this is out of scope for this project, sorry.  It is going to stay simple where a user that has access can control all of it.  We aren't going to start adding knobs to allow individual features to be enabled/disabled.

**Comment by 15927561264** [comment]
@ppihus 
You can find the following file.
![image](https://user-images.githubusercontent.com/13898848/33301381-79251e32-d430-11e7-9982-f0a3f910c5b8.png)

**_Clean up the red marks._**

![image](https://user-images.githubusercontent.com/13898848/33301421-b17bbd04-d430-11e7-9fd7-b1eff2c82d7e.png)
