### ISSUE TITLE
ctlplugin ignored in include files

### ISSUE THREAD

**Issue by astronouth7303** [Supervisor/supervisor#993]
On supervisor 3.3.1 (Debian), it seems like `ctlplugin:` sections are ignored by `supervisorctl` if they are in include files.

So, the following block:

```
[ctlplugin:jcmd]
supervisor.ctl_factory = supervisor_jcmd.controllerplugin:make_controllerplugin
```

If this is in an included file, it is ignored and `supervisorctl help` doesn't show the extra commands. But if the block is in the main config file, it works just fine and is shown.

**Comment by mnaberez** [comment]
There is an open pull request for this in #277. I will close this issue in favor of that one.

**Comment by geoffjukes** [comment]
Thanks you! This bug report helped me solve an issue loading the supervisor-wildcards plugin!
