### ISSUE TITLE
Supervisorctl reload socket error

### ISSUE THREAD

**Issue by arcsector** [Supervisor/supervisor#994]
I try to reload but I'm given this error instead: 

`error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228`

I'm running Ubuntu server 16.04 with python 2.7

**Comment by mnaberez** [comment]
The error is saying that the socket file that `supervisorctl` uses to communicate with `supervisord` does not exist.  This usually means that `supervisord` is not running.  The log file may have details why `supervisord` could not (re)start.

Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
