### ISSUE TITLE
Kill supervisord lead to subprocess crash

### ISSUE THREAD

**Issue by zhangketing** [Supervisor/supervisor#995]
Hello,I want to ask a question:
when I use supervisord to watch the golang server process , I manually kill supervisord, then golang server process exited. What's the reason for that ?

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by zhangketing** [comment]
I want to know killing supervisord, why subprocess exited ?

**Comment by julien6387** [comment]
That's the way Supervisor works.
It owns all the processes that it spawns. When it stops, it automatically
stops all the processes that it owns.

2017-09-22 9:07 GMT+02:00 zhangketing <notifications@github.com>:

**Comment by zhangketing** [comment]
Sorry, I killed supervisord(order : kill -9 pid(supervisord)). and I didn,t execute /etc/init.d/supervisord stop

**Comment by chenliangomc** [comment]
As julien6387 said:
> It owns all the processes that it spawns. When it stops, it automatically stops all the processes that it owns.

When a signal is sent to supervisord process, the signal handler of supervisord will do the actions as stated in [doc](http://supervisord.org/running.html#signal-handlers).

Please read the documentation carefully, and review the knowledge of UNIX kernel about process and signal.
