### ISSUE TITLE
How to run a command as a specific group?

### ISSUE THREAD

**Issue by Siecje** [Supervisor/supervisor#996]
I want to run jupyterhub as the jupyterhub user. The jupyterhub user doesn't have permission to run Python. But it does have permission to run jupyterhub with the python group, which does have the correct permissions on the files.

In sudoers
```shell
jupyterhub ALL=(:python) NOPASSWD:/boot/tp/python/bin/jupyterhub
```

Without supervisord I can run the command as follows

```shell
$ whoami
jupyterhub
$ sudo -g python ./jupyterhub
```

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.

**Comment by Siecje** [comment]
Thanks. The certificate on that link is not valid in Chrome on Windows 10. It says the certificate is issues to `bahia.palladion.com`.

I did mean this as a bug report as I didn't think it was possible because I don't see a way to specific the group as you can specify the user.

http://supervisord.org/configuration.html#program-x-section-values

So it is possible to set the group?

**Comment by Siecje** [comment]
FWIW by group I meant the Linux group.

**Comment by Siecje** [comment]
When you set the `user` for a program, it will set the group to be the user's group as specified in `/etc/passwd`.

https://github.com/Supervisor/supervisor/blob/1f916d5c174654912a94f035d9baa922aa148110/supervisor/datatypes.py#L320-L322

I would like to specify the group to run the command as instead.

A new program value `group` would be added. Here are the other existing values. http://supervisord.org/configuration.html#program-x-section-values

If `group` is confusing with supervisord groups then what about `gid`?

**Comment by Siecje** [comment]
If anyone else finds this the go supervisord implementation as added this feature.

You can specify the group on the user line `user = $user:$group`

https://github.com/ochinchina/supervisord
