### ISSUE TITLE
use command line directly successed, and the supervisor doesn't work

### ISSUE THREAD

**Issue by pengha** [Supervisor/supervisor#998]
#### Context

* os : centos 3.10.0
*  version : 3.3.3

#### 
 I want to use supervisor start a program, use the command directly successed, but use supervisor failed.
thank  you very much for any help
program:
```
[program:agent]
command= xvfb-run /home/chrome
autostart=true               
startsecs=3               
startretries=3         
stopsignal=QUIT    
stdout_logfile=agent_out.log     
stdout_logfile_maxbytes=20MB 
stdout_logfile_backups=10  
``` 
log:
```
/bin/xvfb-run: line 186 kill: (32284) - no such process
/bin/xvfb-run: line181: 32338    DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
/bin/xvfb-run: line 186 kill: (32335) - no such process
```
But I start the program  with the command directly , the process could be started.
log:

```
[538:538:0929/164549:ERROR:gl_surface_glx.cc(403)] glxQueryVersion failed
[538:538:0929/164549:ERROR:gl_initializer_x11.cc(130)] GLSurfaceGLX::InitializeOneOff failed.
[538:538:0929/164549:ERROR:gpu_child_thread.cc(331)] Exiting GPU process due to errors during initialization
[493:518:0929/164549:ERROR:browser_gpu_channel_host_factory.cc(113)] Failed to launch GPU process.
```
Although there were some errors in the log,  the program really started and worked
I confuse about it that why supervisor cant't start the program.   the content in the log affect it

**Comment by mnaberez** [comment]
Please ask questions about using Supervisor on the [supervisor-users mailing list](https://lists.supervisord.org/mailman/listinfo/supervisor-users).  We use this issue tracker mainly for bugs in Supervisor itself.
